### ISSUE TITLE
Enquires on supported types

### ISSUE THREAD

**Issue by mikecc2008** [lprhodes/homebridge-broadlink-rm#10]
Hi all,

May I know all available types supported? 

In the sample config, there are on, thermostat, and channel. Any other supported types? Any link or reference would be helpful as well. 

Btw, I am using a thermostat-typed accessory to control my aircon. Despite modes and temperatures, can I have control on other stuff like fan speed? 
My current workaround is to map different temperatures to different fan speeds. For example, temperature16 is mapped to 22 deg C with high fan, temperature22 as 22 deg C with medium fan, temperature30 as 22 deg C with low fan. 
I'd like to know if you have better solutions. 

Thank you.

**Comment by lprhodes** [comment]
Those are the supported types at this time. I’ll be expanding as I receive requests and have time. The ability to use the volume type will be coming this week.

Because the fan speed, temperature and mode all get put into a single IR code the only solution I can think of that would work simply is to have a matrix of temperature/fan speed combinations (and potentially modes too). That would take a long time to learn every code combination, though I could create a specific air-conditioner learning tool that would help speed things up by requests each code in turn and outputting the config at the end.

Perhaps if you can find the exact IR hex value that is changing depending on what speed is set then we could use that as a modifier. We’d then have one switch for temperature and one for fan speed. This would be ideal…I haven’t looked for it in my own since I started decrypting the hex codes so I’ll take another look tomorrow and see what’s possible.

**Comment by mikecc2008** [comment]
Hi @lprhodes 

Thank you so much for the reply. 

I thought types were limited by HomeKit API previously which is not true. Modes (off/heat/cool/auto) available in Home app are defined and implemented in ThermostatService.js. So we can actually implement our own Characteristic indeed. Am I correct? IR code of each combination needs to be learned one by one as you said, which might be quite time-consuming and troublesome though.

I haven't find out any trivial pattern for the changing IR codes yet. But this is not a big issue IMAO. I'd rather learn all combinations one by one instead. And I can skip most combinations that I will never use like 16 degrees and 30 degrees. 

Codes below are IR values all for 22 deg C and different fan speeds of my aircon. I haven't figure out any pattern. 

1 bar:
26004c026f3b0b2e0c2c0c110b110c110c2c0d100c110b2d0c2d0b110c2d0b120c100c2c0c2d0d100c2c0d2c0b120b110b2e0c100c110b2d0d100b110c110b110c110c100d100d100b110c110c100d100b110d100c100c110b110c100c110b120c2c0d100c100d100d0f0d100b2e0d2c0b110c110b110c110b2d0d2c0c100d100b110d100b110d100b2d0c2d0b120c2c0d2c0b120b110c2d0d100c100b2e0c100c2d0c2d0c100b120b110c2d0b110c110b2d0e0f0b120b110c100c110c100c110b110c110b110d100c100c110b110c110b120b110b120b110c110b110b120b110c110b110c110c100d100b110c110b110c110c110b110c110b110c110b110b120c100b110d100c100c110b110c110c100c110c100c110b110e2b0c2d0c100e2b0c110b110c110b00023a743a0d2c0c2c0d100b120b110b2e0d0f0d100c2c0c2d0c110b2e0c100b120b2d0c2d0c110b2d0d2c0c110b110d2c0b110c110c2c0d100c100c110b110c110c100c110d100b110c110c100c100c110b110d100b110c110b110b120b110c2d0c100c110c100c110c100c2d0c2d0c100c110b110d100b2d0d2c0b120c100b120b110c110b110c2d0b2e0c100c2c0c2d0c110b110b2e0c100c110b2d0d100b2d0c2d0d100b110c110c2c0b120c100b2e0d100b110b110c110b110c110b110d100b110c110c100c110b110c110c100c110b120b110c110b110b120b110d100b110b120c100c110c100d100c100c110b110d100b120b110b120c100b120b110c110b110b120b110b110c110b110d100b120c100b110c110d2c0b2e0c100c2d0b110c110c100c000d050e2b0c2d0c100e2b0c110b11
2 bars:
26004c026f3a0c2d0d2c0c100d100b110d2c0b120c100c2d0b2d0d100b2d0d100b110c2d0b2e0c100c2d0d2c0b110c110b2d0c110c110c2c0c110c100c110c110b110c110b110d100d100d0f0d100b110c110b110d100c100d100b110c110b110d2c0c100c110b110c110b110c2d0d2c0c100c110b110c110c2c0d2c0c100d100b110c110b110d100c2c0c2d0c110c2c0d2c0d100b110b120c2c0d100c2c0d100b2d0d2c0c110c100c100c2d0c110b110b2e0c100d100b110c110c100c110b120c100c110c100b120c100b110d100b120b110b110c110c110b110b120b110b120c100c100c110c100d100c100d100b110c110b110c110b110c110c100c110b110b120b110c110c100b120b110b120c100b110c110b110c2d0b2e0c2d0b110c2d0b110d100c100c000233723c0b2d0d2c0c110b110b120c2c0c110b110c2d0c2d0b110b2e0c100c110b2e0c2c0c110b2d0d2c0c110b110c2d0c100c110c2c0c110b120b110b110c110b120b110d100b110c110b110d100c100d100b110d100b110d100b110c110c2c0d100c110c100c110b110c2d0c2d0b110d100c100d100c2c0d2c0d0f0d100b120c100b110c110b2e0c2c0c110d2c0c2c0d100c110c100d2c0c100c2d0c100d2c0b2e0c100c110b110c2d0b110c110b2d0d100c100d100b110c110b110d100b110b120b110c110b110c110c100c110b110c110c110c100b120b110b120b110c110c100c100d100c100c110b110c110c100d100b110d100e0f0d0f0c110b110c110c100c110c100d100b110d100b110d100b110c110b2d0c2d0d2c0c100d2c0c100c110b110d000d050b2e0c2d0b110c2d0b110d10
3 bars: 
26004c026f3b0b2e0c2c0d100c100c110b2d0c110c110c2c0d2c0c100c2d0c100c110b2d0d2c0d100b2e0c2c0d100c110c2c0d100c100c2d0c100c110c100c110c100c100d100c100d100d100c100c100c110c110c100c110c100c100d100b110d2c0c100d100c100c110c110c2c0d2c0c100d100c100d100c2c0d2c0d100c100b120b110c110c100c2d0b2d0d100c2c0d2c0d100c100c2d0c2c0d100c2d0c100c2d0b2d0c110c100d100c2c0d100b120c2c0d100c100d100b120c100b120c100c110b110b120c100c110c100d100c100d100c100c110c100b120c100e0f0b120b110c100d100c110c100c110c100b110d100c100d100c100d100c100c110c100b120b110c110b110d100c100b120c100d100c100c100d100c100d100c2d0c2c0d100c100d100c000232733b0d2c0d2c0c100c110c100c2d0c100c110c2d0c2c0d100b2d0d100c100d2c0b2e0c100c2d0d2c0b110c110b2e0c100d100c2c0d100b110c110c100d100c100c110b120c100c100d100c100c110b110d100b120c100c100c110c110c2c0b120c100c100d100c100d2c0c2c0d100c100d100c100d2c0c2d0c100d100b110c100d100c100c2d0b2e0c100c2d0c2d0d0f0d100c2c0d2c0d100c2c0d100c2c0d2c0c110c100c110c2d0c100c110c2c0d100d100c100d100c100c110b110b120c100d100c100c110c110b110c110c100c100d100c100d100c100b120b110c100c110c110c100c110c100c110b110c110c100c100c110c100d100b110c110c110c100d100c100d100c100c110c100c110c100c110c100c110c100c2d0c2c0d100d0f0d100c000d050c100d100c2d0c2c0d100c10
4 bars: 
26004c026f3b0b2d0d2c0c100d100b110c2d0c110c100d2c0c2d0c100b2e0c100b120b2d0d2c0b120b2d0c2d0c110b110d2c0c100c110b2d0d100c100d100b110d100c100c110d100b110c100c110b120b110d100b110c110c100c110c100b120b2d0c110c110b110c100c110c2d0b2d0c110b120c100b120c2c0b2e0c100d100d100b110b120b120b2d0c2d0b120c2c0d2c0c110c100c110c100d2c0c2c0c110b2e0b2d0d100c100e0f0d2c0c110b110c2d0b120c100b120b110d100c110b110c100d100b110c110b110c110b110d100c110c100c110c100e0f0c110b110c110b110d100b110d100b110c110c100b120b110b120b110c110b110c110b110b120c100b120c100b120c100c110b120c100c110b110c100c2d0d0f0c110c2c0d2c0c100d100b110c000233723c0b2e0c2c0d100b110c110b2e0c100b120b2d0c2d0c100c2d0c110b110c2d0c2d0c100c2d0c2c0c110c110b2d0d100b110c2d0c100c110b110d100b120c100b110d100b110c110d100b110b110d100c110c100b120b110c100d100c2d0c100c110b110b120c100b2e0c2c0e0f0c110b110c110b2e0b2d0c110c110b110d100b110c110c2c0c2d0c110b2d0c2d0d100c100c110c100d2c0b2d0d100b2d0c2d0c110b110d100c2c0d100b110c2d0e0f0c100d100c100c110b110c110b110d100b110d100b110c110b110c110b120b110d100b110c100d100c100c110b120c100b120c100b120c100b120b110b120c100d100b110c110c100c110c100c110b110d100c100c110b110c110c100c110c100c110c2c0d100b110d2c0b2e0b110c110b120b000d050d0f0c110c2c0d2c0c100d10

**Comment by lprhodes** [comment]
Yea you're right, at the moment I'm setting whether the mode is heating or cooling based on which temperature has been selected - just so that fits well visually.

I found a service called [Service.HeaterCooler](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2730) which has the option of setting speed but unfortunately it doesn't allow you to set a target temperature so there'd need to be a second accessory that set the fan speed.

I couldn't find any pattern in the codes you sent either, perhaps they're encrypted or hashed somehow. but to learn 10 fan speeds for 15 temperatures and 3 modes would be 450 codes. I'm not sure I have the patience. 

Personally I just have the air con cooling or heating rather than maintaining a specific temperature hence the implementation you see here - not very efficient though.

**Comment by jat80** [comment]
@lprhodes can't wait for volume control. Thanks for all your hard work. :)

**Comment by lprhodes** [comment]
@jat80  I've added volume support in 1.0.0 - it's not exactly what I want but it's as good as we can get with IR and HomeKit right now.

Please read the release notes https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.0.0

**Comment by jat80** [comment]
Thanks @lprhodes.  A great update and very informative.  A quick question -   Can I just have the volume up and down accessory for the TV or do I have to have the on/off as well?

**Comment by lprhodes** [comment]
@jat80 They're completely flexible so you can use just one if you like.

**Comment by jat80** [comment]
@lprhodes perfect. Thanks for the quick response.  Just updating the plugin now to try it out :)
