### ISSUE TITLE
How to overriding the homebridgedirectory with Systemd automatic start up?

### ISSUE THREAD

**Issue by guagsak** [lprhodes/homebridge-broadlink-rm#100]
I can run the this plugin perfectly when using the homebridge as normal (/home/pi/.homebridge directory).

However, when I try to run on systemd setup when the homebridge directory is /var/homebridge. It is not working. I saw the section in the wiki to overriding the homebridgedirectory with key/value, but I don't know to do it.

Can anyone explain me how to do it or have an example?

Thank you.

**Comment by anvial** [comment]
Hi, have you find the solution of this problem?
