### ISSUE TITLE
no device found.

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#102]
the plugin cannot find the device after a router reset, here is the log:
`May 21 17:04:25 raspberrypi homebridge[9510]: [5/21/2017, 5:04:25 PM] [Broadlink RM] Tree Lights sendData(no device found at 10.0.0.4)`

I can see the device connected to my router on that exact IP and I can control it from another plugin I made sending udp packet to this specific IP.

I'm also using homebridge-broadlink-platform and we found out that sometime you need more than one call to the device to find it, once in a second  to send `b.discover` command.

Please help!

UPDATE: it only happens every once and then...

**Comment by lprhodes** [comment]
The plugin isn't constantly discovering, it discovers the devices on load. If the devices doesn't exist on load then it will never see it whether the IP is hard-set in the config or not.

How often are you resetting the router for this to be an issue?

**Comment by nitaybz** [comment]
happens when the electricity drop sometimes, or when the router need a restart

**Comment by lprhodes** [comment]
Happy to receive a pull request for this but it's not something I'll be working on sorry

**Comment by nitaybz** [comment]
Ok I'll work on it

**Comment by lprhodes** [comment]
I had an idea for a quick fix with this. Should be fixed with 2.5.9

**Comment by hackruu** [comment]
same problem on first run. homebridge have two network interfaces. when i'm restart homebridge then it won't complain anymore.

**Comment by lprhodes** [comment]
The latest release (3.3.2) includes support for multiple network interfaces.
