### ISSUE TITLE
Problem with Led strip

### ISSUE THREAD

**Issue by Nixontira** [lprhodes/homebridge-broadlink-rm#103]
Hey!

I got a lil problem with configuring my Led Lightstrip... Maybe you could tell me what the best configuration is, because I can't get it to work well.

{
"name":"Lightstrip“,
"type":"light",
"defaultBrightness":70,
"useLastKnownBrightness":true,
"disableAutomaticOff":false,
"onDuration":5,
"data":{
"off":"26005000000121941014101510150f14111410150f1510141138103910390f391139103810391039101411140f161014101410150f3911141039103811390f3910391039101410391000050d0001224b11000d050000000000000000",
"brightness10":"xxxxxx",
"brightness20":"xxxxxx",
"brightness30":"xxxxxx",
"brightness40":"xxxxxx",
"brightness50":"xxxxxx",
"brightness60":"xxxxxx",
"brightness70":"xxxxxx",
"brightness80":"xxxxxx",
"brightness90":"xxxxxx",
"brightness100":"xxxxxx"
}
},

for thee "xxxxxx" I set the code to make the light darker. but if so then my lights won't get lighter anymore, because it doesn't know the code for it. So which code do I have to put in for the dimming?

[this remote I use](https://lh5.ggpht.com/1ZM32b8_tK1xyMdDd_oZdmRj1xEWlM4Mp4R3l3MFnY6eurJPUpf0semo3eMgMCFoPjI=h900)

And is there a way to configure preset colors?

**Comment by lprhodes** [comment]
The light accessory is really intended for accessories where you can set a specific brightness rather than just increase or decrease.

You could use multiple switch-repeat accessories to increase/decrease the brightness by whatever amount you want.
