### ISSUE TITLE
Fan swingToggle

### ISSUE THREAD

**Issue by skyfremen** [lprhodes/homebridge-broadlink-rm#104]
I have added the swingToggle hex for the Fan, However i am not sure how to activate it via the homekit app or via siri. Please advice, thank you.

**Comment by lprhodes** [comment]
This would work in Siri only (not the Home app) but I've no idea what the wording is, sorry @skyfremen

In case it helpers the technical wording on it is "Swing Mode" and disabled/enabled 

You'd be able to control it with the unofficial Home app.

**Comment by skyfremen** [comment]
Able to advice what u mean by unofficial Home app?

**Comment by DJay79** [comment]
#116
