### ISSUE TITLE
Roller blinds closes 10% after reboot of Raspberry PI

### ISSUE THREAD

**Issue by FamJohansson** [lprhodes/homebridge-broadlink-rm#105]
Every time the Raspberry PI reboot my FR roller blinds closes 10%.

Any idea?

**Comment by lprhodes** [comment]
Have you got resendHexAfterReload set to true on that particular accessory?

**Comment by FamJohansson** [comment]
Thanks, that was missing..

**Comment by lprhodes** [comment]
odd - I was expecting you'd need to remove it rather than add it.

**Comment by FamJohansson** [comment]
It still go down 10%

Where should I add the resendHexAfterReload in the config.jason file?
Do you have a example?
