### ISSUE TITLE
Learn RF for blinds 

### ISSUE THREAD

**Issue by FamJohansson** [lprhodes/homebridge-broadlink-rm#106]
Should I leave the config file as this to let the home app learn automatically RF?
          "data":{
            "open":"2600500000012...",
            "close":"2600500000012...",
            "stop":"2600500000012..."

Or should I set it like this?

          "data":{
            "open":"",
            "close":"",
            "stop":""

**Comment by lprhodes** [comment]
I assume you got this working?

There's no learning automatically - you use the learn accessories to get a hex code back.
