### ISSUE TITLE
A Homekit device with several different switches

### ISSUE THREAD

**Issue by SeanJohn888** [lprhodes/homebridge-broadlink-rm#108]
Hello Iprhodes, is it possible that you create a device in which several switches are created?

I would like to integrate several commands into Homekit for my TV, but these have under one device?

Thank you.

**Comment by lprhodes** [comment]
That’s not something HomeKit allows, sorry. The best you can do it use switch-repeat, switch-multi or switch-multi-repeat

**Comment by SeanJohn888** [comment]
Are you sure? I have the Harmony Plugin installed there under one device several switches are created. This should work synonymous for your plugin?

![image2](https://cloud.githubusercontent.com/assets/27686185/26434602/df356e62-4109-11e7-8c8c-7ae6bf2b1436.PNG)
![image1](https://cloud.githubusercontent.com/assets/27686185/26434603/df58f1de-4109-11e7-9f02-02f83a368171.PNG)

**Comment by lprhodes** [comment]
OK I misunderstood.

I don’t see what the advantage is over creating the switches separately though?

**Comment by SeanJohn888** [comment]
The advantage is that under one device in Homekit several switches are displayed.

Example:
Living room:

Device - TV
Switch On / Off
Switch channel change
Switch Play / Pause

At the moment it is so that every switch in the room is displayed and not under a device.

I hope it is more understandable now

**Comment by SeanJohn888** [comment]
It would make the rooms clearer. Especially for devices which have several commands, but for which different switches are needed.

**Comment by lprhodes** [comment]
That's seems specific to the app you're using. The official Home app (and unofficial Home app) don't group this way.

It's a lot of work for not much gain - it's not something I'll be working on sorry

**Comment by SeanJohn888** [comment]
The grouping is the same as the other Homekit apps. It has nothing to do with this app.

This is part of the description of the Harmony Plug:

As part of this, how your activities show up in HomeKit are very different. Each hub will now properly show up as a single device in HomeKit instead of a device for each activity. That device (accessory) for the hub will contain a switch for each activity on that hub

**Comment by lprhodes** [comment]
You sent an image of a UI that groups switches by accessory. This is specific to the app you’re using; the Home app doesn’t group devices like that.

Can you explain how the multiple switches within one accessory is an advantage in the offical Home app?

**Comment by SeanJohn888** [comment]
I have looked again in the Apple Home App. You're right there, the switches are not grouped. I was sure it was there.

Then it is really only in the app I currently use. (Http://www.homedash-app.com)

Would be a really nice function, which would make it much clearer.

**Comment by SeanJohn888** [comment]
Sorry for the inconvenience

**Comment by lprhodes** [comment]
Is there a "Light" theme on that app - it looks nice but way too dark for my liking

**Comment by lprhodes** [comment]
I personally never go into any of the apps as the Control Center widget (Swipe up then right twice) feels easier to get to.

**Comment by SeanJohn888** [comment]
No there is not at the moment. 
It is definitely the most beautiful and clearest homekit app.
I will pass the idea but to the developer of the app, he also comes from Germany. There will be a big update very soon. We are just testing the beta.

The developer also ordered a Broadlink hub yesterday and will use your Window Covering soon. The world is a Village :-)))

I can only recommend you to test the app times is really great. -)

**Comment by lprhodes** [comment]
I'll give it a go thanks - is there a Notification Center widget?

**Comment by SeanJohn888** [comment]
Yes there is. 

![img_1509](https://cloud.githubusercontent.com/assets/27686185/26435683/3fcf1b4a-4111-11e7-9449-5d0d17faff66.PNG)

**Comment by lprhodes** [comment]
How is that so ugly when the rest is so nice?! Ha :)

**Comment by SeanJohn888** [comment]
I will pass it on 😂
