### ISSUE TITLE
Clarifying Documentation and Properties

### ISSUE THREAD

**Issue by bdill12** [lprhodes/homebridge-broadlink-rm#109]
There are multiple instances in the readme file where the explanations aren't as helpful as they could be, especially in the descriptions for the properties.

For example:
persistState and resendHexAfterReload are confusing. 
`    When persistState is true (it is by default) this will resend the hex code for the last known state if homebridge is restarted.`
Does that mean the Broadlink will send the code to the accessory again after homebridge starts up? Or does that mean it will send a code to HomeKit? 
disableAutomaticOff is confusing as well. If the value is set to false, then it is a very confusing double negative because "disableAutomaticOff: false" makes it seem as though I am not changing anything. "enableAutomaticOff: false" would make more sense as a default because the user is not changing any behavior. Is there a reason why this property needs a verb at the beginning? Could it be changed to "automaticOff" to avoid the confusion? "automaticOff: false" would be the default and if the user wanted the switch to turn off automatically, he or she would set "automaticOff: true"

I'd be glad to give the readme an edit to reduce wordiness and clarify things once I understand how it works.

**Comment by lprhodes** [comment]
How come you closed this?

**Comment by lprhodes** [comment]
Documentation cleared up a bit - I'll be going through and updating properties during a more significant refactor
