### ISSUE TITLE
dev.on("deviceReady", () => { this.emit("deviceReady", dev); });

### ISSUE THREAD

**Issue by lily148** [lprhodes/homebridge-broadlink-rm#11]
When I tried to run the homebridge, it throw me this error. May I know what happen?
dev.on("deviceReady", () => { this.emit("deviceReady", dev); });
               ^

TypeError: Cannot read property 'on' of undefined
    at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:183:16)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:545:8)
root@mediahub:~/.homebridge# dev.on("deviceReady", () => { this.emit("deviceReady", dev); });
bash: syntax error near unexpected token `"deviceReady",'

**Comment by lprhodes** [comment]
Sounds like you have an unsupported device or perhaps the wrong IP address for the device. What broadlink rm device do you have?

**Comment by lily148** [comment]
I am having RM Pro but the code is not inside your index.js. I temporary change the last line
else{
...
dev.rm();
return dev;;
}
then the problem resolved. The IR is working but the RF is not working...
I will try to get the devgeneration code for you.
