### ISSUE TITLE
[Question] fan speed

### ISSUE THREAD

**Issue by DJay79** [lprhodes/homebridge-broadlink-rm#110]
@lprhodes First of all thanks for your work and sharing this great and helpful plugin.
I'm relatively new to homebridge but thanks to the good documentation of this plugin I was able to configure it and adding my fan. 
The fan (Balmuda GreenFan Cirq), has three buttons on the original remote. Up, Down and Power toggle. No swing option, so I just removed the line in the config.json

But because of only four possible speeds of the fan I set up 10-50% to (-) and 60-100% to (+) hex. Any more elegant suggestion on this? Four LED on top of the fan indicates the speed.

Thanks in advance for your help and reply.

**Comment by lprhodes** [comment]
Not really, sorry...I'd probably set these up as one of the switch types

**Comment by benvallack** [comment]
I'm wondering about how to translate the percentage to the incremental buttons too. Have you considered firing multiple (-) followed by the correct number of (+) so it always counts up from the lowest level. i.e you setup the 75% speed (speed three) to do this: 

(-) (-) (-) (-) (+) (+) (+)

That way it will always get it right no matter what the current speed is.
