### ISSUE TITLE
Window Cover Slider

### ISSUE THREAD

**Issue by Nastras** [lprhodes/homebridge-broadlink-rm#112]
Hello Iprhodes,

I know we have already talked about the development of the window cover.

Is it somehow possible that you at 0 and 100 per cent at the slider the calculation take out and the window cover completely on or to drive?

Maybie as an additional option which is turned on in the config?

I have the following problem at the time:

I have fixed switches these are also radio receivers. My wife does not like to use Homekit and always uses the original switch.

If my wife pressed the window cover over the original switches in Homekit the status is no longer and an operation is then no longer properly possible.

That's why I can not use the window cover tool at the time of you and had to switch to the switch solution. Now I can only completely switch on, or stop with two switches.

Even though we've done so much work. "

I hope you may have an idea and can help me there.

Thank You!!!

Have you already tested the Homekit app I showed you at our last talk? Today is release a big update with the new Dashboard function.

I have now a few codes for the app store if you want I'll send you one?

**Comment by SeanJohn888** [comment]
With this function it would be possible to adjust the status in homekit without extra switch

**Comment by lprhodes** [comment]
Is this fixed with the new `sendStopAt0` and `sendStopAt100` options?

**Comment by Nastras** [comment]
Hello Luke,

Unfortunately I did not get to test the new function before.

Now I have tested it though .-)

It's not like I imagined back then.

I'll try to explain it again

if the shutter manual was operated and in reality stands at about 50%, the status is no longer the same as in HomeKit.

In HomeKit is assumed after manual operation a status of 100%

Now there is no way to set the shutter back to 100% on Homekit.

For this, the slider in HomeKit if set to 0 or 100% should also always send the command for 0 or 100% without calculating where it stands.

The shutter in reality will have an end stop on this one, they will always stop when they fully retract or extend and reach the end.

The idea would be either to set the slider to 0 and 100% to send a start and stop command without calculation.

Another possibility would be if you would install an additional switch under the slider as a separate feature. This switch could be assigned the Start and Stop command and is independent of the slider.

This could also fix the wrong status after a manual operation in homekit.

I hope it is understandable?

Thank !

**Comment by lprhodes** [comment]
I believe v2.7.2 should have what you need

**Comment by Nastras** [comment]
Hey Luke,

I wanted exactly this function. Thank you very much!

**Comment by carolinomv** [comment]
Hello,

What code are you using for this accessory? Is the status already updated after acting manually? Mine has no stop button. To stop I use the up or down button as the case may be. You have a solution for this.
Thanks.
