### ISSUE TITLE
TC2 setup

### ISSUE THREAD

**Issue by 7mllm7** [lprhodes/homebridge-broadlink-rm#115]
This might be a very stupid question (or a suggestion to improve the docs).
I can't seem to understand how to add a TC2 switch as an accessory.
I've got the `homebridge` server running and added the "platform" accessory to the Home app on my iPhone.
This is my `config.json`:
```
{
  "bridge":{
    "name":"Homebridge",
    "username":"CD:22:3D:E3:CE:30",
    "port":51826,
    "pin":"031-45-156"
  },
  "description":"Homebridge",
  "accessories":[

  ],
  "platforms":[
    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "accessories":[
        {
          "name":"My Switch",
          "type":"switch",
          "disableAutomaticOff": false,
          "onDuration": 5,
          "data":{
            "on":"2600500000012...",
            "off":"2600500000012..."
          }
        }
      ]
    }
  ]
}
```

Besides the predefined "Learn" and "Scan-Frequency" accessories, the configuration also added the "My Switch" `switch`.

Now my question is how do I find the `on`/`off` HEX codes in the `data` section?
I tried both the "Learn"  and "Scan Freq" options, but nothing happened in the log, and I tried playing with the RM Pro 2 and TC2 switch (turn on/off by touch, with Broadlink iPhone app, entering learn mode for the switch (long press), and basically anything I could think of.

Your guidance would be appreciated!

**Comment by phenix13** [comment]
add a "learn-code"  switch into your config.json ,then run "homebridge" on pi and open HOME app on you iphone , you can see a switch named "learn",when you open it ,you can make it learn code, then  you can see HEX date

**Comment by phenix13** [comment]
i have add a switch which style is "garage-door-opener" in my config.json ,but when i open it , it always auto close ,how about your?

**Comment by 7mllm7** [comment]
I'm not really using `garage-door-opener`, but I'm guessing it's got to do with the `autoCloseDelay` field that maybe should be set to `false`.

**Comment by 7mllm7** [comment]
Like I wrote, I did everything that you suggested, what I'm asking is then ext step - how do I make it learn? I turn on learn mode, now what??

**Comment by phenix13** [comment]
open "learn" switch then push button face toward the broadlink rm pro, then you can see a hex code in the homebridge control windows, copy the code and add it to you configuration film,then reboot homebridge and use it .

**Comment by 7mllm7** [comment]
@phenix13, I'm sorry but I don't think you understood what exactly I'm asking.
TC2 is a smart switch made by Broadlink that communicates with the RM Pro via RF signals.
The HEX code I'm trying to find is the one that is sent from the RM Pro hub to the TC2 in order to turn it on/off.

How do I find out the RF HEX code that is sent out from the hub to the TC2? Again, I tried entering the `homebridge` server into learning mode and make the hub send the signal, but nothing is read.

Thanks!

**Comment by lprhodes** [comment]
I assume you read #88 and #69?

**Comment by lprhodes** [comment]
...from what I can tell you'd need to learn the TC2 into another RF remote and use the broadlink RM to learn from the remote.

**Comment by sendorm** [comment]
Hello you can get the codes through Broadlink RM Plugin Lite in your android phone. Emulators also work. Just setup your e-control app and then use the Broadlink RM Plugin Lite to get the codes. there is a tutorial on [https://narongdej.sarnsuwan.com/blog/2017/02/19/Control-Broadlink-TC2-through-python/](url). If you are using ios for e-control, just make a backup and download that backup from you android emulator's e-control app.

**Comment by lprhodes** [comment]
Closing given the thumbs up on @sendorm's solution

**Comment by Referor** [comment]
Another way, but you still need 2 devices and RM Pro plus (this way work for TC2) for me:
1. First IOS device(to control e-control app). In your e-control application you need to have already educated TC2 remote / TC1 remote. 
2. Second IOS device with homekit and homebridge with scan_frequency function (to control your homebridge) / Mac (OS Mojave beta have home kit application)
Algorithm:
1) You need to start "Scan_frequency" in your homebridge with second device
2) You need to push the preferred button at your first device several times
And you can add buttons step-by-step to your homebridge. 
I think we can use this algorithm because RM Pro can scan frequency and send frequency in same time. We start scanning process and then we send some RF frequency in this one RM Pro plus device

**Comment by 7mllm7** [comment]
So... back in 2018 I asked this question, and then found a solution - however, I did not update my solution here.
Now in 2019 I encountered the same issue, and from Google reached this same thread, and was mad at myself for not posting anything...

KARMA!

The problem was basically finding my Broadlink's "remotes" (TC2) RF frequency, so I can add them to my `config.json` file.

So here is how I solved it (using my iPhone and Mac):
1. Add remotes (again, in my case TC2) to Broadlink e-Control app (I did it from iOS, install it if needed)
2. Plug iPhone to computer and create iTunes backup
3. Copy iTunes backup from [its location](https://ccm.net/faq/12901-how-to-find-your-itunes-backup-folder) to some readable place on your harddrive (otherwise next step will fail due to permissions)
4. Download and install [iExplorer](https://macroplant.com/iexplorer), and use it to explore the created backup
5. Locate and export the _cn.com.broadlink.e-Control_ folder to somewhere on your harddrive
6. Open _BroadLinkDeviceList.sqlite_ in some [ online SQLite browser](https://sqliteonline.com/)
7. Get relevant `subirID` by `SELECT * FROM 'broadlink_subir';` based on the name of the remote in the app
8. Get buttons by `SELECT * FROM 'broadlink_button';`, where the `subirID` is what you identified in previous step
9. Get hex codes by `SELECT buttonid, lower(hex(code)) FROM 'broadlink_code';` - these are the hex codes of all of the buttons, and you'll need the ones you're trying to add
10. In my setup, SSH to your Raspberry Pi (`ssh pi@192.168...`)
11. `cd /var/homebridge`
12. Backup _config.json_ `cp config.json config.old.json` - remember that if you do it more than once then you'll overwrite the previous backup each time
13. Copy hex code from SQLite and paste it *TWICE* inside _config.json_ (my preference is `vi /var/homebridge/config.json`) - add remote entry in JSON if needed, as appear in the documentation. Twice means if your code is `"ABCD"`, then the code that you'll paste inside _config.json_ will be `"ABCDABCD"` - yup!
14. `sudo systemctl restart homebridge` to restart service

And that's it - that's how you get the RF frequency HEX
