### ISSUE TITLE
Learned codes do not work

### ISSUE THREAD

**Issue by det-box** [lprhodes/homebridge-broadlink-rm#118]
Hi, I would like to switch a Sony AV Receiver.
With the original remote control (RMT-AA320U) and a Logitech Elite everything works.
Here the codes for Power on / off:
RMT-AA320U: 26006600501329121512291315122912151315121512151315121513281329121512150002c1501328131512291215132912151215131512151315121513281328131512150002c150132813151229121513281315121513151215131512151229132813151215000d050000
Logitech: 260066004f1329121216261512152417131413151314141314141413271427141413130002c64e142714141427131315261a0f1314141215141314141116271427141413150002c34f142615151226151315271413141314141512141513121625152813131414000d050000

Both codes do not go with the broadlink-rm!

addendum:
This code switches the FS and AV receiver on / off with the broadlink-rm.
260054004f14271413142714131527131315131428131314131514131400034e4e14281314142714131428131414121527141314141414131300034f4e142813131527141314271414141314271414131414131413000d0500000000

I am grateful for any help.

**Comment by lprhodes** [comment]
I'd suggest confirming that they work with the official broadlink app first.

**Comment by det-box** [comment]
The idea is good,
I will test

**Comment by det-box** [comment]
Hello,
successfully all tests.

after the test with the APP it comes at a time.
Thanks again.

**Comment by scorpioRED** [comment]
Hi! maybe you can help me with setup this plugin with RM 3 Pro.
I have installed homebridge and this plugin, then I runned homebridge with command `sudo homebridge` and console show me pin code,  in Home app I added "homebridge", but it`s have grey color, it`s not active.... how I can start lear code and add my TV to Home app?
