### ISSUE TITLE
AirCon implementation

### ISSUE THREAD

**Issue by ageorgios** [lprhodes/homebridge-broadlink-rm#123]
Thank you so much for the great work!

Although I would like to have the standard configuration of the Homekit airconditioner.

To make myself clear, I would expect this kind of configuration:

{ 
cool: hex-data
heat: hex-data
auto: hex-data
off: hex-data
}

and would expect the temperatures do not change the heatingcoolingstate at all.

I would also like if you could implement a 
{
fan: hex-data
}
that would emulate a fan accessory for the airconditioner

**Comment by ageorgios** [comment]
see https://github.com/lprhodes/homebridge-broadlink-rm/pull/126

**Comment by lprhodes** [comment]
So you're lucky enough to have an aircon that doesn't send all the information (mode, swing, temperature) in every single IR command? Which AC is it?
