### ISSUE TITLE
scan frequency remove

### ISSUE THREAD

**Issue by ageorgios** [lprhodes/homebridge-broadlink-rm#127]
how can I remove the scan frequency button because i have incompatible hardware?
(rm3 mini)

**Comment by nitaybz** [comment]
you can delete directly from the Home app

**Comment by ageorgios** [comment]
I am not sure you can do that. 
Please clarify if I am wrong.

**Comment by nitaybz** [comment]
for some reason I remembered this option is available, but I guess you are right... can't find it

**Comment by lprhodes** [comment]
Not at the moment sorry

**Comment by lprhodes** [comment]
Added "hideScanFrequencyButton" and "hideLearnButton" to  2.5.12. Check out the config-sample.json for an example on how to use it
