### ISSUE TITLE
Sending Off command when the switch is off

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#128]
I've noticed that the plugin will not turn off/on a switch when it's already in that state,
sometimes accessories are controlled outside of the Home app like TV, RF switch etc... and when I want to tell Siri or set in scene to turn it off/on, it will not always send the command.

it would be great if this is something that can be controlled in the config like:
"sendAlways": true

Thanks!

**Comment by ageorgios** [comment]
try with "allowResend": true
on the accessory configuration

**Comment by nitaybz** [comment]
I will try this, didn't see in the Readme file, Thanks!

**Comment by lprhodes** [comment]
https://github.com/lprhodes/homebridge-broadlink-rm/issues/93
