### ISSUE TITLE
Step 3: Update your configuration file. (See config-sample.json)

### ISSUE THREAD

**Issue by Amansomal** [lprhodes/homebridge-broadlink-rm#129]
Hi Luke, 
Im stuck at step 3, Update your configuration file.
After installing the RM plugin when I run the home bridge server, it lists the MAC address of my Broadlink Pro, so it is talking but thats where I'm stuck, unsure about what to do next.
![screen shot ](https://user-images.githubusercontent.com/29544133/27286384-1c47376a-553f-11e7-8ab9-4d3fc917f498.png)
I am hoping you can help me with this.
Regards,
Aman

**Comment by lprhodes** [comment]
You should be able to add this accessory to the Home app. You'll then see a button for "Learn" in the Home app. Turning the "Learn" button on will start the learning process. You'll see instructions in the Terminal app when you do.

You can then learn an IR device and the code will show up in the Terminal app. 

You can then look at the README file and the config-sample file to see how you can use the codes to create different types of accessories.

**Comment by Amansomal** [comment]
Thank you for your quick reply. 
That is what I thought should happen. But I only see Default root home bridge in the Home app. once I add it, it is greyed out. There is no learn button showing. here is a better screenshot.

**Comment by Amansomal** [comment]
![screen shot 2](https://user-images.githubusercontent.com/29544133/27286849-c690b39e-5540-11e7-8e8c-cdc833aaa05f.png)

**Comment by Amansomal** [comment]
in the terminal window nothing shows after the last line in the screenshot "Discovered Broadlink.....
". Nothing happens afterwards. Am I missing something in the config?

**Comment by Amansomal** [comment]
![img_4865 png](https://user-images.githubusercontent.com/29544133/27287054-a1cfc436-5541-11e7-9d86-9a5495b8f231.PNG)

**Comment by Amansomal** [comment]
Hi Luke,

After a steep learning curve, I was able to get one step closer; I am now able to scan IR codes and they work.
However, when I press the Scan Frequency button, I get the following error:
Scan RF (RF Learning not supported for device at undefined)

Are you able to help me with this please? I am using an RM Pro and RF functionality is working with the normal econtrol app.

**Comment by lprhodes** [comment]
Hi @Amansomal can you open that as a separate issue please.

**Comment by dmarinb** [comment]
Hi @Amansomal how do you fix the problem, I am stuck in the same part has you
