### ISSUE TITLE
RF sending

### ISSUE THREAD

**Issue by lily148** [lprhodes/homebridge-broadlink-rm#13]
how do I send the RF code to my broadlink? I have the code but it is not working.

**Comment by lprhodes** [comment]
In issue #11 you said you were seeing an error, did you get any further than this?

**Comment by lily148** [comment]
I solved the issue at issue #11, but the FR still not working. My IR is working, code learning also works..

**Comment by lprhodes** [comment]
Ah I see, there's no support for RF at the moment, sorry. I'll need to create a learner for that so you can get the unencrypted hex code.

**Comment by lily148** [comment]
I actually already extract the unencrypted hex code from my broadlink. I am working on that to see what can I make it work. Will update the status if it works.

**Comment by lily148** [comment]
Okay, found the way to submit the RF and it is working now.

**Comment by lprhodes** [comment]
@lily148 Was there anything special you needed to do?

**Comment by lily148** [comment]
I extract the RF code using an Android device.
then when send code, I just duplicate the RF code in a single HEX data. Example as below.
RF for switch on= 091159103...
data: [091159103...091159103...]

This work perfectly.

If you can implement a RF learning then it will even better.

**Comment by lprhodes** [comment]
@lily148 Have you tried just using the Learn IR method to learn RF? Supposedly it should work the same but I'm looking for confirmation

**Comment by lily148** [comment]
I tried the normal Learn IR method, it is not working. As what I understand, RF learning should obtain the frequency first before it can proceed to learn the command.
