### ISSUE TITLE
Controlling volume (television / sound system)

### ISSUE THREAD

**Issue by 7mllm7** [lprhodes/homebridge-broadlink-rm#133]
Hi,

As you know, Broadlink's eControl app allows IR control for televisions / sound systems (i.e. receivers).
One of the best features is controlling the volume through the app (attached screenshots).
![img_0182](https://user-images.githubusercontent.com/7550012/27510959-38823f5e-5924-11e7-98fe-f6f9f5bc5575.PNG)
![img_0183](https://user-images.githubusercontent.com/7550012/27510960-388a88a8-5924-11e7-992a-b21b01f40997.PNG)

What is the best option to achieve such control?

**Comment by sendorm** [comment]
You can create a switch called tv volume up and use the same code of volume up for both on and off commands of the switch. That way, you can quickly turn off and on the switch to increase the volume. 
Do the same thing for volume down. 

With the current homekit, this is what i would use.

**Comment by j796160836** [comment]
So there is no stateless switch, right?

**Comment by j796160836** [comment]
I found we can do a auto off switch to do act as a stateless switch.

```
{
  "name":"Volume Up",
  "type":"switch",
  "enableAutoOff": true,
  "onDuration": 0.3,
  "data": {
        "on": "260048000.....",
        "off": ""
  }
}
```
