### ISSUE TITLE
Apple TV 4. Gen. command doesn't work

### ISSUE THREAD

**Issue by DJay-X** [lprhodes/homebridge-broadlink-rm#135]
I tried to configure a new switch to control some functions of Apple TV.
With my Harmony Elite Remote and Hub this works. Unfortunately I can't bring broadlink-rm to do so.
When learning a Code from the Harmony I can see the learned hex code but when in the config.json and switching it on, nothing happens.

The following code is for example from the Home/Menu Button.
Any suggestions? Thx.

[Broadlink RM] Learn Code (learned hex code: 2600a8000001279413121237133712371213133614361237143513371435131214111412131212371336133714111214111313121214111315341412121411131214121213121312130005940001284912000c4f0001264a13000c4f0001264a14000c4d0001284915000c4c0001264a14000c4e0001264a13000c4e0001284914000c4d0001274913000c4f0001264a13000c4e0001284716000c4d0001284912000c4f0001274914000d05)

**Comment by lprhodes** [comment]
I assume you don’t mean the latest Apple TV? It doesn’t use IR to send anything but the volume command as far as I know

**Comment by DJay79** [comment]
Hi Luke. Yes, it's about the latest Apple TV 4.
Harmony can control it. And as mentioned when I learn the code with your module from the Harmony, I get this hex of the Home/Menu Button.
Also in the iOS Broadlink e-Control App I can add directly the Apple TV as a device and this also works. So I assume it is regular IR code.
Is there a way to see the hex code that e-Control uses? But strange, that the hex code from the Harmony works on the Apple TV but not when placed in the config.json with your module.

**Comment by sendorm** [comment]
Try doubling(pasting it twice) the hex code.

**Comment by DJay79** [comment]
@sendorm Thx. You mean just in a long row?

I did this, but unfortunately didn't change anything.

{
                                 "name":"Display",
                                 "type":"switch-multi",
                                 "interval":10.0,
                                 "disableAutomaticOff":false,
                                 "data": {
                                 
                                 "on": [ "2600a8000001279413131237133612371412123713361336143613371137141213121214111313361337123712141113131312131312121313361412111312141212131313121312120005950001274913000c4e0001274a12000c4f0001264a14000c4e0001264a14000c4d0001284913000c4e0001264a13000c4f0001264a12000c4f0001274a12000c4f0001264a14000c4e0001264a14000c4d0001274a12000c4f0001274914000d052600a8000001279413131237133612371412123713361336143613371137141213121214111313361337123712141113131312131312121313361412111312141212131313121312120005950001274913000c4e0001274a12000c4f0001264a14000c4e0001264a14000c4d0001284913000c4e0001264a13000c4f0001264a12000c4f0001274a12000c4f0001264a14000c4e0001264a14000c4d0001274a12000c4f0001274914000d05"
                                        ],
                                 "off": [ "260050000001269416101213133612131312141114111412133612371312143613361237143613361312131214361313111312131336131213371336131312371336123713121337120005280001274914000d050000000000000000"
                                         ]
                                 }
                                 },

**Comment by sendorm** [comment]
@Djay79, glad it worked. No problem.

**Comment by ageorgios** [comment]
I think it would be great if you shared the codes for those that do not have the harmony remote control but have an apple TV!

Thanks!

**Comment by DJay79** [comment]
@ageorgios  My pleasure.. ☺️ here you go. Quick and dirty. 😬

Home
2600a8000001269511131337123712371213133712371237143613361435141114121214121212371237143713111312131311131413111312371313111312131213131313121213120005940001284913000c4e0001274a12000c4f0001274914000c4d0001274a12000c4f0001274a12000c4f0001274913000c4f0001274913000c4e0001274a12000c4f0001284814000c4e0001274912000c4f0001284913000c4e0001264a13000d05

Menu
260050000001269513121237133614361312123714361337123613371237131212131313121213371238123713111412121412131113131313361312121313121214111312131213120005950001264a13000d050000000000000000

OK
260098000001289b11151139103a11381313123812391139103a113912381214101510151015103a121410151139113911391015113912141138111511150f1510151114111510141100054d0001279c111411391239103a1114113911391239113a103912381115101413131015113a0f3a1114123812131214101510160f1511391115101511131115101510160f160f00054e0001284b11000d05

Back
260050000001289312131237133712371312133713371137143613361237141114121411131213361237153512141212121312141113131312371312141211131214121214111411140005930001274b11000d050000000000000000

Up
260050000001279413131137133713371213123614361336133613381137131311141212131214371212123713121338111312131313111312371511131212141114121311131312130005940001274a13000d050000000000000000

Down
260050000001279414121137143612371411123812371237133712371435131314101412121312371214111313361337131311131312131213371313111411131313111411131313120005940001274a13000d050000000000000000

Left
260050000001289312131337133612371412123614361237143614351238131212131312131213361336141213121237121411131312141213361312121313131312121312121313120005940001284913000d050000000000000000

Right
260050000001279314121237123713371214133513361436123713361436131311141312121213371214113713361312131411131510141112371412121312131312111413121213120005950001274917000d050000000000000000

Play
260098000001299a1213113a103a103a1214103a103a103a103a103a14361214121310151015103a113912381238113a1139121411381213123912131213101511141115101412141000054d0001279c1213113a1238103a1114113912381239103a103a123812131213111511151039113912141036161211151015111510151138121312140f151214101510160f151000054e0001274c10000d05

Stop
260050000001269414371114113712141212133712371336143612371336141113131312131313351336141213121214113712381213131212381114121312121312141212131312120005950001264a13000d050000000000000000

Pause
260098000001279c111510391338113911151039113911371439103a113912140f1612131015103a1139123811391239113911150f3a1213113911141214111411141114111411141200054c0001289b11141238123912381015103a1238113a1139113911391114121313121313103a103a1114113911151113121411150f15113911141115111311141213111412141000054e0001284a11000d05

Fast Forward
260050000001289313361411133811131214113713371336133614361336151013121312141212381114133514121435133613131212151015341413121212141113131213121412120005940001274a12000d050000000000000000

Fast Backward
260050000001279313381113133613121411143612371336133713361237141212131312131311381212141113371435123813121213131212371312131213121313121312141213110005950001274913000d050000000000000000

Skip Forward
260050000001289313351413133614121212123812371237133613371237141212131212141213361237133614121312131312361214111313371411131311131214121311141410130005940001274a12000d050000000000000000

Skip Backward
260050000001269512371214113713121313123712371436123712371337121412121312131212371337131311371213141213361213121312371312141213121214131013131312130005940001274913000d050000000000000000

Next Chapter
260050000001279313371213133613131212123713371436133612371336131312131213131212381236133712131313121214361411131213361313111411141114121213131312130005930001274a14000d050000000000000000

Prev Chapter
260050000001269413361213123713131213123712371337133613361536131213121213111313361535121313361412131212371214111313361313121312131313111312141114120005940001264b12000d050000000000000000

Video Mode
2600500000012793131314351237133712131237123713361337123714361213121312141212123713371237123713131336121412121312123615121312121313121313121312121200054d0001264a14000d050000000000000000

**Comment by ageorgios** [comment]
Thank you!

**Comment by lprhodes** [comment]
I'm finding this pretty odd. I wonder how it know when to send the left IR command and when to use bluetooth to send the left inertial scrolling command (on the trackpad)

**Comment by lprhodes** [comment]
Just to clarify, these still don't work for you, right?

Did you ever try learning the remote directly with the plugin?

**Comment by cbek09** [comment]
> @ageorgios My pleasure.. ☺️ here you go. Quick and dirty. 😬
> 
> Home
> 2600a8000001269511131337123712371213133712371237143613361435141114121214121212371237143713111312131311131413111312371313111312131213131313121213120005940001284913000c4e0001274a12000c4f0001274914000c4d0001274a12000c4f0001274a12000c4f0001274913000c4f0001274913000c4e0001274a12000c4f0001284814000c4e0001274912000c4f0001284913000c4e0001264a13000d05
> 
> Menu
> 260050000001269513121237133614361312123714361337123613371237131212131313121213371238123713111412121412131113131313361312121313121214111312131213120005950001264a13000d050000000000000000
> 
> OK
> 260098000001289b11151139103a11381313123812391139103a113912381214101510151015103a121410151139113911391015113912141138111511150f1510151114111510141100054d0001279c111411391239103a1114113911391239113a103912381115101413131015113a0f3a1114123812131214101510160f1511391115101511131115101510160f160f00054e0001284b11000d05
> 
> Back
> 260050000001289312131237133712371312133713371137143613361237141114121411131213361237153512141212121312141113131312371312141211131214121214111411140005930001274b11000d050000000000000000
> 
> Up
> 260050000001279413131137133713371213123614361336133613381137131311141212131214371212123713121338111312131313111312371511131212141114121311131312130005940001274a13000d050000000000000000
> 
> Down
> 260050000001279414121137143612371411123812371237133712371435131314101412121312371214111313361337131311131312131213371313111411131313111411131313120005940001274a13000d050000000000000000
> 
> Left
> 260050000001289312131337133612371412123614361237143614351238131212131312131213361336141213121237121411131312141213361312121313131312121312121313120005940001284913000d050000000000000000
> 
> Right
> 260050000001279314121237123713371214133513361436123713361436131311141312121213371214113713361312131411131510141112371412121312131312111413121213120005950001274917000d050000000000000000
> 
> Play
> 260098000001299a1213113a103a103a1214103a103a103a103a103a14361214121310151015103a113912381238113a1139121411381213123912131213101511141115101412141000054d0001279c1213113a1238103a1114113912381239103a103a123812131213111511151039113912141036161211151015111510151138121312140f151214101510160f151000054e0001274c10000d05
> 
> Stop
> 260050000001269414371114113712141212133712371336143612371336141113131312131313351336141213121214113712381213131212381114121312121312141212131312120005950001264a13000d050000000000000000
> 
> Pause
> 260098000001279c111510391338113911151039113911371439103a113912140f1612131015103a1139123811391239113911150f3a1213113911141214111411141114111411141200054c0001289b11141238123912381015103a1238113a1139113911391114121313121313103a103a1114113911151113121411150f15113911141115111311141213111412141000054e0001284a11000d05
> 
> Fast Forward
> 260050000001289313361411133811131214113713371336133614361336151013121312141212381114133514121435133613131212151015341413121212141113131213121412120005940001274a12000d050000000000000000
> 
> Fast Backward
> 260050000001279313381113133613121411143612371336133713361237141212131312131311381212141113371435123813121213131212371312131213121313121312141213110005950001274913000d050000000000000000
> 
> Skip Forward
> 260050000001289313351413133614121212123812371237133613371237141212131212141213361237133614121312131312361214111313371411131311131214121311141410130005940001274a12000d050000000000000000
> 
> Skip Backward
> 260050000001269512371214113713121313123712371436123712371337121412121312131212371337131311371213141213361213121312371312141213121214131013131312130005940001274913000d050000000000000000
> 
> Next Chapter
> 260050000001279313371213133613131212123713371436133612371336131312131213131212381236133712131313121214361411131213361313111411141114121213131312130005930001274a14000d050000000000000000
> 
> Prev Chapter
> 260050000001269413361213123713131213123712371337133613361536131213121213111313361535121313361412131212371214111313361313121312131313111312141114120005940001264b12000d050000000000000000
> 
> Video Mode
> 2600500000012793131314351237133712131237123713361337123714361213121312141212123713371237123713131336121412121312123615121312121313121313121312121200054d0001264a14000d050000000000000000

Hello,
Thanks for this IR sequence, do you know how to convert them into Discrete Code (for Pronto or Nevo)?
Thanks,
Cyril
