### ISSUE TITLE
Ignore status and resend command

### ISSUE THREAD

**Issue by Giorgiofox** [lprhodes/homebridge-broadlink-rm#136]
Hello,
I'm using a switch to turn on and off my IR device.

My device is also operated by his own remote or remote control. 
My problem is that if I turn on by using remote, I cannot turn it off using home bridge, because his internal status is already off, and this problem happen also If I want to turn it on using home bridge but his internal status is already on. Is very annoying using Siri. 
Can I set is to send command again ignoring his status?

thanks
Giorgio

**Comment by ageorgios** [comment]
This has a fix explained here:
https://github.com/lprhodes/homebridge-broadlink-rm/issues/132

Just use allowResend in your configuration.

I think @lprhodes should write this in the documentation

**Comment by Giorgiofox** [comment]
Perfect thank you
