### ISSUE TITLE
ThermostatService not updating temperature

### ISSUE THREAD

**Issue by clkao** [lprhodes/homebridge-broadlink-rm#14]
Apparently `this.currentTemperature` is always 0, since we are not updating through the rm devices' temperature event.

**Comment by mikecc2008** [comment]
Hi @clkao 

Thanks for your great update. 

I encountered this error when I open Control Center after launching Home app, and vice versa.

0|homebrid | Error: This callback function has already been called by someone else; it can only be called one time.
0|homebrid |     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
0|homebrid |     at device.on (/usr/lib/node_modules/homebridge-broadlink-rm/ThermostatService.js:220:4)
0|homebrid |     at emitOne (events.js:101:20)
0|homebrid |     at device.emit (events.js:188:7)
0|homebrid |     at device.on (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:565:22)
0|homebrid |     at emitTwo (events.js:106:13)
0|homebrid |     at device.emit (events.js:191:7)
0|homebrid |     at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:237:18)
0|homebrid |     at emitTwo (events.js:106:13)
0|homebrid |     at Socket.emit (events.js:191:7)

**Comment by clkao** [comment]
I've updated the PR, however this requires https://github.com/momodalo/broadlinkjs/pull/4 to be in broadlinkjs as well.

**Comment by lprhodes** [comment]
Added full support in 1.0.0 - the pull request wasn't enough to combat issues caused by the value being requested multiple times so I implemented myself.

Please read the release notes https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.0.0
