### ISSUE TITLE
Speaker accessory **Suggestion**   

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#140]
Hi Luke,
Thanks again for your amazing work!
Since iOS 11 is here, I had an idea regarding the new speaker accessory.
I thought that by learning the commands volume Up/Down & Mute you can achieve that, I'll explain:

The user will setup in the config the min value and the max value and the default volume,
once this is in the config, 2 accessories will be created, one will be for the speaker of course, which will get the current volume from the memory and will be able to repeat the volume up/down command until the desired volume.

The issue with that method is when a user control their volume outside of homekit, the current volume will not be saved and that can cause issues mainly on automation (too loud or too quite).

Therefore, the second accessory, which will be used to sync homekit with the device volume, for example: it will need to lower the volume to minimum by sending (max volume -(minus) min volume) volume down commands to the device and than bringing it to the default volume from the config file by sending volume up commands.

Hope I made myself clear and maybe it will make sense to you too...
will be happy to hear your thoughts

**Comment by Nastra888** [comment]
Good idea, would also interest.

**Comment by lprhodes** [comment]
Sure, I understand - nice. I'll see what I can do once it's available: https://github.com/nfarina/homebridge/issues/1326

**Comment by lprhodes** [comment]
Closing until 11.3 is available.

**Comment by Catta1997** [comment]
any plans to add it?
