### ISSUE TITLE
Lock Accessory

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#141]
I'm using an electromagnetic lock which is connected to a relay with RF receiver.
is it possible to make a lock accessory to work with broadlink device?

**Comment by lprhodes** [comment]
You should just be able to learn the RF code. Use Scan RF button and follow the instructions. You'll need the remote that transmits the RF code to the receiver.

**Comment by nitaybz** [comment]
I know all that.... what I meant is that I want a Lock accessory and not just a normal switch.... can you use the Lock characteristic as an accessory so it will show properly on my phone?
![image](https://user-images.githubusercontent.com/16838394/28120364-8031e0ac-6720-11e7-9558-178213c344b5.png)

**Comment by lprhodes** [comment]
Is this still something you want? It'd need to work in the same way as the garage door accessory I guess?

**Comment by nitaybz** [comment]
sure... still want it!
thought you neglected the plugin :)

**Comment by lprhodes** [comment]
I've added support for the "lock" accessory in the next release

**Comment by lprhodes** [comment]
@nitaybz I've just been away and without a house for a while :)

**Comment by iandronowicz** [comment]
could it be that the broadlink can't learn my multlock entr remote fob rf code? this is the one: https://www.mul-t-lock.com/en/site/mul-t-lock/products/digital-residential-solutions-/entr--smart-lock-solution/entr-remote-control/
