### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by neoTUGA** [lprhodes/homebridge-broadlink-rm#142]
Hey guys, 
Trying to use your plugin to test on a "kind of" RM PRO, but havent been able too even star the plugin, i know there is a specifick version of node,js needed, but when i change to that version, i cont even start homebridge. Can i get some help here please?

**Comment by rainus87** [comment]
hi. i can help you/
{
	"bridge": {
		"name": "Homebridge",
		"username": "CD:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-156"
	},
	"description": "Homebridge",
	"accessories": [

	],
	"platforms": [{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideScanFrequencyButton": false,
		"hideLearnButton": false,
		"accessories": [{
				"name": "Auto-off Switch",
				"type": "switch",
				"disableAutomaticOff": false,
				"onDuration": 5,
				"data": {
					"on": "2600500000012...",
					"off": "2600500000012..."
				}
			},
			{
				"name": "TV On/Off",
				"type": "switch",
				"data": {
					"on": "2600500000012...",
					"off": "2600500000012..."
				}
			},
			{
				"name": "Channel Up",
				"type": "switch-repeat",
				"sendCount": 1,
				"data": "2600500000012..."
			},
			{
				"name": "Channel Down",
				"type": "switch-repeat",
				"sendCount": 1,
				"data": "2600500000012..."
			},
			{
				"name": "Volume Up",
				"type": "switch-repeat",
				"sendCount": 5,
				"interval": 0.3,
				"data": "2600500000012..."
			},
			{
				"name": "Volume Down",
				"type": "switch-repeat",
				"sendCount": 5,
				"interval": 0.3,
				"data": "2600500000012..."
			},
			{
				"name": "Entertainment",
				"type": "switch-multi",
				"interval": 0.5,
				"data": [
					"2600500000012...",
					"2600500000012...",
					"2600500000012..."
				]
			},
			{
				"name": "Entertainment 2",
				"type": "switch-multi-repeat",
				"interval": 2,
				"data": [{
						"data": "2600500000012...",
						"sendCount": 2,
						"interval": 0.3,
						"pause": 10
					},
					{
						"data": "2600500000012...",
						"sendCount": 2,
						"interval": 5
					}
				]
			},
			{
				"name": "Light",
				"type": "light",
				"defaultBrightness": 70,
				"useLastKnownBrightness": true,
				"disableAutomaticOff": false,
				"onDuration": 5,
				"data": {
					"off": "2600500000012...",
					"brightness10": "2600500000012...",
					"brightness20": "2600500000012...",
					"brightness30": "2600500000012...",
					"brightness40": "2600500000012...",
					"brightness50": "2600500000012...",
					"brightness60": "2600500000012...",
					"brightness70": "2600500000012...",
					"brightness80": "2600500000012...",
					"brightness90": "2600500000012...",
					"brightness100": "2600500000012..."
				}
			},
			{
				"name": "Air Conditioner",
				"type": "air-conditioner",
				"data": {
					"off": "2600500000012...",
					"temperature30": {
						"pseudo-mode": "heat",
						"data": "2600500000012..."
					},
					"temperature16": {
						"pseudo-mode": "cool",
						"data": "2600500000012..."
					}
				}
			},
			{
				"name": "Air Conditioner Advanced",
				"type": "air-conditioner",
				"autoSchedule": [{
						"days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
						"startTime": 6,
						"endTime": 8
					},
					{
						"days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
						"startTime": 16,
						"endTime": 22
					},
					{
						"days": ["Saturday", "Sunday"],
						"startTime": 6,
						"endTime": 22
					}
				],
				"autoSwitch": "A/C Auto Switch",
				"data": {
					"off": "2600500000012...",
					"temperature30": {
						"pseudo-mode": "heat",
						"data": "2600500000012..."
					},
					"temperature16": {
						"pseudo-mode": "cool",
						"data": "2600500000012..."
					}
				}
			},
			{
				"name": "A/C Auto Switch",
				"type": "switch"
			},
			{
				"name": "Fan",
				"type": "fan",
				"data": {
					"on": "2600500000012...",
					"off": "2600500000012...",
					"swingToggle": "2600500000012...",
					"fanSpeed10": "2600500000012...",
					"fanSpeed20": "2600500000012...",
					"fanSpeed30": "2600500000012...",
					"fanSpeed40": "2600500000012...",
					"fanSpeed50": "2600500000012...",
					"fanSpeed60": "2600500000012...",
					"fanSpeed70": "2600500000012...",
					"fanSpeed80": "2600500000012...",
					"fanSpeed90": "2600500000012...",
					"fanSpeed100": "2600500000012..."
				}
			},
			{
				"name": "Garage Door",
				"type": "garage-door-opener",
				"openCloseDuration": 8,
				"data": {
					"open": "2600500000012...",
					"close": "2600500000012...",
					"lock": "2600500000012...",
					"unlock": "2600500000012..."
				}
			},
			{
				"name": "Blind",
				"type": "window-covering",
				"totalDurationOpen": 45,
				"totalDurationClose": 40,
				"data": {
					"open": "2600500000012...",
					"close": "2600500000012...",
					"stop": "2600500000012..."
				}
			}
		]
	}]
}

**Comment by lprhodes** [comment]
@neoTUGA you'll need to provide logs so that we can see what the error is
