### ISSUE TITLE
Remotecentral.com

### ISSUE THREAD

**Issue by samsonrosen** [lprhodes/homebridge-broadlink-rm#144]
Hi!

There are a bunch of 'discrete IR codes' littering the internet specifically this page:

http://www.remotecentral.com/cgi-bin/mboard/rc-discrete/thread.cgi?6824

Is there a way these codes could be used in the config.json?

**Comment by lprhodes** [comment]
If you're able to find some for LG 55EC9300 then I'll happily give it a go.

**Comment by DJay79** [comment]
@lprhodes What do you mean by "If you're able to find some for LG 55EC9300 then I'll happily give it a go." I own a LG 55EG9209 and I think it could be nearly similar to the one you pointed to. 
If there is anything I can do, of course let me know.

**Comment by lprhodes** [comment]
By that I mean...I have that TV and if you can find codes for that exact one then I'd be happy to play around to see if I can get them working.

**Comment by Alex-developer** [comment]
Has anyone managed to get these codes to work?

Thanks

**Comment by iKrushYou** [comment]
Any update?

**Comment by St0nehead** [comment]
Looking for SONY RM-S241 remote control HEX codes (this remote used with HCD-241 HCD-251 HCD-261 R2400 R2500 R2600)
