### ISSUE TITLE
Creating one Fan..two detected!

### ISSUE THREAD

**Issue by real-Stario** [lprhodes/homebridge-broadlink-rm#146]
Hi..

first of all, thanks for that mighty tool. I really appreciate your work!
This is may one of the minor issues, but when I create the "fan" (just one), everything is working fine but Siri was telling me, that "both" fans are ON right know... BOTH?!? So I started troubleshooting.. the HomeKit App itself is not showing a second one, expecting the Elgato Eve app (see below). I did not implement the SwingMode line im my config, because it is a ceiling fan. However it  seems that it has something to do with that. Take a look.
![img_6365](https://user-images.githubusercontent.com/29930233/27883266-41f2d2a6-61d0-11e7-8c21-05529b46e595.PNG)
The first one implements the option for swing mode (schwenken). So, how can I get rid of that one? Also the log is showing that Broadlink is always requesting the swing mode. Any option for disabling?

[7/5/2017, 10:24:56 PM] [Broadlink RM] Ventilator getFanSpeed: 16
[7/5/2017, 10:24:56 PM] [Broadlink RM] Ventilator getSwitchState: false
[7/5/2017, 10:24:56 PM] [Broadlink RM] Ventilator getSwingMode: 0
[7/5/2017, 10:24:56 PM] [Broadlink RM] Ventilator getFanSpeed: 16
[7/5/2017, 10:24:56 PM] [Broadlink RM] Ventilator getSwitchState: false

"name": "Fan",
          "type": "fan",
          "data": {
            "on": "26004a.....",
            "off": "26004e0...",
            "fanSpeed10": "26004a...",
            "fanSpeed50": "260068...",
            "fanSpeed100": "26004a..."
                 }

Thanks for your support in advance!

**Comment by DJay79** [comment]
Same question here. Fan does not have a swing option, so it would be great to exclude this somehow in the config.json Thx.

**Comment by lprhodes** [comment]
Check out 2.5.14

**Comment by DJay79** [comment]
@lprhodes You are awesome! Thanks a lot for this implementation. Works great here. 👍🏻

**Comment by real-Stario** [comment]
Just like this! @lprhodes Thanks for the support.
