### ISSUE TITLE
How do I scan HEX code?

### ISSUE THREAD

**Issue by scorpioRED** [lprhodes/homebridge-broadlink-rm#147]
Hi!
How do I scan HEX code with my RM 3 Pro ?
Here is my config.json : 
`
{
  "bridge":{
    "name":"Homebridge",
    "username":"CD:22:3D:E3:CE:30",
    "port":51826,
    "pin":"031-45-156"
  },
  "description":"Homebridge",
  "accessories":[

  ],
  "platforms":[
    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "hideScanFrequencyButton": false,
      "scanFrequency": true,
      "hideLearnButton": false,
      "accessories":[
        {
          "name":"TV On/Off",
          "type":"switch",
          "data":{
            "on":"2600500000012...",
            "off":"2600500000012..."
          }
        }
      ]
    }
  ]
}

`

When I lear code in my IOS app I don`t see nothing in homebridge console. Please help me

**Comment by dessmith** [comment]
Have you added the HomeBridge in the iOS Home App?
Once you do that, you should be able to see a new accessory that is a Switch called "Learn"
You need to then tap that switch within the Home app, and then use the remote pointing at your RM3 Pro, and you'll get some hex in the console.

**Comment by sokompheak** [comment]
You can try this code if you don't see Learn Button.

{
"bridge":{
"name":"Homebridge",
"username":"CD:22:3D:E3:CE:30",
"port":51826,
"pin":"031-45-156"
},
"description":"Homebridge",
"accessories":[

],
"platforms":[
{
"platform":"BroadlinkRM",
"name":"Broadlink RM",
"hideScanFrequencyButton": false,
"hideLearnButton": false,
"accessories":[
{
  "name":"RM Pro Learn",
  "type":"learn-code",
  "host":"your rm pro IP address",
  "disableAutomaticOff": true,
  "scanFrequency": true
}
]
}
]
}

**Comment by sokompheak** [comment]
If you have only one RM pro, you can delete ("host":"your ip address")

**Comment by chietanjain** [comment]
@sokompheak 
how do I start the concole. I'm on a pi. I use ssh. I don't get any output when I run "journalctl -f -u homebridge"
is there something else I should do to get console output?

**Comment by Leafney** [comment]
I have the same issue .I bought a RM Pro maybe is RM 3 Pro   whitch for S/N:RM03******* .
For my raspberryPi2 ,install nodejs v8.x  and homebridge    homebridge-broadlink-rm 
my config.json and logs:

```
   {
    "platform":"BroadlinkRM",
    "name":"Broadlink RM",
    "homebridgeDirectory":"/var/lib/homebridge",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "accessories":[
    {
        "name":"TV On/Off",
        "type":"switch",
        "data":{
            "on":"",
            "off":""
        }
    }
    ]
   }

```

logs:
```
pi@raspberrypi:~ $ sudo systemctl status homebridge.service
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Sun 2017-10-22 17:45:39 CST; 14s ago
 Main PID: 3010 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─3010 homebridge

Oct 22 17:45:47 raspberrypi homebridge[3010]: [2017-10-22 17:45:47] [Broadlink RM] Initializing BroadlinkRM platform...
Oct 22 17:45:47 raspberrypi homebridge[3010]: [2017-10-22 17:45:47] [Broadlink RM] Initializing platform accessory 'Learn'...
Oct 22 17:45:47 raspberrypi homebridge[3010]: [2017-10-22 17:45:47] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...
Oct 22 17:45:47 raspberrypi homebridge[3010]: [2017-10-22 17:45:47] [Broadlink RM] Initializing platform accessory 'TV On/Off'...
Oct 22 17:45:47 raspberrypi homebridge[3010]: [2017-10-22 17:45:47] Loading 0 accessories...
Oct 22 17:45:47 raspberrypi homebridge[3010]: Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
Oct 22 17:45:47 raspberrypi homebridge[3010]: ┌────────────┐
Oct 22 17:45:47 raspberrypi homebridge[3010]: │ 031-45-156 │
Oct 22 17:45:47 raspberrypi homebridge[3010]: └────────────┘
Oct 22 17:45:47 raspberrypi homebridge[3010]: [2017-10-22 17:45:47] Homebridge is running on port 51826.
pi@raspberrypi:~ $



pi@raspberrypi:~ $ sudo journalctl -fu homebridge
-- Logs begin at Sun 2017-10-22 03:13:19 CST. --
Oct 22 17:47:29 raspberrypi homebridge[3010]: [2017-10-22 17:47:29] [Broadlink RM] TV On/Off getSwitchState: 0
Oct 22 17:47:32 raspberrypi homebridge[3010]: [2017-10-22 17:47:32] [Broadlink RM] Send data (no devices found)
Oct 22 17:47:32 raspberrypi homebridge[3010]: [2017-10-22 17:47:32] [Broadlink RM] Attempting to discover RM devices for 5s
Oct 22 17:49:37 raspberrypi homebridge[3010]: [2017-10-22 17:49:37] [Broadlink RM] TV On/Off getSwitchState: 0
Oct 22 17:49:47 raspberrypi homebridge[3010]: [2017-10-22 17:49:47] [Broadlink RM] Send data (no devices found)
Oct 22 17:49:47 raspberrypi homebridge[3010]: [2017-10-22 17:49:47] [Broadlink RM] Attempting to discover RM devices for 5s
Oct 22 17:51:47 raspberrypi homebridge[3010]: [2017-10-22 17:51:47] [Broadlink RM] TV On/Off getSwitchState: 0
Oct 22 17:51:57 raspberrypi homebridge[3010]: [2017-10-22 17:51:57] [Broadlink RM] TV On/Off setSwitchState: true
Oct 22 17:52:13 raspberrypi homebridge[3010]: [2017-10-22 17:52:13] [Broadlink RM] TV On/Off setSwitchState: false
```

when touch "Learn" button ,console shows `Attempting to discover RM devices for 5s` ,and then use the remote pointing at RM3 Pro, but the RM3 Pro lights don't respond, and the console doesn't have any output.

**Comment by mestery** [comment]
I have this same problem, also with an RM3 Pro. No lights on, the message "Attempting to discover RM devices for 5s" displays. What else can I do to help diagnose this problem? Thanks!

**Comment by mestery** [comment]
Turns out the solution is that the new Broadlink RM Pro I bought wasn't recognized, see this issue [here](https://github.com/lprhodes/broadlinkjs-rm/issues/3) for details on how to fix it.

**Comment by huynhlebaoanh** [comment]
I use this plugin and config as intruction.
When I restart homebridge, log shows:
Error: The requested platform “BroadlinkRM” was not registered by any plugin. (I did install this plugin)
Anyone could help me,please?
