### ISSUE TITLE
Available Hex-Codes from Cable Provider Unitymedia in different format

### ISSUE THREAD

**Issue by DJay-X** [lprhodes/homebridge-broadlink-rm#148]
There are Hex-Codes that the Germany Cable Provider Unitymedia is making available for there Horizon HD Recorder Box.
But they look very different to what normally is used I know from broadlink-rm.
Unfortunately the original remote can't be used to learn directly on the boradlink hub. So the listed hex codes could be helpful but I have no Idea how.
Anyone who can help? Thanks in advance.
http://bit.ly/2sAKayZ

![hexcodes](https://user-images.githubusercontent.com/3874239/27985229-bca382c0-63e7-11e7-9e97-5af47ac7bd85.JPG)

**Comment by lprhodes** [comment]
Hopefully work from #144 can help with this
