### ISSUE TITLE
Aircon: Not able to use autoCoolTemperature sucessfully

### ISSUE THREAD

**Issue by dessmith** [lprhodes/homebridge-broadlink-rm#149]
Hi,

Great work on this. It took me just a few hours to get my air con up and running with HomeKit!

**Issue**
One of the few issues I've found while using your plugin, is I'm not sure if `autoCoolTemperature` is implemented. I know that `autoSchedule` isn't implemented yet as I see no reference to it in the code (I don't know js too well unfortunately), so I tried various permutations of `autoCoolTemperature` along with `autoHeatTemperature` and the `autoSwitch` (which is a great idea), I also had `autoMinimumDuration` set to 5, so I'd get updates very quickly while testing.

**My expectations**
I have an a/c that can only cool, so I'd ideally like to just set `autoCoolTemperature`, and get the plugin to check the temps every `autoMinimumDuration` seconds, but I saw nothing in the logs about `autoMinimumDuration` or anything related to auto checking of temps 

**My config**
 in fact see my accessory setup below (just the JSON that matters)

```
     "accessories": [
      	{
          "name":"A/C Auto Switch",
          "type":"switch"
        },
        {
          "name": "Air Conditioner",
          "type": "air-conditioner",
          "autoMinimumDuration ": "5",
          "defaultCoolTemperature": "19",
          "defaultHeatTemperature": "28",
          "autoCoolTemperature ": "24",
          "data": {
          "autoCoolTemperature ": "24",
            "heatTemperature": "30",
            "off": "replaced hex with this smaller string!",
			"temperature19": {
              "pseudo-mode": "cool",
              "data": "replaced hex with this smaller string!"
            },
```
// I have temps from 28 - 19 defined

**Comment by lprhodes** [comment]
You're correct, `autoSchedule` isn't implemented yet, sorry.

If the A/C turns on automatically because the temperature is higher `autoCoolTemperature` then even if the temperature decreases back below `autoCoolTemperature`, it won't do anything until the amount of `autoMinimumDuration`in seconds has passed. The opposite also applies (to turn off the A/C)

Personally I have `autoMinimumDuration` set to 300 (5 minutes), otherwise it just keeps turning on/off very frequently.

The following is my actual AC config:

```
{
              "name": "Air Conditioner",
              "type": "air-conditioner",
              "minTemperature": 16,
              "autoHeatTemperature": 21,
              "autoCoolTemperature": 28,
              "autoMinimumDuration": 300,
              "disableLogs": true,
              "data": {
                "off": "IRCODE",
                "temperature30": {
                  "pseudo-mode": "heat",
                  "data": "IRCODE"
                },
                "temperature16": {
                  "pseudo-mode": "cool",
                  "data": "IRCODE"
                }
              }
            }

```

**Comment by lprhodes** [comment]
Re-open please if you need more info
