### ISSUE TITLE
After Update  2.5.14 Homebridge no longer starts

### ISSUE THREAD

**Issue by Nastra888** [lprhodes/homebridge-broadlink-rm#150]
Hello Luke,

Nice that you have again made improvements to the plugin. Thank You!

But unfortunately there is a problem with the new version that the homebridge no longer starts.

Here I made a screen:

![img_1567](https://user-images.githubusercontent.com/27686185/27988615-34ba5778-6426-11e7-9c0f-b77f268489e6.PNG)

I hope you have an idea to fix the error?

Greeting Nastra

**Comment by DJay79** [comment]
Hi @Nastra888 you probably have to change your config.json to something like this, like I did.
Hope this helps. See you here or in our German forum. ;)

{
                                 "name": "Ventilator",
                                 "type": "fan",
                                 "hideSwingMode":true,
                                 "hideV2Fan":true,
                                 "data": {
                                 "on":"26004800000128921411141114351510141113111511133614111435153514351535143613361436143613111510141114351510141114111411143514361436131115351435153415000d05",
                                 "off":"26004800000128921411141114351510141113111511133614111435153514351535143613361436143613111510141114351510141114111411143514361436131115351435153415000d05",
                                 "fanSpeed10": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed20": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed30": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed40": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed50": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed60": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05",
                                 "fanSpeed70": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05",
                                 "fanSpeed80": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05",
                                 "fanSpeed90": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05",
                                 "fanSpeed100": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05"
                                 }
                                 }

**Comment by lprhodes** [comment]
Sorry, it was late when I worked on that. Try 2.5.15

**Comment by Nastra888** [comment]
Now everything works again. Many Thanks!
