### ISSUE TITLE
air conditioner on via Apple Home app automation only works second time

### ISSUE THREAD

**Issue by slawnz** [lprhodes/homebridge-broadlink-rm#151]
Hi, have successfully setup my Broadlink RM Mini 3 with your INCREDIBLE Homebridge plugin (thank you!). All is working as expected except for turning on via timed automation via the Apple Home app on iOS. I have found that when the air conditioner is currently off, if I program an automation to turn it on the automation does not trigger. However, if I set a second, identical, automation it works the second time.

e.g. set to turn on at 8:45am - nothing happens. Homebridge output in terminal shows no command sent.
set to turn on at 8:45am, then turn on again at 8:46am - 8:46am automation works. Homebridge output shows nothing sent at 8:45am but command sent at 8:46am.

Have you seen same?

Using the "set twice" workaround at the moment but wondering if there's a proper fix.

Turn off automation has no such problem.

Cheers.

**Comment by lprhodes** [comment]
It sounds like this could be a similar issue to #124

if the logs aren't showing that anything it been sent to it on the second attempt then there's nothing I can do unfortunately, sorry.

**Comment by slawnz** [comment]
Makes sense I guess... wish Apple were a bit dynamic at fixing things like this... probably won't be fixed til iOS 12! Thanks anyway, love this plugin.
