### ISSUE TITLE
Dealing with Homekit Scenes and Asynchonous Switch Statuses

### ISSUE THREAD

**Issue by mrwagga** [lprhodes/homebridge-broadlink-rm#153]
If a plugin switch is already in the "off" mode in homekit, will subsequent "off" triggers (from homekit scenes for example) cause further "off" RF code to be sent?

I notice that the current case is that further RF codes will not be sent, which is problematic for accessories like the TC2 that have their own on/off switches and do not report their status back to homebridge. Switch statuses that are out of sync will mean HomeKit scenes may not work properly (for example, a scene will not turn off a light if it were turned on at the TC2 itself instead of through HomeKit).

Is there a way to fix this?

**Comment by mrwagga** [comment]
Here is the log of my current predicament.

[7/9/2017, 11:43:33 PM] [Broadlink RM] Living Down setSwitchState: false
[7/9/2017, 11:43:33 PM] [Broadlink RM] Living Down setSwitchState: already false

Ideally, homebridge could just send the state again regardless of the existing state.

**Comment by lprhodes** [comment]
You can add `allowResend: true` to you config

**Comment by imperialjoy** [comment]
I can't find a reference to allowResend: true in the Readme.  Where does this key go?
