### ISSUE TITLE
some advise about the switch plugin.

### ISSUE THREAD

**Issue by phenix13** [lprhodes/homebridge-broadlink-rm#154]
Thanks for your plugin that make my life so smart. Now , I have some advice about your switch plugin, I use your plugin to control my TV on or off, but my parent like use remote control. a lot of times the TV is off but the switch in my home app is still on, Fortunately, my TV is smart TV, it can connect to the internet by WiFi , so it will have an IP address , wish you make the switch plugin  test the TV IP address every 5 mins, when it is offline , make the switch to the off state ,also you can let us chose use test function or not, like: "testIPaddress" = true,
"IPaddress" = 192.168.1.101,

**Comment by lprhodes** [comment]
I can see some wider use for this - interesting idea.

You may want to check that your TV is definitely unreachable when turned off though as I'd expect the connection to remain open so that it can be remotely turned on

**Comment by phenix13** [comment]
Smart TV in our county is like a big pad which is running Android system and use IR remote control to turn it on, it's not smart, lol,So there is no plugin I can use to control it

**Comment by phenix13** [comment]
I just want the switch plugin can reflect the true state of some smart equipment.

**Comment by maragelis** [comment]
you can use <<Wake on Lan>> to switch on the TV

**Comment by lprhodes** [comment]
This has been implemented in the next release

**Comment by luvmex** [comment]
@maragelis Hi, I have researched the plugin for smart TV but most that are for Android system, but mine is Linux system,  Don't have a suitable plugin to connect with Homebridge.

So I'm using the Broadlink to instead the remote control, but there is some problem to sync the state of TV on & off, And you mention the WOL, How to set it on the homebridge?

Thanks!
