### ISSUE TITLE
"No Response" on all accessories IF if say "Siri turn aircon on"

### ISSUE THREAD

**Issue by dessmith** [lprhodes/homebridge-broadlink-rm#155]
Hi,

My accessories will report No Response (in Red) in the HomeKit control centre (and in the Home app), if I say "turn aircon on". 

However IF I say to siri "Set Air con **to 20**" (_or other temperature_) do I then it corrects itself and starts to report updated statuses for my accessories as normal.

I've done all sorts, such as update to the latest node version on my raspberry-pi, but I still get this.

To be clear, everything works really well, I'm just running into a bug where if I verbally tell Siri to turn the air con on, then it turns ON the air con, but homekit then states no response for the homebridge accessories, and this can be corrected ONLY when I state set aircon to a specific temperature.

Looking at the logs, there appears to be no difference in the output when I use Siri, vs using any other method to control the air con. 

Also even after the Home app says "No response" I can still see homebridge performing things such as "getCurrentTemperature" when I tap on the air con in Home app in that "No response" state.

My config is 

```
  "platforms": [
    {
      "platform": "BroadlinkRM",
      "name": "Broadlink RM",
      "accessories": [
        {
          "name": "Air Conditioner",
          "type": "air-conditioner",
          "defaultCoolTemperature": "19",
          "defaultHeatTemperature": "28",
          "autoCoolTemperature ": "24",
          "autoMinimumDuration ": "10",
          "data": {
            "heatTemperature": "30",
```

**Comment by cherysun** [comment]
Same issue. Changing the temperature in Home app on my iPhone will result in "No Response" on all accessories.

**Comment by lprhodes** [comment]
Fixed in the next update
