### ISSUE TITLE
Broadlink rm config-sample.json

### ISSUE THREAD

**Issue by AlbertoDiVenti** [lprhodes/homebridge-broadlink-rm#158]
It has creeped in an extra comma in the config-sample.json and thus throws out an error

It is the comma just after the graph closed parenthesis after the sat/sun end 22 hour in the advanced ac conditioner, line 141 according to JSONLint.com parser , followed by a square closed bracket.

No idea if the error is replicated too in the multi config json

Thanks

**Comment by kic883** [comment]
I've encountered the same issue. 
My Pi has problem with the config sample json. It works after I removed the comma.
