### ISSUE TITLE
Window Blinds ( up down ) via rf

### ISSUE THREAD

**Issue by AlbertoDiVenti** [lprhodes/homebridge-broadlink-rm#159]
I have all house motorised blinds via rf remote controllers

But they are just two buttons: up and down

Also you do not need to keep the button pressed 

You just press down briefly once and the blind will go down till either has all gone down or you press up to stop it at the position has arrived/you desire

Similarly for up

I have tried putting the up and down codes in both the garage door open close and blind open close samples of the config-sample.json 

But for both garage and blind buttons it doesn't work properly

When I start homebridge , the blind goes down as it reports last state was down ( it physically send the down command ) but when I try pull it up it doesn't send the rf command

So I pull it up with the real original blind remote and goes fully up. Now that it is up I try to send it down with the HomeKit but does' t go down , it isn't the hex code because when I start homebridge it managed to pull it down ( to be in sync with last known state )
I cannot understand what's wrong

I couldn't program with a code the stop , because my system has two different stop commands:
When blind is going up the stop command is a down command , and when is going down the stop is au up command , it could be an idea to define two stops one for up and one for down and users that have just one stop put the same code in both , or if it is omitted the stop it means that a reverse direction command must be sent out.

To solve without changing your coding is there a way to define a "pulse RF" type button that just sends an rf command ( stateless ) e.g. Blinds up 

Thanks

**Comment by AlbertoDiVenti** [comment]
I'm getting mad, I have copied the rf codes of my blinds up down into the TV channel up down of the sample-config json file and the two buttons channel up down work so I can control the blind as on the original blind remote , tested it and every time I press the buttons instantly the blind reacts.

I then tried via Siri voice commands ,  on the raspberrypi terminal I see the command accepted and the send rf code but the blind doesn't react

Can you pls help...

**Comment by XRJoao** [comment]
Hello, I have the same problem..

**Comment by lprhodes** [comment]
Hey, can you post your config please and I'll take a look.

**Comment by lprhodes** [comment]
Closing, if you'd still like help please re-open
