### ISSUE TITLE
Support referencing accessories by mac address

### ISSUE THREAD

**Issue by clkao** [lprhodes/homebridge-broadlink-rm#16]
When IP is changed we shouldn't need to reconfigure.
The plugin can also hint all the discovered device on startup so people can edit the config accordingly.

**Comment by lprhodes** [comment]
Added in 1.0.0 - Please read the release notes https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.0.0

**Comment by lprhodes** [comment]
@clkao the wrong MAC address was being returned, this has been fixed in 1.1.19 (check out the release notes if it doesn't work)
