### ISSUE TITLE
Broadlink RM with Chacon DIO #1

### ISSUE THREAD

**Issue by XRJoao** [lprhodes/homebridge-broadlink-rm#161]
Hi, I am trying to use your project. But I have a problem with my shutters. Because I don't have a button to stop for example if I want to stop when the shutter is going up I press again Up if I want to stop when the shutter is going down I press again down.

Can you help me with this?
I have no idea how to find the "stop" code to put in your script.

Thank you in advance.

**Comment by jeyremy** [comment]
Hello, 

I have some chacon but not controlled by the broadlink.
But mine do this : 
1) go for opening you shutter "on"
2) rePress "on" : shutters Stops

**Comment by lprhodes** [comment]
Sounds like @jeyremy has the solution, let me know if not.
