### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by chietanjain** [lprhodes/homebridge-broadlink-rm#162]
I have just installed the plugin and I am receiving the following error and homebridge enter's failed state:
 . . .
Jul 19 08:54:13 pi homebridge[30072]: [2017-7-19 08:54:13] [Broadlink RM] Initializing BroadlinkRM platform...
Jul 19 08:54:13 pi homebridge[30072]: /usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:90
Jul 19 08:54:13 pi homebridge[30072]: throw err0;
Jul 19 08:54:13 pi homebridge[30072]: ^
Jul 19 08:54:13 pi homebridge[30072]: Error: EACCES: permission denied, mkdir '/home/homebridge'
Jul 19 08:54:13 pi homebridge[30072]: at Object.fs.mkdirSync (fs.js:890:18)
Jul 19 08:54:13 pi homebridge[30072]: at sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:71:13)
Jul 19 08:54:13 pi homebridge[30072]: at sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:77:24)
Jul 19 08:54:13 pi homebridge[30072]: at sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:77:24)
Jul 19 08:54:13 pi homebridge[30072]: at Function.sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:77:24)
Jul 19 08:54:13 pi homebridge[30072]: at LocalStorage.parseStorageDirSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:619:20)
Jul 19 08:54:13 pi homebridge[30072]: at LocalStorage.initSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:142:14)
Jul 19 08:54:13 pi homebridge[30072]: at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/node-persist.js:37:32)
Jul 19 08:54:13 pi homebridge[30072]: at Object.init (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:10:15)
Jul 19 08:54:13 pi homebridge[30072]: at BroadlinkRMPlatform.HomebridgePlatform (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:14:21)
Jul 19 08:54:13 pi homebridge[30072]: at BroadlinkRMPlatform (/usr/lib/node_modules/homebridge-broadlink-rm/index.js:11:1)
Jul 19 08:54:13 pi homebridge[30072]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:32)
Jul 19 08:54:13 pi homebridge[30072]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
Jul 19 08:54:13 pi homebridge[30072]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Jul 19 08:54:13 pi homebridge[30072]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Jul 19 08:54:13 pi homebridge[30072]: at Module._compile (module.js:569:30)
Jul 19 08:54:13 pi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jul 19 08:54:13 pi systemd[1]: Unit homebridge.service entered failed state.
. . .
my config.json has only this:

{
			"platform": "BroadlinkRM",
			"name": "Broadlink RM"
		},

Note that when I remove the platform entry from the config.json there are no errors, but there are no new accessories in the apple home app either.

any help is appreciated.

thanks.

**Comment by klebermagno** [comment]
permission error:

**Comment by jsholiday** [comment]
I'm having this same issue. Can you tell me how to give homebridge permission?
