### ISSUE TITLE
Can get the temperature from other sensor?

### ISSUE THREAD

**Issue by FradSer** [lprhodes/homebridge-broadlink-rm#164]
Hey all,

I used RM mini 3 to control my air conditioner, but RM mini 3 has no temperature sensor. So that the temperature is always 14º, and I have an independent temperature sensor get the right temperature 27º.

Is there any way to replace the temperature sensor's reading to the air conditioner's?

![28460142-559f44f4-6e43-11e7-97dd-c21f5881818a](https://user-images.githubusercontent.com/1439628/28745951-b7079cbe-74b5-11e7-8dea-f1a32426c649.PNG)

Thank you all.

**Comment by wilkinsm89** [comment]
I would also be interested if this is possible.

**Comment by CSnloscalzo** [comment]
I'd be super interested in this as well.  I have a temperature sensor in the air conditioned room that I can pull readings from over HTTP.

**Comment by GreenTentacle** [comment]
I'd be super interested in this as well. I have a temperature sensor in the air conditioned room that I can pull readings from over HTTP.

**Comment by sendorm** [comment]
good idea. I would like to have that capability too.

**Comment by imperialjoy** [comment]
+1 that would be useful.

**Comment by klebermagno** [comment]
+1

**Comment by ashtonaut** [comment]
Another vote here, would be great to be able to use a 1-wire temp sensor connected to the Pi as the source of the temperature.

**Comment by lprhodes** [comment]
This one needs some discussion. Plugins can't talk to one another so I can't get the temperature from another HomeKit device.

For flexibility though I could read it from a file or url at regular intervals, thoughts?

**Comment by FradSer** [comment]
> For flexibility though I could read it from a file or url at regular intervals, thoughts?
Good idea.

Maybe [`homebridge-http-temperature`](https://www.npmjs.com/package/homebridge-http-temperature) is useful.

**Comment by ashtonaut** [comment]
Reading from a file at regular intervals would be great!

**Comment by lprhodes** [comment]
Please refer to #244

**Comment by lprhodes** [comment]
Support has been added for `temperatureFilePath` in 3.0.5
