### ISSUE TITLE
Support for different hex for fan swing toggle off and on

### ISSUE THREAD

**Issue by honcheng** [lprhodes/homebridge-broadlink-rm#166]
My fan has different signal for clockwise and anti-clockwise direction. 
That’s what swingToggle is supposed to do right? But the library only support a single value at the moment. Any plan to support 2 separate values?

**Comment by pat2man** [comment]
@honcheng did you get this to work?

**Comment by honcheng** [comment]
@pat2man no. But I think I misunderstood what 'swing toggle' means. What I need is actually support for direction change.
