### ISSUE TITLE
Learn and Scan Frequency Accessories do not initialise if accessory config empty

### ISSUE THREAD

**Issue by peterrussell** [lprhodes/homebridge-broadlink-rm#169]
If creating a basic config with no accessories defined in the config.json file then the Learn & Scan Frequency accessories are not added to Home App.
Additionally if one is manually configured in the config.json, it does not work correctly.

**Comment by bg4acd** [comment]
I have the same problem，and I don't know how to fix it ：）

**Comment by lprhodes** [comment]
Hi @bg4acd @peterrussell, I'm not seeing any issues with it on this end - can you send your configs over and I'll take a look.

**Comment by lprhodes** [comment]
This was fixed in v2.6.9
