### ISSUE TITLE
Multiple switch services?

### ISSUE THREAD

**Issue by kideight** [lprhodes/homebridge-broadlink-rm#17]
Firstly I'm completely new to Pi to apologies if this is a straight forward issue. 

I've installed the plugin and am trying to use multiple switches in the config file to control various appliances. I'm getting 'Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.'

Are you only able to control one switch from the RM2? is the config.json file wrong?

both error and config file below

---------------------
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[3/21/2017, 12:48:12 PM] Loaded plugin: homebridge-accessory-neurio
[3/21/2017, 12:48:12 PM] Registering accessory 'homebridge-accessory-neurio.neurio'
[3/21/2017, 12:48:12 PM] ---
[3/21/2017, 12:48:12 PM] Loaded plugin: homebridge-broadlink-rm
[3/21/2017, 12:48:12 PM] Registering accessory 'homebridge-broadlink-rm.Broadlink RM'
[3/21/2017, 12:48:12 PM] Registering accessory 'homebridge-broadlink-rm.Broadlink RM Learner'
[3/21/2017, 12:48:12 PM] ---
[3/21/2017, 12:48:12 PM] Loaded plugin: homebridge-lockitron
[3/21/2017, 12:48:12 PM] Registering accessory 'homebridge-lockitron.Lockitron'
[3/21/2017, 12:48:12 PM] ---
[3/21/2017, 12:48:12 PM] Loaded config.json with 2 accessories and 0 platforms.
[3/21/2017, 12:48:12 PM] ---
[3/21/2017, 12:48:13 PM] Loading 2 accessories...
[3/21/2017, 12:48:13 PM] [Learn IR] Initializing Broadlink RM Learner accessory...
[3/21/2017, 12:48:13 PM] [Broadlink RM2] Initializing Broadlink RM accessory...
[3/21/2017, 12:48:13 PM] [Broadlink RM2] add switch service
[3/21/2017, 12:48:13 PM] [Broadlink RM2] add switch service
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:131
        throw new Error("Cannot add a Service with the same UUID '" + existing.UUID + "' as another Service in this Accessory without also defining a unique 'subtype' property.");
        ^

Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:131:15)
    at /usr/local/lib/node_modules/homebridge/lib/server.js:418:19
    at Array.forEach (native)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:402:14)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

--------------------

{
	"bridge": {
		"name": "Homebridge",
		"username": "B8:27:EB:40:74:7D",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
		"accessory": "Broadlink RM Learner",
		"name": "Learn IR",
		"host": "192.168.1.109"
	}, {
		"accessory": "Broadlink RM",
		"name": "Broadlink RM2",
		"host": "192.168.1.109",
		"data": [{
			"name": "Gates",
			"type": "on",
			"on": "e92f1c000f140e140e09180a19150d150d0a180a18150d0b17150d0b170001ee000000000000000000000000",
			"off": "e92f1c000f140e140e09180a19150d150d0a180a18150d0b17150d0b170001ee000000000000000000000000"
		}, {
			"name": "KitchenLED",
			"type": "on",
			"on": "e91334000e21250b0d23240c0d22240b0d230d230d22240c0c220d220d22240b0d23240b0d230d220d23240c0d23230c0d23240c0c00014900000000",
			"off": "e91334000e21250b0d23240c0d22240b0d230d230d22240c0c220d220d22240b0d23240b0d230d220d23240c0d23230c0d23240c0c00014900000000"
		}, {
			"name": "Pool Table",
			"type": "on",
			"on": "e91034000e22240b0e21240c0d22240c0d220d230c230c230d230d220d23240b0d22240c0d230d220d22240c0d22240c0c23240b0d00014800000000",
			"off": "e91034000e22240b0e21240c0d22240c0d220d230c230c230d230d220d23240b0d22240c0d230d220d22240c0d22240c0c23240b0d00014800000000"
		}, {
			"name": "Office Spots",
			"type": "on",
			"on": "e90022030b060b290b060b2a09070a2a0a290a08092a0a08092a0a08092b0908092b09090809082b0908092b082b0908092c0809082b0909082b09080909082c082b0809090a072b092b080a0809082b0909082c0809082b080a082b080a082b082d08090809082b080b072c0809072c092a09090809092c070a072c0809092c0709082c0800014e09560909092b08090a2a08090a2a092b0908092b0a07092b0a07092b0908092b09080909092b0809082c082b09090a290909092a0909082c080a0808092b092b090908080a2a092b090a0808092b0809092b08090a2a0809082d0709082c082b09090809082c0809082c080a072b092b080a080a072b0909092a0909082c0809082b0800014d0a550909082b0908092b09080a2a082b0908092b0908092b0908092b0908092b090809080a2a09080a2a082c0808092b0909092a0908092b0908090a072d072b09090809082d072b09080a09072c0809092a0909082d0808082b0909082b092b090a0709082b090a072b0909092a092b09080909082b0909082b090a082a0908092b0900014d09550a08092a09080b290908092b0a2a0908092b0908092b0909082c0709092a09090908092b0908092b082b0a07092c0808092b0908092b09080909082b092b080a0809082b092b08090909082b0909082b080a082b080b072d060a082b082b09090809082c080b062d070b062c092b080a0709082c0809082d0709082c0809082c0800014e08560908092b0908092c0808092c082a0a08082c0809082b0909082b0909082c0a070809092b08090a2a092a0909082b0909082b090a072b09080909082c082b080a0809092a082c08090809092b0809092b080a082b0908092b080a092b072c08090809092b0a08082b0809092b092a09090809082c0809082c0809082c0809092b0800014e085708080a2b08080b2909080a2b082b0908092a0b07092b0908092b0908092a0a0908080b29090a072b092b0908092b0908092b0809092b08090909082b0a2a08090a08082c082b080a0808092b0909092a0909082b0908092b09080a2a092b08090909082b0908092b0909082b092b090809080a2a0909082b0908092b0809092b080005dc0b29090a072b",
			"off": "e9002603041804090c050b290d050a290a09082b092a0a08092a090a082c07080a2a090a072c080909080a29090b072b082b0909082c0809082b0909092a09080909082c082c070a0809092b082b09090809082b0909082c0809082c0809082b0909092c062c08090909092a0909082c0809082c0809082c0809082b0909082b090a072b0909082c0800014e0855090a072c080a072b090a072b092b080a082b0809092a0b07092b0809092a0b080709092b0809092b082c0809082b0909082c0809082b09090809082c082b09090809082b0a2a08090908092b0908092b0809092b080a082a0a08092a082b09090809092b0809092b080a072c0809092b0809082c0809092a0909092b0908082c0800014c09560a08092a0909082b0909082b092b0908092a0a08092a0909092a0a08092b080a0808092b0909082b082b0908092b0908092b090a072b09080909092b082c07090909082b092c07090908092c080a072b0908092b08090a2a0809092b082b0909080a092a0809092b0809092b0809092b0a07092c070a082c0708092b0909082b0800014d095609080b290908092b0908092b092b09080a2a0908092a090a082a09080a2b08090809092c0709092a092b0908092b0908092b0809092c07090908092b082c08090809092b082d07090809092b0908082c0908082c0809082c0809082c082b080a080a082c070b062c0809082c0908082c0809082c0809082c0809082c0809082c0800014c0a550908092b0909092a0a08082c082a0a070a2a0908092b0909082b0809092b08090908092b0809092b082c0809082d0708092b0a07092b09090809082b092b080b06090a2a082c080a070a082b08090a2a0809082c0809082d0709082c082b08090909082b0908082c0809082b0909082c0808092b0a07092b0809082c080a072b0800014e08560b06092b09080a2a0908092c082a0a08092a09090a2a08080a2a0909092a09090908092a0909082c092a0908092c08080a2a0908092b09080909082b0a2a08090909082b092b08090909082b0908092b0908092d0709082b0a07092b092b08090908092b090a072c0809082b0809092b090a072b0809092b0809092b0809092b090005dc082c"
		}, {
			"name": "Bathroom Spots",
			"type": "on",
			"on": "e90027030607040d060b0e04190b070a290a070a2b092a09080a2a0908092a0b07092b0908092b09080909082b0909082b092b080a082b08090a2a0809092b08090908092b082c0809080a082c072c080a070a082c0709082c0809082d0709092b0809092c072b080b070a072c070a082b080a082b082d070a082b08090909082b0809092b0809082c0800014d08570908092b0a07092b0908092a092b0908092c0909072b0908092b0909082b0a080809082b090a072c082b0909082b0909082b090a072b08090909082c082b09080909082b092b080b0709082b0909082b0909092c0709082b0908092b092b08090909082b0909082b0a08092a092b0809092b08090809092b0809092b0809092b0800014d09560908092b0908092b0a07092b092a0909082b0909082b0909092a0909092a09090908092b09080a2a082b0a08082b0908092b0909082b09080909082c092b07090909082b092b080a0909072b0909082b0909082b0a07092c0808092b082c08090909082b0908092b0909082b082b0909092b09080809092b0809092b0a08082b0a00014c09550a09082b0908092b0908092b092a0909092a0908092b0a08092a0909082b0908090a082b0809092a092b0a08082b0909082c0809092b08090809092b082b09090908092b082b090a0709082c0809082d0709082c0809082c0909072c082c070a0908082c0809082b0909092c072c070b072b080b070a072c0809082d0709082c0800014e08560a07092b0908092b09080b29092b0809092b0809092a0909092c0709092b08090908092b0909092a092b0809082b09090a2a0809082c08090809082b092b0809090a072b082b09090809092b080b072b0809092c0709082c0809082d072c08090809092c0709092b0809092b082c0908082d07090809092c0709092b08090a2a0800014d095609080a2a0909092a0909092a092c0907092b0a07092b090a082a09080a2a090809080a2a09080a2a0a2a0908092b0a07092b09080a2a09090909082c092909090908092b092b09090809092b0809092b0809082c0a07092b0809092b092b09080a070a2b0809082c0809092b082b0a08092a09090809092b0908092b0a08092a090005dc2a",
			"off": "e90022030c050c280c050b290b08082b0a290a08092a0a070a2a0b08072b0a07092b09090809092c0808092b092b0809092b0809092c070a082b09080909092b082b09090809082c082b09090809082c0a07092b0809092c080a072c070a082c082b080a0809082b0909082c0809082b0909082c082b0a080908082c080a092b0809082b0800014f08570909082b0908092b0908092b082b0a08082b0909082b0809092a0909082d07080a08092b0809092c072b0908092b0909092a0908092c08090809082c092a09090809082c082b09080909082c0809082c0809082c0809082c0908082c092a09090809092b0809092b0809082b0809092b082c08090908092b0909082c0808092b0900014e07560909092a09080a2a0b070a29092b09080a2a0908092b090a072b0908092b09090809082b0a080a29092b0908092b0908092b0a07092b0a080809082b092b09080909082b092b0a070b07082c0908082b0909082d0709082b090a082b082d07080909092b0909092a0a070a2a0809092b082b0a090709092b0809092b0809092b0800014d095609080a2a0909082b0908092c092a0909082b0908092b0908092b0909082c08080b070a2909080b29092b0908092c0808092b0908092b09080908092c092a09080909082c092a090a0709082b0909082b0809092b0809082d0709082d072c070a0908082b080a082c070a082b080a082b082c0908080a082b080a082b080a082b0800014d09570908092a0a09072b0a070a2a092b0809082b0809092b08090a2a0809092b08090909082b0908092b092b0809082b0909082b0a07092b09080909082b092b08090909082b092b08090909082b0909082d0808082c0809082c0809082b092b09080909082c0809082b0909092b0809082b092b0a070909082c0809082b0909082c0900014b095708090a2a08080a2a0909092a092b0908092b0909082b0908092b0909082b09080909092a0909082b092b09080a2a0909092a0908092c08090809082b0a2a0a07090a072b092c08080909092a0909082b0a08082b0909082c0809082c082b080a0809082b0909082c0809082b0909082c082b09090809092a0909082c0809082d070005dc092a0909082b"
		}, {
			"name": "Lamp Left",
			"type": "on",
			"on": "e90e34000e21250b0d22240b0d22240c0d220d220d220d220d23240b0d220d230d230d230d220e220d23240b0d22240c0d22240c0c00014800000000",
			"off": "e90b34000e21250b0d22240b0d23230b0d220d220d220d220d23240b0d220d230d220d220d220d220d22240b0d22240c0d220d220d00014900000000"
		}, {
			"name": "Lamp Right",
			"type": "on",
			"on": "e90734000d22240c0c23230c0c23240c0c240c230d23230c0c24230c0c23230d0b23240c0d230b230c23240c0c23230c0c23230d0c00014a00000000",
			"off": "e90734000d22240c0c23230c0c23230c0c230c230c23230c0c23230c0c23230c0c23230c0c230c240c23240c0c23230c0c230c230c00014a00000000"
		}, {
			"name": "Kitchen Blue",
			"type": "on",
			"on": "260060000001329314111610141115101512150f151016111534153515361436141114361535153515361412133615341511161014111512141014381312131115361436153415361400052e0001344715000c1e0001354814000c3a0001344715000d050000000000000000",
			"off": "260060000001329314111610141115101512150f151016111534153515361436141114361535153515361412133615341511161014111512141014381312131115361436153415361400052e0001344715000c1e0001354814000c3a0001344715000d050000000000000000"
		}, {
			"name": "Pool Spots",
			"type": "on",
			"on": "e9004203080404040404040506040410040505060406040408070804040d07043d0405040b070a290b060b2a0a070b280a2a0a070a2a0a08092a09080a2a09080b29090809090a290908092c082b0908082b0909092b0908082c08090809092b082c0908080a072c082d08080809082d07090a2a0809082c0908082c0809082d072c08090809082d0709082d0809082b082b080a0809082c082b080a0809082d0709082c0800014d09560a07092b0908092b0908092a092b0908092b0908092b0908092b0908092b09090809092a090a072b092b08090a2a0809092b0809082c08090809092b082c080a0709092c072c0808090a072c0908082c0809082b0909082b0908092c072c090808090a2a080b072b0809092b082b09090809082c082c070a0809082b0909082b0800014d09560a07092c08080a2a0908092b092a0908092b0908092b0908092b0908092b090809080a2a0908092b092a090a072b0909092a0909092a09090809092b082d08070908092b092b08090909092a0a07092c08080a2b07090a2a0a07092b082d070908090a2a08090a2a08090a2a092a09080a08082b092b08090909082c0809082b0900014c0a550908092b0909082b0908092b092a0909092a09090a2a08080b2909080b2909080909092b0809092a092a0a08092b0809092b0809082c080a0709092b082b080a080a072b092c070a0709082c0809082c0809082c070a082b080a082c082a090a0808082d0709092b080a072b092b08090909082b082b09090809082c0908082c0800014c09570808092a0a08092a0908092b092b0908092a0909092a0909082c0808092b08090909082b0908092b092a090a082a0809092b080a082b09080809092b082b090909080a2a082b09090809082b09090a290908092b0909082b0809092b082c08090809082c080a072b0909082b092b08090809092b082b0909080a072c0809082c0800014c09560a07092b0908092b0908092b092a0908092c08080a290a08092b08080a2a090a0808092a0909082b092c0808092b0a07092a0909092b08090809092b082d0708090a0929092b08090908092b0908092b0809082b0909082b0909092a082c08090809092b0908092b0809082c082b08090909082b0a2909090809092b0809082c080005dc0929092b0809",
			"off": "e9006402040d0405070d15041025041e07040b060b290b060b2909080a2a092c0808092a0a070a2a0908092b0908092b0a070a08082b0a08082b092a0909092b0809082c0809082b0a08080a072b092c080a0709082d082a0a07090a072c0809082c070b082a080a082b080b072b082c080a0809082b0909082c0809082c080909090809082c082c08090809092b0908082c082c0809082c0809082c08090a08082c0800015009570808092b0908092c08080a2a092b0a07092b0908092b09080a2b0809092a09090809092b0809092b092b0809092a0909082c0809082b090a0709092b082b0a080809092b082c08090908092b0909082c0809092c0709082c080a072c082c09080809092b0908092d0709082b090908090909092a082c080a070a082b0908092b092b0809092b0909082c08090809082c0800014e09560a07092b0909092c0709092b092a0a08092a0909092b0908092b0909082b09080909092b0908092b092c0808092b0908092b0909092a0a080908092b092b08090909082b092b090908090a2b0709092b0809092b0908092b0909082b0a2a09080909092c0709082c0809092b080909090809082b092b0909080a072c0809082d072b0909092b0809082c09080809092b0900014d0a550909092a090a072b09090a29092b0908092b0908092b0908092b090a082a09080909082c080a072b092b0909082b0809092b080a082c07090909082c082b080b0709092c082a080a0908082b0909082c0909072b090a072c0809082c082b080a0908082c0809082b0909082c0809080a070a082b082c0908080a082b080a082b082c080a072c0908082c080a070a082b080005dc092b092a"
		}, {
			"name": "Wardrobe Light",
			"type": "on",
			"on": "e90a34000e21240c0d23240b0d22250b0d220d230d230c230d220d220d23240b0d220d220d220d220d22240c0d22250b0d22240c0c00014800000000",
			"off": "e90834000d22240c0d23230c0d22240c0d230c230c230c230c230c230d23230c0c230c230c230c230c23230c0c23240c0c240c230c00014900000000"
		}]
	}]
}

**Comment by lprhodes** [comment]
Create a separate accessory for each device you wish to control, rather than a separate value in the "data" value.
