### ISSUE TITLE
Feedback Wanted: Anyone find that sometimes the RM Mini doesn't trigger properly?

### ISSUE THREAD

**Issue by jat80** [lprhodes/homebridge-broadlink-rm#172]
I'm finding that sometimes it won't trigger properly.  Usually if it hasn't been used for a while.  For example, The TV was on for a while then when I turned it off  (Switch multi, 1 for the tv one for the receiver) the tv didn't trigger but the receiver did.  It's like it missed the first hex as it didn't have time to connect it then it just carried on and triggered the second hex.  

How do I find the logs for this?

Every device (homebridge server, apple tv 4 and rm mini) has a static internal IP address, the RM mini 3 firmware is up to date.

Here is my config:
{
"name":"TV",
"type":"switch-multi",
"interval":0.9,
"disableAutomaticOff":true,
"data":{
"on": ["TV ON hex code",
"RECEIVER ON hex code"
],
"off": ["TV OFF hex code",
"RECEIVER OFF hex code"
]

**Comment by jat80** [comment]
Anyone?

**Comment by jat80** [comment]
@lprhodes would be good if you could chime in.  I've finding that if the rm mini hasn't been used for a while when I go to trigger the above, it only turns on the the 2nd Hex Code (receiver) missing the first which is the TV.  I have to manually turn the TV.

Looking at the RM Mini led light it only lights up once (for the 2nd code) showing me that it definitely doesn't trigger the 1st hex code.

What would be causing this?  Should I put a dummy hex code in first to make it 3 so it "wakes it up" and gives it time to trigger the other 2??

Any help from anyone would be appreciated.

Also I find it does this with other devices I use to control with it (turning on and off the heat pump).  Sometimes it won't trigger first time.

Thanks!

**Comment by klebermagno** [comment]
In my case some times broadlink look like in standby and don't respond.
When I open the official app "e-control" they informe connecting and the homebridge back to work.
I don't know why. Maybe need send a request to start the broadlink.

**Comment by jat80** [comment]
That makes sense to me now.  Is there anyway to keep the rm mini 3 out of "standby"  ot keep it connected?

**Comment by jat80** [comment]
A workaround for this which seems to work most of the time now is doubling up the IR codes so use switch-repeat or switch-multi (inputing the IR code twice in your config) and this seems to "wake up" the RM Mini then fires the 2nd one off.  If it is "awake" having the code sent twice doesn't do hinder anything.
