### ISSUE TITLE
Speed for AirConditioner

### ISSUE THREAD

**Issue by cece99** [lprhodes/homebridge-broadlink-rm#174]
I think that adding the possibility of regulating the speed of the air conditioner would be useful and appreciated. 
As far as I understood the speed setting is not supported natively by HomeKit, as a workaround I was thinking that a fan accessory could be created together with the AC accessory to set the speed.

**Comment by lprhodes** [comment]
I like the idea of combining the two accessory types but the problem is that you'd end up needing so many variations of the IR codes

**Comment by lprhodes** [comment]
Closing for now as it seems impractical to learn all of these codes. Happy to be persuaded otherwise.
