### ISSUE TITLE
managing RF light switch help needed

### ISSUE THREAD

**Issue by imperialjoy** [lprhodes/homebridge-broadlink-rm#176]
Fist off the plugin works very well, so many thanks to the writer for making that happen!

I have a question about RF light switches.  My switches are defined as type 'switch', and work fine from the Home app.  But since they are also physical switches, the actual state can become different from what the Home app expects.  If the switch is off in HomeKit, but actually on because it was toggled by hand, how can I get HomeKit to shut off the switch?  I don't mind pressing on/off to do this manually, but I'd like to program automations so that the lights go off when I leave.  Right now if HomeKit thinks the light is already off, it sends no codes and the light just stays on when I leave.

**Comment by sendorm** [comment]
There is a beta feature. Add  "allowResend":true to your commands. So that even if homebridge thinks the lights are off, it will send an off command.

**Comment by imperialjoy** [comment]
This worked!  My automations work now!  Thank you.

**Comment by sendorm** [comment]
No problem.
