### ISSUE TITLE
Homebridge configured to start on reboot fails when running broadlink-rm plugin 

### ISSUE THREAD

**Issue by honcheng** [lprhodes/homebridge-broadlink-rm#178]
I’ve installed the plugin, setup the config.json file properly and able to run homebridge fine from command line. I usually do that only for testing. 

But when I start homebridge automatically on reboot with systemctl, homebridge crashes. 
Can someone help?

 09 01:50:43 raspberrypi systemd[1]: Starting Node.js HomeKit Server...
Aug 09 01:50:43 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Aug 09 01:50:45 raspberrypi homebridge[3957]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Aug 09 01:50:45 raspberrypi node[3957]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Aug 09 01:50:45 raspberrypi node[3957]: *** WARNING *** Please fix your application to use the native API of Avahi!
Aug 09 01:50:45 raspberrypi node[3957]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Aug 09 01:50:45 raspberrypi node[3957]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Aug 09 01:50:45 raspberrypi node[3957]: *** WARNING *** Please fix your application to use the native API of Avahi!
Aug 09 01:50:45 raspberrypi node[3957]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Aug 09 01:50:45 raspberrypi homebridge[3957]: *** WARNING *** Please fix your application to use the native API of Avahi!
Aug 09 01:50:45 raspberrypi homebridge[3957]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Aug 09 01:50:45 raspberrypi homebridge[3957]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Aug 09 01:50:45 raspberrypi homebridge[3957]: *** WARNING *** Please fix your application to use the native API of Avahi!
Aug 09 01:50:45 raspberrypi homebridge[3957]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Aug 09 01:50:48 raspberrypi homebridge[3957]: fs.js:681
Aug 09 01:50:48 raspberrypi homebridge[3957]: return binding.read(fd, buffer, offset, length, position);
Aug 09 01:50:48 raspberrypi homebridge[3957]: ^
Aug 09 01:50:48 raspberrypi homebridge[3957]: Error: EISDIR: illegal operation on a directory, read
Aug 09 01:50:48 raspberrypi homebridge[3957]: at Object.fs.readSync (fs.js:681:18)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at tryReadSync (fs.js:542:20)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at Object.fs.readFileSync (fs.js:585:19)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at LocalStorage.parseDirSync (/opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:637:35)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at LocalStorage.parseDataDirSync (/opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at LocalStorage.initSync (/opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at Object.nodePersist.initSync (/opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at Object.init (/opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:29:13)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at module.exports (/opt/nodejs/lib/node_modules/homebridge/lib/cli.js:24:7)
Aug 09 01:50:48 raspberrypi homebridge[3957]: at Object.<anonymous> (/opt/nodejs/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 09 01:50:48 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Aug 09 01:50:48 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by webpablo** [comment]
I see you closed this issue, did you ever solve this issue? I am having the same problem. homebridge + broad link run great, but if I try to use systemd it fails on the broad link plugin.

**Comment by webpablo** [comment]
For anyone who might stumble across this like I did, looks like the solution is to add the following to your config file. 
“homebridgeDirectory”:”/var/homebridge”,
