### ISSUE TITLE
 Scan RF (RF learning not supported for device at undefined)

### ISSUE THREAD

**Issue by jm0477** [lprhodes/homebridge-broadlink-rm#179]
node -v 
    v8.2.1
nodejs -v 
    v8.2.1

I am trying to make my Broadlink Mini 3 can be scaned for the hex, but failed.
the homebridge started success, but failed logs below:

Discovered Broadlink RM device at 192.168.1.204 (34:ea:34:88:fe:e6)

After I toggle the learn switch "On" on the IOS homekit, the console shows:
[2017-8-10 00:39:00] [BroadlinkRM] Scan RF (RF learning not supported for device at undefined)

When I pointing my remote to Mini 3, no hex code returned in the console.

Could anyone shed some lights on how to make it works? 
I followed the #147 suggestion, and it's config part. but no luck

my config.json:

    {
      "platform":"BroadlinkRM",
      "name":"BroadlinkRM",
      "accessories":[
      ]   
         "hideScanFrequencyButton": false,
        "hideLearnButton": false,
        "accessories":[
        {
        "name":"RM Pro Learn",
        "type":"learn-code",
        "host":"My mini 3 local IP",
        "disableAutomaticOff": true,
        "scanFrequency": true
        }
        ]     
    }

**Comment by lzammit** [comment]
Hello @jm0477 did you fix it ? Thanks.

**Comment by novakben** [comment]
Bump

**Comment by S474N** [comment]
Mini 3 have ONLY IR, not IR+RF!
