### ISSUE TITLE
No device found after restarting Homebridge

### ISSUE THREAD

**Issue by wilkinsm89** [lprhodes/homebridge-broadlink-rm#18]
My Broadlink Mini3 was working until I restarted Homebridge to make a change to another accessories and now I see the following in the log:

`[Broadlink Mini3] LearnIR (no device found at <IP>)`

I can ping the IP address for the machine running Homebridge and get a successful response. The device is also still working through the e-control app.

Any idea why it would now no longer be able to locate the device? I verified and the IP address for the IR device is still the same.

Great project by the way and I appreciate the work you have put in!

**Comment by lprhodes** [comment]
Check out release 1.0.0 and let me know how you go - please read the release notes https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.0.0
