### ISSUE TITLE
Translation of other forms of IR codes

### ISSUE THREAD

**Issue by tomhoplon** [lprhodes/homebridge-broadlink-rm#182]
Hi,

First of all. Many thanks for an amazing piece of work. Doing amazing things already.

Is it possible to use published IR codes for remotes I don't have. Here's an extract of a specification for a light IR control:

Transmitter   Button: | IR   Command: | Pronto   Command:
-- | -- | --
Full Off | FF88BD120h | 0000 0069 0007 0007   032a 010e 005a 010e 005a 005a 0168 005a 005a 010e 005a 00b4 005a 01c2 032a   010e 005a 010e 005a 005a 0168 005a 005a 010e 005a 00b4 005a 01c2
Scene 1 | FF88BD1D0h | 0000 0069 0007 0007   032a 010e 005a 010e 005a 005a 0168 005a 005a 010e 010e 005a 005a 0168 032a   010e 005a 010e 005a 005a 0168 005a 005a 010e 010e 005a 005a 0168

I can't see how it would be converted.

**Comment by St0nehead** [comment]
Same problem! Bought RM3, since i can't find remote for my old Sony Imperator. Now i search for any instructions on how to configure my RM3 to get them work with Sony Imperator

**Comment by tomhoplon** [comment]
I found the answer in the end. The pronto codes can be run through this script to get codes which will work with broadlink in homebridge. https://gist.github.com/appden/42d5272bf128125b019c45bc2ed3311f

**Comment by lprhodes** [comment]
Neat, I'll look into integrating that right into the plugin

**Comment by lprhodes** [comment]
Pronto code support is now built into the plugin as of v2.7.0
