### ISSUE TITLE
switch-repeat on a single button

### ISSUE THREAD

**Issue by zootersg** [lprhodes/homebridge-broadlink-rm#185]
Hi all, 
How do i make switch-repeat work? I am right now contended to only on/off on the connected devices. But there's a device which i need to off twice in order to get it switch off. May i know i do i use the switch-repeat on this device - Electrolux Air Cleamer? Or can i add the same data code on the data **off** twice? 

`					}
				},
				{
					"name": "Electrolux Air Cleaner On/Off",
					"type": "switch",
					"host": "192.168.0.XXX",
					"**data**": {
						"**on**": "26005c000800027000012a92141212371415111212121312131315361314121411361a1312151037131312151113121213131213121115131013131411371935143515361338143616371539180005bb0001294c15000c610001284c15000d05000000000000000000000000",
						"**off**": "26005c00060002790001299115101436141313141213121312131236141312141434161411141137131114131213121114131412121115121114121213361534163716361337133614361538140005be00012c4d13000c6000012b4d13000d05000000000000000000000000"
					}
				},
				{

Thank you!

_I am very new to this, knew nothing about coding with zero knowledge, forgive me if i don't know how to put out the right questions.

**Comment by lprhodes** [comment]
#229 should help, please re-open if not.
