### ISSUE TITLE
Broadlink error with systemd start

### ISSUE THREAD

**Issue by ekky2h** [lprhodes/homebridge-broadlink-rm#186]
Installed the homebridge plugin and configured successfully. When I run it thru the homebridge command it works flawlessly.
The problem starts after following this guide to start homebridge automatically on reboot:
https://timleland.com/setup-homebridge-to-start-on-bootup/ 

This is the message I get:

> pi@raspberrypi:~ $ sudo systemctl -l status homebridge
> ? homebridge.service - Node.js HomeKit Server
>    Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Thu 2017-08-17 15:43:33 CEST; 6s ago
>   Process: 10687 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
>  Main PID: 10687 (code=exited, status=1/FAILURE)
> 
> Aug 17 15:43:33 raspberrypi homebridge[10687]: at Function.sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:77:24)
> Aug 17 15:43:33 raspberrypi homebridge[10687]: at LocalStorage.parseStorageDirSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:619:20)
> Aug 17 15:43:33 raspberrypi homebridge[10687]: at LocalStorage.initSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:142:14)
> Aug 17 15:43:33 raspberrypi homebridge[10687]: at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/node-persist.js:37:32)
> Aug 17 15:43:33 raspberrypi homebridge[10687]: at Object.init (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:10:15)
> Aug 17 15:43:33 raspberrypi homebridge[10687]: at BroadlinkRMPlatform.HomebridgePlatform  #(/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:14:21)
> Aug 17 15:43:33 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
> Aug 17 15:43:33 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

Any ideas?

**Comment by webpablo** [comment]
Consider this a me too. I am having the exact issue. Works great when run directly, when dunning as a system service it fails over and over immediately when trying to load the broadlink plugin. FWIW I am following this information: https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/

**Comment by mattangelofdeth** [comment]
I'm curious as to if this was resolved?
I'm trying to install this plugin at the moment too and think I'm running into the same issue

**Comment by webpablo** [comment]
I had the same issue: 
For anyone who might stumble across this like I did, looks like the solution is to add the following to your config file.
“homebridgeDirectory”:”/var/homebridge”,

**Comment by mattangelofdeth** [comment]
@webpablo Thanks sooo much! Ill try it out now

**Comment by mattangelofdeth** [comment]
@webpablo Can you explain which config file and where you have placed it?
I still cant boot unfortunately

**Comment by lprhodes** [comment]
@mattangelofdeth in the main homebridge config (not this plugin config)
