### ISSUE TITLE
Now what??

### ISSUE THREAD

**Issue by dmarinb** [lprhodes/homebridge-broadlink-rm#192]
Thanks for your works, but I dont know what else to do, I have the app on the iphone and I also have the homebridge on the app, but I cannot learn any FR
[2017-9-8 16:27:22] Loaded plugin: homebridge-broadlink-rm
[2017-9-8 16:27:22] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2017-9-8 16:27:22] ---
[2017-9-8 16:27:22] config.json (/Users/danilomarin/.homebridge/config.json) not found.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2017-9-8 16:27:22] Homebridge is running on port 63574.
Discovered Broadlink RM device at 192.168.55.26 (34:ea:34:e8:29:cd)
Discovered Broadlink RM device at 192.168.55.24 (0d:43:b4:c3:e0:c1)

**Comment by DieMetRik** [comment]
Push button "Learn" on your iphone (in one of the room in Home app). In log watch data.

**Comment by bg4acd** [comment]
I have a problem like this。And I can't find the button “Learn” in the room in Home app。

**Comment by lprhodes** [comment]
@dmarinb your logs say "onfig.json (/Users/danilomarin/.homebridge/config.json) not found.". Make sure you setup your config.json

@bg4acd Can you send your config.json please if you're still facing this problem.

**Comment by lprhodes** [comment]
Closing, please re-open if you would like help
