### ISSUE TITLE
Changing air con temperature

### ISSUE THREAD

**Issue by binglenozumi** [lprhodes/homebridge-broadlink-rm#193]
Hi, so the air con that I have is using only + and - to change temperature. And it looks like currently the slider for the temperature did not work.

Just wondering, how can I set change temperature? the + sign only gives out 2 RF Hex code

Thanks

**Comment by lprhodes** [comment]
@binglenozumi are you still having this issue or did you find a suitable work-around. I'm happy to help out.

**Comment by lprhodes** [comment]
Closing for now - please re-open if you still want help
