### ISSUE TITLE
HomeKit blind icon disappearing

### ISSUE THREAD

**Issue by sifield** [lprhodes/homebridge-broadlink-rm#195]
Hi,

I have been using this great plugin for months without an issue to control my blinds, however a few days ago it disappeared off the system. I have several devices running through homebridge and the icon for these are all ok and working.

If I restart homebridge the blinds icon reappears and work fine and after some time (minutes to a few hours), it disappears again.

No updates were performed before the issue started and to try and fix it I have updated homebridge, the plugin etc.

Any thoughts on what the issue might be?

Thanks

**Comment by lprhodes** [comment]
This is a new one on me, sorry. Did you have any luck getting it back?

**Comment by lprhodes** [comment]
Closing for now - please re-open if you think it'll help
