### ISSUE TITLE
RM Pro does not work right away, but e-control app works 100% of the time

### ISSUE THREAD

**Issue by sebabordon** [lprhodes/homebridge-broadlink-rm#196]
I have an issue with the plugin. Whenever some time passes (I would say about 3-5 minutes) the commands sent from the home app do not work on my RM Pro. It might take a minute to work again. If I open the e-Control app then issue new commands form the Home App then everything works.
The same problem happens with home assistant plugin, which I solved by assigning the temperature sensor there and it seems that it keeps the device somehow out of stand by. That means it also works reliably from homebridge as well.
Available to help if needed, the configuration now is in manual:

  {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false,
      "accessories":[
        {
          "name":"Cocina",
          "type":"light"

Thanks!

**Comment by jat80** [comment]
Yeah I find that sometimes the command won’t send if I haven’t used it for “x” amount of time or if it’s a multi switch it misses the first IR code in the sequence and then just sends the rest.   I wish there was someway that we could keep the rm mini “active” so it’s always ready to send the codes.

**Comment by sebabordon** [comment]
The only way I found to keep it alive was to install homeassistant and set it as a sensor for temperature, and with just that commands work 100% of the time now!

Seba
________________________________

**Comment by jat80** [comment]
Could you post a how to for those new to home assistant?

**Comment by sebabordon** [comment]
Will do. I have this on my pending list.

If you already have Homeassistant installed the follow this to get it up and running

https://community.home-assistant.io/t/how-can-i-add-broadlink-temperature-to-ha/28627/2

Seba
________________________________

**Comment by sebabordon** [comment]
Well. after you've installed Homeassistant, edit the .homeassistant/configuration.yaml and go for the default #weather prediction section. Below you'll find mine, I have two RM Pro configured:

`# Weather prediction                                                                                                                                                                                               
sensor:                                                                                                                                                                                                            
  - platform: yr                                                                                                                                                                                                   
    name: Weather                                                                                                                                                                                                  
    forecast: 0                                                                                                                                                                                                    
    monitored_conditions:                                                                                                                                                                                          
      - temperature                                                                                                                                                                                                
      - symbol                                                                                                                                                                                                     
      - precipitation                                                                                                                                                                                              
      - pressure                                                                                                                                                                                                   
      - humidity                                                                                                                                                                                                   
                                                                                                                                                                                                                   
  - platform: broadlink                                                                                                                                                                                            
    name: Living                                                                                                                                                                                                   
    host: 10.0.xx.xx
    mac: 'xx:xx:xx:xx:xx:xx'                                                                                                                                                                                       
    update_interval: 15                                                                                                                                                                                            
    timeout: 15                                                                                                                                                                                                    
    monitored_conditions:                                                                                                                                                                                          
      - temperature                                                                                                                                                                                                
  - platform: broadlink                                                                                                                                                                                            
    name: Room
    host: 10.0.xx.xx
    mac: 'xx:xx:xx:xx:xx:xx'                                                                                                                                                                                       
    update_interval: 15                                                                                                                                                                                            
    timeout: 15                                                                                                                                                                                                    
    monitored_conditions:                                                                                                                                                                                          
      - temperature                                                                                                                                                                                                `

After that, restart homeassistant and the sensor temperature should appear on the homepage (http://<haipaddress>:8123 if using default port)

Feel free to let me know if this works for you. Already working properly after 3 months.

**Comment by jat80** [comment]
Thanks but I have an RM mini3 so it doesn't look like it works :(

**Comment by jat80** [comment]
@sebabordon I've had another think about this and wondered if it's my config that isn't right in homeassistant.  Should it really matter if it's the RMMini that I'm using with the config in homeassistant rather than the RM Pro?  or is the above only working with the pro?

**Comment by sebabordon** [comment]
The config should work for the RM Mini but i Have none to test it.


Try setting the type to rm_mini manually:


type (Required for some models): Switch type. Choose one from: rm, rm2, rm_mini, rm_pro_phicomm, rm2_home_plus, rm2_home_plus_gdt, rm2_pro_plus, rm2_pro_plus2, rm2_pro_plus_bl, rm_mini_shate, sp1, sp2, honeywell_sp2, sp3, spmini2, spminiplus or mp1.


as per guide: https://home-assistant.io/components/switch.broadlink/

[https://home-assistant.io/images/default-social.png]<https://home-assistant.io/components/switch.broadlink/>

Broadlink RM Switch - Home Assistant<https://home-assistant.io/components/switch.broadlink/>
home-assistant.io
How to obtain IR/RF packets? Choose Call Service from the Developer Tools. Choose the service broadlink/learn_command from the list of Available services: and hit ...



________________________________
De: JT <notifications@github.com>
Enviado: sábado, 30 de diciembre de 2017 12:59:41 a.m.
Para: lprhodes/homebridge-broadlink-rm
Cc: sebabordon; Mention
Asunto: Re: [lprhodes/homebridge-broadlink-rm] RM Pro does not work right away, but e-control app works 100% of the time (#196)


@sebabordon<https://github.com/sebabordon> I've had another think about this and wondered if it's my config that isn't right in homeassistant. Should it really matter if it's the RMMini that I'm using with the config in homeassistant rather than the RM Pro? or is the above only working with the pro?

**Comment by jat80** [comment]
Thanks @sebabordon. I've actually found an easier and quicker way to accomplish the same thing.  We know the problem is keeping the Broadlink RM device "alive" so I just used a little program on my Mac mini server to ping it's IP address (which I've made static) at regular intervals.  It's been working 100% without a glitch so far since I've implemented it.  Basically the same solution but using a different method.   

For anyone else having this problem with a similar setup I used a free program from the Mac App Store called "PingBar".  If you have a windows or linux system you will be able to find a similar free program that does the same thing.

Thanks!

**Comment by sebabordon** [comment]
Good idea, I might go on that if needed. Thanks!

________________________________
De: JT <notifications@github.com>
Enviado: miércoles, 03 de enero de 2018 03:51:14 a.m.
Para: lprhodes/homebridge-broadlink-rm
Cc: sebabordon; Mention
Asunto: Re: [lprhodes/homebridge-broadlink-rm] RM Pro does not work right away, but e-control app works 100% of the time (#196)


Thanks @sebabordon<https://github.com/sebabordon>. I've actually found an easier and quicker way to accomplish the same thing. We know the problem is keeping the Broadlink RM device "alive" so I just used a little program on my Mac mini server to ping it's IP address (which I've made static) at regular intervals. It's been working 100% without a glitch so far since I've implemented it. Basically the same solution but using a different method.

For anyone else having this problem with a similar setup I used a free program from the Mac App Store called "PingBar". If you have a windows or linux system you will be able to find a similar free program that does the same thing.

Thanks!

**Comment by lprhodes** [comment]
Great tips here - I'll add host pinging. What interval are you using @jat80 ?

**Comment by lprhodes** [comment]
1 second interval pings are included in the next release

**Comment by jat80** [comment]
@lprhodes I’m using 3s.  Thanks for the enhancement!!! :)

**Comment by lprhodes** [comment]
I've changed to 5s

**Comment by jat80** [comment]
I think having an option to set the ping in the config would be great upto 10s but 1-5s should be fine IMO
