### ISSUE TITLE
RM 3 mini does not read remote control signals

### ISSUE THREAD

**Issue by nunesdennis** [lprhodes/homebridge-broadlink-rm#199]
Hi, I've been trying to make my RM 3 mini to work with my air conditioner and my umidifier, read a lot of issues, but none could help me
what I did:

- Installed homebridge;
- Installed plugin;
- update the plugin;
- checked the node version(v8.4.0);
- Edited the config.json file;
- ran homebridge on terminal;
- Added homebridge in home app;
- Added accessories with both learning options;
- Pressed switch to start scanning on both switches.

my config.json file is like this:
`
{
	"bridge":{
	"name":"Homebridge",
	"username":"CD:22:3D:E3:CE:30",
	"port":51826,
	"pin":"031-45-156"
	},
	"description":"Homebridge",
	"accessories":[],
	"platforms":[
		{
			"platform":"BroadlinkRM",
			"name":"Broadlink RM",
			"hideScanFrequencyButton": false,
			"hideLearnButton": false,
			"accessories":[
				{
  					"name":"Scan RF",
  					"type":"learn-code",
  					"scanRF": true
				},
				{
					"name":"RM Pro Learn",
					"type":"learn-code",
					"scanFrequency": true
				}
			]
		}
	]
}
`
My log from terminal is this:

Homebridge is running on port 51826.
Discovered Broadlink RM device at 192.168.25.226 (34:ea:34:b2:fe:fd)
[Broadlink RM] Scan RF (RF learning not supported for device at undefined)

**Comment by ashtonaut** [comment]
Are you trying to learn IR or RF commands? The RM3 only supports IR, it doesn’t support RF remotes.

**Comment by nunesdennis** [comment]
I tried both because the IR did not work, But I have 2 remote controllers... one from my [air conditioner](https://a-static.mlcdn.com.br/1500x1500/ar-condicionado-split-electrolux-24000-btus-frio-ti24f-autolimpante/magazineluiza/084231300/1255e2bafd0114d6d5de602760a3212d.jpg) and other from my [humidifier](https://images-soubarato.b2w.io/produtos/01/00/item/121593/3/121593316_5SZ.jpg).

**Comment by lzammit** [comment]
Same here.. with the RM 3 mini.

Thanks,

**Comment by lzammit** [comment]
@ashtonaut you're right.

https://m.banggood.com/Broadlink-Black-Bean-Smart-Home-Wifi-Remote-IR-Controller-Universal-Appliances-Smart-Control-p-1049494.html

```
For All IR controller smart control, if you want an IR+RF controller,
please find the big brother broadlink RM-Pro
```

Thanks.

**Comment by nunesdennis** [comment]
My controller is Just a normal IR.

**Comment by giantoctopus** [comment]
try adding this as an accessory - its the only way I can get IR working so far.. it'll remove the 2 default learning switches

```
{
              "name":"Scan IR",
              "type":"learn-code",
              "scanRF": false
          
},
```

**Comment by nunesdennis** [comment]
I will try it, Thanks man.

**Comment by nunesdennis** [comment]
It worked, thanks man 😄

**Comment by lprhodes** [comment]
Odd, I'll figure out why the defaults don't work sometimes when the specific learn accessories do. Thanks @giantoctopus
