### ISSUE TITLE
Broadlink RM Pro, UDP packet send but nothing happened

### ISSUE THREAD

**Issue by daniel4099** [lprhodes/homebridge-broadlink-rm#2]
Hi

I have a problem with sending command to braodlink rm pro.
When I put the TV On in home app iOS I can see on raspberry console UDP Packet send to "broadlink ip address" but on boradlink nothings happend red light not flashing....

Can anyone help me ?

It's working while I'm using home assistant, but not on this plugin...

**Comment by lprhodes** [comment]
It could be that you're not using the RM 2 and not the RM 3. I don't have an RM 2 to test with, sorry.

The code sends a broadcast UDP packet before sending whichever hex code you've stated. It seems most likely that this broadcast packet is different between RM 2 and RM 3. Perhaps you could use Wireshark to determine the broadcast packet.


This is the RM 3 and Mini 3's for reference, it's the same each time so if you don't see this in Wireshark then that's a good indicator that you need to find a different one:
`5aa5aa555aa5aa55000000000000000000000000000000000000000000000000a2f3000037276a00528022a2f00d43b40100000090c80000178a382be0b953f51e066fa79407190dfec18c688af01de0dc428a1f11ace75a10dacb9050c542110e29cc734468d0ae6c476c87c99544bbd0587d14182256eb3b23c674c57d8a2852412c1c335003d6a5fa1d3080c9d1b6210983b3879657a6`

Let me know how it goes and if you figure it out I can update the code to let you use a different broadcast packet.

**Comment by daniel4099** [comment]
This is the code working on RM Pro via home assistant, and I think it's sending via TCP

**Comment by lprhodes** [comment]
home assistant is using https://github.com/mjg59/python-broadlink/ to send hex codes using UDP.

Also, the code you just gave isn't a HEX code which is what this plugin needs. You need to use Wireshark or something similar to get these.

**Comment by daniel4099** [comment]
There is info in homeasisitant to convert hex to base64. It means that hombridge plugins should work also if it use a UDP packet. 

Should I use hex packet to work with your plugin ?

like this ?

ffffffffffffb827eb90c74e0800450000222f9740004011420fc0a8087dffffffff27102710000e0ec1686400067161000000000000000000000000

**Comment by lprhodes** [comment]
Yes...hex. You need to get them from Wireshark - check out the README for a rough guide and you can see roughly what they should look like by looking at the config; your looking for codes that start with 5aa5aa555aa5aa55

**Comment by daniel4099** [comment]
But shouldn't Broadlink red light turn on even if I send not hex packet ?

**Comment by lprhodes** [comment]
Not necessarily

**Comment by daniel4099** [comment]
<img width="883" alt="zrzut ekranu 2017-03-16 o 01 09 37" src="https://cloud.githubusercontent.com/assets/25808596/23976058/4b5c64e4-09e5-11e7-8f16-c69a665ba209.png">

This is my packet from wireshark, when i click command turn on tv on previously learned e-control braodlink app. Now I should click on the packet, copy as stream hex and add it in your config.

Is that right ?

**Comment by lprhodes** [comment]
I personally get the data by having it go through their remote servers which then shows as such: 
<img width="902" alt="screen shot 2017-03-16 at 1 12 59 pm" src="https://cloud.githubusercontent.com/assets/162989/23978869/5eed9a0e-0a4a-11e7-8a6f-3e94bc95c069.png">

I've just committed an update that allows you to add a new accessory in HomeKit for learning a code and have it display in the console logs (see the new config sample and README for details).

Give that a go, if it doesn't work then I'm afraid there's not much more I can do at the moment without an RM 2 to test on.

**Comment by daniel4099** [comment]
I will try harder next week, I will let you know info about the progress.
Maybe someone has RM Pro 2 tested ?

**Comment by lprhodes** [comment]
Hey - I've updated the code so you shouldn't see these issues now (nor will you need to use Wireshark). Note that you'll need to use the Learn IR accessory to learn new codes. Closing for now.

**Comment by daniel4099** [comment]
After last update it start working with RM2.
But I have few Issue, I hope you can help ;)

**There is a problem with multiplay switch, please see my config below, where is the problem ?**

{
          "name": "Xbox",
          "type": "on",
          "on": "260050000001268e131214111411131214121311131214351312131211151235133712121337133514121236131113361313123715101212133613121437111411351314103713371200058a0001244813000d050000000000000000",
          "off": "26005400080002fa000123921114121113141213131014131112133613121312141112391237140f113911371137131312121237121214361213121311151136143612121236131213361337130005880001244813000d0500000000"


},
{
          "name": "TV",
          "type": "on",
          "on": "2600460092941337113811381213111411131213121312371237113812131213121212131213121211391212121312121312121311131238111312381237123712371238123711000d050000",
          "off": "2600460092941337113811381213111411131213121312371237113812131213121212131213121211391212121312121312121311131238111312381237123712371238123711000d050000"
	  
},


{
"1": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
  "2": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
  "3": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
  "4": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
  "5": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
  "6": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
  "7": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
  "8": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
  "9": "2600500000012b93143713371337131312131213131213361313123614371337143613131237141313351413111214121212131213111312131212371437143613391238133614371200050400012b4915000d050000000000000000",
          "type": "channel"
}

After I run hombridge I can see Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.

**Type chanel is displayed as unrecognized accessory in HOME KIT, I can use it only in Elgato Eve App.**

**Comment by lprhodes** [comment]
@daniel4099 To fix the same UUID issue create a separate accessory for each device you wish to control, rather than a separate value in the "data" value.

As for the channel type - it's something I inherited from a different repo, I'll try it out later today and get back to you

**Comment by daniel4099** [comment]
Thanks ;), I will change configuration. Waiting for information about channel ;)

**Comment by daniel4099** [comment]
Any news about channel type ;) ?

**Comment by panacy** [comment]
Hey. Could you guys tell me where do I find console log on raspberry Pi?

Thanks
