### ISSUE TITLE
help with config for air conditioner

### ISSUE THREAD

**Issue by jat80** [lprhodes/homebridge-broadlink-rm#20]
Hi there,

I'm wanting to input a hex code just to turn the air con on.  The problem is that I can't just say siri turn on the air con because it wants a temp and mode as well.  When I turn the air con on it's at 19 degrees and cooling (the last state it was in before turning it off and this was the hex code learnt to turn it on) Off is not a problem.  I can manually set it to cool, 19degrees and then it turns on but just want a hex code to turn it on. How do I do this?

 Here is what i have so far.

  "name": "Air Conditioner",
          "type": "thermostat",
          "data": {
            "off": "260016026b370b2c0f0c0f0c0f0c0e0e0f0d0f0c0f0c0f0c0e0e0c0e0b100b2c0e0d0f0c1e0f0e0d0f0c0f0c0c0f0b100e0d0f0c0f0c0f0c0e0e0c0e0c110a100f0c0f280f0c0e290e2a0b2b0b2c0b2c0e290f0c0f280f290d2a0b2b0b2c0b2c0e290f280f280f0c0f0c0f0c100c0e0e0c0e0c100a100b100e0d0f280f280f0c0e0e0c2a0b2c0b2c0e290f0c0f0c0f280e2a0c0e0b100b100e290f0c0f0c0f28100c0f0c0e2b092c0b100e290f280f0c0f280e2a0c0e0b2c0b2c0b100e0d0f280f0c0e0e0c0e0f0c0f0c0f280e2a0e0c0f280f280e2a0c0e0c0f0b2c0e0d0b10130d0c0f0b100b2c0f280f0c0f280e290d2a0c2b0b2c0d0e0e0d0f0c0f0c0f0c0e0e0b0f0b100f280e290e2a0b2b0b2c0f280f280f280e0e0b0f0b100b100e0d0f0c0f0c0f0c0d2a0c2b0b2c0b2c0e290c2b0b2c0b2c0e0d0f0c0f0c0f0c0e0e0b0f0b100e0d0f280f280e2a0c2a0c2b0d2a0b2c0b2c0e0d0f0c0f0c0f0c0e0e0c0e0b100b100e290f280f280f280e2a0c2a0c2b0b2c0e0d0f0c0f0c0f0c0e0e0c0e0b100e0d0f280f280d2a0b2c0b2c0e290f280f280f280e2a0c2a0b100b2c0e0d0f280f0c0f0c0e0e0c0e0b2c0b100b2c0f0c0f280f280f0c0d0e0c0f0b100e0d0f280f280f0c0e2a0c2b0b2b0b2c0b2c0e0d0f0c0f0c0f0c0e0e0b0f0b100b100e0d0f0c0f280f280e2a0c2a0c2b0b2c0e290f280f0c0f0c0e0e0c0e0c0f0b100e0d0f0c0f280f280e290e290c2b0b2c0b2c0f280f000d050f28",
            "temperature30": {
              "mode": "heat",
              "data": "2600500000012..."
            },
            "temperature19": {
              "mode": "cool",
              "data": "260016026b370b2c0e0d0f0c0f0c0f0c0e100e0c0f0c0e0e0c0e0c0f0b100c2b0b100b100e0d0f0c0f0c0f0c0e0e0c0e0b100b100e0d0f0c0f0c0f0c0e0e0c0e0b100b2c0e0d0f280f280f280e2a0c2a0c2b0b100b2c0e290f280f280f280d2a0c2c0a2c0b2c0f0c0f0c0e0e0b0f0b100b100e0d0f0c0f0c0f0c0e290c2b0b100b100e290f280f280f280e0e0b0f0b2c0b2c0e0d0f0c0f0c0f280e0e0b0f0b2c0b100e0d0f280f280f0c0f280f290d0e0e280e2a0b0f0b2c0b2c0e0d0f0c0f280f0c0e0e0c0e0c0f0b100b2c0e290f0c0f280f280e290c0f0f0d0e280e2a0c0e0f0c0f280f0c0e2a0b2b0f0c0f0c0f280c2b0b100b2c0e0d0f0c0e0e0d0e0b0f0b100b100e0d0f280f280f280e290c2b0b2c0b2c0e290f0c0f0c0f0c0e0e0b0f0b100b100e0d0f280f280f280e2a0b2b0b2c0b2c0e290f0c0f0c0f0c0e0e0c0e0b100b100e0d0f280f280f280e290e290c2b0b2c0e290f0c0f0c0f0c0f0c0e0d0c0f0b100b100e290f280f280f280e2a0b2b0b2c0b2c0e0d0f0c0f0c0f0c0e0e0b0f0b100b100e290f280f280f280e290c2b0b2c0b2c0e290f280f0c0f0c0f280f280d0e0e0e0b0f0b100b2c0e290f0c0f0c0f280e2a0c2a0b100b100b100f280f0c0f280e290d0e0c2b0b2c0e290f0c0f280f0c0e0e0c0e0c0f0b100b100e0d0f0c0f0c0c0f0b2c0b2c0e290f280f280f280e2a0b2b0b100b100e0d0f0c0f0c0f0c0e0e0b0f0b2c0b2c0e290f280f280f280e2a0c2a0b000d050f29"
            }
          }
        },

**Comment by jat80** [comment]
Ok I've managed to set it up as a scene.

**Comment by lprhodes** [comment]
Have you got this working? When you send a code to an air conditioner it includes information about temperature, fan speed and the like so if you learn the code for turning it on you get all of that information too.

I say things like "Siri cool the room" or just "Siri set the temperature to X" and it'll turn the air con on.

"Turn on the air conditioner" may work, I can't remember - working on that code at the moment.

Re-open if you need. 1.0.0 due out later today.
