### ISSUE TITLE
how to control homekit remotely<as we have apple tv>

### ISSUE THREAD

**Issue by wadechat** [lprhodes/homebridge-broadlink-rm#200]
cuz the broadlink can use over the 4G, so I think it possible to control the home app via 4G as well
,anybody have the idea of this issue example use the cloud mqtt as a host instead of apple tv.

thanks so much

**Comment by iCarl** [comment]
This is not possible

**Comment by lprhodes** [comment]
HomeKit requires an Apple TV or iPad on the network for them to perform the HomeKit commands sent over cellular.

homebridge itself could be controlled remotely but then it's not using HomeKit.
