### ISSUE TITLE
Air Conditioner Auto mode not turning on A/c automatically

### ISSUE THREAD

**Issue by rafayez** [lprhodes/homebridge-broadlink-rm#201]
Hi,

Can someone please help me with the code that i can use to set the A/C to a certain temperature from the OFF position. As my A/C doesn't turn ON by itself when a certain temperature is selected, I have to initially turn it ON with the ON button and then set the temperature. I Learned the temp. hex code from the device itself, by selected the learn function and then coping the HEX code learned, to no success.

As a workaround, would it be possible to send two HEX codes at the same time, to the A/c once the temperature is selected(First code to turn the A/c ON and the second to set the temperature), something like below " tbh, being a newbie here makes it difficult to figure out the code on my own. Any help will be highly appreciated. Thank you in advance

"name": "Air Conditioner",
				"type": "air-conditioner",
				"host": "192.168.0.40",
				"replaceAutoMode": "cool",
				"autoHeatTemperature": "18",
				"autoCoolTemperature": "26",
				"autoMinimumDuration": "120",
				"data": {
					"off": "260076006c350f0b0f0c0e27110b0e260f0d0e0c0e0c0f2710250f0c0e0c100b0f270e270e0d100b0d0e0e0c0e0c100c0e0c0f0c0e0d0f0a0f0c0f0d0d0d0f270f0b0f0b100c0e0d0e0b0f0c0f0c0e280d0d0e0c110a100b0e270f0d0f0b0e0d0f0b0e0d100a11250e0d0e280e260e290e260e280f290e000d050000",
					"on":"260006016b350f0b0e0d0e280d0c10260f0c0f0b0f0c0f280e260e0d0e0c110a0f260f280d0d100a0f0d0e0b0f0c100b100b0e0c0f0d0d0c0f0c0e0c0f0c0f270f0c0e0c0f0c100a0f0c0e0d0f0b0f270f0c0e0c0f0d0f0a0f280e26102510260f270e270e270f270f0d0c0d0f270e0d0e0d0f0b100b0d0d0e0d0e0c0e0c11250e270f0d0e0c0f260f0c0e0c110b0e0d0d0d0e270f0b0f281009110a100b100c0d0e0e0b0f0b0f0c0e290e0c0e0c0e0d0f26100c0e0b100d0c0d0f0c100a0f0c0f0b100c0e0c0e0d0f0b0e0e0f0b0e0c110a100a0f0c0e0c0f0e0d0c100c0f0a0f0c0f0b0f0c100c0e0c0e0d0e0c100b0f260e0d0e0d0e0d0f0a10280e25100b0f0d0e260f0f0e000d050000",
					"temperature30": {
						"pseudo-mode": "heat",
						"power": "on",
						"data": "260006016b34100b0e0c0f270e0d0e280d0d0f0b0f0c0f270f270f0a0f0c0e0d0e280f260e0d0e0c100b0e0c100b0f0d0e0b0e0d0e0c100c0d0d0e0c0f0c10260f0c0e0d0e0b0f0c0f0c0e0c110a10260e0c100c0e0c0e0d0e280d270e290d270f270e2610260e27100b0f0d0d270f0c0e0c100b0f0c0f0b0f0c0f0c0f0c0e270f260f0d0d0d0e0d0e0d0f0a0f0d0e280e0d0d270e0d0e270f0c0f0c0e0d0f0b0e0c100b100c0d0e0d27100a0e0e0d0d0f260f0c0e0e0d0c100b0f0b0f0c100b0f0b0f0d0e0c0e0c110a110a0f0b0e0d0e0d0e0c0f0c0e0c0f0c0f0c0e0d0f0b0f0c100c0d0c0f0c100a110b0f0b0e0c0f270e0e0f0b0f270f0a10260f260f270f26100b0f0e0f000d050000"

**Comment by lprhodes** [comment]
Added this to the next release (check out the `sendOnWhenOff` option)
