### ISSUE TITLE
Air-conditioner real temperature value

### ISSUE THREAD

**Issue by acc-ua** [lprhodes/homebridge-broadlink-rm#202]
Is there any way to add configuration for external temperature sensor for Air-conditioner ?
I have a external temperature sensor (xiaomi) that is available in HomeKit, and it will be useful if air-conditioner accessory can use it's real temperature value.

**Comment by alesf** [comment]
I also have this feature request. Maybe the easiest way would be to pool for temperature from local file or url.

**Comment by alesf** [comment]
I see this is dupe of https://github.com/lprhodes/homebridge-broadlink-rm/issues/164
