### ISSUE TITLE
RM Pro Plus

### ISSUE THREAD

**Issue by akaro9er** [lprhodes/homebridge-broadlink-rm#208]
Anyone managed to connect to their RM Pro Plus? I can't get Homebridge RM to discover the device, and assigning an IP/MAC address as host does not solve the issue.

**Comment by Leafney** [comment]
The same problem.

**Comment by RickHOZ** [comment]
Hi Guys, nobody seems to be responding to any of the requests in this area.

**Comment by NoTrace-Kai** [comment]
Hi there ...
here is the same problem, the RM Pro + will not be found from the Homebridge.
I think the Problem is the "new" Version of the RM Pro +, the Version 2017 called 
Broadlink RM3 RM Pro+.
Perhaps there is another protocoll for that device necessary?
Please help ... :)

**Comment by StSei** [comment]
I‘m also Sträfling to connect the RM3 RM pro +. Also adapters for software like iobroker not working anymore. Just the IHC App is working.

**Comment by jakaboers** [comment]
I have the same problem
Has anyone tried Home assistant or similar? I hope those still work, I do not totally understand yet, but as far as I do that is a different mechanism, doesn't need bridge to work.
I've opened a ticket for support at RM tasker plugin site, they're supposed to be fast to react, but nothing yet.
Maybe everyone should open a ticket :)

**Comment by tianshuo** [comment]
The problem is not in this project, but here: https://github.com/lprhodes/broadlinkjs-rm/issues/3

A quick fix is to go into the `node_modules/broadlinkjs-rm` directory of where `homebridge-broadlink-rm` is found(I found it here:`/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm`)

And add these following lines:

```
}else if(devtype == 0x279d){ // RM3 Pro Plus
        dev = new device(host,mac);
        dev.rm(true);
        return dev;
    }
```

after the RM Mini Shate. 
If it still doesn't work, please add this line:
```
console.log("Unknown version:"+devtype);
```
before the `return null;`
and send the log here.

**Comment by NoTrace-Kai** [comment]
Hi there ...
thank you for this information ... now my broadlink RM3 Pro+ is was found by the homebrige ;)
And when i want to scan a RF signal the LED ist on ... but i can't find any "Code" in my syslog:
`Dec 17 23:00:27 hbridge2 homebridge[4527]: [2017-12-17 23:00:27] [Broadlink RM] Garage getTargetDoorState: 0
Dec 17 23:00:27 hbridge2 homebridge[4527]: [2017-12-17 23:00:27] [Broadlink RM] Garage getCurrentDoorState: 0
Dec 17 23:00:32 hbridge2 homebridge[4527]: [2017-12-17 23:00:32] [Broadlink RM] Scan RF (scanning)
Dec 17 23:00:32 hbridge2 homebridge[4527]: [2017-12-17 23:00:32] [Broadlink RM] [Hold down the button that sends the RF frequency]
Dec 17 23:00:35 hbridge2 homebridge[4527]: [2017-12-17 23:00:35] [Broadlink RM] Scan RF (found frequency - 1 of 2)
Dec 17 23:00:35 hbridge2 homebridge[4527]: [2017-12-17 23:00:35] [Broadlink RM] [Keep holding that button!]
Dec 17 23:00:53 hbridge2 homebridge[4527]: [2017-12-17 23:00:53] [Broadlink RM] Scan RF (stopped - 20s timeout)
Dec 17 23:00:54 hbridge2 homebridge[4527]: [2017-12-17 23:00:54] [Broadlink RM] Scan RF (stopped)
`

**Comment by tianshuo** [comment]
@NoTrace-Kai Hi, that's another issue. I suggest you create a new thread.

If you want to use the new `index.js` file, see qata's PR here: https://github.com/Qata/broadlinkjs-rm/pull/1

**Comment by NoTrace-Kai** [comment]
Hi,
thanks a lot, i'll try the file with my homebridge.
And after that i'll start another issue ;)
CU

**Comment by inffc** [comment]
Hi,
I tried to add both lines and the new index.js file @Qata's. None of it worked. My homebridge still wont connect with RM3 pro plus.  I am running homebridge on windows 10 and RM3 pro plus with V52 firmware. 
Please help! 
Thanks

**Comment by NoTrace-Kai** [comment]
Hi. 
I only edited the existing index.js file.
And I only added the first part. 
When I tried to use the new index.js file from Quata it did not work.
CU

**Comment by st3v3nFr** [comment]
Hi Guys.

**Comment by mrblack7** [comment]
My RM Pro died and I was only able to get a RM Pro+ as a replacement.

Would love to get it working with this plugin, if anyone needs any testing done, let me know.

**Comment by NoTrace-Kai** [comment]
Hi there ...

did you see this post?
https://github.com/lprhodes/homebridge-broadlink-rm/issues/222#issuecomment-354954163

CU

**Comment by mrblack7** [comment]
@NoTrace-Kai That worked, thank you very much!

**Comment by Ltomi78** [comment]
![blrmpro_mcu](https://user-images.githubusercontent.com/34459398/35564252-772fef0a-05b1-11e8-8f94-0a44eab12ea6.jpg)
Hi!
I have a working and a bricked (by wrong v20025 FW) rm pro plus device. I would like to relflash the bootloader on the bricked device. I cannot identify the main processor on the pro+ board. Can somebody check the id on the chip marked with red circle on attached picture.
I guess it can be ATtiny 44A-20 MUR or ATtiny 1634 both has 20 pinout.
But probably it is not an Atmega mcu ?
![blrmpro_mcu](https://user-images.githubusercontent.com/34459398/35564210-4fa42d02-05b1-11e8-8125-03518bd1005e.jpg)

**Comment by lprhodes** [comment]
Added proper support for this in the next update

**Comment by lprhodes** [comment]
What's actually new in this version?

**Comment by enishoca** [comment]
when is the next  update? or is it already published?

**Comment by lprhodes** [comment]
The update that fixed this issue is already published

**Comment by Damarus001** [comment]
When is the update coming?

**Comment by kloshar4o** [comment]
@Ltomi78 I did the same stupid thing and broke my rm pro+ have you managed to fix it?

**Comment by Ltomi78** [comment]
Kloshar4o no i boughtba new one and use with google home mini.
The broken rm pro need eeprom desolder reprogram and solder it back.
Raspberrypee..but i think effora does not worth

**Comment by lprhodes** [comment]
@Ltomi78 just curious here...is there any need for a plugin such as this for google home? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ltomi78** [comment]
Iprhodes...no need plugin it works with IHC app very simple.
On the other hand a few days ago rm plugin were updated and now it supports rm pro+ if you want to use with other voice application.
But g h mini not requires any plugin fortunatelly

**Comment by 5chr4mm** [comment]
Is it works with RM Plus (2018)?
