### ISSUE TITLE
Is it possible to control RGB lights?

### ISSUE THREAD

**Issue by KingNickIII** [lprhodes/homebridge-broadlink-rm#209]
I’m sure this is a simple question for some of you, but I have some of those RGB strips with remotes. Would it be possible to control these via home bridge and this plugin?

**Comment by shawnsplace** [comment]
I would think as long as the remote is using either the 315 MHz or 433 MHz or is just a simple infrared remote and you have your device close enough for the ir blaster on it to reach your IR receivers that it would work just fine.

The only thing the RM Pro hardware device does really is capture button presses from remotes and retransmits them. So in any situation where this would be relevant this setup should work fine for it.
