### ISSUE TITLE
Maximum RM device ?

### ISSUE THREAD

**Issue by lynque** [lprhodes/homebridge-broadlink-rm#210]
Thank you for making great plugin.
I wonder if I use more than 2RM device. I have 3 device , but I can only 2 device maximum .
*server cannot detect 3rd device.

Is there any way to use 3 RM device at the same time ?

Thank you

**Comment by dermotos** [comment]
I get this too. I can only control 3 devices though. Cannot detect 4 at the same time. Looking in `getDevice.js`, there seems to be a limit of 5 devices? Bumping this up to 8 didn't seem to let it detect all 4 devices however.

**Comment by dermotos** [comment]
To add to this, today I received an RM Pro to supplement my 4 RM Minis. I can successfully detect and use the Pro along with 3 Mini devices.

**Comment by lprhodes** [comment]
@dermotos The `limit = 5` in getDevice.js isn't actually doing anything

You could try increasing the number of times that it tries to discover new devices by increasing the value in `if (count >= 5) {`.

You could also decrease the amount of time between discovers by decreasing the value in the following:

```
  setTimeout(() => {
    discoverDevices(count);
  }, 5 * 1000)
```

I only have one device so I can't help out much more than that. There should be no limit (within reason). I don't suppose one of the RM Mini's has the same MAC address as another?

Another suggestion is to explicitly specify the IP address of the RM device you with to use in the command as per https://github.com/lprhodes/homebridge-broadlink-rm#multiple-broadlink-rm-devices

**Comment by Nude2life** [comment]
anyone solved this? I got 3 RM4 mini and can only discovered 2 !

**Comment by skumancer** [comment]
This is happening to me too. I've got 4 RM Mini 4 and an RM Mini 3, I can only ever control 3 devices. @lprhodes if you have any debugging steps I should follow, LMK.
