### ISSUE TITLE
[solved] No buttons in Home App

### ISSUE THREAD

**Issue by drtp** [lprhodes/homebridge-broadlink-rm#211]
Hello,

I own a Braodlink RM Pro 2017, which works flawlessly so far. After updating Node.js from version 6.12 to 8.9.1, I installed the homebridge-broadlink-rm plugin under Raspian Stretch. In my config.json I added the following lines:

` "platforms": [
   {"platform": "BroadlinkRM",
  "name": "Broadlink RM",
  "hideScanFrequencyButton": false,
  "hideLearnButton": false,
  "accessories": []
  },...`

My Homebridge starts without any problem and shows that the broadling-rm plugin has found the RM Pro under IPv4 adress 192.168.0.46. In addition, the log shows that there is no accesorie for the "BroadlinkRM" platform. 

I now would expect a Learn and a ScanFrequency Button within my Home App under iOS 11. However, I can not found such buttons. What do I have to do, in order to overcome this problem?

Best regards,

Thorsten

**Comment by drtp** [comment]
Okay, now it works. Thank to [this description](https://forum.smartapfel.de/forum/thread/218-broadlink-rm-pro-funk-und-infrarot-sender/?postID=8783#post8783) I only had to add some additional lines to the accessories part of the BroadlinkRM platform within config.json:

`"platforms": [ {"platform": "BroadlinkRM", "name": "Broadlink RM", "hideScanFrequencyButton": false, "hideLearnButton": false, "accessories": [{"name": "New switch", "type": "switch", "data":{"on" :"", "off": ""}}] },...`

Why is this missing within the manual on the start page of the plugin?

Best regards,

Thorsten

**Comment by alexymik** [comment]
Hi,

I had the same problem and your post helped me figure it out. I had an empty array of accessories `[]` as I was hoping to populate it after learning codes. Turns out you need at least one device as you point out.

Here's some better formatting of your example:

```json
"platforms":[
  {
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "accessories": [
      {
        "name": "New switch",
        "type": "switch",
        "data": {
          "on": "",
          "off": ""
        }
      }
    ]
  }
]

```

I am also hoping to submit a pull request for some more clear documentation so I'm include this image so I can reference it later.

![homebridge-broadlink](https://user-images.githubusercontent.com/3083780/33922435-d6ce64f8-df98-11e7-8da3-16113eb726e0.png)


Thanks

**Comment by GHaigh** [comment]
Hi there, wonder if anyone can help.  I too don't see any buttons in my home app.  I'm running Homebridge on a Mac mini and it discovers my Broadlink Pro and shows me it's IP & MAC address but still no buttons.  Here is the extract from my config.json,  can anyone spot what I might be doing wrong?

"platforms": [
      {
      "platform": "BroadlinkRM",
      "name": "Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false,
      "accessories":[
        {
          "name": "New switch",
          "type": "switch",
          "data": {
            "on": "",
            "off": ""
          }
          }
      ],

Thanks
Greg

**Comment by alexymik** [comment]
@GHaigh I can only give some shots in the dark:

1. Try running your entire config through [JSONLint](https://jsonlint.com/), though if Homebridge is starting without error I doubt the syntax is the issue
2. Did you try force quitting the Home app on iOS and looking at the default room?
3. Perhaps try another accessory type to see if it makes some difference:

```json
{
  "name":"Volume Up",
  "type":"switch-repeat",
  "sendCount":5,
  "interval":0.3,
  "data":"2600500000012..."
}
```

**Comment by GHaigh** [comment]
@alexymik, thanks for the advice, I tried each step.  Unfortunately no difference, I still can't see any see switches in the Home app.

At a bit of a loss now. :-(

**Comment by alexymik** [comment]
What if you try to add the accessory manually?

```json
{
  "name": "Learn IR",
  "type": "learn-code"
}
```

**Comment by GHaigh** [comment]
No, just tried that too.  How strange!

I've deleted the Homebridge Cache and that didn't help, removed the Hombridge 'Hub' from the Home App and re-added, again no difference.

Struggling now.  I am running on a Mac and can't seem to see any Homebridge log files, any ideas where they might be?  Nothing in /var/log nor in the ~/.homebridge directory.

Greg

**Comment by GHaigh** [comment]
Sorted, all my fault, I needed each platform between {}!

Thanks for your pointers though, they really did help!

Greg

**Comment by dibelli5** [comment]
I used the example of alexymik and I arrived at this point (see photo).
My iphone sees the broadlink-rm pro but I do not know what to do who helps me?

![fullsizerender-21-01-18-04-59](https://user-images.githubusercontent.com/35661229/35196054-4e32a362-fecd-11e7-932c-15f0c81b022e.jpg)

**Comment by alexymik** [comment]
You need to monitor the homebridge log and use the "Learn" and "Scan Frequency" accessories to get the codes from your devices.

Look at my rewritten documentation for more detail in this section https://github.com/alexymik/homebridge-broadlink-rm#learning-hex-ir-and-rf-codes

**Comment by dibelli5** [comment]
thanks for the reply, I saw and reviewed so many times that guide, I managed to recover even the hex code but I did not understand where I have to insert it

**Comment by alexymik** [comment]
You need to put it into the `"data"` parameter of the accessory you are trying to replicate in homebridge.

**Comment by dibelli5** [comment]
ahhhhh ok I try and let you know thanks 1000

**Comment by dibelli5** [comment]
thank you, thank you, thank you, I finally succeeded I am very happy !! I wanted to add another 3 Auto-off Switch buttons but I could not get the .json file that I compile is always wrong. you can help me?

**Comment by lprhodes** [comment]
Sorry, I'll make it so that no accessories are needed for the default buttons
