### ISSUE TITLE
Reverse Blinds 

### ISSUE THREAD

**Issue by RodolfoPortugal** [lprhodes/homebridge-broadlink-rm#215]
I have a problem, in my blinds, when it is open, the blind in the home app appears closed, and when it is closed in the home app it is open, there is some way to reverse these commands, I tried to change open for close, but nothing has changed !! !

sorry if you have any errors like mine, already reported, I really searched, but I did not find !!!

thank you

**Comment by felipesalomao** [comment]
Just use:

`"allowResend": "true",`

this way it ignore status and execute command anyway..

**Comment by lprhodes** [comment]
@RodolfoPortugal you could also turn your blinds off and press the button then turn them back on.
