### ISSUE TITLE
Scan RF Codes

### ISSUE THREAD

**Issue by hpascual** [lprhodes/homebridge-broadlink-rm#217]
Hi, I just installed you plugin for Homebridge. First of all, let me tell you it's an amazing work. Works like a charm with my Air Conditioner, and it's super easy to configure.

In the case of my windows shades, they work with RF, and I just can't learn the HEX Codes, because they change randomly on every learn. I saw a previous thread where you solved it on v2.2.1 of your plugin. I think I am using the latest version of your plugin, but for me it's not working. 
The shades work great with the Broadlink App.

Any help will be much appreciated.

Best regards!

**Comment by lprhodes** [comment]
I suspect this is related to #119 - keep an eye on that.
