### ISSUE TITLE
Add a delay option between commands (rf)

### ISSUE THREAD

**Issue by iandronowicz** [lprhodes/homebridge-broadlink-rm#219]
I have 10 rf blinds and 9 rf switches. All controlled in 3 separate broadlinks rm. When I try to open or close all blinds (worse if I set them in a specific position since an stop command for each is needed) some blinds won’t respond to the rf command. I can tell that the commands are all being sent because I see the broadlink orange light but I think that because all 3 broadlinks start sending rf commands the blinds go crazy and some respond and others don’t.

Wouldn’t it be possible to add like a delay between commands? Configurable in the config.json?

I know that a possible solution would be to separate the automation in 3 or 4 automation at 7:00, 7:01, 7:02... and so on so to delay the rf commands in between but that’s not a nice solution.

Thanks!

**Comment by iandronowicz** [comment]
I can say now that the problem is when sending rf commands from more than 1 broadlink is what is making the mess, the rf commands get jammed up. If I send all the commands through only one it works ok because it sends them one by one

**Comment by lprhodes** [comment]
I'd be happy to add support for this, can you send over your config.json please. I'd like to make sure we're on the same page.

**Comment by lprhodes** [comment]
There's a new "delay" option I've just added in 2.6.2 that delays all commands for that accessory by the provided value.
