### ISSUE TITLE
Help Please !Multiple Platform items, multiple accessories, struggling in config,json 

### ISSUE THREAD

**Issue by RKF-FKR** [lprhodes/homebridge-broadlink-rm#221]
Hello folks - this is my first post on GitHub - please be gentle

I'm trying to configure my Broadlink Mini 3 using this plugin without joy.

I've been playing with homebridge for the last two weeks with great success.  I've got my TV to switch on and off through IOS Home (with the home bridge SonyAndroidTV plugin) as well as switch on my wemo plug with Homebridge.plugin - in both cases I simply cut and pasted their sample config.json and corrected the odd quotation marks in order to achieve success.  I thought I was fast becoming a Homebridge / json pro.

What I've now noticed is that every contributor posts a sample config.json in order to get their plugin up and running.  But what happens to the existing config, and how do I add other accessories reliably using the sample .json supplied?

Sadly now I'm thinking that my two previously enabled plugins above were enabled quite by chance, because by my observation in my original config I have only got one platform and one accessory..

NOW - my quest is to add one or 2 Broadlink RM accessories. I just want to use it to turn on my air conditioner and perhaps my heater.  I don't care about temperature adjustments or anything.  Just switch it on 20 minutes before I get home.  I can do it with the Broadlink IOS app.  So they're working as they should.

The homebridge-broadlink-RM is recognised in my Homebridge startup - so it's up and running.
But if I add the sample.json with my personalisation, my config,json my homebridge won't work.  

So I spent 3 days bumbling around to the point where I'm totally bamboozled.  I'm yet to get my first button in my IOS home to even trap my first code.

I'd appreciate any hand holding to get me on my way.  Thank you.
Rod

Here's the latest fail: but bear in mind I've added the "learn code", and many others just to get some sign of life.

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-12-17 07:16:03] Loaded plugin: homebridge-broadlink-rm
[2017-12-17 07:16:03] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2017-12-17 07:16:03] ---
[2017-12-17 07:16:07] Loaded plugin: homebridge-platform-wemo
[2017-12-17 07:16:07] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2017-12-17 07:16:07] ---
[2017-12-17 07:16:12] Loaded plugin: homebridge-sony-android-tv
[2017-12-17 07:16:12] Registering accessory 'homebridge-sony-android-tv.SonyAndroidTV'
[2017-12-17 07:16:12] ---
[2017-12-17 07:16:12] Loaded config.json with 2 accessories and 2 platforms.
[2017-12-17 07:16:12] ---
[2017-12-17 07:16:12] Loading 2 platforms...
[2017-12-17 07:16:12] [Broadlink RM] Initializing BroadlinkRM platform...
[2017-12-17 07:16:12] [Broadlink RM] No accessories have been added to the undefined config.
[2017-12-17 07:16:12] [WeMo Platform] Initializing BelkinWeMo platform...
[2017-12-17 07:16:12] Loading 2 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**AND HERE IS MY config.json**

{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "BroadlinkRM",
      "name": "Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false
    },
    {
      "platform": "BelkinWeMo",
      "name": "WeMo Platform",
      "expected_accessories": "1",
      "timeout": "25",
      "homekit_safe": "1"
    }
  ],
  "accessories": [
    {
      "name": "Auto-off Switch",
      "type": "switch",
      "host": "192.168.1.131",
      "disableAutomaticOff": false,
      "onduration": "5",
      "data": {
        "on": "2600500000012...",
        "off": "2600500000012..."
      }
    },
    {
      "accessory": "SonyAndroidTV",
      "name": "Sony TV",
      "ip": "192.168.1.103",
      "psk": "my password"
    }
  ]
}

____________________________________________________________________________________________
**EDIT
SO - I deleted my entire config.json to ONLY include the mini RM3 (mine)**
changing it to something really simple:

{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "BroadlinkRM",
      "name": "Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false
    }
  ],
  "accessories": [
    {
     "accessory": "Broadlink RM Learner",
             "type": "learn-code",
             "name": "Learn IR",
             "host": "192.168.1.131"
     }
       ]
     }

And here's the sad result - I smell a rat.

[2017-12-17 10:43:59] Loaded plugin: homebridge-broadlink-rm
[2017-12-17 10:43:59] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2017-12-17 10:43:59] ---
[2017-12-17 10:44:03] Loaded plugin: homebridge-platform-wemo
[2017-12-17 10:44:03] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2017-12-17 10:44:03] ---
[2017-12-17 10:44:08] Loaded plugin: homebridge-sony-android-tv
[2017-12-17 10:44:08] Registering accessory 'homebridge-sony-android-tv.SonyAndroidTV'
[2017-12-17 10:44:08] ---
[2017-12-17 10:44:08] Loaded config.json with 1 accessories and 1 platforms.
[2017-12-17 10:44:08] ---
[2017-12-17 10:44:08] Loading 1 platforms...
[2017-12-17 10:44:08] [Broadlink RM] Initializing BroadlinkRM platform...
[2017-12-17 10:44:08] [Broadlink RM] No accessories have been added to the undefined config.
[2017-12-17 10:44:08] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Broadlink RM Learner' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by alexymik** [comment]
It looks like the main issue is that your configuration contains some invalid values. The `"accessories"` array for your Broadlink devices needs to be nested under the Broadlink platform. You also have an extra `"accessory"` parameter in the device definition.

You might see it better with the correct formatting.

Before:

```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideScanFrequencyButton": false,
		"hideLearnButton": false
	}],
	"accessories": [{
		"accessory": "Broadlink RM Learner",
		"type": "learn-code",
		"name": "Learn IR",
		"host": "192.168.1.131"
	}]
}
```

```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideScanFrequencyButton": false,
		"hideLearnButton": false,
		"accessories": [{
			"accessory": "Broadlink RM Learner",
			"type": "learn-code",
			"name": "Learn IR"
		}]
	}]
}
```

Note that the `"host"` is optional unless you have multiple units, so I removed it from your example.

**Comment by RKF-FKR** [comment]
Hello alexymik:  Thanks very much for your reply.

The device worked as expected after implementing your suggestions.  The nesting was invaluable. The Broadlink displays the RF code in the console for the button presses of my Air Conditioner remote.

I was also able to successfully add-in my wemo platform as was shown in my earlier correspondence.  It was a matter of knowing where to put the comma.  To accomplish this, I pasted your code, duplicated your platform, and edited the fields in the construction pane on the RHS (on https://jsoneditoronline.org).

But some of my original confusions still remain.

(1) Once I have the rf codes I'd like to use them control the A/C switch on/off in homekit.
(2) I'm still failing in my attempts to reintroduce the lines of json that controlled my sonyAndroid TV
{
"accessory": "SonyAndroidTV",
"name": "Sony TV",
"ip": "192.168.1.103",
"psk": "my password"
}

I just don't know how to insert the lines of code in the right place in the config.json, despite various attempts.

Once I get these two accessories inserted in the code I should be in the box seat to interpret how the logic works.  I'm not just sitting on my hands - but finding the right place to learn as a rookie seems to be proving difficult.

Cheers

**Comment by alexymik** [comment]
If your original config from your first post worked to control your tv then it work if you add it as an accessory in the main homebridge accessories list:

```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
			"platform": "BroadlinkRM",
			"name": "Broadlink RM",
			"hideScanFrequencyButton": false,
			"hideLearnButton": false,
			"accessories": [{
					"accessory": "Broadlink RM Learner",
					"type": "learn-code",
					"name": "Learn IR"
				},
				{
					"name": "TV Power",
					"type": "switch-repeat",
					"sendCount": 1,
					"data": "260088000b3a0c170a180b1..."
				},
				{
					"name": "Air Conditioner",
					"type": "switch-repeat",
					"sendCount": 1,
					"data": "2600d6006e6f0d2a0e0e0e..."
				}
			]
		},
		{
			"platform": "BelkinWeMo",
			"name": "WeMo Platform",
			"expected_accessories": "1",
			"timeout": "25",
			"homekit_safe": "1"
		}
	],
	"accessories": [{
		"accessory": "SonyAndroidTV",
		"name": "Sony TV",
		"ip": "192.168.1.103",
		"psk": "my password"
	}]
}
```

**Comment by RKF-FKR** [comment]
Hello Alexymik.
Again, thanks so much for your help.  All is working as expected.  For me, it was not including the square brackets that caused the problem.
I'm starting to understand the code syntax a little better now and I think I'll be okay for the future accessories.
I'm so pleased that it's all set up and running.  I owe you a beer!

**Comment by rbhale** [comment]
RKF-FKR, 

Thanks for asking this question! I felt just like you, clueless as to how this was really done. This post helped a lot. I'll probably have to post later to get more help haha but I appreciate you being willing to ask for those of us struggling like you were!

**Comment by jimmibond** [comment]
Use this JSON Formatter and Validator for JSON editing. 
https://jsonformatter.org

**Comment by ricar61** [comment]
I cannot fix the IP of the RM..(tried to fix via router assignment of Mac address, apple time capsule, did not work...) is there a way to specify the Mac address of the desired RM for a given accessory, TV, for instance.... ? i.e.: I want to specify the room to send the HEX_Code specifying Mac address of the appropriate RM, not the IP address... thanks

**Comment by cubilon** [comment]
solve the fixed DHCP assignment. you’re doing something wrong.

**Comment by dietlow** [comment]
I'm having the same issue. i can't add this the ip camera platform to my exiting code below.






 {
  "bridge":{
    "name":"Homebridge",
    "username":"CD:22:3D:E3:CE:30",
    "port":50430,
    "pin":"031-45-154"
    },
  "description":"Homebridge",
  "accessories":[


  ],
  "platforms":[
    {


      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false,
      "hideWelcomeMessage": true,
      "accessories":[
        {
          "name":"Auto-off Switch",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 5,
          "data":{
            "on":"2600500000012...",
            "off":"2600500000012..."
          }
        },

        {
          "name":"TV ",
          "type":"switch",
          "data":{
            "on":"26007600093c0a19091a091a0919091a093c093d0919093d0919091a091a093c091a090001753932300606790829150001e309000119093c091a091a0919091a093c091a091a093c091a093c093c0a3c091a093c0900059b093c091a0919091a091a09190a3c093c091a093c091a091a0919093d091909000d050000",
            "off":"26007600093c0a19091a091a0919091a093c093d0919093d0919091a091a093c091a090001753932300606790829150001e309000119093c091a091a0919091a093c091a091a093c091a093c093c0a3c091a093c0900059b093c091a0919091a091a09190a3c093c091a093c091a091a0919093d091909000d050000"
          }
        },
        {
          "name":"Audio box",
          "type":"switch",
          "data":{
            "on":"260054004e1426151314261513142714131412161215131412161215260003514d15251612152714131427141314131513141314121612152700034f4e142615131427141315251612151314131413151314131427000d0500000000",
            "off":"260054004e1426151314261513142714131412161215131412161215260003514d15251612152714131427141314131513141314121612152700034f4e142615131427141315251612151314131413151314131427000d0500000000"
}
},
{
  "name":"Cable On/Off",
  "type":"switch",
  "data":{
    "on":"26004c000d091428080c040a04190424083e040b0428040005970a0006490c0a14140423041a12240712080907151309081813000bd90d0815150410041d050a14060715041504100523042913000d05000000000000000000000000260060000d091415072004191219041504290419042908000bd70c091514090b091904270424080c0423040b042805000bda0d081514080c081a140814090812080c04240429040908000bd80d1708120410041e130913240410081f05080a1704000d050000000000000000260032000d091415072e042704160811080c0820042913000bda0d07080607150410081a040a14220416080c08111309081804000d05000000000000260030000d0a1414081f041a1223061408250419082504000bda0e07151507080a1c14081415041504100424040a081704000d05000000000000000026002e000d190811082e141704240429040a0409052a07000bd70d0815150410081914080608151404100523043708000d050000000000000000000026005a001d0707140424040a040b0607050a04160415042906070806072806000bd90d0608080714060e061c0508061805140416050f05220508081913000bd90e0706090515041004101309050a05230514041006210607081904000d05000000000000000000000000000026002e000c09050908130410041e040a051814280423053704000bdb0d0715150809091b05191223080d0423141904000d0500000000000000000000",
    "off":"260054004d1526151215271413142714131412161314131413151215260003504d1525161314271413142714121513151314121513151314270003504e142615121527141215261513141315131413141315131427000d0500000000"
}

},


{
  "name":"Mute TV",
  "type":"switch",
  "data":{
    "on":"260054004d1512161215271413142714121513151314131412161215270003634d1512161116251612152714141312161215131411161315250003644e151215121526151215271413151314121513151215121526000d0500000000",
    "off":"260054004d1512161215271413142714121513151314131412161215270003634d1512161116251612152714141312161215131411161315250003644e151215121526151215271413151314121513151215121526000d0500000000"
}


},
{
          "name":"Apple Tv Audio",
          "type":"switch",
          "data":{
          "on":"260054004e1413152615121513141215271412161314121513151314260003644d1512152615131513141215261512151315121513141216250003654d151314261512151216131427141215121513151314131427000d0500000000",
          "off":"260054004e14131427141215271412152714271413151314121513142700033d4e14131427141215271412152714271413151314131413152600033e4e141315261512152615131427142714121513151314131427000d0500000000"
}

},
        {
          "name":"O Apple Tv Audio",
          "type":"switch",
          "data":{
          "on":"260054004e1427141314271427142714271427141314131413151215270003144e1427141315251527142714271427141315131412151314270003174e142813131427142714271427142714121512161314131426000d0500000000",
          "off":"260054004e14131427141215271412152714271413151314121513142700033d4e14131427141215271412152714271413151314131413152600033e4e141315261512152615131427142714121513151314131427000d0500000000"
}
},
        {
          "name":"Channel up2",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 1,
          "data":"26003c002c12070d070d05091507080608070912070d0614050807070806080e06000b872c13060e060e230617060913070d05141506170e05000b880d000d05000000000000000000000000"

        },
        {
          "name":"Android Audio",
          "type":"switch",
          "data":{
          "on":"260054004f13271413141315261512152615261512151215131512152600033d4f13271412151315261512152615271412151315121513142700033c4e132714131513142714121527142714131512151314121526000d0500000000",
          "off":"260054004e14131427141215271412152714271413151314121513142700033d4e14131427141215271412152714271413151314131413152600033e4e141315261512152615131427142714121513151314131427000d0500000000"
}
},
        {
          "name":"TV Audio",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 1,
          "data":"260054004e14131427141215271412152714271413151314121513142700033d4e14131427141215271412152714271413151314131413152600033e4e141315261512152615131427142714121513151314131427000d0500000000"

        },

        {
          "name":"Volume Up",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 2.5,
          "data": [
            {
              "data": "260034014e1413142714121514142714131413141315131412151315270003634e1412152615121513142714131513141215131513141314270003664e1412152714121512152714131512151314121613141314270003644e1413142714131413152615121512151215131513141314270003644e1413142714131412152714131512151314131513141314270003634e1412152714131413152615131413141216131413141315260003644e1412152714121513152615131413141215141413141314260003654d1612142516131512152615121512151315121513141315250003644e1515122616111512152715111612161115121612151216250003654d1611162516111611162615121513141116121613151116250003674d161017251512161215271412151215121612171015121625000d0500000000",
              "sendCount": 5,
              "interval": 0.6
            }
          ]
        },
        {
          "name":"Double Up ",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 2.5,
          "data": [
            {
              "data": "260034014e1413142714121514142714131413141315131412151315270003634e1412152615121513142714131513141215131513141314270003664e1412152714121512152714131512151314121613141314270003644e1413142714131413152615121512151215131513141314270003644e1413142714131412152714131512151314131513141314270003634e1412152714131413152615131413141216131413141315260003644e1412152714121513152615131413141215141413141314260003654d1612142516131512152615121512151315121513141315250003644e1515122616111512152715111612161115121612151216250003654d1611162516111611162615121513141116121613151116250003674d161017251512161215271412151215121612171015121625000d0500000000",
              "sendCount": 10,
              "interval": 0.6
            }
          ]
        },
        {
          "name":"Double Down ",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 2.5,
          "data": [
            {
              "data": "26008c004e14261526151314131427141315131413141315121513142700034f4e1427142714131413152615131413141315121512151314260003514e1427142714131513142615121513151215131413141315260003504e1427142714131413152516131412151315121513141314270003504e142714261513141314271412161314131413151314131427000d05000000000000000000000000",
              "sendCount": 10,
              "interval": 0.6
            }
          ]
        },
        {
          "name":"Volume Down ",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 2.5,
          "data": [
            {
              "data": "26008c004e14261526151314131427141315131413141315121513142700034f4e1427142714131413152615131413141315121512151314260003514e1427142714131513142615121513151215131413141315260003504e1427142714131413152516131412151315121513141314270003504e142714261513141314271412161314131413151314131427000d05000000000000000000000000",
              "sendCount": 5,
              "interval": 0.6
            }
          ]
        },
        {
          "name":"HHHHHHHHH",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 1.5,
          "data":[
            {
              "data": "260060002c13070d070d140726130613070d07122307090d07000b861c070912070d070d14070807080609130514070d0515050807070707080e07000b860e0707070814050f050f050807070707080707140515050e0614050807070807070f06000d050000000000000000",
              "pause": 0.3
            },
            {
              "data": "",
              "pause": 0.3
            },
            {
              "data": "HEX_3...",
              "pause": 0.3
            }
          ]
        },
        {
          "name":"etertsnment",
          "type":"switch",
          "data": [
            {
              "data": "2600a20070731c551c1d1b1d1c561a1e1b571b1d1c1d1b1d1b1e1c1d1a571b1e1a571a571c1c1b571b1d1c561a551e551b561c561c1c1c0004526f741a571b1d1c1d1b561b1e1c551b1e1b1d1b1e1b1e1b1d1b561b1e1c551c551c1d1b561b1e1c551b561b571c551b561c1d1c0004526f731c551b1e1c1d1b561b1d1b571a1e1c1d1b1d1c1d1c1d1a571c1c1b571b561b1e1a571b1e1a571a571b561c551c561b1d1b000d05000000000000",
              "sendCount": 2,
              "interval": 0.3,
              "pause": 2
            },
            {
              "data": "",
              "sendCount": 2,
              "interval": 5
            }
          ]
        },
        {
          "name":"Apple Tv V",
          "type":"switch",
          "data": {
            "on": [

              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "sendCount": 4,
                "interval": 0.6,
                "pause": 0.3
              }
            ],
            "off": [
              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "pause": 0.1
              },
              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "sendCount": 9,
                "interval": 0.6,
                "pause": 0.3
              }
            ]
          }
        },
        {
          "name":" O Apple V",
          "type":"switch",
          "data": {
            "on": [

              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "sendCount": 5,
                "interval": 0.6,
                "pause": 0.3
              }
            ],
            "off": [
              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "pause": 0.1
              },
              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "sendCount": 8,
                "interval": 0.6,
                "pause": 0.3
              }
            ]
          }
        },
        {
          "name":" Android V",
          "type":"switch",
          "data": {
            "on": [

              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "sendCount": 6,
                "interval": 0.6,
                "pause": 0.3
              }
            ],
            "off": [
              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "pause": 0.1
              },
              {
                "data": "260088000a3b091a09190a19091a093c0a3b0b180a19093c091a091a0919093d0a180b0005de0a3c0a180a190a1909190a19091a093c093d0a18093d093c0a3b0a19093c0a00059a0a3b0a190a19091a081a0a3c083d091a0919093d0919091a091a093c091a090005e00b3a0a190a19081a091a091a0a18093d0a3b091a0a3b09390d3c0a180b3b0a000d05",
                "sendCount": 7,
                "interval": 0.6,
                "pause": 0.3
              }
            ]
          }
        },
        {
          "name":"Blind Multi",
          "type":"window-covering",
          "totalDurationOpen": 5,
          "totalDurationClose": 2,
          "data":{
            "open":"OPEN_HEX...",
            "close":[
              {
                "data": "CLOSE_HEX_1...",
                "sendCount": 2,
                "interval": 0.3,
                "pause": 0.3
              },
              {
                "data": "CLOSE_HEX_2..."
              }
            ],
            "stop":"STOP_HEX..."
          }
        }
      ]
    }
  ]
}
