### ISSUE TITLE
Cannot run Homebridge as a service with homebridge-broadlink-rm plugin

### ISSUE THREAD

**Issue by jasehigh** [lprhodes/homebridge-broadlink-rm#224]
I have set-up a separate insistence of Homebridge (utilising the homebridge-broadlink-rm plugin) following the instructions from @NorthernMan54  here - [https://github.com/nfarina/homebridge/issues/1246](url)

While I can manually start Homebridge without issue:

`sudo DEBUG=* homebridge -D -U /Users/admin/.broadlink`

The global deamon on my Mac mini refuses to start this instance of Homebridge.
The "LaunchDaemons" script is as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/usr/local/bin/:$PATH</string>
	</dict>
	<key>GroupName</key>
	<string>wheel</string>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>com.broadlink.server</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/homebridge</string>
		<string>-U</string>
		<string>/Users/admin/.broadlink</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/tmp/com.broadlink.server.err</string>
	<key>StandardOutPath</key>
	<string>/tmp/com.broadlink.server.out</string>
	<key>UserName</key>
	<string>root</string>
</dict>
</plist>
```
An identical script referencing my other Homebridge instance works fine.

The error I get points to an issue with the homebridge-broadlink-rm plugin:

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1249:7)
    at Object.init (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:7:32)
    at BroadlinkRMPlatform.HomebridgePlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:14:21)
    at BroadlinkRMPlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/index.js:11:1)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:624:30)
```

If anyone can help with this issue it would be very much appreciated.

Jason.

**Comment by gid204** [comment]
I’m having the same problem...

Running with systemd on raspberry pi 2.
It works fine when I do not have any broadlink config data in config.json file but when I add it in it freezes up when registering that platform.

I have noticed in the readme file that there is a section titled “Overriding the homebridge directory (AKA where the consig.json file lives)”. I believe I need to implement this as my config.json file lives in var/Homebridge and not it’s original directory. I’m just unsure of how I go about “adding a "homebridgeDirectory" key/value pair to the platform config“.

Thanks in advance

**Comment by gid204** [comment]
@jasehigh I managed to get mine working....

The Broadlink platform is using the default location to look for config.json, so you need to tell it where to look as per what I wrote above..
Mine now looks like this:
"platforms": [{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideScanFrequencyButton": true,
		"hideLearnButton": true,
		"homebridgeDirectory": "/var/homebridge",    <------adding this line fixed it for me

Substitute your config.json file location and it will hopefully fix it.

Cheers

**Comment by jasehigh** [comment]
Perfect!

Adding:

````
"homebridgeDirectory": "/Users/admin/.broadlink",
````

To my config.json file did the trick. I wouldn't have thought this was required as the launch script specified the path to the config.json file:

````
/usr/local/bin/homebridge -U /Users/admin/.broadlink
````

Many thanks for the assistance.

Jason.
