### ISSUE TITLE
Turning switch on/off (Multiple presses to power off)

### ISSUE THREAD

**Issue by alantahoe** [lprhodes/homebridge-broadlink-rm#229]
I have a projector that uses the same hex code to turn the device on and off. However in order to turn the device off, it requires you to hit the power button once, then a message pops up and asks you to hit the power button again to turn it off (so a total of 2 times, with about half a second in-between). Is there any way to accomplish this with these commands? I have tried switch, switch-repeat and switch-multi with no luck.

here is my code

{
			"platform": "BroadlinkRM",
			"name": "Broadlink RM",
			"hideScanFrequencyButton": false,
			"hideLearnButton": false,
			"accessories": [{
					"name": "Projector",
					"type": "switch-repeat",
					"host": "192.168.0.59",
					"data": [{
							"on": "2600d80000012b95133712381337143613131212133712131312121312131212133812131237121313121337121313131212121313111312133813111337133814351337133714361300056500012a96133712381337133713121312133712121412121312121312143712131237121314111337121313121411131212121411133812121337133714361337133713371300056500012b961336133714371336131312131237131213121312131212131238131212371312131312371313111314121212121312131337121312371437123812371437123713000d05"
						},
						{
							"off": "2600d80000012b95133712381337143613131212133712131312121312131212133812131237121313121337121313131212121313111312133813111337133814351337133714361300056500012a96133712381337133713121312133712121412121312121312143712131237121314111337121313121411131212121411133812121337133714361337133713371300056500012b961336133714371336131312131237131213121312131212131238131212371312131312371313111314121212121312131337121312371437123812371437123713000d05",
							"sendCount": "2",
							"interval": "1"
						}
					]
				},

**Comment by S474N** [comment]
Try this:

```
	    {
			"platform":"BroadlinkRM",
			"name":"Broadlink RM",
			"host":"192.168.0.59",
			"hideScanFrequencyButton": false,
			"hideLearnButton": false,
			"accessories":[
			{
				"name":"Projector",
				"type":"switch-repeat",
				"sendCount":1,
				"interval":1,
				"data":"2600d80000012b95133712381337143613131212133712131312121312131212133812131237121313121337121313131212121313111312133813111337133814351337133714361300056500012a96133712381337133713121312133712121412121312121312143712131237121314111337121313121411131212121411133812121337133714361337133713371300056500012b961336133714371336131312131237131213121312131212131238131212371312131312371313111314121212121312131337121312371437123812371437123713000d05"
			}
				]
		},
```

**Comment by alantahoe** [comment]
I dont understand how this would work? I need to hit the power button once to turn on and requres two sends of the same hex code to power off. I dont think this config would power the device off

**Comment by S474N** [comment]
Mea culpa! And what about two buttons? One for ON and second for OFF?

**Comment by alantahoe** [comment]
that is what i am trying to avoid doing. I know how to do that but was trying to get it on one button/switch

**Comment by S474N** [comment]
But if you once power on or off with another device (remote, no power,...), there may be real state of device on another state in HomeKit. I think it's better two buttons.

**Comment by Silentbob101** [comment]
"accessories": [
                {
                    "name": "Projector On/Off",
                    "type": "switch-repeat",
                    "host": "192.168.1.25",
                    "sendCount": 1,
                    "offSendCount": 2,
                    "interval": 1,
                    "disableAutomaticOff": true,
                    "data": {
                        "on": "26006201733b0f0e0f2b0e100d100c110d0f0e0f0e0e0f0f0d0f0f0e0e100d100c2d0e0f0d0f0f0f0d100d100d0f0f0e0e100c100e2c0e0f0d100e0e0f2b0e0f0e0f0e2b0f0e0e100e0e0f0e0e0f0f0e0e0f0d110c110c2c0f0e0f2b0f2b0e2c0e2b0f0e0f0e0e2c0f0f0c2d0e0f0e2b0f2b0f2b0f2b0e00094274390f0f0d2c0e0f0e0f0e0f0e0e0f0e0f0e0e0f0f0f0d100d100c100d2c0e100d0f0f0b120e0e0f0d110c100e0e0f0f0d2c0f0f0d0f0e0f0e2c0e0f0d0f0f2b0f0e0f0f0d100d0f0d100e100c0f0e0f0f0e0f2b0e0f0e2c0d2c0f2b0f2b0e0f0e0f0e2b0f0e0f2b0f0e0e2c0e2c0e2b0f2b0e00094274390f0f0d2c0e0f0e0f0d110c100e0f0e0e0f0e0e0f0f0f0d100c110c2c0f0f0d0f0f0f0d0f0f0e0f0e0e0f0d110c100d2c0e100d0f0f0e0e2c0d100e100b2d0f0e0f0e0e0f0e100c100e0f0e100c100d100e2b0f0f0d2c0e2b0f2b0e2c0f0e0f0e0e2c0e0f0e2b0f0e0f2b0e2c0e2b0f2b0f000d05000000000000",
                        "off": "26006201733b0f0e0f2b0e100d100c110d0f0e0f0e0e0f0f0d0f0f0e0e100d100c2d0e0f0d0f0f0f0d100d100d0f0f0e0e100c100e2c0e0f0d100e0e0f2b0e0f0e0f0e2b0f0e0e100e0e0f0e0e0f0f0e0e0f0d110c110c2c0f0e0f2b0f2b0e2c0e2b0f0e0f0e0e2c0f0f0c2d0e0f0e2b0f2b0f2b0f2b0e00094274390f0f0d2c0e0f0e0f0e0f0e0e0f0e0f0e0e0f0f0f0d100d100c100d2c0e100d0f0f0b120e0e0f0d110c100e0e0f0f0d2c0f0f0d0f0e0f0e2c0e0f0d0f0f2b0f0e0f0f0d100d0f0d100e100c0f0e0f0f0e0f2b0e0f0e2c0d2c0f2b0f2b0e0f0e0f0e2b0f0e0f2b0f0e0e2c0e2c0e2b0f2b0e00094274390f0f0d2c0e0f0e0f0d110c100e0f0e0e0f0e0e0f0f0f0d100c110c2c0f0f0d0f0f0f0d0f0f0e0f0e0e0f0d110c100d2c0e100d0f0f0e0e2c0d100e100b2d0f0e0f0e0e0f0e100c100e0f0e100c100d100e2b0f0f0d2c0e2b0f2b0e2c0f0e0f0e0e2c0e0f0e2b0f0e0f2b0e2c0e2b0f2b0f000d05000000000000"
                    }
                }
            ]

**Comment by lprhodes** [comment]
@alantahoe 

@Silentbob101 's solution is the way to go
