### ISSUE TITLE
Fan is duplicated. Is this expected behavior?

### ISSUE THREAD

**Issue by shawnsplace** [lprhodes/homebridge-broadlink-rm#232]
I got the plugin and a few device setup and working properly but I notice that when I add a FAN in the config file that I get two fan switches that show up in the home app on iOS for the same device.

One fan switch has a normal dimmer type of switch and the second one has the dimmer switch AND a clickable OSCILLATE button on the bottom left.

Is this expected behavior or a bug?

I don't really need the second switch with the oscillate function. Is there any was to change my config to just show one or the other of these switches? I didn't really notice anything that mentioned this in the documentation.

Thanks for any help, and thanks to the plugin creator for all the hard work on this!

**Comment by lprhodes** [comment]
I expect it's due to iOS 11 now properly supporting the newer fan. Previously Fan V1 showed up in the Home app and Fan V2 allowed Siri to be used to control it.

I'll default the V1 fan to bring hidden now and add an option to show it

**Comment by lprhodes** [comment]
Amended in the next update -also be sure to check out the README which covers options for hiding/showing the different fan buttons
