### ISSUE TITLE
Noob Harmony hub homebridge custom RF and broad link-rm

### ISSUE THREAD

**Issue by KennethNorway** [lprhodes/homebridge-broadlink-rm#233]
Hi all. I just got my RPi running home bridge with home alarm system, door lock and IKEA lights hub.
Just bought the harmony hub and need som help. I am learning config.json slowly so bare with me.

With my harmony hub I now want to know if there is any possibility to add custom rf commands in my config file to make te harmony hub send command I like to my DVR thru SIRI. ex: "Hey Siri, switch to Eurosport" or " put on SKY sports" or "Show me the TV guide"

And does broad link-rm work with harmony hub as only hardware?

Any help is valued. Have a good evening to all.

Regards, Kenneth - Trondheim - Norway

**Comment by gid204** [comment]
Harmony Hub uses its own software (MyHarmony) to configure devices and activities. There is a Homebridge plugin for harmony hub but in my experience (and I think others) its quite buggy and does not really work.

In saying that I worked around this by using IFTTT and webhooks (formerly Maker).

Using this plugin: https://github.com/ilcato/homebridge-ifttt

So you can set up activities, through MyHarmony to start the entertainment system with the correct inputs, channels etc. Then make an IFTTT applet utilising webhooks and the harmony support, then with the Homebridge plugin you'll be able to control it with home app and Siri etc.

Hopefully that made sense :)

**Comment by lprhodes** [comment]
Closing this - feel free to re-open
