### ISSUE TITLE
2 RM but 1 only one discovered

### ISSUE THREAD

**Issue by m4d-maNu** [lprhodes/homebridge-broadlink-rm#235]
I need 2 Broadlink, because my AVR is hidden in a lowboard. So I have a Broadlink in the lowboard and the other so that he has the DVR in view.

But my Homebridge always only recognizes a Broadlink.

My Config:
 ```
{
		"platform": "BroadlinkRM",
		"name": "Broadlink",
		"hideScanFrequencyButton": true,
		"hideLearnButton": false,
		"accessories": [
			{
			"name":"AVR Learn",
			"type":"learn-code",
			"host":"192.168.1.8",
			"disableAutomaticOff": true,
			"scanFrequency": false
			},
			{
				"name": "Lauter",
				"type": "switch-repeat",
				"sendCount": 5,
				"interval": 0.3,
				"host": "192.168.1.8",
				"data": "26004800000127941213111411131213111411131213123811131411121311141138123712381213113812381138121313121113123811381213121311141138123712381114111312000d05"
			},
			{
				"name": "Leiser",
				"type": "switch-repeat",
				"sendCount": 5,
				"interval": 0.3,
				"host": "192.168.1.8",
				"data": "26004800000129931311131213121312121213121312123713121312121312121337133613371311131213121312123713121213123713361436133614361312123713371311131213000d05"
			},
			{
				"name": "Lautlos",
				"type": "switch",
				"host": "192.168.1.8",
				"data": {
					"on": "260050000001289414111213131213121313131213131336121312131411131213371435153514111337131312121412131212131336153513121337133614361237143612131411130005bc0001284a12000d050000000000000000",
					"off": "260050000001289414111213131213121313131213131336121312131411131213371435153514111337131312121412131212131336153513121337133614361237143612131411130005bc0001284a12000d050000000000000000"
				}
			},
			{
			"name":"DVR Learn",
			"type":"learn-code",
			"host":"192.168.1.7",
			"disableAutomaticOff": true,
			"scanFrequency": false
			},
			{
				"name": "Sender vor",
				"type": "switch-repeat",
				"sendCount": 1,
				"host": "192.168.1.7",
				"data": "2600b4000e091513050f0515050f051a050a0509050a0514060f0514050a0514050a050905000b870e091414050f0515050f051a0509050a05090515050f0515050905150509050a05000b860f08050a0514060f0514050f051a050a0509050a0515050f0514050a05140609050a05000b860e0905090515080c0515050f051a0509050a050a0415050f051505090515050a040a05000b870e081514070d0514060e051a0707070808120515050f05141514051805000d0500000000"
			},
			{
				"name": "Sender zurück",
				"type": "switch-repeat",
				"sendCount": 1,
				"host": "192.168.1.7",
				"data": "260092000e091414050f0515050f051a050a0509050a0514050f0515050a0514050a050f05000b7e0e0905090614050f0515050f051a05090609050a0514050f0515050a0415050a050f05000b7e0e091414050f0515050f051a0509050a050a0415050f051505090515050a041005000b7e0e081514050f0514060e06190609050a05140515050f0515050905150509050f05000d05000000000000"
			}
		]
	}
```

Homebridge discovered only 1 Broadlink:
`Discovered Broadlink RM device at 192.168.1.7 (34:ea:34:43:a5:d8)`

**Comment by lprhodes** [comment]
Odd that the second one isn't discovered automatically.

Specifying a "host" by-passes the discovery though. If the switches don't work on the 192.168.1.8 host then it sounds like there's a connectivity issue - can you `ping 192.168.1.8` ?

**Comment by rednini** [comment]
I have the same problem.

2 RM mini
ping ok
random discovered only 1

v2.6.3
node /node_modules/homebridge-broadlink-rm/helpers/getDevice.js
Discovered Broadlink RM device at 192.168.0.10 (34:ea:34:42:bb:bb)
^C
node /node_modules/homebridge-broadlink-rm/helpers/getDevice.js
Discovered Broadlink RM device at 192.168.0.15 (34:ea:34:42:b5:e7)
^C

Thanks

**Comment by takjg** [comment]
I have the same problem. 

Although [python-broadlink] discovers all RMs in a local network,  getDevice.js does not.

I hope you will find the function [discover] of [python-broadlink] helpful.

I really appreciate all your work on homebridge-broadlink-rm.

[python-broadlink]: https://github.com/mjg59/python-broadlink/blob/master/cli/broadlink_discovery
[discover]: https://github.com/mjg59/python-broadlink/blob/master/broadlink/__init__.py#L66

**Comment by m4d-maNu** [comment]
Yes, I can ping my RM Minis.

On my router can I See the RM Minis, too.

**Comment by takjg** [comment]
Solved!  Please check a PR: https://github.com/lprhodes/broadlinkjs-rm/pull/6 .

**Comment by lprhodes** [comment]
Fixed in 2.6.4 - due out in the next hour or so

**Comment by m4d-maNu** [comment]
Thx now works fine

**Comment by lprhodes** [comment]
In case you have further issues there's a new method of adding devices manually to your config in case auto-discovery isn't working for whatever reason.

Check out the [docs](https://lprhodes.github.io/slate/#device-discovery) on it.
