### ISSUE TITLE
Allow multiple (hex) IR codes for light switches

### ISSUE THREAD

**Issue by tomhoplon** [lprhodes/homebridge-broadlink-rm#236]
Hi,

Thanks for the amazing pluggin. It has unlocked all sorts of possibilities for me. In particular, I'm trying to control Lutron Rania (dual) dimmers which are IR capable. Unfortunately, the Lutron remotes only do "on", "off", "up" and "down". So for (e.g.) "brightness20", I'd like to do "off" followed by "up". However, it doesn't seem to like two Hex values in an array.

Could that be added.

**Comment by lprhodes** [comment]
You can do this. I've added an example in the `config-sample.json` - search for "Entertainment 3"

**Comment by tomhoplon** [comment]
Thanks. I did spot that but it doesn't seem to work on light. Here's the config code:

{
                "name":"Zone2",
                "host":"0d:43:b4:e4:20:f2",
                "type":"light",
                "disableAutomaticOff": true,
                "useLastKnownBrightness": true,
                "data":{
                        "off":"26001400000256e0e04a4a4a0001764a4ae04a954a0001760d050000",
                        "brightness100":"26001400000256e0e04a4a4a0001764a4ae0e04a4a00012b0d050000",
                        "brightness75":"26001400000256e0e04a4a4a0001764a4a954a954a0001c10d050000",
                        "brightness50":"26001600000256e0e04a4a4a0001764a4a954a4a4a4a9500012b0d05",
                        "brightness25":"26001400000256e0e04a4a4a0001764a4a4ae0e04a00012b0d050000",
                        "brightness10":[
                                        {
                                        "data":"26001400000256e0e04a4a4a0001764a4a4ae0e04a00012b0d050000",
                                        "sendCount":1,
                                        "pause":2
                                        },
                                        {
                                        "data":"26001600000256e0e04a4a4a4a00012b4a00012b4a4a4a0001c10d05",
                                        "sendCount":1,
                                        "pause":0
                                        }
                                        ]
                         }
                },

and here's the error, sorry if I'm being stupid:

setBrightness: (closest: 10)
(node:2825) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError [ERR_ASSERTION]: HEX value is missing
(node:2825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lprhodes** [comment]
brightness10 doesn't match up with the config-sample.json. You have no on/off keys.
