### ISSUE TITLE
"Long press"

### ISSUE THREAD

**Issue by tomhoplon** [lprhodes/homebridge-broadlink-rm#237]
One more query. On of my light switches can be programmed with a 'long press' on the remote control. Although I have the code I can't execute it. I've tried switch-repeat with it firing 200 times but this does not have the desired effect. Any ideas.

**Comment by lprhodes** [comment]
Generally a long press with IR means that the code learnt ends up being a longer code, so it should still just end up being a single code.

Without one to test with I can't do much else to help, sorry! I'm happy to receive one to test on.

**Comment by tomhoplon** [comment]
Thanks, I'm afraid that's my dilemma too because I've not got the remote I'm trying to emulate but I do know the codes, in pronto format. I was interested to read this wiki article on pronto codes http://www.etcwiki.org/wiki/Pronto_Infrared_Format. It suggests that the format is explicit in it's inclusion of an alternative code for long press. I'm using this script to convert the raw codes for use on broadlink: https://gist.github.com/appden/42d5272bf128125b019c45bc2ed3311f. But it only seems to carry across the first short press, not the ability to hold the button down. Which - in my case - would programme the lightswitch itself. I need to do four PRONTO codes (for a Lutron Switch). One of them is: 
0000 0069 0000 0007 032A 010E 005A 010E 005A 005A 0168 005A 005A 005A 010E 010E 005A 0168

It's easy to see the pattern there for the initial and repeat bursts but I can't make it work by just using switch-repeat.

**Comment by lprhodes** [comment]
It sounds like the converter script could be updated to support the long press codes - it may be worth checking with the author of that. There's not much else I can do to help here, sorry!

**Comment by tomhoplon** [comment]
I'll check in with the script author, thanks. I'd be more than happy to send a remote which has this behaviour if that was a serious offer. Just let me know your address.

**Comment by lprhodes** [comment]
Pronto IR code support is now included in the plugin. I just converted the python code so it doesn't help with the long press sorry.
