### ISSUE TITLE
Impossible to send RF command on RM PRO PLUS

### ISSUE THREAD

**Issue by Hohnjo** [lprhodes/homebridge-broadlink-rm#238]
Hello !
Thanks for the great plugin !

I've managed to get the RM PRO PLUS detected by editing the index.js file and to get the hex codes of my RF remote but it doesn't work, don't know if it sends nothing or wrong rf command...

Here is the broadlink part of my config.json :

"platform": "BroadlinkRM",
			"name": "Broadlink RM",
			"hideScanFrequencyButton": false,
			"hideLearnButton": false,
      "accessories":[
      {
  "name":"RF On/Off",
  "type":"switch",
  "data":{
  "on":"260008016c400a0f0a300b0f0a300a130b2d0a1408140a1107120a130b2f0a110b0b0f110c15092a0b2d0d2e0a4e0a300910091308120b100b120a120b2f0a110a32080f06180a130a1308120b32090e09300a120b2e0b2e0b110a330a00099b6e3f0b0e0c300a1509100a1409120a490a110b0e0c180911092e0a30091209150b0b09150b2e0b4d0a2b0a150a460c110c110b33092b0a100d2d0b1409100a130b1008140a3109120a2d0c1409310a2c09110b2d0c00099f705c093008120a1109130a14091107170c2a0b11081408140a30072e0c1309110b12094d0a2e0b110a320b0e08120c110c130a1009130a130e0f0a2d094a0b4a0c120b0b104c09300a100a68091209310a000d05",
  "off":"2600f4006e4109110b2d0c110a2d0a110b2e0b4a0b110a140a2c0b130a110d1009130a0f0b17092e092e0a0f0c2f0b15090f0b120b2c0a140b1309120a2b0d4a0b100b1009690b2d0b140a300a0f0a33092b0b130a12070009a16e3e0a4b0a120b10094d0b140a0d0d110a110b100c6809150b2a0b0f09110e2f0c2c0b100c2d0b2f0b0d074e0c130a130a2c0a120f2a0a1607110c100b14096708130b4e092d0a2e0e0b0d140a00099d713f09150a2a0a120a110c1409130a12092c0a0e0e140a2d08670c30099d09130934090c0d2e0c100a110c160a130a0e0d2b0a6a090c0d120b150a2c0a310b100a2e0c0f0c300a2f0a2c0f000d0500000000"

**Comment by santiagos5** [comment]
Are you sure RF device isn’t rolling code?

**Comment by Hohnjo** [comment]
i'm not sure I've understood, you mean the hex codes i got frome the learn button are not RF codes ?

**Comment by santiagos5** [comment]
RF remote can be rolling code (change everytime the hex code when press the button) and fixed code. you can use only devices which have remote with fixed code. if you don't know if remote is rolling code, you can scan another time the hex code and compare it with the first you get. if they are different, it is a remote with rolling code so the RM pro doesn't work. if the remote is rolling code neither the Broadlink app standalone will work.

**Comment by Hohnjo** [comment]
Okay thanks for the answers ! It works with the broadlink app so i guess it’s A fixed code.

There are threads that suggest that rf codes doesn’t work with the last rm pro plus.. :(

**Comment by santiagos5** [comment]
I got my rm pro plus two weeks ago and rf code works for me.. S/N: RM3322xxxxxx
have you scan frequency correctly? my RF hex codes are very shorts respect IR codes.. your seems like an IR code..
I only update index.js file, and then learn hex code in this way #222

**Comment by Hohnjo** [comment]
I havn't tried this way to learn codes i'll try tomorrow ! Thanks again for your answers !!

**Comment by santiagos5** [comment]
you're welcome!

**Comment by iCarl** [comment]
@santiagos5 Could you please send me your config.json and index.js, I have the same version of RM as you, and I can't even get the buttons to show up.

**Comment by santiagos5** [comment]
this is my index file, and config-sample.json that I used. replace hex code and (or) delete switches that you won't.
 https://www.dropbox.com/s/4tq3nnge5b8gxbj/config-sample.json?dl=0

**Comment by iCarl** [comment]
@santiagos5 Thank you!, I managed to get it to work.
Although the buttons that should appear automaticallty didn't, so I added them manually.

**Comment by lprhodes** [comment]
I'll sort out a fix specifically for the Pro Plus so you don't need to do the trick with Learn Code

**Comment by Reddyzinho** [comment]
Well I have a problem like this but with the IR codes. The plugin finds the RM3 mini and my pro plus Broadlink devices ...I have put the “host” in each acessorie (mac address). The plus send only the RF codes and the mini the IR codes. When try to send IR code from pro plus nothing occurs. Any help on this ?
