### ISSUE TITLE
can't set scene.

### ISSUE THREAD

**Issue by jat80** [lprhodes/homebridge-broadlink-rm#24]
Hey @lprhodes 

Trying out your new update and the TV codes are working great for on/off and volume.  Thanks.

I'm having problems with the air con though.  Previously I could have a hex code for 18 cooling and then have a scene with those parameters and it worked fine.  Now it's not.

Here's my config:

<img width="490" alt="screen shot 2017-03-30 at 9 18 26 pm" src="https://cloud.githubusercontent.com/assets/23650727/24494489/eec12eee-158e-11e7-8a72-8d91f79283b5.png">

And heres what it looks like on the home app:

![fullsizerender 2](https://cloud.githubusercontent.com/assets/23650727/24494516/04eba74e-158f-11e7-9ed2-73934e5e1340.jpg)

**Comment by lprhodes** [comment]
So the scene is designed to set it to 18?

What happens when you ask Siri to set the temperature to 18? I've just tried that and it works. I see the following in the logs:
<img width="843" alt="screen shot 2017-03-30 at 9 35 58 pm" src="https://cloud.githubusercontent.com/assets/162989/24500427/0de36236-1591-11e7-8929-8a61f886c923.png">

...using the following config:
<img width="683" alt="screen shot 2017-03-30 at 9 36 18 pm" src="https://cloud.githubusercontent.com/assets/162989/24500501/5bba7b8e-1591-11e7-9256-ebfcb77eb659.png">

What do your logs say?

**Comment by jat80** [comment]
Here's what it looks like:

![img_4551](https://cloud.githubusercontent.com/assets/23650727/24530300/8225397c-160d-11e7-89c8-531574678f3f.PNG)

![screen shot 2017-03-31 at 12 25 41 pm](https://cloud.githubusercontent.com/assets/23650727/24530310/915b4e5e-160d-11e7-9de8-a1611cb6428b.png)

it turns on but something is quite not right. Then when I look back into the home app (after 2mins or so) the failed under the scene is gone and logs show this:

[3/31/2017, 12:25:30 PM] [Broadlink RM] getTemperatureDisplayUnits (0)
[3/31/2017, 12:25:30 PM] [Broadlink RM] getTargetTemperature (18)
[3/31/2017, 12:25:30 PM] [Broadlink RM] getTargetHeatingCoolingState (cool)
[3/31/2017, 12:25:30 PM] [Broadlink RM] getCurrentHeatingCoolingState
[3/31/2017, 12:25:30 PM] [Broadlink RM] getSwitchState: 0
[3/31/2017, 12:25:30 PM] [Broadlink RM] getSwitchState: 0
[3/31/2017, 12:25:30 PM] [Broadlink RM] getCurrentTemperature (13.8)

**Comment by jat80** [comment]
And yes - scene is designed for 18degrees, cool.

**Comment by jat80** [comment]
@lprhodes the state in the home app seems to reset so even though the accessory is on it gets reset to off as well.  I think I'm going to do a complete reset.  Didn't have these issues on the previous version.

**Comment by lprhodes** [comment]
@jat80 the state in the home app will reset any time you restart home bridge as it has no way of getting the current status when it starts again

**Comment by jat80** [comment]
Ended up setting up 2 switches (1 for 18degress cooling and 1 for 30 degrees heating) to make this work.  Couldn't get the actual air con type to work properly with my air con unit.  Happy with it currently like this.  Thanks.

**Comment by lprhodes** [comment]
If the two hex codes work then the air conditioning type will work - I feel like there's a misunderstanding about how it's implemented. Let me know if you'd like to get it working fully.

**Comment by jat80** [comment]
@lprhodes probably due to my lack of no how! lol  I just don't know what the config should look like to stop the app switching to show it's heating when initially I set it to cool when I go out and back into the app.   And it always showing 14degrees for some reason.  Sometimes when I turn it off manually it says not responding as well.  I'm obviously doing something wrong as the hex codes work fine with switches and they worked fine on the previous version.

**Comment by lprhodes** [comment]
What does running `npm -v homebridge-broadlink-rm` output?

**Comment by lprhodes** [comment]
What does running `npm view homebridge-broadlink-rm version` output?

**Comment by lprhodes** [comment]
If it's returning 14 and the room is definitely not 14 then it's likely that the broad link device you have doesn't support temperature control (most likely) or has a broken one (least likely). Override this to 0 using `"psuedoDeviceTemperature": 0` You can then just ignore the 0 when you see it in the Home app.

If you're wanting to use 18 and 30 then set `"minTemperature": 18` (maxTemperature already defaults to 30) and `"defaultCoolTemperature": 18`

Finally add "temperature18" and "temperature30" to the "data" part of the config.

Now whenever you set the temperature to 18, 19, 20, or 21 the temperature18 hex will be sent and the mode will be set to cool. If you set the temperature to 22 or above, temperature30 will be sent and the mode will be set to heat.

If you want to change the point at which it selects 18 or 30 - you need to add a "heatTemperature" value. By default this is 22 (which is shown in the example above)
