### ISSUE TITLE
Outlet type showing as switch and viceversa

### ISSUE THREAD

**Issue by iandronowicz** [lprhodes/homebridge-broadlink-rm#240]
First of all thank you for the great work and for keeping up with our annoying requests!

I've just updated the plugin and without changing anything in the config the switch accesories I have are now outlet type. This is great news, I had to change some of them to light type from the home app since they were lights but one of them I want to keep as switch in the home app and couldn't find they switch type in the home app. Only light, outlet and fan.

The strange thing is that I modified the config.json so that only the actual outlet have the outlet type instead of the switch type and when I restarted homebrige those accessories configured as outlet didn't have the outlet option anymore from the home app!

So the switch types in the config appear as outlet but the outlet types appear as switch.

Thanks in advance!

{
          "host":"10.0.1.7",
          "name":"Calentador De Toallas",
          "type":"outlet",
          "data":{
            "on":"b21524005054151915191519151815181518151715172817151729171417281628161516150002a500000000",
            "off":"b21824005054151915191519151814181518151815172817151728171516141615162915280002a500000000"
          }
        },
        {
          "host":"10.0.1.7",
          "name":"Luz De Pasillo",
          "type":"switch",
          "data":{
            "on":"b21f2400111412131113111322131113211211122112221221112200022c4245111411141114111400000000",
            "off":"b22124001213121223121212221212111211121112111200022b424412131213121312141213131300000000"
          }
        },

**Comment by lprhodes** [comment]
Sorry - fixed in 2.6.3

**Comment by lprhodes** [comment]
Whoops - good catch. I've sorted for the next update, thanks
