### ISSUE TITLE
I have a dream about temperature, sound, light, air quality

### ISSUE THREAD

**Issue by yanmeyer** [lprhodes/homebridge-broadlink-rm#242]
First, thank you for all the job, and the great development.

I try the new RM pro 3 with your recent development and it’s working great.

I read about request about temperature for air-con. The best would be to
support the Broadlink A1 sensor, that would give information not only for temperature, but
also for humidity, sound, light and air quality.

As you get the control of the new rm-pro, would be possible to get info from A1 sensor?

Thank you for feedback.

**Comment by lprhodes** [comment]
Hey - I'll add it to the wish list for the temperature requests. I'll likely get to it one day this week.

**Comment by lprhodes** [comment]
Please refer to #244

**Comment by lprhodes** [comment]
Support has been added for `temperatureFilePath` in 3.0.5
