### ISSUE TITLE
Converting Pronto to Broadlink Codes

### ISSUE THREAD

**Issue by taitems** [lprhodes/homebridge-broadlink-rm#243]
First of all, thanks for the great plugin.

My goal is to have explicit commands for most things, as I want to turn the TV off as part of a Siri Good Night scene, and not *toggle* the power state. 

What I've found is that my learned code for power toggle is really long:
`260070004f1428141314271414142714131514132715131413151314140003524e1527141314271513142715131413152714131414141314140003524e1528131414271413142814131413152714131513141315130003544f132814131427151314281314141314271513141414131414000d050000000000000000`

But if I take a discrete power off **pronto** code for a Sony TV and convert it with the often referred to [python script](https://repl.it/repls/AcademicNiftyMantisray), I end up with something much shorter?
`26001c004e1327132713271327131313271313132713131313131313130003270d0500000000000000000000`

I'm wondering if this not working is the original pronto codes fault, or the conversions fault. Would love some better docs here for sourcing codes online and getting them into this library. (PS. the black bean does fire the LED when I run the command, so that part is working)

Any help would be appreciated.

**Comment by lprhodes** [comment]
Hey, the intention for this plugin is primarily to learn and then re-send rather than be able to use all of the different codes that various learning devices offer.

If someone wants to code some javascript that is able to consistently convert codes from whichever device they use to codes that Broadlink can send then I'd be happy to integrate it.

**Comment by taitems** [comment]
I guess this wasn't so much a feature request as a "has anyone else had any success here"? Googling hasn't turned up much, so hopefully the next person to stumble across this issue may be able to shed some light.

**Comment by tomhoplon** [comment]
JavaScript rather than python?

**Comment by lprhodes** [comment]
@tomhoplon yes

**Comment by lprhodes** [comment]
@taitems how come you can't just learn using the Learn IR button?

**Comment by taitems** [comment]
@lprhodes So nearly all IR remotes are stateless, they'll send a power **toggle** command.

If you consider the Siri "Good Night" command, it goes through and turns off all my stateful IoT devices. This could potentially toggle a TV on command, rather than sending an explicit TV OFF command. These commands exist, and can be found online, but cannot be triggered from a remote. Therefore they must be converted from a simple pronto code to what Broadlink expects. I've had some level of success using the Python script to convert it, but my commands are substantially shorter than the ones that this script learns.

There are possibly really convoluted ways of getting around this though. If you send a channel up command, that will turn on a sleeping TV (or if already on, change the channel), sleep X seconds, then fire the power toggle command. The down side of this is that a powered off TV will momentarily turn on, only to turn off again. An already on TV will lose it's channel state and potentially end up on a telemarketing channel next time you turn it on.

That's my predicament, if that helps :)

**Comment by lprhodes** [comment]
Ah, interesting - I hadn't realised off-specific commands were available.

I've just added Pronto support in 2.7.0. I converted the python code to javascript so I can more easily support it.

Given that it's using the same logic for conversion it likely won't help your predicament (there's a pingIPAddress option that may be helpful...so it won't send an on/off code it's already off).

I've yet to test Pronto codes other than make sure the output in the conversion script is correct so I'll see if I come across any similar issues with my Dyson fan I'll be using for testing.

**Comment by hepcat72** [comment]
I obtained hex codes for my LG TV from irdb.globalcache.com.  I *think* they are pronto codes.  They start with `0000`, which the docs here say is what they use to identify pronto codes, but when I enter them into the config and try them, I get the error:
```
[9/7/2023, 12:14:43 PM] [Broadlink RM] [ERROR] Main Viewscreen sendData (A Pronto code was detected however its conversion to a Broadlink code failed.)
```
Does anyone know if the code needs massaged in some way in order to be successfully converted?
