### ISSUE TITLE
Temperature from alternate sources

### ISSUE THREAD

**Issue by lprhodes** [lprhodes/homebridge-broadlink-rm#244]
Wrapping up what people want in terms of getting the temperature from other sources for use with the "aircon" accessory:

- File - simply a number in a file
- URL - either a number or a JSON payload that you specify
- Broadlink devices including the A1
- HomeKit accessory temperatures

The last time I checked, HomeBridge isn't architectures to allow communication between plugins. This means that this isn't possible at this time.

Ref: #164 and #242

**Comment by ashtonaut** [comment]
I use a 1-wire temperature sensor hooked up to the Raspberry Pi GPIO pins. It’s pretty easy to poll this and dump the temperature to a file, so I’d love to see this method supported.

**Comment by RealLittleSherman** [comment]
I thinks that MQTT that a multi purpose data source for this type of data

**Comment by tomky** [comment]
I think either File or URL are useful enough in many cases. We may then use some shell scripts or http-webhooks as proxy.

**Comment by lprhodes** [comment]
Support has been added for `temperatureFilePath` in 3.0.5

**Comment by lprhodes** [comment]
My thinking is in line with @tomky's in that you should be able to achieve what you need using `temperatureFilePath` combined with other shell scripts.

I'll likely add support for other broadlink sources such as the A1 in the future
