### ISSUE TITLE
Unable to install due to dependency broadlinkjs-rm@^0.2.4

### ISSUE THREAD

**Issue by dessmith** [lprhodes/homebridge-broadlink-rm#246]
Hi,

If I run npm install -g homebridge-broadlink-rm / with or without sudo I get 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for broadlinkjs-rm@^0.2.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'homebridge-broadlink-rm'
```

If I check https://www.npmjs.com/package/broadlinkjs-rm it only shows version 0.2.2 is there some delay, or some command I can run to update the repo so that it can download 0.2.4. Even if I install broadlinkjs-rm directly with npm it pulls 0.2.2

Thanks

**Comment by Silentbob101** [comment]
Having same issue here

**Comment by lprhodes** [comment]
Sorry, published it.
