### ISSUE TITLE
Problem with fan

### ISSUE THREAD

**Issue by siobhanellis** [lprhodes/homebridge-broadlink-rm#247]
running node 8.7

I've upgraded to the new version of your plugin, and I'm now getting:

[11/02/2018, 6:29:38 pm] [Broadlink RM] Initializing platform accessory 'LR Fan'...
/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/fan.js:122
          onData: clockwise,
                  ^

ReferenceError: clockwise is not defined
    at FanAccessory.getServices (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/fan.js:122:19)

I have tried various options as this is a new item. My relevant section of my config.json is:

        {
          "name": "LR Fan",
          "type": "fan",
          "data": {
            "on":"640b1c000b0b16160b0b150b160b16160b160b0b16160b160b160b160b00016f000000000000000000000000",
            "off":"65271c000b0c15160b0c150c160b15160b160b160b160b160b0b15160b000170000000000000000000000000",
            "fanSpeed30": "65511c000b0b15160b0b160b150b15160b160b160b0b16160b150b160b000170000000000000000000000000",
            "fanSpeed60": "640b1c000b0b16160b0b150b160b16160b160b0b16160b160b160b160b00016f000000000000000000000000",
            "fanSpeed100": "650e1c000b0b15160b0b150b150b15160b0b15160b160b160b160b160b000170000000000000000000000000",
            "showRotationDirection": false,
            "showV1Fan": true,
            "showV2Fan": false 
          }

**Comment by lprhodes** [comment]
Fixed this in v2.6.6

**Comment by siobhanellis** [comment]
Thanks. I had upgraded, but was running 2.6.5. Now on 2.6.7 and all is good.
thanks
