### ISSUE TITLE
Suggestion: Send Multiple Codes In A Sequence

### ISSUE THREAD

**Issue by RickNunn** [lprhodes/homebridge-broadlink-rm#25]
Firstly, awesome, I picked up one of these little IR blasters a while ago hoping that it would make it into HomeBridge! So thanks so much for making this plugin. 

I have a suggestion, adding the ability to send multiple IR codes from a single switch. This would allow someone to turn on a TV/Soundbar/Xbox etc… all with one switch. Would this be possible? 

Thanks

**Comment by lprhodes** [comment]
You're very welcome!

Great idea - I just released 1.0.5 with support for that in https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.0.5

**Comment by astrojetson8** [comment]
@RickNunn @lprhodes can either of you post an example of how to do this? thanks

**Comment by RickNunn** [comment]
@astrojetson8 You can find an example here: https://github.com/lprhodes/homebridge-broadlink-rm/blob/master/config-sample.json#L51

**Comment by astrojetson8** [comment]
@RickNunn Thanks Rick
