### ISSUE TITLE
Color for Lights

### ISSUE THREAD

**Issue by Nastras** [lprhodes/homebridge-broadlink-rm#251]
Hey Luke,

I have maybe an idea for the lights.I have led candles these are controlled via ir. These also support different color.
I have currently assigned the hex codes for color as brightness.
Is there a way to incorporate a slider for color or something similar?

**Comment by lprhodes** [comment]
Hey @Nastras there's no way for me to add elements to the Home app that don't already exist, sorry.

**Comment by Nastras** [comment]
i just thought of a dummy switch type slider in the stages 1-10 sending a hex code.

Each level would be a color. That would be better than using the brightness for it.

Thought that would be possible.

Can not do anything. Thank you anyway.

**Comment by lprhodes** [comment]
Latest release includes support for hue
