### ISSUE TITLE
Can we have the option "onDuration": 5 with a switch multi repeat?

### ISSUE THREAD

**Issue by bertybassett** [lprhodes/homebridge-broadlink-rm#252]
I'd like for this to happen

> {
>                 "name":"vacuum",
>                 "type":"switch-multi-repeat",
>                 "disableAutomaticOff": true,
>                 "onDuration": 5,
>                 "data": {
>                 "on": [
>                 {
>                     "data": "26004800000128941411131214111312121...",
>                     "sendCount": 1,
>                     "interval": 0.1
>                 }
>                 ],
>                 "off": [
>                 {
>                     "data": "260048000001289414121212131213...",
>                     "sendCount": 5,
>                     "interval": 5
>                 }
>                 ]
>                 }
>             }

However I believe the "onDuration": 5 isn't a valid option because at present it just gets ignored?  I would be super happy should this be implemented or someone can suggest a way to achieve this.

Tested the onDuration feature with a standard switch and it work.  My issues is I need to press off at least 5 times to get my vacuum to work consistently (it could be out of range of the IR blaster)

**Comment by lprhodes** [comment]
Yep - available in v2.6.13

**Comment by bertybassett** [comment]
What a Legend !!!!

**Comment by bertybassett** [comment]
next question how do I update to v2.6.13

**Comment by lprhodes** [comment]
https://docs.npmjs.com/getting-started/updating-global-packages
