### ISSUE TITLE
discovery unknown broadlink

### ISSUE THREAD

**Issue by RayL1234** [lprhodes/homebridge-broadlink-rm#253]
When i update my broadlink plugin it's show me
Feb 14 10:26:25 hassio homebridge[4219]: Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "271f" so that we can handle it correctly and prevent this message from appearing.

**Comment by lprhodes** [comment]
You’ll need to provide more details as per the instructions

**Comment by lprhodes** [comment]
I just need to know what broadlink devices you have on your network so I can ignore this one if it's not a Broadlink RM.

Closing until further info.
