### ISSUE TITLE
pingIPAddress not working

### ISSUE THREAD

**Issue by theo-69** [lprhodes/homebridge-broadlink-rm#256]
I tried to use pingIPAddress, this is my config:

`{
                    "name": "Fernseher",
                    "type": "switch",
                    "pingIPAddress": "192.168.0.27",
            "data":{
                "on":"2600...",
                "off":"2600..."
          }`

But homebridge stopped and says:

`if (config.pingIPAddress) checkStateWithPing()
                              ^
ReferenceError: checkStateWithPing is not defined
`

**Comment by theo-69** [comment]
Still the same after update
`/usr/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:16
    if (config.pingIPAddress) self.checkStateWithPing()
                                   ^
TypeError: self.checkStateWithPing is not a function
`

**Comment by AndiEss71** [comment]
same to  me!

**Comment by theo-69** [comment]
please release merge request
