### ISSUE TITLE
How to update node?

### ISSUE THREAD

**Issue by atx-eshaheen** [lprhodes/homebridge-broadlink-rm#257]
Trying to use this plugin on a new Homebridge setup, but getting the following message when starting:

Error: Homebridge plugins that use the "homebridge-easy-platform" library require your node version to be at least v7.6.0. Current version: v6.10.2

I'm a newbie and cannot find a way to update.  Any help is greatly appreciated.

**Comment by lprhodes** [comment]
Sorry @atx-eshaheen this really isn't the best place for this - try StackOverflow and Google searches

**Comment by theo-69** [comment]
@atx-eshaheen `$ sudo apt install nodejs`

**Comment by atx-eshaheen** [comment]
I really appreciate your response - this has me stuck.  I tried that and get this:

Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/apt" (-1)

Don’t wanna trap you with helping me with this.  If you have a quick suggestion great - but don’t feel obligated.  Thanks again.

**Comment by theo-69** [comment]
You run homebridge on Raspberry?

**Comment by atx-eshaheen** [comment]
No - on a Mac.

**Comment by atx-eshaheen** [comment]
Thanks anyway - appreciate the time.  I may look into it!

**Comment by theo-69** [comment]
`sudo n latest` not working as well?

**Comment by atx-eshaheen** [comment]
Nope…
