### ISSUE TITLE
Stop window covering / blinds

### ISSUE THREAD

**Issue by subivan** [lprhodes/homebridge-broadlink-rm#259]
I am not sure if it is possible to support this feature, but, my blinds have a stop button that lets me half close the blind. I have the stop hex code, but can’t seem to find a way to send it manually. Am I doing something wrong or is this not supported?
Apologies if this has been raised before, I couldn’t find anything that related.
Cheers

**Comment by lprhodes** [comment]
@subivan you could put it on a switch accessory that has an auto off timeout
