### ISSUE TITLE
Using pingIPAddress for status only

### ISSUE THREAD

**Issue by vince105** [lprhodes/homebridge-broadlink-rm#260]
It would be nice to have `pingIPAddress`, or something similar, be used to update the `on` and `off` state of the switch/outlet only. Currently, `pingIPAddress` will send commands with this state change.

A use case for this would be for the tv, the switch would be smart enough to know if the tv was on or off based on if the device is on the network.

**Comment by RealLittleSherman** [comment]
+1

**Comment by theo-69** [comment]
+1

**Comment by theo-69** [comment]
may be it could ping for bluetooth as well?

**Comment by AndiEss71** [comment]
+1

**Comment by lprhodes** [comment]
Available in v2.6.12
