### ISSUE TITLE
pingIPAddress still not working

### ISSUE THREAD

**Issue by theo-69** [lprhodes/homebridge-broadlink-rm#265]
Hi last update did not resolve this problem. Still getting Error:
`/usr/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:16 if (config.pingIPAddress) self.checkStateWithPing() ^ TypeError: self.checkStateWithPing is not a function`

**Comment by vince105** [comment]
Replace ‘self’ with ‘this’

**Comment by theo-69** [comment]
@vince105 sorry newbie tried but cant get it installed via github :-(

**Comment by vince105** [comment]
No worries 😄 I'm pretty new to it myself.

**Comment by theo-69** [comment]
@vince105 got it installed but it seems he does not see the IP 
`[2018-2-21 11:39:24] [Broadlink RM] Fernseher setSwitchState: false
[2018-2-21 11:39:24] [Broadlink RM] Fernseher setSwitchState: already false (no data sent - B)
`is the only thing he shows configures IP is online

**Comment by theo-69** [comment]
okay its working, just my stupid TV its online, but its not. It some how can not be pinged :-(

**Comment by lprhodes** [comment]
Further fixes in v2.6.12
