### ISSUE TITLE
RM Plugin - Broadlink device not found

### ISSUE THREAD

**Issue by dkraz** [lprhodes/homebridge-broadlink-rm#266]
Hi,
I have Broadlink RM Pro+, Firmware v52, I purchase RM Plugin 2.3.2  App.
I'm trying to use the app for sending HTTP commands .
the problem is that i can't see my RM Pro+ in device list.
I'm on the same network and i can see my remote code list..

Please help ..

thanks
Daniel

**Comment by bobik180** [comment]
I have the same problem and no where have solved this problem. Some one maybe have any solution for this problem. Thanks for any idea how to solve not working RM plugin tasker for Rm3 pro plus

**Comment by lprhodes** [comment]
This sounds unrelated to this plugin - this isn't related to the RM Plugin 2.3.2 app

**Comment by bobik180** [comment]
How can be not related to this plugin. RM plugin do not discover broadlink device I think it is related and it is a problem for everyone who has RM 3 pro plus.

**Comment by lprhodes** [comment]
Based on the initial description:

" I purchase RM Plugin 2.3.2 App." - unrelated
"I'm trying to use the app for sending HTTP commands" - unrelated
" i can't see my RM Pro+ in device list." - there is no "device list" so it's also unrelated

**Comment by bobik180** [comment]
Based on my problem is related because I use RM plugin with tasker app and there when I want send any commend to RM3 pro plus from Android system I can't. RM plugin don't discover model RM 3 pro plus and U can't send any commend. I ask some one have any idea how I can something change to RM plugin discover RM 3 pro plus. And that is my question for some one here. For any solution I thanks a lot.

**Comment by lprhodes** [comment]
Sorry @bobik180, I must be missing something.

I don't see how being unable to send a command from Android relates to a problem with this plugin.

The "RM Plugin 2.3.2 App" is also nothing to do with this code.

**Comment by lprhodes** [comment]
If you have Homebridge installed, have followed the instructions to setup an appropriate config.json s per the README and have the latest version of this code (homebridge-broadlink-rm) installed then please provide your config.json and any logs.

**Comment by bobik180** [comment]
I saying about tasker and RM plugin for tasker no about RM plugin app ;) a thinking that some one here have the same problem like I and can't send any code to broadlink RM 3 pro plus :)

**Comment by lprhodes** [comment]
Removing this issue - please request support from the RM Plugin creators
