### ISSUE TITLE
Add colour to light accessory to control RGB Lightstrips

### ISSUE THREAD

**Issue by Green-Kite** [lprhodes/homebridge-broadlink-rm#268]
Is it possible to add a colour option to the switch type light?

**Comment by Hohnjo** [comment]
Would love to see this !

**Comment by lprhodes** [comment]
Similar to #251 

There's no interface for it in the Home app as far as I'm aware but Siri has support so I'll look into that

**Comment by Nastras** [comment]
Such a switch I mean the color change. With this one could deposit a color for each number.
Each number has a hex code.

Would not that be possible?

https://github.com/grover/homebridge-automation-switches/blob/master/docs/Slider.md

**Comment by lprhodes** [comment]
@Nastras it wouldn't, that slider is in an dedicated app - not in the Home app

**Comment by Nastras** [comment]
You're right. It only appears in HomeKit apps like Elgato Eve and similar.
Unfortunately, the Apple Home App does not support their own HomeKit options.

But it would be possible .-)

**Comment by Hohnjo** [comment]
I was thinking about this wheel that is already integrated in homekit : 
![img_9218](https://user-images.githubusercontent.com/36167959/36664256-5e216ed8-1ae4-11e8-8d68-34f404f29be2.PNG)

**Comment by lprhodes** [comment]
I've never seen that wheel - thanks @Hohnjo I'll check it out

I guess the difficulty with the wheel is that IR codes would need to be learned for each color variation.

**Comment by santiagos5** [comment]
maybe can be help this..

![img_6918](https://user-images.githubusercontent.com/35889101/36726069-ba60b652-1bb8-11e8-866e-98b8ffe8e55a.PNG)

**Comment by lprhodes** [comment]
Check out the latest release
