### ISSUE TITLE
"Learn" and "Scan Frequency" accessories not appear to the home app

### ISSUE THREAD

**Issue by j796160836** [lprhodes/homebridge-broadlink-rm#269]
Hi there,
I'm newbie to use this `homebridge-broadlink-rm` plugins. The document says,
> "Learn" and "Scan Frequency" accessories are automatically added to the Home app (so long as you've not added either manually in the config).

But actually, It does found the device but no accessories added.
I had success setup my Broadlink RM-pro+ via [Intelligent Home Center](https://itunes.apple.com/us/app/intelligent-home-center/id1084990073?mt=8) (ihc) and I had success let RM-pro+ connect to my home Wi-Fi.
Here is the logs of homebridge,

```
[2/22/2018, 3:34:39 PM] Loaded plugin: homebridge-broadlink-rm
[2/22/2018, 3:34:39 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2/22/2018, 3:34:39 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/22/2018, 3:34:39 PM] ---
[2/22/2018, 3:34:39 PM] Loading 1 platforms...
[2/22/2018, 3:34:39 PM] [Broadlink RM] Initializing BroadlinkRM platform...
[2/22/2018, 3:34:39 PM] [Broadlink RM] No accessories have been added to the "Broadlink RM" config.
[2/22/2018, 3:34:39 PM] Loading 0 accessories...
[2/22/2018, 3:34:39 PM] Homebridge is running on port 51826.
Discovered Broadlink RM device at 192.168.1.3 (xx:xx:xx:xx:xx:xx)
```

So it stucked, within `Discovered Broadlink RM device` message.

Here is config.json
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "xx:xx:xx:xx:xx:xx",
    "port": 51826,
    "pin": "111-11-111"
  },
  "description": "This is an example configuration file.",
  "accessories": [],
  "platforms": [
    {
      "platform": "BroadlinkRM",
      "name": "Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false
    }
  ]
}
```

How can I do? Any help is appreciation.

**Comment by j796160836** [comment]
After seeking issues list, I found where the problem is.
**"Learn" and "Scan Frequency" accessories will not automatic added without ANY device.** 
That is quite different with document says " (so long as you've not added either manually in the config)".

Just add mock switch on it and solved the problem.
I think next time need to edit code to fix this issue.

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "xx:xx:xx:xx:xx:xx",
    "port": 51826,
    "pin": "111-11-111"
  },
  "description": "This is an example configuration file.",
  "accessories": [],
  "platforms": [
    {
      "platform": "BroadlinkRM",
      "name": "Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false,
      "accessories": [
        {
          "name": "Mock switch",
          "type": "switch",
          "data": {
            "on": "",
            "off": ""
          }
        }
      ]
    }
  ]
}
```

I think next time need to edit code to fix this issue.

**Comment by lprhodes** [comment]
This was fixed last week. Please update to the latest version.
