### ISSUE TITLE
Air Conditioner config

### ISSUE THREAD

**Issue by astrojetson8** [lprhodes/homebridge-broadlink-rm#27]
I'm not really sure how to get Air Conditioner work properly. Maybe, I'm missing something or didn't setup correctly?

- To get the off hex code, I turned on my aircon and turned it off and go the hex code for off
- To get 16 degree (min on my aircon), I set my aircon to 17 degree, and capture hex code for 16 degree
- To get 30 degree (max on my aircon and it only cools), I set my aircon to 29 degree, and capture hex code for 16 degree

The aircon I'm using is Piu' 14
http://www.olimpiasplendid.com.au/portable-air.html

I have few questions regarding Home app
- what's the temperature inside blue circle? I get 12c. Is this static icon?
- i can toggle between 0 and 30. I tried to add min temperature to be 16 just above data ie "minTemperature": 16, and  "minTemperature": "16", but in both cases it crashed Home app.

At launch:
```
[3/31/2017, 1:17:19 PM] [Broadlink RM] getTargetHeatingCoolingState (off)
[3/31/2017, 1:17:19 PM] [Broadlink RM] getTargetTemperature (0)
[3/31/2017, 1:17:19 PM] [Broadlink RM] getTemperatureDisplayUnits (0)
[3/31/2017, 1:17:19 PM] [Broadlink RM] getCurrentHeatingCoolingState
[3/31/2017, 1:17:19 PM] [Broadlink RM] getCurrentTemperature (12.1)
```
Launching air conditioner:
```
[3/31/2017, 1:20:34 PM] [Broadlink RM] setTargetHeatingCoolingState (cool)
[3/31/2017, 1:20:34 PM] [Broadlink RM] Potentially sendTemperature (16)
[3/31/2017, 1:20:34 PM] [Broadlink RM] sendTemperature (16, cool)
[3/31/2017, 1:20:34 PM] [Broadlink RM] setTargetTemperature (16)
[3/31/2017, 1:20:34 PM] [Broadlink RM] Potentially sendTemperature (16)
[3/31/2017, 1:20:34 PM] [Broadlink RM] Payload message sent to Broadlink RM device (192.168.1.4; 37:27:04:01:a8:c0)
```
Asking Siri to set temperature to 20 degree but its still at 16.
```
[3/31/2017, 1:21:35 PM] [Broadlink RM] setTargetTemperature (20)
[3/31/2017, 1:21:35 PM] [Broadlink RM] Potentially sendTemperature (20)
[3/31/2017, 1:21:35 PM] [Broadlink RM] Update to default temperature (16)
```
From Home app, I tried to toggle from 16 to 20 but it still didn't work.
```
[3/31/2017, 1:23:52 PM] [Broadlink RM] getTargetHeatingCoolingState (cool)
[3/31/2017, 1:23:52 PM] [Broadlink RM] getTargetTemperature (16)
[3/31/2017, 1:23:52 PM] [Broadlink RM] getTemperatureDisplayUnits (0)
[3/31/2017, 1:23:52 PM] [Broadlink RM] getCurrentHeatingCoolingState
[3/31/2017, 1:23:52 PM] [Broadlink RM] getCurrentTemperature (12.2)
[3/31/2017, 1:27:05 PM] [Broadlink RM] setTargetTemperature (18)
[3/31/2017, 1:27:05 PM] [Broadlink RM] Potentially sendTemperature (18)
[3/31/2017, 1:27:05 PM] [Broadlink RM] Update to default temperature (16)
[3/31/2017, 1:27:06 PM] [Broadlink RM] setTargetTemperature (19)
[3/31/2017, 1:27:06 PM] [Broadlink RM] Potentially sendTemperature (19)
[3/31/2017, 1:27:06 PM] [Broadlink RM] Update to default temperature (16)
[3/31/2017, 1:27:07 PM] [Broadlink RM] setTargetTemperature (20)
[3/31/2017, 1:27:07 PM] [Broadlink RM] Potentially sendTemperature (20)
[3/31/2017, 1:27:07 PM] [Broadlink RM] Update to default temperature (16)
```

My config:
 ```
           {
              "name": "Air Conditioner",
              "type": "air-conditioner",
              "data": {
                "off": "260016016f370e0d0e0e0e0d0e0e0e0d0e0e0e290e0d0f0d0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e290e0d0e290f0d0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e290e290e290e0d0f0d0e0e0e0d0e290e0e0e290e0d0e0e0e290e0d0f0d0e0d0f290e0d0e0e0e290e0d0e290e290e0e0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e290e0d0e0e0e0d0e0e0e0d0f0d0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0d0f0d0e0e0e290e0d0e290e290e0e0e0d0e0e0e0d0f0d0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e290e0d0e290f290e290e0d0e0e0e000d050000",
                "temperature30": {
                    "pseudo-mode": "heat",
                    "data": "260016016f360f0d0e0e0f0c0e0e0e0d0e0e0e29100b0e0e100b0e0e0e0d0f0d0e0e0e0d0e0e100b100c0e290e0d0e290e0e0e0d100c100b100c0e0e0e0d0e0e0e0d0e0e0e2910270e290e0d0e0e0e0d0f0d0e290e0e0e0d100c0e0d0e290e0e0e0d0e0e0e290e0e0e0d0e290e0e0e290e29100b0e0e0e0d0e0e0e0d0f0d0e0e0e0d10270e0e0e0d0e0e0e0d0e0e0e0d0e29100c0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d100c0e0d0e0e0e0d10270f0d0e290e290e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e100b0e0e0e0d0e0e0e0d100c0e0d0f0d0e0e0e0d0e290e29100c10270e290e290e0d0f0d0e000d050000"
                    },
                "temperature16": {
                    "pseudo-mode": "cool",
                    "data": "260016016e370e0e0e0d0e0e0e0d0e0e0e0d0f280f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f280f0d0e290e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f280f2910270e0d0e0e0e0d0e0e0e290e0d0f0d0e0e0e0d0e290e0e0e0d0e0e0e290e0d0e0e0e0d0f280f290e0d0f0d0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f280f0d0e0e0e0d0e0e100b0e0e0e290e0d100c100b0e0e0e0e0e0d0e0e100b0e0e0e0d0e0e0e0d0e0e0e290e0d0e290f280f0d0e0e0e0d0e0e0e0d100c0e0d0e0e0e0d0e0e0e0d0f0d0e0d0f0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d100b0f0d0e0e100b0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0e0e0e0d0f0d0e0e0e290e0d0e290e290e290e290f0d0e0d0f000d050000"
                    }
                }
            },
```

**Comment by jat80** [comment]
I also get a random temp of 14 degrees.  Also if I manually set it to 18degrees cooling go out of the home app and back into it, it then says 18 degrees heating???

I didn't have these issues with the previous version and using the same IR hex codes.  Stumped.  @lprhodes

**Comment by lprhodes** [comment]
The temperature comes from the Broadlnk device unless you override the psuedoDeviceTemperature which will set it to whatever temperature you put as the value.

If you add a hex for "temperature16" and "temperature30" and you ask for a temperature that you haven't set a hex code for (e.g. temperature18) then if the requested temperature is below 22 (or whatever value you set for "heatTemperature" to in the comfy) then the temperature16 hex will be used. If it's above or equal to 22 (or again - whatever you set "heatTemperature " to in the confit) then it will use the "temperature30" hex

**Comment by lprhodes** [comment]
@ja870 try relearning the codes?

**Comment by lprhodes** [comment]
@jat80 also try the codes on a switch to make sure they work

**Comment by astrojetson8** [comment]
@lprhodes 
thanks for getting back to me!

Sorry, i wasn't sure about few things. 

- do I need to capture temperature IR codes for varying temperature ie 16, 17, 18...
- if I define minTemperature (16) and maxTemperature (22) values in config, the toggle I get on Home app will be the range I specified here 16 to 22?
- psuedoDeviceTemperature is the data inside blue circle from RM Mini 3? If so, in future would it possible to read temp from another homekit temperature sensor, and display that? 

```
          {
             "name": "Air Conditioner",
             "type": "air-conditioner",
             psuedoDeviceTemperature: 20,
            minTemperature: 16,
            maxTemperature: 22,
             "data": {
               "off": "260016016",
               "temperature30": {
                   "pseudo-mode": "heat",
                   "data": "260016016f36...},
               "temperature16": {
                   "pseudo-mode": "cool",
                   "data": "260016016e37..."
                   },
               "temperature17": {
                   "pseudo-mode": "cool",
                   "data": "260016016e37..."
                   },
               "temperature18": {
                   "pseudo-mode": "cool",
                   "data": "260016016e37..."
                   }
               }
           },
```

**Comment by jat80** [comment]
@lprhodes using the hex codes for a simple on off switch works fine for the air con. (cool 18 degrees)  I think i'm just going to use it as that as no matter what I do the actual air conditioner type doesn't work for me.

**Comment by astrojetson8** [comment]
@lprhodes 

- do I need to capture temperature IR codes for varying temperature ie 16, 17, 18...

> I do and solved

- if I define minTemperature (16) and maxTemperature (22) values in config, the toggle I get on Home app will be the range I specified here 16 to 22?

> If I add minTemperature and/or maxTemperature, I get No Response in Home app. However, Siri can set the desired temp.

- psuedoDeviceTemperature is the data inside blue circle from RM Mini 3? If so, in future would it possible to read temp from another homekit temperature sensor, and display that?

> psuedoDeviceTemperature needs to be lower ie 15 or below. it's strange how the temp fluctates from 12-13

- also, any plans to include fan speed in future?


```
{
              "name": "Air Conditioner",
              "type": "air-conditioner",
              "replaceAutoMode": "cool",              
              "defaultCoolTemperature": 18,              
              "minTemperature": 16,             
              "maxTemperature": 22,              
              "data": {
                "off": "260016016",
                "temperature16": {
                    "pseudo-mode": "cool",
                    "data": "260016016"
                    },
                "temperature17": {
                    "pseudo-mode": "cool",
                    "data": "260016016"
                    },
                "temperature18": {
                    "pseudo-mode": "cool",
                    "data": "260016016"
                    },
                "temperature19": {
                    "pseudo-mode": "cool",
                    "data": "260016016"
                    },
                "temperature20": {
                    "pseudo-mode": "cool",
                    "data": "260016016"
                    },
                "temperature21": {
                    "pseudo-mode": "cool",
                    "data": "260016016"
                    },
                "temperature22": {
                    "pseudo-mode": "cool",
                    "data": "260016016"
                    }
                }
            },
```

**Comment by lprhodes** [comment]
> do I need to capture temperature IR codes for varying temperature ie 16, 17, 18...

You definitely don't _need_ to - it's optional. You could otherwise just set 16 and 22 if you wren't bothered about it setting the exact temperature.

> psuedoDeviceTemperature is the data inside blue circle from RM Mini 3? If so, in future would it possible to read temp from another homekit temperature sensor, and display that?
There's no way to communicate with other HomeKit devices within homebridge at this time sorry.

> also, any plans to include fan speed in future?
If Apple adds support to the thermostat service then sure but you would need to add a hex code for each fan speed/temperature combination and it seems unlikely for Apple to add this as thermostats don't generally have the option to set a fan speed. There is another fan option that Apple allows you to set speeds for but you can't set specific temperatures on that one, you can only ask it to increase or decrease temperature. We'll have to see what iOS 11 holds.

I'll have a play with your config later today but on first look:

- You don't need a defaultCoolTemperature if you have set a hex for every possible temperature.
- Set psuedoDeviceTemperature to 0 if your temperature isn't reporting back correctly
- Set heatTemperature to 23 otherwise selecting 22 may have a conflict

**Comment by astrojetson8** [comment]
Your plugin is freakin amazing!!! 

> You definitely don't need to - it's optional. You could otherwise just set 16 and 22 if you wren't bothered about it setting the exact temperature.

Probably not but I wanted to understand how it all works. My initial assumption was wrong because I thought you need to only capture lowest and highest temp, and rest is not required but you can still set temp in between. 

> There's no way to communicate with other HomeKit devices within homebridge at this time sorry.

Thanks for clarification. Is it limitation of homebridge or Homekit API doesn't allow this? 
And regarding that ghost temp, I'm wondering if it's temperature inside the aircon? I doubt it though. The thing is, it's not static, and it varies with a decimal value.
btw I've a Broadlink rm mini 3 

>-  You don't need a defaultCoolTemperature if you have set a hex for every possible temperature.
- Set psuedoDeviceTemperature to 0 if your temperature isn't reporting back correctly
- Set heatTemperature to 23 otherwise selecting 22 may have a conflict

- I was just playing around with settings but I like the idea you've implemented default temp.
- Yes, that I got it work. fyi, I did notice psuedoDeviceTemperature needs to below min temp ie 15 if min cooling temp is 16. 
- Will test later tonight. I had 30c initially but i removed it. 

Let me know your feedback on min and max temp cause I couldn't get it to work!

Looking fwd to iOS 11!

**Comment by lprhodes** [comment]
> Thanks for clarification. Is it limitation of homebridge or Homekit API doesn't allow this?

Homebridge doesn't allow you to communicate with other homebridge accessories and homebridge also has no way of discovering non-homebridge accessories.

> And regarding that ghost temp, I'm wondering if it's temperature inside the aircon? I doubt it though. The thing is, it's not static, and it varies with a decimal value.
btw I've a Broadlink rm mini 3

Definitely not the temperature inside the air con, it's whatever is being returned from the broadlink device. It's odd but you're not alone - perhaps worth asking broadlink themselves.

**Comment by lprhodes** [comment]
Just pushed a fix for pseudoDeviceTemperature not actually being returned.

Also corrected mis-spelling of psuedoDeviceTemperature to pseudoDeviceTemperature

**Comment by astrojetson8** [comment]
i tested following on your latest build:

pseudoDeviceTemperature value can now only be 0. I tried 1 and above but it won't work.
 "pseudoDeviceTemperature": 0, 

In order to test min and max temp. I removed all plugins, and reset Home app.
- maxTemperature by itself works.
- minTemperature needs to be 0, and any other value it shows No Response in Home app.

**Comment by astrojetson8** [comment]
also, i noticed it says Heating to 18c when I use Home app instead of Siri. I'll do more on QA so I can replicate exactly what causes this as I noticed this on 2 occasions.

**Comment by lprhodes** [comment]
As of 1.1.3 pseudoDeviceTemperature no longer cares what's happening elsewhere, if you set it - that's what will show.

**Comment by lprhodes** [comment]
Actually I spoke too soon. I've updated 1.1.5 with better error messages so hopefully you can figure this out from them.

The pseudoDeviceTemperature needs to be between the minTemperature (default 16) and maxTemperature (default 30) otherwise "No Response" will be returned.

**Comment by lprhodes** [comment]
I'd suggest having the minTemperature be 1 below what you want otherwise it won't turn on when you select 16 after loading home bridge as it's already selected.

**Comment by astrojetson8** [comment]
with 1.1.5, i'm getting following error:

`====================
[4/6/2017, 9:39:30 AM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[4/6/2017, 9:39:30 AM] /usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:34
  async setCharacteristicValue (props, on, callback) {
        ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:1:92)
[4/6/2017, 9:39:30 AM] ====================`

i've reverted back to 1.0.6

**Comment by lprhodes** [comment]
Node needs to be at least 7.6

**Comment by lprhodes** [comment]
Upgrade node to at least 7.6

**Comment by astrojetson8** [comment]
I did but this now throwing me another error.  I removed all plugins, and reinstalled homebridge and your latest plugin 1.1.5 on 7.6 node and 4.4.4 npm.

`/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)`

**Comment by lprhodes** [comment]
What platform? Try the latest node? 7.8.X

**Comment by lprhodes** [comment]
Try:

```
npm r homebridge -g
npm i homebridge -g
```

**Comment by astrojetson8** [comment]
same on 7.8, and i'm on mac

**Comment by astrojetson8** [comment]
rebuild did the trick! thanks 👍 
will test and report back bit later.

**Comment by astrojetson8** [comment]
all good now, and thanks for all your help!

i've left my config below incase someone else runs in to a similar issue or have a similar question.

```
            "platform":"BroadlinkRM",
            "name":"Broadlink RM",
            "accessories":[
            {
              "name": "Air Conditioner",
              "type": "air-conditioner",
              "defaultCoolTemperature": "cool", 
              "replaceAutoMode ": 18, 
              "pseudoDeviceTemperature": 21, 
              "minTemperature": 15, 
              "maxTemperature": 24,               
              "data": {
                "off": "2600160...",
                "temperature16": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    },
                "temperature17": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    },
                "temperature18": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    },
                "temperature19": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    },
                "temperature20": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    },
                "temperature21": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    },
                "temperature22": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    },
                "temperature23": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    },
                "temperature24": {
                    "pseudo-mode": "cool",
                    "data": "2600160..."
                    }
                }
            }
```

**Comment by lprhodes** [comment]
Awesome.

Looks like "replaceAutoMode" and "defaultCoolTemperature" have the wrong values though

**Comment by astrojetson8** [comment]
oh yeah! oops

i fixed it above! i was changing few things after pasting my config, and mixed up the values .
