### ISSUE TITLE
discovered unknown device

### ISSUE THREAD

**Issue by consoleman** [lprhodes/homebridge-broadlink-rm#272]
I get this error:
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4ead" so that we can handle it correctly and prevent this message from appearing.

I have a Broadlink WiFi power socket in my network

**Comment by lprhodes** [comment]
Thanks for reporting - can you link me to the product you purchased please? I want to make sure I make note of all of the right details.

**Comment by consoleman** [comment]
It’s an RM Pro bought about 2 years ago from Banggood

**Comment by consoleman** [comment]
It has Firmware V30 and underneath is printed „e-remote RM Pro“

**Comment by lprhodes** [comment]
4ead appears to be for the Hysen Heating Controller.

I'll have the plugin ignore it in the next update

**Comment by consoleman** [comment]
Yes, I have 2 Floor Heating Controller in my WiFi. Named Fluoreon.
So I have to wait for the update to use the plugin for my RM Pro?

**Comment by lprhodes** [comment]
No - the error is just to make sure you report it here

**Comment by consoleman** [comment]
I see. But the plugin does not work for me.
I don’t get any devices in the home app

Von meinem iPhone gesendet

**Comment by lprhodes** [comment]
v2.6.11 includes a fix for the error log you're seeing.

As for it not working, please create a separate issue.
