### ISSUE TITLE
Multi - & Repeat Switches do not turn off automatically since update

### ISSUE THREAD

**Issue by denzel1994** [lprhodes/homebridge-broadlink-rm#273]
Everything worked fine until last nights update. Now my multi-, repeat- and multi-repeat-switches do not turn off automatically anymore after sending the code.

I did not change anything inside the config prior to the update. I also tried "disableautomaticoff" set to false on a few switches. No change.

**Comment by gerritfries** [comment]
Same for me.

**Comment by lprhodes** [comment]
`"disableAutomaticOff": false` will do the trick

**Comment by denzel1994** [comment]
Like I already said in my first post. It does not do the trick.

**Comment by lprhodes** [comment]
Your first comment had the key written incorrectly. Can you send an accessory config that isn't working correctly with that key in place.

**Comment by denzel1994** [comment]
Here you go.
The "ATV Menü" switch used to turn off automatically prior to the update. 
Adding `"disableAutomaticOff": false ` does not fix the issue. The switch just stays on.
>   {
            "platform": "BroadlinkRM",
            "name": "Broadlink",
            "hideScanFrequencyButton": true,
            "hideLearnButton": false,
            "accessories": [
                {
                    "name": "IR Lernen",
                    "type": "learn-code",
                    "disableAutomaticOff": true,
                    "scanFrequency": false
                },
                {
                    "name": "ATV Menü",
                    "type": "switch-repeat",
                    "sendCount": 1,
                    **"disableAutomaticOff": false,**
                    "data": "260050000001269513121237133614361312123714361337123613371237131212131313121213371238123713111412121412131113131313361312121313121214111312131213120005950001264a13000d050000000000000000"
                },

**Comment by lprhodes** [comment]
<img width="742" alt="screen shot 2018-02-28 at 9 10 09 pm" src="https://user-images.githubusercontent.com/162989/36782072-dd3b84b8-1ccb-11e8-9de2-901fdcdaff8a.png">
It's working as expected. What version are you running? There's been lots of updated today.

**Comment by denzel1994** [comment]
I'm running version 2.7.3.
Okay now I see the "60 seconds" message in my log as well.
However this does not explain why I now have to add `"disableAutomaticOff": false` to all of my switches when they were turning off automatically and instantly after sending the code in versions prior to 2.7.3.

It even states this functionality in the readme.

> switch-multi

Turn the switch on and the switch will send each hex code in the provided array. **It then turns itself off automatically**. You can also set the interval between each send.

> switch-repeat

Turn the switch on and the switch will repeatedly send the hex code until it reaches the defined send count. **It then turns itself off automatically**. You can also set the interval between each send.

**Comment by lprhodes** [comment]
I'll update the docs.

The change was introduced in v2.6.13 https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.6.13

The reason was to ensure make the option consistent across all accessories.
