### ISSUE TITLE
List of Discovered Unknown Devices

### ISSUE THREAD

**Issue by guagsak** [lprhodes/homebridge-broadlink-rm#274]
@lprhodes  First of all, thank you for your awesome plugin. I've been using this plugin for a year now.

Below is the error status. I have many smart plugs, A1, S1C, Curtains DT360E. The plugin found my two rm pro with now problem. So, you can clear these devices that are not RM device.

[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4ef7" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "9471" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "9479" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4f1b" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4f1b" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "9471" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4f1b" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4ef7" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "9479" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4f1b" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4f1b" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "9479" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4ef7" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4f1b" so that wecan handle it correctly and prevent this message from appearing.
[Important!] We've discovered an unknown Broadlink device.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "9471" so that wecan handle it correctly and prevent this message from appearing.

**Comment by lprhodes** [comment]
Thanks @guagsak 

Any chance you can match up those devices codes to device names? I'll be adding support for direct control over broadlink devices in the near future so it'd really help.

**Comment by lprhodes** [comment]
4EF7 is an OEM MP1
9479 is an SP3S

I don't know what 9471 and 4f1b are

**Comment by lprhodes** [comment]
Closing - I'll reopen if further information is provided.
