### ISSUE TITLE
Send tuple HEX codes with timing for Brightness adjust

### ISSUE THREAD

**Issue by iShift** [lprhodes/homebridge-broadlink-rm#275]
Hi, thanks for plugin, i play with it and with Belarussian IOT system - Noolight, they have dimmers for light, with strange algorithm:
They Have 4 HEX Codes
1. ON
2. OFF
3. START DIMMING
4. STOP DIMMING

So, if i want dimming - i should send:
1. ON Code
2. START DIMMING Code
3. Wait few second (when i wait - dimmer works until i send stop HEX)
4. Send STOP HEX

Can you add support for that type of dimmer, i think it could be new type in light, i can measure time (from MAX bright to low one and convert time to brightness %)

**Comment by iShift** [comment]
now i have 3 device for one light switch:
on/off (type - switch)
low brightness  (type - switch-multi)
high brightness (type - switch-multi)

**Comment by lprhodes** [comment]
Check out the 3.1.0 update and the updated documentation here:
https://github.com/lprhodes/homebridge-broadlink-rm#hex-object-structure

You should be able to achieve what you need by using this new functionality.

**Comment by iShift** [comment]
hmm, sound good, can i use new hex-obj structure in light device type? or i should create 2 device:
1. On/off light
2. Max/low bright

**Comment by lprhodes** [comment]
You can use it in all accessory types
