### ISSUE TITLE
Some suggestions about air condition and switch controls

### ISSUE THREAD

**Issue by phenix13** [lprhodes/homebridge-broadlink-rm#278]
Thank you for the great plugin  , I have some sugestions about air condition and switch controls. I not only use broadlink but also use AC partner [https://github.com/LASER-Yi/homebridge-mi-acpartner](url) to control air condition , when the air condition is in the off stage , I change the temperature , then the air condition will auto on , but in another plugin ,the air condition is not start , it have a parameter which you write in the config.json that whether you want open the air condition when change the temperature or not , Can you add the parameter ?  
PingIPAdress is a great function, that i can use it to know whether the device is online or not , wish your add it to all kinds of switch, and you also can creat a sensor to display it

**Comment by lprhodes** [comment]
@phenix13 do you mean like this `turnOnWhenOff` option?

**Comment by lprhodes** [comment]
Closing until further information is provided.

**Comment by phenix13** [comment]
I mean I need a parameter like "autoStart" when AC turn off, change temperature will set to this mode. If you set this to "off", change temperature will not turn on AC. I don't want to turn on AC when I only change 
temperature , I want to turn on AC only by change mode to heat or cool
