### ISSUE TITLE
upDown support? 

### ISSUE THREAD

**Issue by webpablo** [lprhodes/homebridge-broadlink-rm#28]
First off, this is great. I have had a sun shade running on 433Mhz that I REALLY wanted to get working with Homekit. This is doing the trick (as a switch) I was digging through the code and noticed up/down accessories are commented out at the moment. I would really like to be able to use the appropriate "open the blind" and "close the bling" language with Siri, I am hoping an up/down accessory would allow that.

**Comment by lprhodes** [comment]
The idea was that you would have a 3-way switch. Toggling up would increase, toggling down would decrease.

Unfortunately neither Siri nor the Home app support anything like that so I've commented it out.

I'll be working on a new home automation app soon with some custom interfaces (though Siri still wouldn't support these).

Let's hope iOS 11 adds a lot more options to work with.
