### ISSUE TITLE
Add multi functionality to window covering

### ISSUE THREAD

**Issue by ZacGrose** [lprhodes/homebridge-broadlink-rm#280]
I’m hoping you’ll indulge my rather strange edge-case here. My shutters require two additional RF commands after closing in order to be able to open them again. Right now I can use the switch-multi accessory with a single On command and an array of three Off hex commands, but it would be tremendous to be able to have HomeKit see these as blinds rather than a switch.

Is it possible to get this functionality added? Or some advice on the way I could just modify my version of windowCovering.js to make the 'close' command work as a series of hex commands rather than just one?

**Comment by lprhodes** [comment]
Hey @ZacGrose, it looks like there's a need for the switch-repeat, switch-multi and switch-multi-repeat functionality to come to lights, fans and now window coverings. I'll see what I can do :)

**Comment by lprhodes** [comment]
Added in 3.0.4

**Comment by lprhodes** [comment]
...check out the "Blind Multi" accessory in config-sample.json

**Comment by ZacGrose** [comment]
Thanks @lprhodes — very appreciative of the turnaround. I'm having some issues though. It's not sending the hex signals for down. Here's the snippet of code from my config json:

`{
	"name":"SuperShutter",
	"type":"window-covering",
	"totalDurationOpen": 1,
	"totalDurationClose": 1,
	"data":{
		"open":"b20184030907…",
		"stop":"b20184030907…",
		"close":[
			{
				"data": "b20184030a0709070a07090808080907090709070a0709070908090808080a06090…"
			},
			{
				"data": "b20184030907090809070a0609080907090808080907090709080a0609080907090…"
			},
			{
				"data": "b20184030908090709070908090709070b060907090809070a06090808080907090…"
			}
		]
	}
}`

But it's not sending any hex for "close":

`[2018-3-14 15:23:24] [Broadlink RM] SuperShutter setTargetPosition: 1s (1 / 100 * 100) until auto-stop
[2018-3-14 15:23:24] [Broadlink RM] SuperShutter setCurrentPosition: 1
[2018-3-14 15:23:24] [Broadlink RM] SuperShutter setCurrentPosition: 2
[2018-3-14 15:23:24] [Broadlink RM] SuperShutter setCurrentPosition: 3`

Compared to the switch-multi, which would have three different lines of sendHex in a row for each of the three commands.

**Comment by lprhodes** [comment]
I'm almost done with making it so that any hex code in any accessory can use the a `switch-multi-repeat` format, I'll let you know once it's complete and tested.

**Comment by lprhodes** [comment]
3.1.0 is available now - check out the updated docs if you're having issues: https://github.com/lprhodes/homebridge-broadlink-rm#hex-object-structure

**Comment by ZacGrose** [comment]
Confirmed as working now! Thanks @lprhodes — this change is a great improvement to the general flexibility of this plugin.
