### ISSUE TITLE
Can I add a room to the JSON?

### ISSUE THREAD

**Issue by bobjoylove** [lprhodes/homebridge-broadlink-rm#283]
Hey, 

First thanks for the awesome awesome plugin. 

Is it possible to set the room in the JSON?  I added 7 blinds and I'd like to optionally use
"name":"Blind"
"room":"Living_Room"
So that I can keep track of the data word with the blind in use.

**Comment by lprhodes** [comment]
Hey @bobjoylove, so this would just be for the purpose of showing in the logs?

**Comment by bobjoylove** [comment]
Hi @lprhodes ,

It's more to help the identifying of blinds as right now all 7 are added to Default Room and they are all called Blinds lol

**Comment by lprhodes** [comment]
I can't specify which room they get added to - you can move them around in the Home app.

**Comment by ZacGrose** [comment]
@bobjoylove You’re best off naming the blinds in the Homebridge config to be more prescriptive (Lounge Room Blind 1) and then renaming it in the Home app. That way whenever you add a blind you’ll know which room to put it in before you rename it.

**Comment by lprhodes** [comment]
@ZacGrose agreed

I'm pretty sure homebridge starts getting upset when you name them all the same in configs anyway.

**Comment by bobjoylove** [comment]
Thanks gents, I guessed that might be the answer a few minutes after posting, since you would likely have added this already.  Thanks!
