### ISSUE TITLE
A/C Fan Speed

### ISSUE THREAD

**Issue by felkahlout** [lprhodes/homebridge-broadlink-rm#285]
Hello,
As A/C panels accepts only one signal for complete a/c status ( temp, fan, mode, swing etc ) i became  little bit confused about A/C fan speed. Does the code allow controlling it?

**Comment by lprhodes** [comment]
It doesn't. You'd end up needing a hex code for every single combination of fan speed and temperature then more codes again if you wanted to add swing mode into it.

**Comment by felkahlout** [comment]
Thanks lprhodes, 
Do you have any plans to allow such type of control? for example:
"temperature16":{
              "pseudo-mode":"cool",
              {"fan-speed": 33, 
               "data":"2600500000012..."},
              {"fan-speed": 66, 
               "data":"2600500000013..."},
              {"fan-speed": 100, 
              "data":"2600500000014..."}
                            }
and same for Temp 17, 18, etc..

**Comment by lprhodes** [comment]
Not at the moment sorry.
