### ISSUE TITLE
Error after updating to v3.1.0

### ISSUE THREAD

**Issue by Green-Kite** [lprhodes/homebridge-broadlink-rm#288]
Hello
with v2.7.4 everything works fine but after updating to v3.1.0 my homebridge won't start, this is my log:

> Mär 14 08:12:43 raspberrypi homebridge[2592]: /usr/local/lib/node_modules/homebridge/lib/api.js:122
Mär 14 08:12:43 raspberrypi homebridge[2592]: throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Mär 14 08:12:43 raspberrypi homebridge[2592]: ^
Mär 14 08:12:43 raspberrypi homebridge[2592]: Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
Mär 14 08:12:43 raspberrypi homebridge[2592]: at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at Module._compile (module.js:643:30)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at Object.Module._extensions..js (module.js:654:10)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at Module.load (module.js:556:32)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at tryModuleLoad (module.js:499:12)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at Function.Module._load (module.js:491:3)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at Function.Module.runMain (module.js:684:10)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at startup (bootstrap_node.js:187:16)
Mär 14 08:12:43 raspberrypi homebridge[2592]: at bootstrap_node.js:608:3
Mär 14 08:12:43 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Mär 14 08:12:43 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by lprhodes** [comment]
Can you send your config please.

**Comment by Green-Kite** [comment]
Is there a need to change a thing when upgrading from v2.7.4 to v3.1.0? As said, v2.7.4 works without any problem.
This is my config:
> {
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:10",
		"port": 51810,
		"pin": "031-45-154"
	},
	"accessories": [],
	"platforms": [{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideScanFrequencyButton": false,
		"hideLearnButton": false,
		"accessories": [{
				"name": "Schrank",
				"type": "outlet",
				"disableAutomaticOff": true,
				"data": {
					"on": "aa00ce0010290f2a2a0e0f2b2a0e0f2a2a0e0f2a2b0e0f292b0e0f2910290f2a2a0e0f292b0e0f2a2b0e10292b0e0f292b0e0f0001a70f29102a0f292b0e0f292b0e0f292b0e0f292b0e0f2a2b0e10290f2a0f292b0e0f292a0f0f292b0e0f292b0e0f292c0e0f0001a610290f2a0f2a2b0e0f292b0e0f292b0e0f292b0e0f292b0f0f290f2b0f292b0e0f292b0d10292b0e0f292b0d10292b0e0f0001a80f2910290f292b0e0f292b0e0f292c0e0f292b0e0f292b0e0f290f2a10292b0e0f292b0e0f292c0f0f2a2a0f2b0e2b0e0f0005dc00000000000000000000",
					"off": "aa00020110290f2a2a0e0f2a2a0f0f2a2a0e0f292b0e0f292c0e0f2a0e2a0f292b0e0f292a0f0f292b0e0f292b0e10290f2a0f0001a70f290f2a10292a0f0f292a0f0f292a0f0f292a0f0f292a0f112a0f2a0f292a0e102a2a120f292a0e0f2b2a0e11290f2a0f0001a80e2a0f290f2a2a0e0f2a2a0e0f2a2a0f0e2a2a0e0f2a2a0e0f2b0f2910292a0e0f2a2a0e0f2a2a0f0e2a2a0e0f2a0f2a0f0001a710290f290f292b0e0f2b2a0e102a2a0e0f2b2a0e102a2a0e0f2a0f290f2a2a0e0f2a2a0e0f2a2a0e0f2a2b0e0f2a0f290f0001a70f2b0f29102a2b0f0f2b2a0e102a2a0e0f292b0e0f292b0f0f2a2a0e0f2a2a0e0f2a2a0e0f2a2a0e0f2a2a0e2b0f2a0e0f0005dc000000000000"
				}
			},
			{
				"name": "Lüfter",
				"type": "switch-multi-repeat",
				"disableAutomaticOff": true,
				"interval": 1,
				"data": {
					"on": [{
							"data": "aa004201136d126d2b6d2a6d126d126d116e116e126d126d126d126d126d116e2a6d116e126c2b6d2b6d2a6d2b6d2a6e2a6e126d2a0003592b6d116d126d2c6d2a6e116d126d136d116e116d126d126d126d126d126c2c6d126d126d2a6d2c6d2b6e2a6d2b6d2a6e116e2c00035d2a6e126d126e2b6d2b6d126d116d126d126d126d126d116d126e126d126d2a6d126d126d2a6e2a6d2b6e2b6c2b6d2b6d126d2a0004752a6d126d126d2a6e2a6d126d116e116e126d126d126d136d126d116d126d2b6d116e136d116d126d2b6d2a6e116d126d126d2a0003342a6d126d126d2a6e2b6e126e126d116e116e116d126d126d126d116e116d2b6d126d126d116e116d2b6d2a6e116e126d126d2a0003342a6e116d126d2a6e2a6e116d126d116e126d116f116d126d126d136d116e2a6d126d126d126d146e2b6d2b6d116e126d126d2b0005dc000000000000",
							"sendCount": 1,
							"pause": 2
						},
						{
							"data": "2600500000012793141213121312131213111510141211131436113913371436143615351337133517111138143614361214131114101412113813121411141014361338123812371400052d0001284913000d050000000000000000",
							"sendCount": 1,
							"pause": 0.5
						},
						{
							"data": "2600500000012594141211141212151014111411141112131436133713371536133614381236143613381436123714371311141114121213131212131311161111381337143614361400052a0001274911000d050000000000000000",
							"sendCount": 1,
							"pause": 0.5
						},
						{
							"data": "2600500000012793141213121311251211131113131213121337143711391138143613381337113915101138133814111535151114101214103911141212143712131336143611381500052a0001274911000d050000000000000000",
							"sendCount": 1,
							"pause": 0.5
						},
						{
							"data": "26004800000125961114121214111411141113111412131213371534123814361436123715351337121313371213143514361510141113121436131213371213131213361337133711000d05",
							"sendCount": 1,
							"pause": 0.5
						}
					],
					"off": [{
							"data": "2600500000012793141213121312131213111510141211131436113913371436143615351337133517111138143614361214131114101412113813121411141014361338123812371400052d0001284913000d050000000000000000",
							"sendCount": 1,
							"pause": 6.5
						},
						{
							"name": "Lüfter",
							"data": "aa001801136c136c136c2b00035a2b6c136c126d2c6c2b6d126d126d126d126c136c136c126d126d126e2b6d2c6c136c136c2b6d156d2c6c2b6d136c126d136d2b00035f2b6c126d136d2b6d2b6c136c136d126d126d126d136c126e126d126c2c6d2b6d126d136c2b6d126d2b6d2a6d126d126d126d2b0004722b6d126d156d2b6c2c6c136c126d126d126d126d126d126e126d126c136c2b6d126d126e126d126d2b6c2c6c126d126d126d2b0003342a6d136c136c2b6d2b6d126d126c126d126d136c126d126d136d126d126d2b6c136c136c146c136c2b6d2b6c146c136c136c2c0003342c6c136d126d2b6c2b6d126d126d126e126d126d126c126d136c126d126d2b6d126d126d126d126c2b6d2b6d126d126d126d2b0005dcs",
							"sendCount": 1,
							"pause": 0.5
						}
					]
				}
			},
			{
				"name": "Ventilator",
				"type": "switch-multi-repeat",
				"disableAutomaticOff": true,
				"interval": 1,
				"data": {
					"on": [{
							"data": "aa004201136d126d2b6d2a6d126d126d116e116e126d126d126d126d126d116e2a6d116e126c2b6d2b6d2a6d2b6d2a6e2a6e126d2a0003592b6d116d126d2c6d2a6e116d126d136d116e116d126d126d126d126d126c2c6d126d126d2a6d2c6d2b6e2a6d2b6d2a6e116e2c00035d2a6e126d126e2b6d2b6d126d116d126d126d126d126d116d126e126d126d2a6d126d126d2a6e2a6d2b6e2b6c2b6d2b6d126d2a0004752a6d126d126d2a6e2a6d126d116e116e126d126d126d136d126d116d126d2b6d116e136d116d126d2b6d2a6e116d126d126d2a0003342a6d126d126d2a6e2b6e126e126d116e116e116d126d126d126d116e116d2b6d126d126d116e116d2b6d2a6e116e126d126d2a0003342a6e116d126d2a6e2a6e116d126d116e126d116f116d126d126d136d116e2a6d126d126d126d146e2b6d2b6d116e126d126d2b0005dc000000000000",
							"sendCount": 1,
							"pause": 1.5
						},
						{
							"data": "2600500000012793141213121312131213111510141211131436113913371436143615351337133517111138143614361214131114101412113813121411141014361338123812371400052d0001284913000d050000000000000000",
							"sendCount": 1,
							"pause": 0.5
						},
						{
							"data": "2600500000012594141211141212151014111411141112131436133713371536133614381236143613381436123714371311141114121213131212131311161111381337143614361400052a0001274911000d050000000000000000",
							"sendCount": 1,
							"pause": 0.5
						},
						{
							"data": "2600500000012594141211141212151014111411141112131436133713371536133614381236143613381436123714371311141114121213131212131311161111381337143614361400052a0001274911000d050000000000000000",
							"sendCount": 1,
							"pause": 0.5
						},
						{
							"data": "26004800000125961114121214111411141113111412131213371534123814361436123715351337121313371213143514361510141113121436131213371213131213361337133711000d05",
							"sendCount": 1,
							"pause": 0.5
						}
					],
					"off": [{
							"data": "2600500000012793141213121312131213111510141211131436113913371436143615351337133517111138143614361214131114101412113813121411141014361338123812371400052d0001284913000d050000000000000000",
							"sendCount": 1,
							"pause": 6.5
						},
						{
							"data": "aa001801136c136c136c2b00035a2b6c136c126d2c6c2b6d126d126d126d126c136c136c126d126d126e2b6d2c6c136c136c2b6d156d2c6c2b6d136c126d136d2b00035f2b6c126d136d2b6d2b6c136c136d126d126d126d136c126e126d126c2c6d2b6d126d136c2b6d126d2b6d2a6d126d126d126d2b0004722b6d126d156d2b6c2c6c136c126d126d126d126d126d126e126d126c136c2b6d126d126e126d126d2b6c2c6c126d126d126d2b0003342a6d136c136c2b6d2b6d126d126c126d126d136c126d126d136d126d126d2b6c136c136c146c136c2b6d2b6c146c136c136c2c0003342c6c136d126d2b6c2b6d126d126d126e126d126d126c126d136c126d126d2b6d126d126d126d126c2b6d2b6d126d126d126d2b0005dcs",
							"sendCount": 1,
							"pause": 0.5
						}
					]
				}
			},
			{
				"name": "Lüfter +",
				"type": "switch",
				"disableAutomaticOff": false,
				"onDuration": 0.5,
				"data": {
					"on": "26005000000127941312141114111414111412121411141114361436143712371436153614361239150f1238133714121436160f15101114123812141112153611131436143612371400052b0001254b12000d050000000000000000",
					"off": ""
				}
			},
			{
				"name": "Lüfter -",
				"type": "switch",
				"disableAutomaticOff": false,
				"onDuration": 0.5,
				"data": {
					"on": "26005000000126931412121313111412131213111213131114371337133713371337143614361436121314361412150f153514111312111414351412123714361411143614371336130005280001274915000d050000000000000000",
					"off": ""
				}
			},
			{
				"name": "Lüfter <->",
				"type": "switch",
				"disableAutomaticOff": false,
				"onDuration": 0.5,
				"data": {
					"on": "2600500000012794131214111411131214111411131214101536143613371536133714341636143613121436141213361436151113121410153614111436141114111337143614361300052e0001284814000d050000000000000000",
					"off": ""
				}
			},
			{
				"name": "Lüfter mode",
				"type": "switch",
				"disableAutomaticOff": false,
				"onDuration": 0.5,
				"data": {
					"on": "26004800000127941312141114111312141015101412131114361436143615371237133615361436133615361436143615101411141114111312141114111312143613371436143613000d05",
					"off": ""
				}
			},
			{
				"name": "K & S",
				"type": "switch-multi-repeat",
				"disableAutomaticOff": true,
				"interval": 1,
				"data": {
					"on": [{
							"data": "aa004001136c2b6d2b6d126d136c136c126d126d126d126d126c126d126d2b6d2b6d2c6d2b6c2c6c2c6d2b6f126d126d126d130003512b6d126d156c2b6d2b6d126d116d136c126d126d126d126d126c126d136d2b6d2a6d2b6d2b6c2b6d2c6d2b6d126d126d126d120003562b6d126d126c2b6d2b6d126d126d136c126d126d126d126c126d126d136d2b6c2b6d2b6d2a6d2b6d2c6c2b6d126d126d136d1200046b2c6d116d126d2b6d2b6d136c126d126d126c126d146c126d126d126d126c2b6d2c6d2a6d136c126d2c6d2b6f136c2b6d126c1200032d2b6d126c136c2b6d2a6e126d116d126d126d126d126e116d126d126d126d2b6c2c6d2b6e126c136c2b6d2a6d136d2a6d126d1200032c2e6d126d126c2b6d2b6d126d116d136f126d126d126d136d126c136c126d2b6d2b6c2b6d126d126d2a6d2b6e126d2b6c126d120005dc0000000000000000",
							"sendCount": 3,
							"pause": 1
						},
						{
							"data": "aa00360110290f2b2a0e102a2b0e0f2b2a0e102a0f290f292b0e0f292b0e0f292b0e0f292a0f0f292c0e0f292a0f0f292a0e100001a710290f290f2a2a0e0f2a2a0e0f2a2a0e0f2a0f2a0f2a2b0e0f2a2a0e0f2a2a0e0f2a2a0e0f2a2a0e0f2d2a0e0f2a2a0e0f0001a70f2a0f290f2a2a0e0f2a2a0e0f2a2a0e0f2a0f290f2a2a0e0f2a2b0e102a2a0e0f292b0e0f2a2a0e0f292b0e0f292b0e0f0001a70f290f2a0f2a2a0e0f2a2b0e102a2a0e0f290f2a0f292b0e0f292b0e0f292b0e0f292b0f0f292b0e0f292a0f0f292a0f0f0001a70f290f2a0f292a0f0f292a0f0f292a0f0f290f2a0f292a0f0f2a2a0e0f2b2a0f0e2a2b0f0e2b2a0e102a2a0f0f2a2a0e0f0001a70f2a0f290f2a2a0e0f2a2a0e0f2a2a0e0f2a0f290f2b2a0e102a2a0e0f2a2a0e0f2a2a0f0f292b0e0f292b0e2a0f2a0e0f0005dc0000",
							"sendCount": 1,
							"pause": 0.5
						}
					],
					"off": [{
							"data": "aa00f600136d136d2b6c2c6c2b6d2b6c2c6d136d2c6c2b6c136c2c6c136c130003572b6d126c136c2c6c2c6c126d136c136d126c136c136c136c136c136c2b6d2b6d2c6c2d6c2b6e126d2b6c2c6c136d2b6c136c1300046e2c6c136c136c2c6c2c6d126d126d126d136c136c136c136c136c136c126d2b6d2b6c2c6d136c126d2b6c2c6d136c2b6d126d1200032d2b6d126c136c2c6c2b6d126d126c136e126c136c136c136c136c136c126d2b6e2c6c2c6c136c126d2b6c2c6c136c2c6c126d1200032d2b6d126d126c2b6d2b6d126d126d126e126d126c136c136c136c136c126d2b6d2b6c2c6d136c136c2b6d2b6d126c2c6c136c120005dc0000",
							"sendCount": 3,
							"pause": 1
						},
						{
							"data": "aa003601102b0f292a0e10292a0f0f292a0e0f2a0f2a0e2a2a0e0f2b2a0e102a2a0e0f2a2a0e0f2a2a0e0f2a2a0e0f2a0f2a0f0001a70f2910300f292c0e0f292b0e0f2a2b0e0f290f2a0f292b0e0f292b0f10292a0f0f2a2a0f0f292c0f0f2a2a0f10290f2a0f0001a710290f2a0f292a0f0f292a0f0f292a0f0f290f2a0e2a2a0e0f2b2a0f0f292a0f0f292a0e0f2a2a0e0f2a2a0e0f2a0f2a0f0001a70f2a0f290f2a2a0e0f2b2a0e102a2a0e0f2a0f2910292a0f0e2a2a0e0f2a2a0e0f2a2b0f0f292a0e0f2a2a0e0f2a0f290f0001a70f2a0f290f2a2a0e0f2a2a0e0f2a2a0e0f2a10290f2a2a0e0f2a2a0e0f2a2a0e0f292b0e0f2a2a0e0f292b0f0f2910290f0001a70f2910290f292b0e0f292a0f0f2a2b0e0f292b0e0f292b0e0f292b0e0f292b0e0f292a0f0f292c0e0f292b0e2a0e2b0e0f0005dc0000",
							"sendCount": 1,
							"pause": 0.5
						}
					]
				}
			},
			{
				"name": "K & S <->",
				"type": "switch",
				"disableAutomaticOff": false,
				"onDuration": 0.5,
				"data": {
					"on": "aa003601102b0f292a0e10292a0f0f292a0e0f2a0f2a0e2a2a0e0f2b2a0e102a2a0e0f2a2a0e0f2a2a0e0f2a2a0e0f2a0f2a0f0001a70f2910300f292c0e0f292b0e0f2a2b0e0f290f2a0f292b0e0f292b0f10292a0f0f2a2a0f0f292c0f0f2a2a0f10290f2a0f0001a710290f2a0f292a0f0f292a0f0f292a0f0f290f2a0e2a2a0e0f2b2a0f0f292a0f0f292a0e0f2a2a0e0f2a2a0e0f2a0f2a0f0001a70f2a0f290f2a2a0e0f2b2a0e102a2a0e0f2a0f2910292a0f0e2a2a0e0f2a2a0e0f2a2b0f0f292a0e0f2a2a0e0f2a0f290f0001a70f2a0f290f2a2a0e0f2a2a0e0f2a2a0e0f2a10290f2a2a0e0f2a2a0e0f2a2a0e0f292b0e0f2a2a0e0f292b0f0f2910290f0001a70f2910290f292b0e0f292a0f0f2a2b0e0f292b0e0f292b0e0f292b0e0f292b0e0f292a0f0f292c0e0f292b0e2a0e2b0e0f0005dc0000",
					"off": "aa00360110290f2b2a0e102a2b0e0f2b2a0e102a0f290f292b0e0f292b0e0f292b0e0f292a0f0f292c0e0f292a0f0f292a0e100001a710290f290f2a2a0e0f2a2a0e0f2a2a0e0f2a0f2a0f2a2b0e0f2a2a0e0f2a2a0e0f2a2a0e0f2a2a0e0f2d2a0e0f2a2a0e0f0001a70f2a0f290f2a2a0e0f2a2a0e0f2a2a0e0f2a0f290f2a2a0e0f2a2b0e102a2a0e0f292b0e0f2a2a0e0f292b0e0f292b0e0f0001a70f290f2a0f2a2a0e0f2a2b0e102a2a0e0f290f2a0f292b0e0f292b0e0f292b0e0f292b0f0f292b0e0f292a0f0f292a0f0f0001a70f290f2a0f292a0f0f292a0f0f292a0f0f290f2a0f292a0f0f2a2a0e0f2b2a0f0e2a2b0f0e2b2a0e102a2a0f0f2a2a0e0f0001a70f2a0f290f2a2a0e0f2a2a0e0f2a2a0e0f2a0f290f2b2a0e102a2a0e0f2a2a0e0f2a2a0f0f292b0e0f292b0e2a0f2a0e0f0005dc0000"
				}
			},
			{
				"name": "Skyline",
				"type": "switch-multi-repeat",
				"disableAutomaticOff": true,
				"interval": 1,
				"data": {
					"on": [{
							"data": "b20934000e280e280e28290e0e28290e0e28290d0e28290d0e28290d0e28290d0e280e280e28290e0e28290e0e28290d0e28290d0e00019c00000000",
							"sendCount": 1,
							"pause": 1
						},
						{
							"data": "26004800000125941411141015101313111315101312141017341435143515361410153513371237173414361213131115111312131115101114141015351337123715351436123517000d05",
							"sendCount": 1,
							"pause": 0.5
						}
					],
					"off": [{
							"data": "260050000001279315121410160f13121411160f131214101634133712371535141114361237143515101337160f14111410151013121411153515101435143614351535133812361500053d0001274b13000d050000000000000000",
							"sendCount": 1,
							"pause": 0.5
						},
						{
							"data": "b20834000f280f280f28290d0e28290d0e28290d0e28290d0e28290e0e28290d0e280f280f28290d0e28290e0e28290d0e280e280e00019c00000000",
							"sendCount": 1,
							"pause": 0.5
						}
					]
				}
			},
			{
				"name": "Skyline bunt",
				"type": "switch",
				"disableAutomaticOff": true,
				"onDuration": 0.5,
				"data": {
					"on": "260050000001279413121311160f141114101411141113111735133513361536121314351435143614361435141213121337131113111411131213121435153515101337133613361600053d0001274912000d050000000000000000",
					"off": "26005000000129911511150e170f14121310170e160f150f1734133615341734150f163415341535163415341633170f1411150f1511150f160e170f1411143515341733163415341700053b00012a4716000d050000000000000000"
				}
			}
		]
	}]
}

**Comment by lprhodes** [comment]
No there shouldn't be any need to update the config. I just wanted to be sure I hadn't missed something there.

Can you type `node -v` on your raspberrypi please and let me know the output. I'll see if I can re-produce the issue on your version of node.

**Comment by Green-Kite** [comment]
My node is on v8.9.4.

**Comment by Nastras** [comment]
With me is the same error I have node 9.8.0

**Comment by zladukas** [comment]
#289

**Comment by lprhodes** [comment]
Can you give 3.1.1 a go please and see if that fixes this error. I still can't re-produce but I believe it though do the trick.

**Comment by Green-Kite** [comment]
Still not working.
But I recognized there is a second error message before the one I posted above:

> Mär 14 12:56:38 raspberrypi homebridge[1236]: [2018-3-14 12:56:38] ERROR LOADING PLUGIN homebridge-broadlink-rm:
Mär 14 12:56:38 raspberrypi homebridge[1236]: [2018-3-14 12:56:38] TypeError: Class extends value undefined is not a constructor or null
Mär 14 12:56:38 raspberrypi homebridge[1236]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/test/helpers/fakeServiceManager.js:4:34)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at Module._compile (module.js:643:30)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at Object.Module._extensions..js (module.js:654:10)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at Module.load (module.js:556:32)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at tryModuleLoad (module.js:499:12)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at Function.Module._load (module.js:491:3)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at Module.require (module.js:587:17)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at require (internal/module.js:11:18)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/serviceManager.js:2:28)
Mär 14 12:56:38 raspberrypi homebridge[1236]: at Module._compile (module.js:643:30)

**Comment by lprhodes** [comment]
Thanks - 3.1.2 fixes that error

**Comment by Green-Kite** [comment]
3.1.2 fixed it for me too.

Thanks for your great work on this plugin!
