### ISSUE TITLE
Window Cover Bug

### ISSUE THREAD

**Issue by Nastras** [lprhodes/homebridge-broadlink-rm#291]
Hello Luke,

the window covers seem to work but I get a lot of errors in the log. 

I think that's the bug I've already reported.  I've finished a file for you in the hope that you can start something.

I still can not fully understand the error, it looks like it happens when the window cover closes.

[Report.txt](https://github.com/lprhodes/homebridge-broadlink-rm/files/1811292/Report.txt)

Here is my config:

"name":"Rollo 1 Wohnzimmer",
"type":"window-covering",
"persistState": true,
"resendHexAfterReload": false,
"totalDurationOpen": 29,
"totalDurationClose": 27,
"disableLogs": false, 
"host":"192.168.6.48",
"data":{
"open":"",
"close":"",
"stop":""
}
},

**Comment by Nastras** [comment]
In addition, the window covers no longer open or close when manually de-synchronized by a user.

I mentioned the problem before. If the window cover really stands at 50% and has 100% in Homekit, you will not be able to open or close it without RF remote control.

**Comment by lprhodes** [comment]
The error can be ignored - it’s just due to timers things being reset. I suppress the error message usually.

Sorry can you just go over the issue with a bit more detail please, step by step.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lprhodes** [comment]
@Nastras I think the issue you're reporting was just fixed in v3.2.6

I'll be suppressing those warning messages shortly.

**Comment by Nastras** [comment]
Everything else seems to work .-)

**Comment by lprhodes** [comment]
Fixed in 3.2.17 👍

**Comment by Nastras** [comment]
👍👍👍👍👌 Thank You 😘

**Comment by Nastras** [comment]
Hello, unfortunately I have bad news. Since the last update, this error occurs:

![23d722bf-c80e-4d38-bd31-bc970657f715](https://user-images.githubusercontent.com/27686185/37576866-d37b99b0-2b2e-11e8-8cd3-c15d7014de1d.jpeg)


Can you do something with that?

**Comment by Nastras** [comment]
Just tested again, the error occurs at each press now

**Comment by lprhodes** [comment]
It’s saying the hex code is missing so probably a config error - send it over and I’ll take a look.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lprhodes** [comment]
Open as a new issue too please 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
