### ISSUE TITLE
Pseudo-mode auto not working anymore

### ISSUE THREAD

**Issue by iandronowicz** [lprhodes/homebridge-broadlink-rm#298]
I used to set the pseudo-mode of all the temps at "auto" and it worked fine. Now its making me set it to heat or cool. The thing is that its summer here so cool mode could be even at 23 or 24 degrees. I know its a small detail but I would prefer to see the icon in the home app just in "auto" mode. Now the ac its cooling to 23C and icon shows "heating". I know that I can set the threshold higher but in the winter I'll have to change it again... maybe theres a solution that im not seeing.

Thanks!

**Comment by lprhodes** [comment]
My concern was that it would create a loop but I've ensured that it does not. Fixed in v3.2.7
