### ISSUE TITLE
Set heat/cool mode depending on the current temp?

### ISSUE THREAD

**Issue by iandronowicz** [lprhodes/homebridge-broadlink-rm#299]
I was just wondering.... couldn’t the heat/cool mode be set according the actual temp reading of the broadlink rm? Like:

actual_temp <= target_temp -> show heating mode
actual_temp > target_temp -> show cooling mode

At least for the broadlinks with temp sensors.

Just an idea

![46a58e01-2c4b-4f5a-bf7b-33242e4dbcf9](https://user-images.githubusercontent.com/250746/37443493-3ce05f90-27eb-11e8-8280-9bccd849c592.png)

**Comment by lprhodes** [comment]
I was just thinking that myself :)

**Comment by iandronowicz** [comment]
In that image you can see that the broadlink sensor reads 26C, I set the target temp to 23C and it shows “heating” wrongly

**Comment by lprhodes** [comment]
This is available as of v3.2.12
