### ISSUE TITLE
Siri

### ISSUE THREAD

**Issue by hkechung** [lprhodes/homebridge-broadlink-rm#30]
Channel up down, Volume up down works on Apple Home apps
however, when I use Siri, it return "Your channel down is off"
Is it another glitch in Siri ?

Thanks
Edwin

**Comment by jat80** [comment]
Mine works fine for the volume up/down with siri.  Obviously you have to say "Hey Siri, turn on volume up/down" which is not very natural.  :)

**Comment by lprhodes** [comment]
Apple doesn't support turn up or turn down for this kind of thing - it's just a work around using standard switches hence having to ask Siri to turn it on or of
