### ISSUE TITLE
When AC turn off, change temperature will case  turn on AC.

### ISSUE THREAD

**Issue by phenix13** [lprhodes/homebridge-broadlink-rm#300]
I need a parameter like "autoStart" when AC turn off, change temperature will set to this mode. If you set this to "off", change temperature will not turn on AC. I don't want to turn on AC when I only change
temperature , I want to turn on AC only by change mode to heat or cool or auto.
You can look another plgin , This is he address: https://github.com/LASER-Yi/homebridge-mi-acpartner/blob/master/doc/README_EN.md# .

**Comment by lprhodes** [comment]
Support has been added to 3.2.15 with the `sendTemperatureOnlyWhenOff` option.
