### ISSUE TITLE
Warnings at startup

### ISSUE THREAD

**Issue by det-box** [lprhodes/homebridge-broadlink-rm#301]
I receive several warnings when starting since version 3. x. x
![grafik](https://user-images.githubusercontent.com/8150405/37456838-a110964c-2840-11e8-8367-f5cfb782451e.png)

Furthermore, the status undefined
![grafik](https://user-images.githubusercontent.com/8150405/37456897-bc10c7dc-2840-11e8-8cc8-82f86c36db43.png)

Thanks

**Comment by det-box** [comment]
Here is my configuration
`       {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "host": "192.168.23.14",
            "disableLogs": false,
		"hideWelcomeMessage": true,
            "homebridgeDirectory": "/var/homebridge/",
            "accessories": [
                {`

**Comment by lprhodes** [comment]
Hey - I'll need the rest of your config. I reckon the warnings aren't coming up because they have a black font color.

**Comment by det-box** [comment]
Hi,
with version 2. 7. 4 there are no warnings,
I just extended the config by one entry.
'hideWelcomeMessage': true,
for the current version.

Here is the config for Broadlink.

And no, there is no black font set.
`        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "host": "192.168.23.14",
            "disableLogs": false,
		"hideWelcomeMessage": true,
            "homebridgeDirectory": "/var/homebridge/",
            "accessories": [
                {
                    "name": "Entertainment",
                    "type": "switch-multi",
                    "interval": 0.5,
                    "data": [
                        "260054004e15271413142715131428131315131427141315131413151300034d5015261513142714131526151314131527141314131513141300034d4f142715131427141315261513141315271413141315131413000d0500000000",
                        "260050000001289313111510141213111411141114111436143614351535143614361436143614351510143614111436141114111411141114351510153514111436143614361435150004f80001294814000d050000000000000000",
                        "26008800501229121612291215122912161215121513151215131512291229121513150002c0511229121512291216122912151216121512151315121513281328131512150002c1501229131512291215122913151215121612151215131512291229121513150002c051122912151229131512291215121612151215131512151328132813151215000d05",
                        "260054004e1527141314271413152714131413142714141414131315130003504e14271414142714131427151314131526151314131513141300034e4e142714141427141314271513141315261513141315131413000d0500000000",
                        "26008800501229121612291215122913151215121513151215131512291229121513150002c0511229121512291315122912151216121512151315121513281328131512150002c1501229121513291215122912161215121513151215131512291229121513150002c050132813151229121513291215121513151215131512151229132813151215000d05",
                        "26004800000128931311151013121411141113121411143614351436153514361436143614351535151014361411143614111411141015111435151014361411143614361436143515000d05",
                        "26008800501229121612291215122912161215121513151215131512291229121513150002c0511229121512291216122912151216121512151315121513281328131512150002c1501229131512291215122913151215121612151215131512291229121513150002c051122912151229131512291215121612151215131512151328132813151215000d05",
                        "260054005012271514132714131427141513141327141315141314131300034f5012271413152714131427141513131428131314131515121500034d4e142714151326151413271413151314271413141315131413000d0500000000",
                        "260060000001279115131213111411131313111411131239113811391238113911381239123711391312113813131138121312141113121311391213113813131138123911381139120004fa0001264b13000c540001264b13000c540001264b12000d050000000000000000",
                        "2600cc004d1526151413271413142715121513141413131413151215261526151314130002c14e1527141314271414132714131513141314131413141315271426151314130002c14f1426151215261513142615141313151215131414131413281327151215130002c14e1427141315271413142615131413141315121513141314271427141314140002c14d1527141413281313152615131413141314131513141314261527141413130002c24e142615131427141314271413151314131413141315121526152714141313000d05000000000000000000000000",
                        "2600aa004e1427141413271414142615131413141314141412151314271427141314130002c24d1526151413271414142615131413141314131414141314261526151314130002c24d1527141413271413152615121513141314131414141215271427141314130002c14f1426151314261513142714131512151314141313141315261526151314130002c14e152615131427141314271413141315131414131314141426152615121513000d050000000000000000000000000000",
                        "2600aa00501229121513281315122813151215121513151215121512291229121513150002bf501229121513281315122813151215121513141315121512291229121512150002c0501229121512291215132813151215121512151314131512291229121512150002c04f1329121512291215132813151215121512151215131512281328131512150002bf50132813151229121512291215131512151215121513141328132813151215000d050000000000000000000000000000"
                    ]
                },
                {
                    "name": "SAT Ein/Aus",
                    "type": "switch",
                    "data": {
                        "on": "260050000001289313111510141213111411141114111436143614351535143614361436143614351510143614111436141114111411141114351510153514111436143614361435150004f80001294814000d050000000000000000",
                        "off": "260050000001299214111411131214101511131213111535143613371436143415361535143613371411133615111336151014121311141113371411133615111336153613361337140004f80001294815000d050000000000000000"
                    }
                },
                {
                    "name": "Verstärker lauter",
                    "type": "switch-repeat",
                    "sendCount": 2,
                    "interval": 0.3,
                    "data": "26006600501315122912151315122912151315121512161215121513281329121512150002d5501215132813151215122913151215121612151215131512291229121513150002d450131512291215131512291215131512151216121512151328132912151215000d050000"
                },
                {
                    "name": "Verstärker leiser",
                    "type": "switch-repeat",
                    "sendCount": 2,
                    "interval": 0.3,
                    "data": "26008800501427152615131413152615131413141513131415131314291227141315130002c34e1427142714131513142813131513141513141313141315261527141314130002c3501326152813151215132615131415131413151313141314291328131413130002c34e142912271512151314271413151512151314131315131427142813151313000d05"
                },
                {
                    "name": "Verstärker Ein/Aus",
                    "type": "switch",
                    "data": {
                        "on": "26008800501229121612291215122912161215121513151215131512291229121513150002c0511229121512291216122912151216121512151315121513281328131512150002c1501229131512291215122913151215121612151215131512291229121513150002c051122912151229131512291215121612151215131512151328132813151215000d05",
                        "off": "26008800501229121612291215122912161215121513151215131512291229121513150002c0511229121512291216122912151216121512151315121513281328131512150002c1501229131512291215122913151215121612151215131512291229121513150002c051122912151229131512291215121612151215131512151328132813151215000d05"
                    }
                },
                {
                    "name": "TV Ein/Aus",
                    "type": "switch",
                    "data": {
                        "on": "260054004e15271413142715131428131315131427141315131413151300034d5015261513142714131526151314131527141314131513141300034d4f142715131427141315261513141315271413141315131413000d0500000000",
                        "off": "260054004e15271413142715131428131315131427141315131413151300034d5015261513142714131526151314131527141314131513141300034d4f142715131427141315261513141315271413141315131413000d0500000000"
                    }
                },
                {
                    "name": "TV lauter",
                    "type": "switch-repeat",
                    "sendCount": 2,
                    "interval": 0.3,
                    "data": "260054004e141315261515121315261513141513271413141315131413000364501314132912131513142813141313142913141313141315130003614e151512291213151314271513141314271513141513121513000d0500000000"
                },
                {
                    "name": "TV leiser",
                    "type": "switch-repeat",
                    "sendCount": 2,
                    "interval": 0.3,
                    "data": "260054004f1427142714131514132813141413142813141413141315130003504e14271527141314131526151314141426151314131513141300034e4e142715261513141315261513141315261513141315131413000d0500000000"
                },
                {
                    "name": "TV-Kanal hoch",
                    "type": "switch-repeat",
                    "sendCount": 1,
                    "data": "26005400501313151314131414142813131513142813141413141414130003774e1513141315121513142715131413142715131413151215130003754e151314131413151314271513141314271513141315131413000d0500000000"
                },
                {
                    "name": "TV-Kanal runter",
                    "type": "switch-repeat",
                    "sendCount": 1,
                    "data": "260054004e1527141314131514132714131512152615131414141314130003644e1427151314131414142714141413142714131513141315130003614e142715131413141315271413151314271413151314131512000d0500000000"
                },
                {
                    "name": "Ambilight Ein/Aus",
                    "type": "switch",
                    "data": {
                        "on": "2600500000012b92151015111411141115101511141114111435153514351535143515351435153514351534151114111510151015111435151015111435143515351435153514111500051a00012b4815000d050000000000000000",
                        "off": "2600580000012b92151015111411141115101510151114111435153514351535143515341535153415111435151015101511141114111534153515101534153515341535143515101500051a00012c4715000c4c00012b4814000d05"
                    }
                },
                {
                    "name": "Ambilight weiss",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "2600500000012c92141114111510151015111411141115101535143515351435153415351534153514351535143515101511141114111534151114111411153415351534153514111500051a00012b4815000d050000000000000000"
                },
                {
                    "name": "Ambilight blau",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "2600500000012a94131212131213141213121312131214111337123713371336143613361337133613121436133613121412121312131337133613121312143612371337133614111400051b00012a4a13000d050000000000000000"
                },
                {
                    "name": "Ambilight grün",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "2600500000012995131213121213131313121312121313121436123714361336143613361436133613371312123713131312131213121337131213361412123712381237133614121300051c00012a4814000d050000000000000000"
                },
                {
                    "name": "Ambilight rot",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": " 2600500000012995121313121313121312131213121313121337133614361336133514371238123713121312133712141212141212131237123813361213133712371337123714121200051c00012a4a12000d050000000000000000"
                },
                {
                    "name": "Ambilight Flash",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "2600500000012995131213121213131312131213121313121337133612381237133614361237133712371337131212371313131212131237141311131237131312371336133712131200051d00012a4913000d050000000000000000"
                },
                {
                    "name": "Ambilight Strobe",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "2600580000012994141114121213131213121312141213121336143612371238133613361436133614361336133713361312131312131336141114121312121312371337133614121200051d0001294a13000c4d0001294913000d05"
                },
                {
                    "name": "Ambilight Fade",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "2600500000012994141113121313131212131213131213131336123713371336133713361436123712381336131312121436131212131337131212131337133612131337133613121300051c00012a4913000d050000000000000000"
                },
                {
                    "name": "Ambilight Smooth",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "2600500000012994141213121213121313121313121313131137143613361335153614361237123812371337123713131237131212131336131312131213123714131236123812131200051d00012a4912000d050000000000000000"
                },
                {
                    "name": "Ambilight",
                    "type": "switch",
                    "data": {
                        "on": "2600500000012b92151015111411141115101511141114111435153514351535143515351435153514351534151114111510151015111435151015111435143515351435153514111500051a00012b4815000d050000000000000000",
                        "off": "2600580000012b92151015111411141115101510151114111435153514351535143515341535153415111435151015101511141114111534153515101534153515341535143515101500051a00012c4715000c4c00012b4814000d05"
                    }
                },
                {
                    "name": "Ambilight one",
                    "type": "switch-multi",
                    "interval": 1.5,
                    "data": [
                        "b20e12009f0c0e0c0e0d0e0d0e0d0e0d0e0d0e0d0da4000000000000",
                        "b21212009d0c0e0c0e0c0e0c0e0c0d0d0d0d0e0d0da3000000000000",
                        "b21712009d0c0e0d0e0d0e0c0e0d0e0c0e0c0d0d0ea2000000000000",
                        "b22412009e0c0e0c0e0d0e0d0d0d0d0d0e0d0e0c0ea2000000000000"
                    ]
                },
                {
                    "name": "SAT lauter",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "260050000001299214111411141114111411141114111435153613361436143614361435153613361412133613371436141015111312131115361311141114111436143515361435140004f800012a4814000d050000000000000000"
                },
                {
                    "name": "SAT leiser",
                    "type": "switch-repeat",
                    "sendCount": 5,
                    "interval": 0.3,
                    "data": "2600500000012a9115111411141015101511131115101436143614361435153613361436143614361411141015111435151014121336141114361435153614101536133614111436140004f80001294815000d050000000000000000"
                },
                {
                    "name": "SAT-Kanal hoch",
                    "type": "switch-repeat",
                    "sendCount": 1,
                    "data": "260050000001299214111411131214101511131213111535143613371436143613361536133613371411131214111411131214101510141213361436143614361336153613361436140004f90001284815000d050000000000000000"
                },
                {
                    "name": "SAT-Kanal runter",
                    "type": "switch-repeat",
                    "sendCount": 1,
                    "data": "260050000001299215111311151014111411141114111436143515361336143614361436143515361336141213111411141114111411141114111436143515351535143614361436140004f80001294814000d050000000000000000"
                },
                {
                    "name": "SAT ok",
                    "type": "switch-multi",
                    "interval": 0.5,
                    "data": [
                        "260050000001299214111411141114101511141113111535143614361436143515351535143614361436143614351536133614111411141114111411141114111410153613361436140004f80001294815000d050000000000000000"
                    ]
                }
            ]
        },
`

**Comment by phenix13** [comment]
So as AC, it's report minTemperature error

**Comment by lprhodes** [comment]
The warning fonts are in black and you have a black terminal...

The warnings are to be expected. Try temporarily changing your terminal background colour 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lprhodes** [comment]
If there’s a CONFIG ERROR then you need to fix it 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by det-box** [comment]
OK,
now you can read it.
![grafik](https://user-images.githubusercontent.com/8150405/37465937-cf913172-285c-11e8-8bb9-29823089ea2c.png)

The displayed status undefined
Is that normal?

![grafik](https://user-images.githubusercontent.com/8150405/37466025-0b141192-285d-11e8-8869-4372378495cd.png)

Thanks

**Comment by lprhodes** [comment]
On first load yes 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
