### ISSUE TITLE
RM Mini 3 Setup Error

### ISSUE THREAD

**Issue by MrAlpaca1** [lprhodes/homebridge-broadlink-rm#303]
I have compiled a working config.json and "taught" my Pi / RM mini the remote hex code and am getting the following error: 

[CONFIG ERROR] Numeric values should look like this: "data": 2600e00000012...
 not this "data": "2600e00000012..."

When plugging in just the number (which is really a long hex string) I get an invalid json error. Not sure if there is something that needs to be done to tell the Broadlink RM platform to read this as a hex string. ``

``

**Comment by MrAlpaca1** [comment]
``

**Comment by lprhodes** [comment]
Hey, can you make sure you’re on he latest version please. If you are and it still happens then please send your config.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MrAlpaca1** [comment]
I installed this last night, so it should be the latest, I would presume. 

Config.json below

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "AlpacaBridge",

    "platforms": [
    {
      "platform":"RM-Mini3",
      "name":"Broadlink RM",
      "host": "192.168.0.111",
      "accessories":[
        {
          "name":"TV On/Off",
          "type":"switch",
          "data":"2600e0000001299313121312123713121312131213121312133713371213123713371337133713371212131213121337131213121312131213371337123713121337133713371336130005290001294913000c5b0001284a13000c5b0001294913000c5b0001284a12000c5c0001274a13000c5b0001284913000c5c0001264a13000c5c0001254b13000c5c0001254b13000c5c0001244a13000c5c0001254913000c5c00012a4913000c5b00012a4a13000c5b00012a4a13000c5b00012a4a13000c5b00012a4a14000c5b0001294a13000c5b00012a4913000c5c00012a4913000d050000000000000000"
          
        },
        
    	

        
        
        
        
        {
              "name":"Scan IR",
              "type":"learn-code",
              "scanRF": false
          
}
        
      ]
    }
  ] 
}`

**Comment by lprhodes** [comment]
To fix this exact issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MrAlpaca1** [comment]
What is the most effective way to update this? And bad timing on my part! Missed it by 12 hours. Facepalm.

**Comment by MrAlpaca1** [comment]
Got it updated and it loads fully now! Thank you. I am not home, so I can't check, but last night when testing the signal wasn't even turning on the little white light when sending. Did this update fix that as well?

**Comment by lprhodes** [comment]
@MrAlpaca1  I generally just run `npm update homebridge-broadlink-rm -g`

I've no idea regarding the white light, sorry. Maybe - the blue light works on the RM Pro.
