### ISSUE TITLE
nothing works while updating from 2.7.4 to 3.2.15

### ISSUE THREAD

**Issue by cubilon** [lprhodes/homebridge-broadlink-rm#304]
got several errors while moving from 2.7.4 to 3.2.15. 
I got two broadlink IR, 192.168.1.90 and 192.168.1.91.
in attach, the previous .json version (working fine with 2.7.4) and actual one (converted for 3.2.15).
this is the error I got when I activate "Radiofreccia" switch (formelly a "switch-multi-repeat"):

[2018-3-15 18:34:20] [Broadlink RM] Radiofreccia setSwitchState: true
setCharacteristicValue err { AssertionError [ERR_ASSERTION]: [ERROR]: HEX value is missing
    at module.exports (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/sendData.js:7:3)
    at SwitchAccessory.setSwitchState (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:44:18)
    at SwitchAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:136:15)
    at emitMany (events.js:147:13)
    at Characteristic.On.emit (events.js:224:7)
    at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:311:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:867:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:807:8)
    at emitMany (events.js:147:13)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }

**tried everything. no luck.**
some of the others switches don't work, no errors on the terminal but NO HEX sent ("SKY on/off", for example), while on 2.7.4 everything worked fine. only the A/C works fine on 3.2.15.

[extract_2.7.4.json.zip](https://github.com/lprhodes/homebridge-broadlink-rm/files/1816507/extract_2.7.4.json.zip)
[extract_3.2.15.json.zip](https://github.com/lprhodes/homebridge-broadlink-rm/files/1816516/extract_3.2.15.json.zip)

**Comment by cubilon** [comment]
(node version is 8.9.4 on Raspberry Pi 3)

**Comment by lprhodes** [comment]
Hey @cubilon 

I'm surprised that config works at all on 3.2.15. Some of the "descriptions" will need updating to pass the config checker (e.g. from `"description": "7"` to `"description": "B7"` or similar.

It'll also need the minTemperature to be set at 10 or below (due to a bug in the Home app).

3.2.15 would have shown error messages about the above though, are you sure you're on the latest version?

**Comment by lprhodes** [comment]
After making the above changes, the config worked as expected on the latest release.

**Comment by cubilon** [comment]
I'm a little bit confused: when you say "I'm surprised that config works at all on 3.2.15" you meant 2.7.4, right?
with 2.7.4 everything works smoothly (using 2.7.4 json versione, of course). "description" fake field purpouse was just having a "note" field, but it doens't cause any kind of problem until 3.x.
what I done BEFORE moving to 3.x was taking my json, reading your notes and "converting" it to the new configuration trying to mantain all the functionalities.. but I got the error I told you.

btw, I tried removing any "description" field, nothing changes, the error with 3.2.15 is still the same. on A/C you're right, 10 value is not shown on Home App on both plugin versione, but this is not a problem.

another thing I've noticed is that if I set on "true" the debug fild, I got an error on start.
hope this helps helping.

**Comment by lprhodes** [comment]
I mean 3.1.5

Your config shows multiple “[CONFIG ERROR]” messages about the description option on the latest 3.X

You can include the “description” option but you need to use some at least one letter in the description. i.e.` “description”: “1”` will not work but .` “description”: “B1”` will

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lprhodes** [comment]
It sounds like you should update to the latest version too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
