### ISSUE TITLE
Inversion of the icon

### ISSUE THREAD

**Issue by Maxwell70** [lprhodes/homebridge-broadlink-rm#305]
I use a garage door. In Homekit the icon is inverted: when I open the icon - bridge sent code to the closing, when I close the icon - bridge sent the code to the opening!

**Comment by lprhodes** [comment]
Hey @Maxwell70 can you end me your config please.

**Comment by Maxwell70** [comment]
Hi @lprhodes 
{
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
"hideScanFrequencyButton":false,
         "hideLearnButton":false,
      "accessories":[
        {
          "name":"NiVorota",
"host":"192.168.1.23",
          "type":"garage-door-opener",
"openCloseDuration":"3",
"autoCloseDelay":"3",
          "data":{
"open":"c2222c00.......",
"close":"b2071c....."
          }
        },

**Comment by lprhodes** [comment]
Please update to the latest version

**Comment by Maxwell70** [comment]
@lprhodes What is the command to update?

**Comment by Maxwell70** [comment]
@lprhodes After the update, the problem was solved! Thank You!!!!!!!
