### ISSUE TITLE
Air conditioner minimum temperature can't be higher than 10 celsius

### ISSUE THREAD

**Issue by tamasvicsotka** [lprhodes/homebridge-broadlink-rm#307]
Mar 17 12:54:22 pimaster homebridge[6300]: [3/17/2018, 12:54:22 PM] [Broadlink RM] A/C Fan Accessory Ready
Mar 17 12:54:22 pimaster homebridge[6300]: [3/17/2018, 12:54:22 PM] [Broadlink RM] A/C Accessory Ready
Mar 17 12:54:22 pimaster homebridge[6300]: /usr/lib/node_modules/homebridge-broadlink-rm/node_modules/chai/lib/chai/assertion.js:141
Mar 17 12:54:22 pimaster homebridge[6300]:       throw new AssertionError(msg, {
Mar 17 12:54:22 pimaster homebridge[6300]:       ^
Mar 17 12:54:22 pimaster homebridge[6300]: AssertionError: [CONFIG ERROR] minTemperature (17) must be <= 10: expected 17 to be below 11
Mar 17 12:54:22 pimaster homebridge[6300]:     at AirConAccessory.setDefaults (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:95:12)
Mar 17 12:54:22 pimaster homebridge[6300]:     at AirConAccessory.HomebridgeAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:39:10)
Mar 17 12:54:22 pimaster homebridge[6300]:     at BroadlinkRMAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:17:5)
Mar 17 12:54:22 pimaster homebridge[6300]:     at AirConAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:14:5)
Mar 17 12:54:22 pimaster homebridge[6300]:     at config.accessories.forEach (/usr/lib/node_modules/homebridge-broadlink-rm/platform.js:74:32)
Mar 17 12:54:22 pimaster homebridge[6300]:     at Array.forEach (native)
Mar 17 12:54:22 pimaster homebridge[6300]:     at BroadlinkRMPlatform.addAccessories (/usr/lib/node_modules/homebridge-broadlink-rm/platform.js:69:24)
Mar 17 12:54:22 pimaster homebridge[6300]:     at BroadlinkRMPlatform.accessories (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:27:10)
Mar 17 12:54:22 pimaster homebridge[6300]:     at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:364:20)
Mar 17 12:54:22 pimaster homebridge[6300]:     at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:308:16)
Mar 17 12:54:22 pimaster systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 12:54:22 pimaster systemd[1]: homebridge.service: Unit entered failed state.
Mar 17 12:54:22 pimaster systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 17 12:54:22 pimaster homebridge[6300]: [3/17/2018, 12:54:22 PM] [Broadlink RM] A/C Fan Accessory Ready
Mar 17 12:54:22 pimaster homebridge[6300]: [3/17/2018, 12:54:22 PM] [Broadlink RM] A/C Accessory Ready
Mar 17 12:54:22 pimaster homebridge[6300]: /usr/lib/node_modules/homebridge-broadlink-rm/node_modules/chai/lib/chai/assertion.js:141
Mar 17 12:54:22 pimaster homebridge[6300]:       throw new AssertionError(msg, {
Mar 17 12:54:22 pimaster homebridge[6300]:       ^
Mar 17 12:54:22 pimaster homebridge[6300]: AssertionError: [CONFIG ERROR] minTemperature (17) must be <= 10: expected 17 to be below 11
Mar 17 12:54:22 pimaster homebridge[6300]:     at AirConAccessory.setDefaults (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:95:12)
Mar 17 12:54:22 pimaster homebridge[6300]:     at AirConAccessory.HomebridgeAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:39:10)
Mar 17 12:54:22 pimaster homebridge[6300]:     at BroadlinkRMAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:17:5)
Mar 17 12:54:22 pimaster homebridge[6300]:     at AirConAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:14:5)
Mar 17 12:54:22 pimaster homebridge[6300]:     at config.accessories.forEach (/usr/lib/node_modules/homebridge-broadlink-rm/platform.js:74:32)
Mar 17 12:54:22 pimaster homebridge[6300]:     at Array.forEach (native)
Mar 17 12:54:22 pimaster homebridge[6300]:     at BroadlinkRMPlatform.addAccessories (/usr/lib/node_modules/homebridge-broadlink-rm/platform.js:69:24)
Mar 17 12:54:22 pimaster homebridge[6300]:     at BroadlinkRMPlatform.accessories (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:27:10)
Mar 17 12:54:22 pimaster homebridge[6300]:     at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:364:20)
Mar 17 12:54:22 pimaster homebridge[6300]:     at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:308:16)
Mar 17 12:54:22 pimaster systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 12:54:22 pimaster systemd[1]: homebridge.service: Unit entered failed state.
Mar 17 12:54:22 pimaster systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by lprhodes** [comment]
You should change `"minTemperature": 17` to `"minTemperature": 10`

**Comment by lprhodes** [comment]
There appears to be a bug with HomeKit that causes devices to show as Not Responding when it's higher than 10.

**Comment by tamasvicsotka** [comment]
Ok, I tried it because my AC has 17 celsius as the lowest temperature. Anyway in the description is the example for 14 celsius, probably it's a bit missleading. :)

**Comment by lprhodes** [comment]
Thanks, I've updated the README.

**Comment by sergiobaiao** [comment]
is this a homekit limitation? My A/C unit also doesn`t go below 18 celsius. It ranges from 18 to 30. How can i make it work that way?
