### ISSUE TITLE
During the day, at least 1 time homebridge crash

### ISSUE THREAD

**Issue by cpvbruno** [lprhodes/homebridge-broadlink-rm#309]
At least 1 time a day my holebridge crashes because of BroadlinkRM plugin, showing a message that could not found “[device]” or something like it.

Any way to put a try catch in this kind of stuff? Lol , also do you know how to run “forever” with homebridge, so it can be auto restarted after crash

**Comment by lprhodes** [comment]
When an RM device can’t be reached for whatever reason it then keeps checking to see when it’s available again. It really shouldn’t be crashing at all. Can you provide a log of the crash the next time it happens please?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cpvbruno** [comment]
Sure, but for now I did a workaround running "forever" npm lib to keep retarting my homebridge
