### ISSUE TITLE
Hello everybody need youre help please !! with an apple tv4 remote

### ISSUE THREAD

**Issue by Erez13** [lprhodes/homebridge-broadlink-rm#312]
hello =] 
someone can please, post the hex command  IR of the new apple remote?  im not find them in anyplace and i saw that someone here post something but its not what i need.
 i mean something that look like:

vol - 
0000 006D 0022 0002 0157 00AD 0015 0015 0015 0015 0015 0041 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0041 0015 0041 0015 0015 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 05FF 0157 0057 0015 0E5F

vol + 
0000 006D 0022 0002 0156 00AC 0015 0015 0015 0015 0015 0041 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0041 0015 0041 0015 0015 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0015 0015 0041 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0041 0015 0015 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 05FB 0156 0056 0015 0E57

and etc..... i have only both of them up here, i need the home button,  menu, siri, play and all the rest 
thanks everybody for your help god bless!! =]

**Comment by nicknicknickos** [comment]
The HEX codes are available in [issue 135](https://github.com/lprhodes/homebridge-broadlink-rm/issues/135)

**Comment by lprhodes** [comment]
I'll also be creating the [homebridge-apple-tv](https://github.com/lprhodes/homebridge-apple-tv) plugin over the next few days so you won't need this
