### ISSUE TITLE
UnhandledPromiseRejectionWarning (Window Cover)

### ISSUE THREAD

**Issue by Nastras** [lprhodes/homebridge-broadlink-rm#315]
Hello Luke,

as previously described I get this error message when pressing a window cover with the current version. My config has not changed for a while.

![37576866-d37b99b0-2b2e-11e8-8cd3-c15d7014de1d](https://user-images.githubusercontent.com/27686185/37585642-14d1b2d4-2b5a-11e8-85a5-cc8b5f2d305c.jpeg)

[config.txt](https://github.com/lprhodes/homebridge-broadlink-rm/files/1824264/config.txt)

**Comment by lprhodes** [comment]
I'm not seeing any issue when using your config.

The line numbers for the errors would suggest that it's not running the latest version though.

**Comment by lprhodes** [comment]
Try typing `cat /usr/lib/node_modules/homebridge-broadlink-rm/package.json` and seeing what the version of the plugin is in there.

**Comment by Nastras** [comment]
I have now changed to version 3.2.20.

The version below
cat /usr/lib/node_modules/homebridge-broadlink-rm/package.json
was the right one.

I'm currently testing it, it seems like the bug does not crop up anymore. I want to test it until tomorrow if everything is ok I will close the issue.

Thanks!

**Comment by lprhodes** [comment]
Closing - let me know if I need to re-open

**Comment by Nastras** [comment]
Sorry, I had a lot to do. I forgot to report again. Everything seems to work. You seemed right that he did not update a file. Thanks again.

**Comment by lprhodes** [comment]
Great :)
