### ISSUE TITLE
Curtains loading circle won’t go away

### ISSUE THREAD

**Issue by iandronowicz** [lprhodes/homebridge-broadlink-rm#318]
When an automation moves the curtains position the loading circle in the accessory wont stop.

If I move the curtains manually everything works fine: the loading circle appears for a while until the curtains stops and then disappears.

But I noticed that on my morning automation where all my curtains fully open the home app just stays with the loading circles forever.

**Comment by iandronowicz** [comment]
![9698f54a-d8ef-4735-ab5a-0012def30364](https://user-images.githubusercontent.com/250746/37650475-cc39388e-2c13-11e8-9293-8b9bc04cd5cf.png)

**Comment by iandronowicz** [comment]
As you can see in the picture the first curtain accessory doesn’t have the loading circle: that’s because I tap it once to start closing and again to open to make it disappear. That’s the only work around I have. If I don’t do that all curtain accessories will get stucked with the loading icon forever.

Seems like the plugin isn’t updating the front end stop command or something.

**Comment by lprhodes** [comment]
Looks like something's stalling somewhere - do accessories come back as Not Responding too?

Can you send your config please.

**Comment by iandronowicz** [comment]
No, the curtains keep responding and working but the loading circle won't go away until I move the curtain position.

Maybe this issue has something to do with the temp issue that was hanging homebridge... I'll try the latest version with the fix and see if it keeps happening.

**Comment by lprhodes** [comment]
@iandronowicz did you have any luck with the latest version?

**Comment by lprhodes** [comment]
Closing for now, I'll re-open if needed.
