### ISSUE TITLE
Mqtt service request

### ISSUE THREAD

**Issue by maragelis** [lprhodes/homebridge-broadlink-rm#32]
Well done and thanks a lot you my friend are a hero. One tiny request if possible. MQTT ? Please can we have the ability to send codes through MQTT. This can help us by integrating it into node-red flows. 
Thanks in advance on a job well done.

**Comment by lprhodes** [comment]
Asking each plugin developer one by one to add MQTT support isn't the solution for external integrations, we need something more globally supported by homebridge. This isn't something I'm looking to add sorry.

At the moment I use node-red to control homebridge using HTTP requests, enabled by adding the -I ("insecure") argument to homebridge.

**Comment by maragelis** [comment]
I don`t know i might be misunderstood. I was asking for a Node-red node to use not to integrate mqtt into the plugin.
