### ISSUE TITLE
Manually specify broadlink devices?

### ISSUE THREAD

**Issue by hackruu** [lprhodes/homebridge-broadlink-rm#321]
Hello. Broadlink devices are not always discovered on my network at startup.
Can i manually describe devices i have and not rely on auto-discovery?

**Comment by cubilon** [comment]
Use DHCP binding on your router, assing them IPs then use them on your json config

**Comment by hackruu** [comment]
that's not the issue, i'm using dnsmasq which is always assigns unique ip based on mac addr. it's not dhcp issue at all.

**Comment by cubilon** [comment]
hm, you say than while plugin is loaded, no broadlink device comes up

**Comment by hackruu** [comment]
3 of 4 times one or another my broadlink devices is not detected, i need to restart homebridge multiple times watching logs to catch moment when both devices are detected at startup.
i'm pinging these devices while this happening, no lost packets, so it's not a connectivity issue.

**Comment by lits101** [comment]
I'm getting this too - no devices are being detected at homebridge start

**Comment by lprhodes** [comment]
I didn't write the underlying broadlink discovery code (https://github.com/momodalo/broadlinkjs) but here's some extra info in case it's of any use in narrowing this down.

It looks like only IPv4 addresses are supported when discovering devices. Ensure UDP is permitted on the router and that no firewall rules are preventing UDP on on the device you're running homebridge on

Previously, only the first IPv4 external IP address was used to listen for UDP packets. In 3.3.0, all detected IP addresses are used.

Previously the plugin only discovered for the first 25 seconds after starting homebridge. In 3.3.0 it tries to discover every 2 seconds, indefinitely.

Hopefully my amends fixes this for your, otherwise there's not much more help I can offer sorry.

**Comment by hackruu** [comment]
```root@homekit:~# npm install -g homebridge-broadlink-rm
npm ERR! code ETARGET
npm ERR! notarget No matching version found for broadlinkjs-rm@^0.2.9
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'homebridge-broadlink-rm'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-22T11_35_17_846Z-debug.log```

**Comment by hackruu** [comment]
same for another dep:
```
root@homekit:~# npm install -g homebridge-broadlink-rm
npm ERR! code ETARGET
npm ERR! notarget No matching version found for homebridge-platform-helper@1.0.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'homebridge-broadlink-rm'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-22T11_45_30_313Z-debug.log
```

**Comment by lprhodes** [comment]
Sorry I forgot to publish the others to npm. They're up there now.

**Comment by hackruu** [comment]
looks like now it's detecting both devices at boot, tried 5 times in a row. amazing, thank you!

**Comment by lprhodes** [comment]
Awesome, that's great news!

**Comment by hackruu** [comment]
i'll reopen this issue shortly. so when auto-discovery is fixed, if i hypothetically could manually add ip address of device, then could i control remote devices, e.g. not in same broadcast network segment? for example, homebridge --> vpn --> broadlink? or is it possible only for local network because of using broadcasts for communication?

**Comment by lprhodes** [comment]
it's local only sorry

**Comment by lprhodes** [comment]
On top of the fixes mentioned previously there's a new method of adding devices manually to your config in case auto-discovery isn't working for whatever reason.

Check out the [docs](https://lprhodes.github.io/slate/#device-discovery) on it.

@hackruu this may allow you to specify a VPN'd IP address so long as port 80 forwarded.

**Comment by hackruu** [comment]
👍👍👍 Thank you! Now i'm more than happy.
