### ISSUE TITLE
How I can change operating mode

### ISSUE THREAD

**Issue by tw0jey** [lprhodes/homebridge-broadlink-rm#322]
Hello! How I can change operating mode cool to heat? I realized that this plugin only works on auto mode?

**Comment by lprhodes** [comment]
You can select heat or cool. Perhaps some further explanation would help.

**Comment by tw0jey** [comment]
I don`t undestand what HEX-code I can use. I have HEX for heat, Hex for cool and hex for automode..

**Comment by lprhodes** [comment]
Do you have hex codes for temperatures?

**Comment by tw0jey** [comment]
Yes, I Have codes to temperatures 16-30.

**Comment by lprhodes** [comment]
In that case setting the mode to cool will send the hex for the temperature specified in `defaultCoolTemperature` and the same for heat with`defaultHeatTemperature`
