### ISSUE TITLE
RM 3 Pro - Scan RF finds freq but never learns code - times out.

### ISSUE THREAD

**Issue by staticnz** [lprhodes/homebridge-broadlink-rm#324]
I have an RM 3 Pro, trying to use it to learn the codes for my Rollease Acmeda motorised blinds. I have no issue getting the Scan RF to find the frequency, but no luck actually learning any hex codes. 

Have included the logs below - any ideas?

`[2018-3-22 22:47:53] [Broadlink RM] Scan RF (scanning)`
`[2018-3-22 22:47:53] [Broadlink RM] [Hold down the button that sends the RF frequency]`
`[2018-3-22 22:47:59] [Broadlink RM] Scan RF (found frequency - 1 of 2)`
`[2018-3-22 22:47:59] [Broadlink RM] [Keep holding that button!]`
`[2018-3-22 22:48:00] [Broadlink RM] Scan RF (found frequency - 2 of 2)`
`[2018-3-22 22:48:00] [Broadlink RM] [Press the RF button multiple times with a pause between them]`
`[2018-3-22 22:48:02] [Broadlink RM] Scan RF (stopped)`
`[2018-3-22 22:48:03] [Broadlink RM] Learn Code (ready)`
`[2018-3-22 22:48:13] [Broadlink RM] Learn Code (stopped - 10s timeout)`
`[2018-3-22 22:48:13] [Broadlink RM] Learn Code (stopped)`

I have tried a few ways to get it to work:
- start with Scan RF, press and hold to get freq and then switch to Learn Code (times out)
- start with Scan RF, press and hold to get freq, turn off Scan RF and then switch to Learn Code (times out)
- just do Learn Code (times out)
- just do Scan RF, finds freq but times out when I try pressing the button with a pause in between

**Comment by staticnz** [comment]
@lprhodes great thank you, looking forward to what you find :)

**Comment by Laazarus** [comment]
I am having the same problem trying to learn a knightbridge IP66 5G. I can get the frequency but there is no way to get RMPRO to learn the button. I
