### ISSUE TITLE
Multiple HEX, very slow to send

### ISSUE THREAD

**Issue by afbenevides** [lprhodes/homebridge-broadlink-rm#327]
Hi I'm configuring led strips with RF controller that has 20 static colors pre-setted. To change colour we have to go through each color, the remote doesn't send a different hex code for each colour. But if we press demo and then color +, the color sequence is always the same and always begin from the same colour.

In order to control directly the colour I,m trying to use the multiple hex function that comes in very handful for that.

So here is my setup:
```

"name":"Light 1",
					"type":"light",
					"defaultBrightness": 70,
					"useLastKnownBrightness": false,
					"enableAutoOff": false,
					"onDuration": 10,
					"data":{
						"off":"Hex_for_off",
						"on":"Hex_for_on",
						"hue350": [
							{
								"data": "Hex_for _demo_mode",
								"pause": 0.1
							},
							{
								"data": "Hex_for_color_plus"
							}
						],
						"hue122": [
							{
								"data": "Hex_for _demo_mode",
								"pause": 0.1
							},
							{
								"data": "Hex_for_color_plus",
								"pause": 0.1
							},
							{
								"data": "Hex_for_color_plus"
							}
						]

```
The setup works, but there is about a 3 to 4 seconds delay beetween each Hex send. Also I can see on the Broadlink that the yellow light keeps on during these 3 to 4 seconds....

I also have a small video sample to show the speed issue if needed. If I send codes with the remote directly I can go much faster.

I did not see in your code where additional delay can occur, but I'm really not a specialist of Javascript... Also in there terminal, I see that the commands are printed instantly, but the broad link does not seem to go faster...

Do you have an idea?

It still works well, but is there something I could do to make it faster? I tried 0.3 and 0.1 delay, but without any noticeable difference.

Thanks again!

**Comment by lprhodes** [comment]
Odd - I'm not seeing the issue on this end, they're all going out immediately. What version are you running?

The default `pause` is 0.1 by the way so you don't need to specify it.

**Comment by afbenevides** [comment]
OK I will change pause, but I also tried with 0.3 and 1.0 and still the other delay os much bigger...

Version written is 3.3.5

**Comment by lprhodes** [comment]
Ok - update to the latest and see how that goes 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by afbenevides** [comment]
HI, I already did. I<m now in 3.4.2 and still have same issue. But when I follow in the console, the output timing corresponds to whatever I put in the pause value... It really looks like if the broad link can't process these faster...

Is there a kind of lock on each connection to the broadlink? and is there a delay in this lock?

**Comment by lprhodes** [comment]
No sorry it just gets sent and then it does what it likes.

You could potentially re-learn the codes.

Just to give some extra info you can add `"debug": true` to the accessory - it'll show you some lower level logs for the packets being sent to the device.

**Comment by afbenevides** [comment]
Says packet sent successfully...

My Broadlink is RM PRO
2ACDZRM3

![img_5553](https://user-images.githubusercontent.com/19934301/37841785-de7c74f4-2e96-11e8-9eca-783dd41d0975.JPG)

**Comment by afbenevides** [comment]
Also I have  2 modifications I would like to have integrated in your code that do not interfere with current functionality, but that would maybe help others.

1- in light accessory:
I couldn't find a way to get white colour with only hue without saturation, so i did a small logic so all saturation under 10 is considered to be white.

2-in window covering accessory:
I added possibility for people with 3 preprogrammed positions for their window covering.

How can I send you this very small modification so it gets in the normal releases? I did not even try to commit or branch, because I don't want to mess your things since I'm not very familiar, but if it is ok, I can try to make a branch and put my version in there for you to revise? It is already based on 3.4.2

I would love to continue to contribute to your great plugin on what I can! With this broadlink device and your plugin, the amount of possibility for home kit setup gets really powerful and for low budget!


Thanks

**Comment by Green-Kite** [comment]
> 1- in light accessory:
I couldn't find a way to get white colour with only hue without saturation, so i did a small logic so all saturation under 10 is considered to be white.

This would be great to be implemented in the official release.
I'm using a RGB LED Strip too and this is the only missing feature right now.


Thanks for your work on this plugin!

**Comment by lprhodes** [comment]
Hey @afbenevides, I try to be as generic as possible in the functionality that gets added to accessories - the solutions are pretty specific. If you could open up separate issues for them I'll take a look at how I can implement a more wide-ranging solution.
