### ISSUE TITLE
Color temperature for lights

### ISSUE THREAD

**Issue by GSanCap** [lprhodes/homebridge-broadlink-rm#328]
Hi, its possible to implement the color temperature in the light class accessory?

Thanks in advance!

**Comment by lprhodes** [comment]
There's no temperature option exactly.

Both the hue and saturation are set when you change either a Colour or a Temperature in the Home app.

So you can just use `hueX`.

**Comment by GSanCap** [comment]
Thanks for the quick response! if i use hueX parameter i will obtains this control?

https://i.redd.it/0k0ath5jr8dx.png

Thanks!

**Comment by lprhodes** [comment]
Yep

**Comment by roberkane212** [comment]
Has anyone used this? Is so can I get an example config?
