### ISSUE TITLE
We've discovered an unknown Broadlink device.

### ISSUE THREAD

**Issue by annahuae** [lprhodes/homebridge-broadlink-rm#330]
Hi, in fact i have mini3 which was working without any notices before update. Last update brought me that:

[2018-3-23 21:00:58] [Broadlink RM] 
[Important!] We've discovered an unknown Broadlink device.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "beb1" so that we can handle it correctly and prevent this message from appearing.

**Comment by lprhodes** [comment]
I've just released v3.4.4 with an improved message which should help you determine which device is causing the message to appear. If you could please update then provide additional information about the unknown device.

**Comment by annahuae** [comment]
Hi Luke

As I mentioned I have only brand new mini3:)

Best regards,
Natalia

Saturday, March 24, 2018, 3:06 AM +0400 from notifications@github.com  <notifications@github.com>:

**Comment by lprhodes** [comment]
If it's working as expected (other than the message) then that usually means there's another device which is using broadlink's hardware inside it (though it may be named something else)

**Comment by lprhodes** [comment]
Closing until further information about the device is provided.
