### ISSUE TITLE
[Important!] We've discovered an unknown Broadlink device.

### ISSUE THREAD

**Issue by samsonrosen** [lprhodes/homebridge-broadlink-rm#331]
Hi! I have a broadlink mini 3 and I am getting this error below! Everything appears to work fine though.

```
[Important!] We've discovered an unknown Broadlink device.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4620" so that we can handle it correctly and prevent this message from appearing.
```

**Comment by lprhodes** [comment]
I've just released v3.4.4 with an improved message which should help you determine which device is causing the message to appear.

Can you please update then provide additional information about the unknown device.

**Comment by annahuae** [comment]
Same here, the only difference device code is “beb1”

**Comment by lprhodes** [comment]
Closing until further information about the device is provided.
