### ISSUE TITLE
host with macAddress

### ISSUE THREAD

**Issue by maobolgi** [lprhodes/homebridge-broadlink-rm#332]
Hi,

I am trying to use the macAddress to filter the different RM3 mini I have deployed. Although it works fine with the IP, it does not with the mac. Am I missing something?

Aria-calda-genitori setSwitchState: false                                                    
[2018-3-24 11:10:57] [Broadlink RM] [ERROR] Aria-calda-genitori sendData (no device found at 78:0F:77:00:0F:6D)

{
          "name":"Aria-calda-genitori",
          "type":"switch",
          "host":"78:0F:77:00:0F:6D",
          "data":{
            "on":"26...",
            "off":"26..."
          }
        },

Thanks!

**Comment by lprhodes** [comment]
Some RM devices report their Mac address in a different order to others which could be the issue.

Check the address reported in the log when it says "Discovered Broadlink RM device at..."

**Comment by maobolgi** [comment]
Great, thanks! It was like that indeed. Please note that the last added device works only if the host value is omitted (I already noticed it with the default IR Learn accessory).

**Comment by lprhodes** [comment]
Interesting, can you provide some more information on that please?

**Comment by maobolgi** [comment]
Apologies, I now found the issue. I had an old problem with a wrong ip and got confused. The described behaviour does not occur (there simply is a default RM3 if you omit the host, but it is not necessarily the last one). Thanks again.

**Comment by lprhodes** [comment]
Awesome news - I'm glad everything's working :)
