### ISSUE TITLE
different temperature sources for A/C

### ISSUE THREAD

**Issue by cubilon** [lprhodes/homebridge-broadlink-rm#334]
should be really useful integrating MQTT on the plugin.
for example, I've a MQTT sensor that gives temperature in json format, a thing like that:

{"Time":"2018-03-24T17:24:47","AM2301":{"Temperature":18.5,"Humidity":74.5},"TempUnit":"C"}

so, will be useful having a MQTT topic variable to be configured, a different data source as "temperatureFilePath" does with data on file.

**Comment by lprhodes** [comment]
At the moment I’m not looking to support anything extra here sorry. People should be able to create their own scripts that update the file. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by phenix13** [comment]
https://github.com/Zzm317/homebridge-broadlink-rm#air-conditioner-pro 
It will help you

**Comment by cubilon** [comment]
thanks @phenix13, I'm using it. currently  I'm using "pseudoDeviceTemperature" field becouse I've no other way to indicate HomeKit the real temperature in the room, even if I've a sensor in it. that's why I suggested more temp sources to be included on the plugin (MQTT could be one of them). :)

**Comment by lprhodes** [comment]
@cubilon mqtt temperature support has been added in 3.5.3.

**Comment by cubilon** [comment]
you someking of hero!

**Comment by cubilon** [comment]
hm seems not working.
from logs:

```
[2018-3-27 19:26:42] [Broadlink RM] Mitsubishi onTemperature ({"Time":"2018-03-27T18:26:32","AM2301":{"Temperature":18.9,"Humidity":55.7},"TempUnit":"C"}0)

/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/chai/lib/chai/core/assertions.js:1354
      throw new AssertionError(errorMessage, undefined, ssfi);
      ^
AssertionError: [CONFIG ERROR] maxTemperature (31) must be more than the reported temperature ({"Time":"2018-03-27T18:26:32","AM2301":{"Temperature":18.9,"Humidity":55.7},"TempUnit":"C"}0): expected '{"Time":"2018-03-27T18:26:32","AM2301":{"Temperature":18.9,"Humidity":55.7},"TempUnit":"C"}0' to be a number or a date
```

**Comment by lprhodes** [comment]
Hey @cubilon I've been unable to reproduce that issue, there may be logs (when "debug": true) is set that include the phrase `onMQTTMessage`. Can you send them if so please.

**Comment by lprhodes** [comment]
I've released v3.5.4 which will log some extra debug information.

**Comment by lprhodes** [comment]
v3.5.5 should fix the issue.

**Comment by cubilon** [comment]
morning @lprhodes, now the error has changed:

```
[2018-3-28 07:50:12] [Broadlink RM] [DEBUG] Mitsubishi onMQTTMessage (raw value: {"Time":"2018-03-28T06:50:11","AM2301":{"Temperature":18.8,"Humidity":64.8},"TempUnit":"C"})
/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:602
    if (debug) log(`\x1b[33m[DEBUG]\x1b[0m ${name} onMQTTMessage (raw value 2: ${temperature.trim()})`);
                                                                                             ^

TypeError: temperature.trim is not a function
    at AirConAccessory.onMQTTMessage (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:602:94)
    at MqttClient.mqttClient.on (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:343:12)
    at emitThree (events.js:136:13)
    at MqttClient.emit (events.js:217:7)

```

**Comment by lprhodes** [comment]
Turning debug to false should sort this for now 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cubilon** [comment]
right, with debug off it's working fine

**Comment by cubilon** [comment]
may I suggest one thing? do a "round" on temperature value. currently, if you send e.g. 18.9 to homekit, he return on screen "18". "19" may be more correct..
