### ISSUE TITLE
[info requested] Getting HEX from manually entered RF

### ISSUE THREAD

**Issue by matrosovas** [lprhodes/homebridge-broadlink-rm#335]
Hey, 
Sorry if this has already been covered somewhere but I have a question. I am planning to have all my house light switches changed to livolo and since I want to have controll over all of them I would either need to have a bunch of remotes or use this https://dimagoltsman.github.io/Random-Broadlink-RM-Code-Generator/# my question would be, how would one get the HEX code, would it be just as simple as converting that base64 to hex?

**Comment by lprhodes** [comment]
Could you use a single remote to pair with each switch in turn and learn the hex code using this plugin from the remote?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by matrosovas** [comment]
Would that work? I was under the assumption that the remote has it’s ID and that’s why it would just always send the same code to the switch.

Regards,
Arminas

**Comment by lprhodes** [comment]
If you don’t have the remotes already and you were to get one then you’d need to pair it somehow?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by matrosovas** [comment]
If I’m not mistaking I would not need remotes. When switch is in pairing mode I would trigger broadlink to RF that code and switch should link itself to that. This is the reason why I would then need 15 remotes for all my switches because they all have unique IDs and their signal is based on that. If I would try to pair same remote to multiple switches I would then end up controlling multiple switches with one button, thus loosing control over individual switch.
Do I understand correctly that HEX is basically the same as that BASE64 code that gets generated, it just defines the code that broadlink will send through RF?

Regards,
Arminas

**Comment by lprhodes** [comment]
No it’s something specific to broadlink - you’ll need to learn the hex with the Scan RF switch 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LukeWJ** [comment]
How is it going on about the problem?
