### ISSUE TITLE
Homebridge working but Broadlink doesn't send anything

### ISSUE THREAD

**Issue by doodoovane** [lprhodes/homebridge-broadlink-rm#342]
Hi there,

I've just received my Broadlink TC2 with 2 gangs and try to make it works with homebridge (work well with the e-control app).

Firstly, I've followed the instructions (here: [Link](https://narongdej.sarnsuwan.com/blog/2017/02/19/Control-Broadlink-TC2-through-python/)) to get the hex codes to control it.

Now that I have those, I've putted them in my config.json as switches.
The toggles are well added to my homekit menu, but when I trigger one of those nothing happens (no orange LED blinking).

Here are the hex codes i've got: (if someone can test it, to see if the broadlink blink)
e90a4200df0909160916160916091609091609161609091609161609160916090916091609161609160916091609091616090916091616091609160909160916160916091609

e90a4200df0909160916160916090916091616091609160916090916091609160916160916090916160909160916160916091609160916090916091609160916091609161609

Is there something I missed about? I've got RF and IR switches that already work. I've done nothing different this time but can't get it works.

Thank you for your help

PS: I use a Broadlink RM3 Pro Plus (279d)

**Comment by doodoovane** [comment]
I've just tried using the hex codes found with the tutorial (using android) and I managed to make it work by duplicating it 10 times. The only problem still not resolved is now that commands are more likely to be missed with homebridge than with the e-control app.

If someone knows the probleme

**Comment by doodoovane** [comment]
Problem solved with the repeat fonction, sending the code 4 times with 0.3delay.
Hope this will help someone

**Comment by Hohnjo** [comment]
Thanks for the help doodoovane. By any chance, could you massage my neck ? it really hurts :/
