### ISSUE TITLE
Syntax for config.json

### ISSUE THREAD

**Issue by ppappalardo** [lprhodes/homebridge-broadlink-rm#343]
Hello, I have a vizio television.  I have found the information to directly go to the HDMI-2 setting using an IR code.  It is this...

HDMI 2 = 82
Device Code: 4.251 Function: 130
0000 006D 0022 0002 0157 00AC 0015 0016 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0689 0157 0056 0015 0E94

What would be the proper syntax for the config.json file to have a single homekit button.  I have already gotten the power on and power off going and I have configured other things like the RF power for my ceiling fan.  I have simply have not figured out how to do it for this discreet input for the IR signal to the TV. 

PS: if this is the wrong forum for this type of question, please let me know and I will correct.

**Comment by lprhodes** [comment]
Hey @ppappalardo, while some IR codes work just by pasting them in, ideally you'd perform a Learn  and get the code that way.

**Comment by jsit** [comment]
@ppappalardo What config did you use for on/off?
