### ISSUE TITLE
High CPU usage(with overheating) with 4 pingers enabled

### ISSUE THREAD

**Issue by hackruu** [lprhodes/homebridge-broadlink-rm#346]
Hello
Today i've set up pingIPAddress for my 4 bulbs and now i getting my CPU(intel i5 750) overheat. It even get 102C, which is way too much. When i disable pinger load average drops to nearly zero and CPU is fine. Any thoughts on reducing cpu usage? (increasing ping interval is least preferred way).
Also i mentioned in another issue on every ping i get log entries in syslog, i wonder if broadlink plugin tries to update accessory state in homebridge on every ping too...

also maybe use https://github.com/stephenwvickers/node-net-ping or any other library that provides ping instead of parallel forking for execing external binary?

**Comment by hackruu** [comment]
i think you're running ping with -w2 parameter while pinging every 1s which makes no sense at all. but that's not root of problem, it's just part of it. i think stop exec-forking will fix things.

**Comment by hackruu** [comment]
okay, i figured out, here is what's going on:
because of -w2 while my FOUR accessories aren't online i got EIGHT ping processes consuming 100% cpu in kernelspace. sadly, this is the point. you must switch node library or use "timeout" variable for existing library.

i've wrote fping wrapper for ping for doing things faster, but it is a dirty hack.

**Comment by lprhodes** [comment]
Hey, I've changed modules and added some performance tweaks in 3.6.11
