### ISSUE TITLE
Limitation with multiple broadlinks?

### ISSUE THREAD

**Issue by tompijls** [lprhodes/homebridge-broadlink-rm#347]
Hi,

I have 2 broadlinks and try to achieve below:

I use 2 elgato eve's power switches, 1 on my tv and 1 on my surround system.
My surround system is in a closet, so I have 2 broadlinks, 1 in the closet, 1 in front of tv.

I'm now trying to get a scene setup in homekit, to achieve the following:

Switch Eve's to on (through Homekit, not your plugin)

broadlink 1:
Pause 5 seconds
Switch on TV
Pause 2 Seconds
Change Channel to correct 1

broadlink 2:
Pause 5 seconds
Select correct input for Audio

I'm using your syntax for Multiple Hex Codes, however as host is not defined per data item to be send, thats not possible. Not specifying hosts does not work either, as only one broadlink will emit in that case.

In my case, I guess being able to specify the host as such would overcome the problem? (Or broadcast to all broadlinks when no host specified, rather than just 1)

{ ...
"data": {
    "on": [
      {
        "host": "192.168.1.3",
        "data": "ON_HEX_CODE_1",
        "pause": 0.3
      },
      {
        "host": "192.168.1.2",
        "data": "ON_HEX_CODE_2",
        "pause": 0.3
      }
    ],
    "off": "OFF_HEX"
  }
  ...
}

Tom

**Comment by lprhodes** [comment]
I would just create two switches for the scene to turn on 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by matijus91** [comment]
I’ve done something like this to. I end up with een switch for your eve. A switch for tv and channel. One for you audio.

You can give them the pauses as you want.

Then I make an automatisation in HomeKit. When the Eve is activated it automatically activate the Broadlink switches. So you just have to activate only you eve switch.

Hope this will help you

**Comment by tompijls** [comment]
Cool,

Can you share the automation you made?

Cheers

Tom

Sent from Outlook<https://aka.ms/sdimjr> for iOS
________________________________

**Comment by matijus91** [comment]
I’m at work right now. If I see a change I will share it 😉
