### ISSUE TITLE
Add an option to turn on automatically after electricity shutdown

### ISSUE THREAD

**Issue by refaelsommer** [lprhodes/homebridge-broadlink-rm#349]
I would really like to have an option in the config to enable autoSendHex to all switches that where on before homebridge was shutdown and restarted so that when there is an electricity shutdown and then electricity restored the Raspberry Pi will start and homebridge starts automatically (already have done that) then all switches hex that where on will be sent.

Please on the next version 🙏🏻

Thanks!
Refael.S

**Comment by cubilon** [comment]
"resendHexAfterReload" option isn't enough?

**Comment by refaelsommer** [comment]
Ohh great! Thanks that does the job!
-- 
בברכה,
רפאל זומר
0526222068
