### ISSUE TITLE
Problems with this plugin on reboot the Pi

### ISSUE THREAD

**Issue by GerSant** [lprhodes/homebridge-broadlink-rm#352]
In some cases when reboot the Raspberry Pi, prior to stop the homebridge-broadlink instance, using the service command, the Homebridge with this plugin associated don´t respond any more, usign DEBUG=* i see a lot of auth pair tries

`  EventedHTTPServer [192.168.0.199] New connection from client +54s
  EventedHTTPServer [192.168.0.199] HTTP server listening on port 41847 +1ms
  EventedHTTPServer [192.168.0.199] HTTP request: /pair-verify +5ms
  HAPServer [ED:32:2D:E3:CE:36] HAP Request: POST /pair-verify +0ms
  EventedHTTPServer [192.168.0.199] HTTP Response is finished +3ms
  EventedHTTPServer [192.168.0.199] Client connection closed +16ms
  EventedHTTPServer [192.168.0.199] HTTP connection was closed +1ms
  EventedHTTPServer [192.168.0.199] HTTP server was closed +1ms '

I delete the persist folder, and accessory folder...nothing happens, the instance remains unresponsive

Thanks

**Comment by lprhodes** [comment]
Hi @GerSant I'm closing this as it's an old issue, please re-open if you're still having issues.
