### ISSUE TITLE
Important! message display

### ISSUE THREAD

**Issue by SamuiSmartHome** [lprhodes/homebridge-broadlink-rm#354]
[Important!] We've discovered an unknown Broadlink device.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "2722" so that we can handle it correctly and prevent this message from appearing.

**Comment by lprhodes** [comment]
Hey @SamuiSmartHome do you know what device it might have found? It's likely a Broadlink device  that isn't an RM Pro/Mini, I can add it to an "Unsupported" list in order to prevent the error from showing. Please re-open if you'd like me to add it.
