### ISSUE TITLE
HONYA outlet device code 2780

### ISSUE THREAD

**Issue by qiqiji** [lprhodes/homebridge-broadlink-rm#356]
I have a HONYA outlet OEM by broadlink

it can be use in ha, just set type to spmini2
`switch 2:
  - platform: broadlink
    host: '10.0.1.35'
    mac: 'B4:43:0D:BC:xx:xx'
    type: 'spmini2'
    friendly_name: 'HONYAR'`

when I use hb with homebridge-broadlink-sp there is a log says found a unknown device with code 2780 ( I'm not sure log came out from homebridge-broadlink-sp or homebridge-broadlink-rm)

[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "2780". The device is connected to your network with the IP address "10.0.1.35".

**Comment by cubilon** [comment]
have you added "debug": true in each accessory on homebridge-broadlink-rm to get - eventually - more info?
