### ISSUE TITLE
my Homebridge can't run with this plugin (with RM 3 Mini)

### ISSUE THREAD

**Issue by wadjj** [lprhodes/homebridge-broadlink-rm#36]
I had homebridge set up for another two plug-ins (aqara and yeelight) and they worked fine, but I can't seem to get homebridge-broadlink-rm to run properly under my clean setup.

I only installed homebridge,yeelight plugin, aqara plugin and broadlink-rm plugin on my raspberry pi (on latest raspian jesse), and I have git installed.

Could the dev or others please help me with this? Thanks a lot in advance.

My config is as follows:

 
```
{
    "bridge":
    {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:DD",
        "port": 51827,
        "pin": "XXX-XX-XXX"
    },

    "platforms":
[
    {
        "platform": "AqaraPlatform",
        "sid": ["286c0785e35e"],
        "password": ["1736D1890E264BFE"]
    },
    {
        "platform" : "yeelight",
        "name" : "yeelight"
    },
    {
        "platform":"BroadlinkRM",
        "name":"Broadlink RM"
    }
]
}
```

and when I run `homebridge`,it returns:

> [4/5/2017, 5:02:53 PM] Loaded plugin: homebridge-aqara
> [4/5/2017, 5:02:53 PM] Registering platform 'homebridge-aqara.AqaraPlatform'
> [4/5/2017, 5:02:53 PM] ---
> [4/5/2017, 5:02:53 PM] Loaded plugin: homebridge-broadlink-rm
> [4/5/2017, 5:02:53 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
> [4/5/2017, 5:02:53 PM] ---
> [4/5/2017, 5:02:53 PM] Loaded plugin: homebridge-yeelight
> [4/5/2017, 5:02:53 PM] Registering platform 'homebridge-yeelight.yeelight'
> [4/5/2017, 5:02:53 PM] ---
> [4/5/2017, 5:02:53 PM] Loaded config.json with 0 accessories and 3 platforms.
> [4/5/2017, 5:02:53 PM] ---
> [4/5/2017, 5:02:53 PM] Loading 3 platforms...
> [4/5/2017, 5:02:53 PM] Initializing AqaraPlatform platform...
> [4/5/2017, 5:02:53 PM] [yeelight] Initializing yeelight platform...
> [4/5/2017, 5:02:53 PM] [yeelight] YeePlatform Init
> [4/5/2017, 5:02:53 PM] [Broadlink RM] Initializing BroadlinkRM platform...
> [4/5/2017, 5:02:53 PM] [Broadlink RM] No accessories have been added to the Broadlink RM config. Only the Learn IR accessory will be accessible on HomeKit.
> [4/5/2017, 5:02:53 PM] [Broadlink RM] Initializing platform accessory 'Learn IR'...
> Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
> 
>     ┌────────────┐
>     │ XXX-XX-XXX │
>     └────────────┘
> 
> [4/5/2017, 5:02:53 PM] [yeelight] DidFinishLaunching
> [4/5/2017, 5:02:53 PM] Homebridge is running on port 51827.
> add to multicast group
> listen on 0.0.0.0
> no did or loc found!
> [4/5/2017, 5:02:53 PM] [yeelight] cached accessory: 0x0000000002f8f81a
> already in device list!
> /usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:336
>     this.prototype.set_power_mask = function(sid_mask, state){
>                                   ^
> 
> TypeError: Cannot set property 'set_power_mask' of undefined
>     at device.mp1 (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:336:35)
>     at module.exports.Broadlink.genDevice (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:94:13)
>     at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:181:29)
>     at emitTwo (events.js:106:13)
>     at Socket.emit (events.js:194:7)
>     at UDP.onMessage [as onmessage] (dgram.js:545:8)

**Comment by lprhodes** [comment]
It's definitely a Broadlink RM? Do you have any other Broadlink devices on the network?

It's detecting something similar to a Broadlink MP1 (in how it identifies itself) but the detected device doesn't comply to normal MP1 calls.

**Comment by lprhodes** [comment]
It'd be still useful to get the above information but I've just published 1.1.2 - update to this then run the following:

`npm i broadlinkjs@"git+https://github.com/lprhodes/broadlinkjs.git" -g`

That will force the MP1 type device to be ignored by the plugin (which doesn't support it anyway)

**Comment by wadjj** [comment]
Yes, it is a RM 3 mini("blackbean"). 

But you are probably right, I belive i have some two 3rd-party smart appliances (a plug and a power strip) that use Broadlink chips or are Broadlink OEM. At least one of them,as I recall, is identified as something like "BroadlinkOEM" by my router.

Since Broadlink is a popular "smart chip/solution" provider or OEM for traditional appliances company in China, this is something that might happen to others down the road.

**Comment by lprhodes** [comment]
Interesting, good to know! How'd you go with it after running the command above?

**Comment by wadjj** [comment]
After update it works normally, I now have an "IR learner" as expected. Thanks for the update!

BTW, after checking, I have a Honyar wifi power strip that is a straight up OEM of Broadlink MP1 (even the app is a rebranded one,based on screenshots on MP1 product description page.)
