### ISSUE TITLE
No icon in Home to scan HEX after install

### ISSUE THREAD

**Issue by mattangelofdeth** [lprhodes/homebridge-broadlink-rm#367]
Hi all,
Any help would be greatly appreciated. I don't appear to be able to be able to get anywhere past the initial installation. No icons appear in home. I've also tried adding the host variable, with no joy. Currently, I run homebridge as a autostart service.

Config is as follows:

  "platforms" : [
    {
      "hideLearnButton" : "false",
      "hideScanFrequencyButton" : "false",
      "hideWelcomeMessage" : "false",
      "name" : "Broadlink RM",
      "platform" : "BroadlinkRM",
      "homebridgeDirectory": "/var/homebridge/"
    },

Any help would be greatly appreciated as Im keen to get this sucker online to control the iRobot :)
Apologies if I havent posted all the correct info. I can find my way around homebridge, but Im far from a knowledgable user. Linux isnt quite my first language!

**Comment by cubilon** [comment]
you need to add leaning accessory too:

```
"accessories":[
        {
          "name":"Auto-off Switch",
          "type":"switch",
          "enableAutoOff": true,
          "onDuration": 5,
          "data":{
            "on":"2600500000012...",
            "off":"2600500000012..."
          }
        }
```

**Comment by mattangelofdeth** [comment]
Thanks @cubilon 
I will try again this weekend and report back.
I really appreciate your response
