### ISSUE TITLE
Dual Fans

### ISSUE THREAD

**Issue by mortocks** [lprhodes/homebridge-broadlink-rm#368]
Fan accessory appears twice 

homebridge v 0.4.38
homebridge-broadlink-rm v 2.5.16

![img_e4d1aec48854-1](https://user-images.githubusercontent.com/314196/39411816-b3e25bf6-4c54-11e8-862c-21a5f574b30b.jpeg)

```
config.json
...
                {
                        "platform": "BroadlinkRM",
                        "name": "Broadlink RM",
                        "hideScanFrequencyButton": true,
                        "hideLearnButton": true,
                        "accessories": [{
                                "name": "Dyson Fan",
                                "type": "fan",
                                "data": {
                                        "on": "2600.....",
                                        "off": "2602.....",
                                        "swingToggle": "2600.....",
                                        "fanSpeed90": "2600.....",
                                        "fanSpeed10": "2600....."
                                }
                        }]
                }
...
```

**Comment by cubilon** [comment]
very strange.
try cleaning homebridge cachedAccessory

**Comment by mortocks** [comment]
Thanks, I’ve tried that. 

Dumb question but I assume that the plugin dosen’t also reference the setting stores in the e-control app correct?

**Comment by cubilon** [comment]
I don’t think so!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mortocks** [comment]
It is strange - one of the fans (the correct one) includes all the oscillation settings in the details section. The "Ghost" fan on is just an on off switch. Very strange

**Comment by cubilon** [comment]
try cleaning cache, removing bridge from Home, changing Homebridge MAC address, then re-add it to Home. I would try something like that

**Comment by wailuen** [comment]
I have the same problem. For me, both fan icons are fully functional.

**Comment by lprhodes** [comment]
Please re-open if you're still seeing these issues.
