### ISSUE TITLE
Config schema refractor

### ISSUE THREAD

**Issue by duyleekun** [lprhodes/homebridge-broadlink-rm#37]
There are two thing should be done. 
- The data should be more flexible (currently, we're very opinionated with the type of remote user have with the accessory)
- We should implement some attribute naming convention based on the `HAP-NodeJS` lib.

For Boolean characteristic like `Characteristic.On`, sometimes we can do config like:
```
{ "on": "xxx", "off": "yyy"
```
But for other Boolean characteristic like `Characteristic.SwingMode`, we do the toggle style like:
```
{ "swingToggle: "xxx" }}}
```
It feels awkward because we've assumed the style of the remote user will have in the config (which we shouldn't do). 

For the naming convention, it's quite a tradeoff thing between config readability and consistent with the `HAP-NodeJS`

I hopes after this issue, we can solve above internal problems so the plugin can move faster during development.

**Comment by lprhodes** [comment]
Any other examples other than the swing toggle?

**Comment by lprhodes** [comment]
Happy for you to provide a tweaked config-sample that we can review

**Comment by lprhodes** [comment]
In terms of tradeoff - I side with readability given how many people are using this with no real programming knowledge and aren't used to reading JSON files and remembering to add commas or adding extra ones by accident.

Something like the attached feels like a better representation of how the config is used but looking from a newbie's prospective I think I'd not go near it.

[config-sample.txt](https://github.com/lprhodes/homebridge-broadlink-rm/files/901735/config-sample.txt)

**Comment by duyleekun** [comment]
Noted :D Current way is more user friendly :) What do you think about #39 schema? Is it too complex?

**Comment by lprhodes** [comment]
I don't see how moving to "hex" would fit in with the other accessories - need to look at all accessories by tweaking the conf-sample to something consistent.

**Comment by duyleekun** [comment]
It's not moving to `hex`, the bare string still supported. It doesn't break any old thing. Just a little teak to make the normal `switch` better.
There will be 3 syntax for hex:

- Bare string
- Dictionary `{hex: "", delayAfter: 3, repeat: 3}`
- Array of 2 above

**Comment by lprhodes** [comment]
I'd rather keep them within the different types as they are now if I can. It makes it easier to comprehend and separate the documentation. Is there still something you can't achieve with the addition of disableAutoOff?

**Comment by lprhodes** [comment]
I agree that there's a lot of utility to a completely configurable switch like you've proposed but I'd like to keep it inside its own accessory (with no amends to sendData).

I've just pushed a "switch-multi-repeat" to master (though I've not pushed it to npm yet) and updated the sample config - I reckon you'll want to take it further so let's make amends to that to get it to where you want?
