### ISSUE TITLE
broadlink tc2 switch 

### ISSUE THREAD

**Issue by ianchan0817** [lprhodes/homebridge-broadlink-rm#372]
I am using broadlink rm3 pro and with TC2 gang 1 switch. However, it requires me to use their app e-control. I have tried in many different ways, 

like this post
https://narongdej.sarnsuwan.com/blog/2017/02/19/Control-Broadlink-TC2-through-python/

trigger by phthon, and even get the codes like below 

`{
repeat: 0,
order: 0,
sendUrl: "http://10.0.1.16:9876/send?deviceMac=780f7700a8c4&codeId=5",
displayName: "TC2 • Button 1 On",
code: "e9144600df090916160909161609160916091609160916091609091609161609091616091609160916090916160916090916091609160916091609161609091616091609160909000148",
learnedByMac: "780f7700a8c4",
remoteName: "TC2",
codeLength: 148,
id: "5",
name: "1路",
index: 0,
remoteType: 14,
type: 0,
delay: 0
},`

But in fact, i wanna trigger it by homekit, ios app. So I need to start it from homebridge. 
But when I used the `code`, encode to `hex` or other format. Then the homebridge crashed. 
Coz it the hex value is so different from others. 
Other value normal just is 
`2xxxxx.....` but it is `6xxxx....`
Does anyone help this or try it successfully using homebridge with homekit in ios? Thanks

**Comment by lprhodes** [comment]
Hey @ianchan0817 you need to learn using the buttons provided by this plugin in HomeKit.
