### ISSUE TITLE
RM Pro Config

### ISSUE THREAD

**Issue by vijayg78** [lprhodes/homebridge-broadlink-rm#376]
Hi,
I have a RM Pro device and have added few remotes using mobile application. 
Now i plan to use homebridge and this library to control them via raspberry pi. 

My questions are
1) How to set the initial config file for this? How can i get the list of devices already existing on RM pro?
2) Is there a utility that converts or creates this config file that i can use?
3) If the hobebridge library can search and find out RMPRO in network and add these devices automatically it would be fantastic.

Let me know if there any possibility.
Regards, Vijay

**Comment by lprhodes** [comment]
Hey, there's no way to do this automatically at the moment, you'll need to use the learn buttons provided in the Home app by the plugin
