### ISSUE TITLE
Log issue in convertProntoCode.js

### ISSUE THREAD

**Issue by sungokay** [lprhodes/homebridge-broadlink-rm#380]
Dear,

If I had used an Pronto HEX code for a IR code without a space for a . There was a problem like a below error message.
Maybe, The log hadn't used in convertProntoCode.js.

- Homebrige's log
May 27 22:06:14 raspberrypi homebridge[31982]: (node:31982) UnhandledPromiseRejectionWarning: TypeError: log is not a function
May 27 22:06:14 raspberrypi homebridge[31982]:     at prontoToLIRC (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/convertProntoCode.js:10:5)
May 27 22:06:14 raspberrypi homebridge[31982]:     at convertProntoToBroadlink (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/convertProntoCode.js:68:22)
May 27 22:06:14 raspberrypi homebridge[31982]:     at module.exports (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/sendData.js:12:15)
May 27 22:06:14 raspberrypi homebridge[31982]:     at SwitchAccessory.performSend (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:45:7)
May 27 22:06:14 raspberrypi homebridge[31982]:     at SwitchAccessory.setSwitchState (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:90:29)
May 27 22:06:14 raspberrypi homebridge[31982]:     at SwitchAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:139:10)
May 27 22:06:14 raspberrypi homebridge[31982]:     at emitMany (events.js:147:13)
May 27 22:06:14 raspberrypi homebridge[31982]:     at Characteristic.On.emit (events.js:224:7)
May 27 22:06:14 raspberrypi homebridge[31982]:     at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
May 27 22:06:14 raspberrypi homebridge[31982]:     at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
May 27 22:06:14 raspberrypi homebridge[31982]:     at Array.forEach (<anonymous>:null:null)
May 27 22:06:14 raspberrypi homebridge[31982]:     at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
May 27 22:06:14 raspberrypi homebridge[31982]:     at emitMany (events.js:147:13)
May 27 22:06:14 raspberrypi homebridge[31982]:     at HAPServer.emit (events.js:224:7)
May 27 22:06:14 raspberrypi homebridge[31982]:     at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
May 27 22:06:14 raspberrypi homebridge[31982]:     at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
May 27 22:06:14 raspberrypi homebridge[31982]:     at emitNone (events.js:106:13)
May 27 22:06:14 raspberrypi homebridge[31982]:     at IncomingMessage.emit (events.js:208:7)
May 27 22:06:14 raspberrypi homebridge[31982]:     at endReadableNT (_stream_readable.js:1064:12)
May 27 22:06:14 raspberrypi homebridge[31982]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
May 27 22:06:14 raspberrypi homebridge[31982]:     at process._tickCallback (internal/process/next_tick.js:180:9)
May 27 22:06:14 raspberrypi homebridge[31982]: (node:31982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
May 27 22:06:14 raspberrypi homebridge[31982]: (node:31982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by chrjs** [comment]
Same for me. Code is:
0000007000000024000F000B0006000B000600170006000B0006001D000600170006000B0006000B0006000B0006000B0006001700060011000600170006000B0006000B0006001D0006000B00060D0F000F000B0006000B000600170006000B0006001D000600170006000B0006000B0006000B0006000B0006001700060011000600170006000B0006000B0006001D0006000B00060CEA

**Comment by cubilon** [comment]
>Same for me. Code is: ...

@chrjsthis is not a valid HEX code to me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chrjs** [comment]
@cubilon, you're right is not correct. I figured out I need to enter the pronto code by putting a space after each 4 digits block. Doing this, the system seems work properly and the code is accepted. Anyhow seems there is still the bug related to the missing log() method declaration in case the code is not properly formatted.

**Comment by sungokay** [comment]
I think that log() had been missed and have to add it to a below line.

hexData = convertProntoCode(hexData) -> hexData = convertProntoCode(hexData, log)

https://github.com/lprhodes/homebridge-broadlink-rm/blob/3939cf5c606a322897bd57a8b2d00d1efbfaa96f/helpers/sendData.js#L12

**Comment by cubilon** [comment]
try this converted code:

260066006a350d0d0d0d0d270d0d0d270d0d0d0d0d0d0d270d270d0d0d0d0d0d0d270d270d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d270d270d0d0d0d0d0d0d0d0d270d0d0d270d270d0d0d0d0d0d0d0d0d270d0d0d0d0d0d0d270d0d0d0d0d0d0d0d0d0005810d05
