### ISSUE TITLE
Auto/Heat/Cool Buttons not working for Air Conditioner

### ISSUE THREAD

**Issue by hpascual** [lprhodes/homebridge-broadlink-rm#381]
Hi, in a previous version you allow to configure the parameters "auto", "cool" and "heat" in an air-conditioner, but not this option seems to be gone, and although I configured them with RF code I need on each command, it does not work at all. Please let me know if you changed something in there, or where could be my error. Here is how I am using it:
                        
                        "name":"Aire Nuestro",
                        "type":"air-conditioner",
                        "host":"10.0.0.210",
                        "data":{
                                "off":"2600ca0092901236121212361236111311131136$
                                "cool":"2600ca009091133512121236123611131113123$
                                "auto":"2600ca009190133512121236123612121212123$
                                "temperature18":{
                                        "pseudo-mode":"cool",
                                        "data":"2600ca0091901236121212361236111$
                                        },
Best regards.

**Comment by lprhodes** [comment]
Hey @hpascual I'll be going through and testing this shortly along with other amends to the air conditioner accessory. Please re-open if you're still seeing this issue.
