### ISSUE TITLE
Cannot change AC temp units

### ISSUE THREAD

**Issue by stefan0p** [lprhodes/homebridge-broadlink-rm#383]
Hello! I have an ac unit that I am trying to control However Homekit units are in F and the plugins are stuck in C
I want to change the plugins units to F but it's not working
Also I have each of the temps with its own HEX
(it would be nice if you allowed min temp to be higher bc my unit doesn't go that low)
I have:
	`"accessories": [{`
			`"name": "Air Conditioner",`
			`"type": "air-conditioner",`
		`	"temperatureDisplayUnits":"F",`
			`"minTemperature": 10,`
		`	"maxTemperature":26,`
		`	"data": {
				"off": "26004c02723...`

However, that doesn't do anything and the units stay in C.

Anything helps thanks!

**Comment by cubilon** [comment]
got the last version of the plugin?

**Comment by lprhodes** [comment]
I shall be adding better support for fahrenheit soon, keep an eye out.
