### ISSUE TITLE
Is there any ablity to use Xiaomi Hygrothermometer for AC temperature value?

### ISSUE THREAD

**Issue by Ugmaxie** [lprhodes/homebridge-broadlink-rm#384]
Hey, great thanks for your hard work for a community.

Could you assist, please, with an ability to use Xiaomi Hygrothermometer as a temperature sensor for **air-conditioner**?
I'm using a [certain plugin](https://github.com/hannseman/homebridge-mi-hygrothermograph) for that.

As I know -  homebridge modules don't know about each other at all, so I have to link it somehow...

**Comment by RealLittleSherman** [comment]
Yes, you need to write (publish) temperature value using the "homebridge-mi-hygrothermograph" plugin (see mqtt section) in the MQTT Broker and then, in the "homebridge-broadlink-rm", inside of the air-conditioner accesory you can read (subscribe) the temperature value using the same Topics
