### ISSUE TITLE
Broadlink not showing up in Home app

### ISSUE THREAD

**Issue by nsbane** [lprhodes/homebridge-broadlink-rm#390]
I've installed the Broadlink plugin and run through all the instructions, but it hasn't shown up on my Home app.

I'm running Hassbian on my Raspberry Pi, and I think the config.json file is in a different location. The plugin directions includes the information below, but I need a bit more detail to figure out what to do (i.e. where is the 'platform config', where I need to add this file path? What is the 'platform config'? What file do I need to modify?)

"Generally the plugin can find where your config.json lives as it commonly sits in the .homebridge directory of your user account. If you're doing something out of the ordinary however you may need to override this. You can do so by adding a "homebridgeDirectory": "/path/to/config.json key/value pair to the platform config."

**Comment by cubilon** [comment]
Post your config

**Comment by lprhodes** [comment]
Closing as no config was provided. Hope you sorted it @nsbane !
