### ISSUE TITLE
Honeywell Tower Fan Speed

### ISSUE THREAD

**Issue by hroman73** [lprhodes/homebridge-broadlink-rm#391]
I've searched but haven't found a solution and am hoping you would know the best approach. I recently bought a honeywell fan which has a three button remote.
1. power
2. speed (fan has 5 speed settings)
3. oscillate
I've got power and oscillate set but i'm not quite sure how to setup the speed since its the same hex every time and when you power the fan on it reverts back to the previous fan speed.

**Comment by cubilon** [comment]
Is it infrared controlled? Have a link urL with specs?

**Comment by hroman73** [comment]
Yes it’s IR

https://www.honeywellpluggedin.com/fans/honeywell-quietset-tower-fan

**Comment by hroman73** [comment]
https://i.ebayimg.com/images/g/AsUAAOSwhI1a0SKP/s-l225.jpg

**Comment by cubilon** [comment]
What about the behaviour. If you set the ventilation to 100% and you power off the unit... when you power on again, what happen?

**Comment by hroman73** [comment]
it would be back to 100%...

**Comment by cubilon** [comment]
ok. I would use a on/off fan configuration with oscillation trigger:

> {
> 					"name": "Fan",
> 					"type": "fan",
> 					"hideSwingMode": false,
> 					"hideRotationDirection": true,
> 					"data": {
> 						"on": "codeforON",
> 						"off": "codeforOFF",
>                                                   "swingToggle": "codeForSwing"
> 					}
> 				}

**Comment by joshuader6** [comment]
I have the same issue with a similar Honeywell model. (It only has 3 Speedsettings) 

Would there be any way to create a `fanSpeed` trigger, that gets fired every time the Slider is moved regardless of it' position?

**Comment by apexad** [comment]
What I did was just add Fan Speed as a separate switch.
enableAutoOff: true,
onDuration: 1

Then in the data block, just supply the on function and it works perfect.

**Comment by mestes136** [comment]
any way i could get yall to post the raw ir data for the fan?? i bought it 2nd hand with no remote

**Comment by dheriman** [comment]
What is the ir code for the remote? I lost mine and trying to reprogram it in my universal remote. Thanks for the help!

**Comment by charlesmunger** [comment]
Remote codes I used with the tower fan for tasmota:
```
ON event#FAN/POWER DO IrSend {"Protocol":"SYMPHONY","Bits":12,"Data":"0xD84","DataLSB":"0xB021","Repeat":0} ENDON
ON event#FAN/SPEED DO IrSend {"Protocol":"SYMPHONY","Bits":12,"Data":"0xDC6","DataLSB":"0xB063","Repeat":0} ENDON
ON event#FAN/OSCILLATE DO IrSend {"Protocol":"SYMPHONY","Bits":12,"Data":"0xDC3","DataLSB":"0xB0C3","Repeat":0} ENDON
```
