### ISSUE TITLE
Accessory Type: Humidifier

### ISSUE THREAD

**Issue by alexander-san** [lprhodes/homebridge-broadlink-rm#392]
After reading the documentation carefully I've seen that the `HMServiceTypeHumidifierDehumidifier` introduced in iOS 10.2 would be a nice addition to this plugin, given that there are no HomeKit Humidifiers (I know of) and also that it seems a common goal to make humidifiers smarter (and that there are almost no humidifier plugins)

I would very much like to work on this and I think that it should not be too complicated given that we already have the FanAccessory and the Switch class. I was looking for some further documentation on the implementation but I don't really understand how the classes in this project communicate with homebridge types/services and ultimately the HAP.

As of now I looked through your source code and created a test service in the HomeKit Accessory Simulator (Humidifier Dehumidifier) and found out that the best way to control it is to have two separate services to form one accessory: fan and humidifier. So the only new key we would have to implement would be the `relativeHumidityThreshold` and combine that with an on/off switch to make a fan only mode (and the already existing fan).

Would it be possible to implement this or is there a Slack channel for this plugin so we can discuss this (and provide some additional information, since I very much would like to learn more)?

Thank you in advance!

**Comment by cubilon** [comment]
Btw, a new accessory of this kind (Humidifier) should use an MQTT relative humidity value like @lprhodes did for temperature in A/C accessory with mqtt temperature support.

**Comment by akseez** [comment]
@AlexanderBabel is this something you could add to your fork?

**Comment by lprhodes** [comment]
I've added this to the latest release, I don't have a real device to test with so let me know how you go with it.

https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/3.6.3
