### ISSUE TITLE
Siri commands not working for TV control

### ISSUE THREAD

**Issue by doner005** [lprhodes/homebridge-broadlink-rm#393]
I have the BroadlinkRM mini3 set up and working great to control my tv with switches in the Home app but Siri isn’t working. She doesn’t recognize any type of turn on the tv command. Is there anyway to fix this? Does this functionality require an Apple TV 4?

**Comment by cubilon** [comment]
please post your config

**Comment by doner005** [comment]
Sorry! I'm still new to this stuff. Here's the config.

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [],

    "platforms": [
      {
        "platform":"BroadlinkRM",
        "name":"Broadlink RM",
        "accessories":[
          {
            "name":"Volume Up",
            "type":"switch",
            "data": {
              "on": [
                {
                  "data": "260098017436100c0f2a0f0f0d18120b0e0e120b0e0e120b0e0f110c0d0e110c0e2a110c0f0d100d0e0e110c0e0e110c120b0f0e11280e0e120b0e0e120b0e0e120b0e0e120b0e0e120b0e0f110b0e0f11270f0e110b0f0e110b0e0f110b0f0d12270f0e11280f00097d7338100d0e2b110b0f0e110b0f0e110b0f0e110b0f0d120b0f0d100d0e2b110b0f0e110b0f0e110b0f0e110b0f0e110b0f2a120b0e0e120b0e0e120b0e0f110b0e0f110b0e0f110b0e0f1109102a120b0e0e120b0e0e120b0e0f110b0f2a110b0f2a1200097b74370e0e11280f0e100c0f0d0f0e0e0e100d0e0e100d0e0e110c0e0e1128120b100c0f0e110b0f0e110b0f0e110b0f0e11280e0f110b0e0f110b0f0e1209100e120a0f0e110c110b0e0f110b0e2b0e0e100d1209100e110b0f0e110b0f2a120b0e2b0e00097e75360f0d13270f0f100b0f0f100b0f0e0e0e100d0e0e100d0e0e110c0e2b110b0f0e110b0f0e110b0f0e110b0f0e110b0f2a120b0e0e110b0f0f100b0f0f100b0f0e0e0e100d0e0e100d0e0e1029120b100c0f0e100c0f0e110b0f0e11280e0e12270f000d05",
                  "sendCount": 1,
                  "interval": 0.3

                }
              ],
              "off": [
                {
                  "data": "260098017436100c0f2a0f0f0d18120b0e0e120b0e0e120b0e0f110c0d0e110c0e2a110c0f0d100d0e0e110c0e0e110c120b0f0e11280e0e120b0e0e120b0e0e120b0e0e120b0e0e120b0e0f110b0e0f11270f0e110b0f0e110b0e0f110b0f0d12270f0e11280f00097d7338100d0e2b110b0f0e110b0f0e110b0f0e110b0f0d120b0f0d100d0e2b110b0f0e110b0f0e110b0f0e110b0f0e110b0f2a120b0e0e120b0e0e120b0e0f110b0e0f110b0e0f110b0e0f1109102a120b0e0e120b0e0e120b0e0f110b0f2a110b0f2a1200097b74370e0e11280f0e100c0f0d0f0e0e0e100d0e0e100d0e0e110c0e0e1128120b100c0f0e110b0f0e110b0f0e110b0f0e11280e0f110b0e0f110b0f0e1209100e120a0f0e110c110b0e0f110b0e2b0e0e100d1209100e110b0f0e110b0f2a120b0e2b0e00097e75360f0d13270f0f100b0f0f100b0f0e0e0e100d0e0e100d0e0e110c0e2b110b0f0e110b0f0e110b0f0e110b0f0e110b0f2a120b0e0e110b0f0f100b0f0f100b0f0e0e0e100d0e0e100d0e0e1029120b100c0f0e100c0f0e110b0f0e11280e0e12270f000d05",
                  "sendCount": 1,
                  "interval": 0.3
                }
              ]
            }
          },
          {
            "name":"Volume Dn",
            "type":"switch",
            "data": {
              "on": [
                {
                  "data": "260036010b000b7075360e0f1028100d0e0e110b0f0e110b0f0e110b0f0e110b0f0e110b0f2a120b0e0f110b0e0f110b0f0d120b0f0d120b0f2a0e0e110c0e0e110b110c0e0e110c0e0e12270f0e110b0f0e110b0f2a120b0e0e12270f0e110b0f0e0f0e12270f0e11270f00097e7239110b0f2a110c0e0e110c0e0e120b0e0e120b0f0e100d0e0e100d0e2b110b0f0e110b0f0e110b120c0e0e110b0f0e11280e0e120b0e0e120b0e0f110b0e0f110b0e2b0e0e0f0f0d0e100d0e2b110b0f0e11280e0e120b0e0f100b0f2a120b0e2b1100097b75360f0e11280e0f110b0f0d120b0f0d120b0f0d0e0f110b0f0e110b0e2b110b0f0f100b0f0f0d0e0f0e0e0e100d0e0e1029120b0f0d120b100c120b100c0f0e110b0f2a110c0e0e110c0e0e11280e10100b10290e0e110c0e0e120b0e2b110b0f2a11000d050000",
                  "sendCount": 1,
                  "interval": 0.3

                }
              ],
              "off": [
                {
                  "data": "260036010b000b7075360e0f1028100d0e0e110b0f0e110b0f0e110b0f0e110b0f0e110b0f2a120b0e0f110b0e0f110b0f0d120b0f0d120b0f2a0e0e110c0e0e110b110c0e0e110c0e0e12270f0e110b0f0e110b0f2a120b0e0e12270f0e110b0f0e0f0e12270f0e11270f00097e7239110b0f2a110c0e0e110c0e0e120b0e0e120b0f0e100d0e0e100d0e2b110b0f0e110b0f0e110b120c0e0e110b0f0e11280e0e120b0e0e120b0e0f110b0e0f110b0e2b0e0e0f0f0d0e100d0e2b110b0f0e11280e0e120b0e0f100b0f2a120b0e2b1100097b75360f0e11280e0f110b0f0d120b0f0d120b0f0d0e0f110b0f0e110b0e2b110b0f0f100b0f0f0d0e0f0e0e0e100d0e0e1029120b0f0d120b100c120b100c0f0e110b0f2a110c0e0e110c0e0e11280e10100b10290e0e110c0e0e120b0e2b110b0f2a11000d050000",
                  "sendCount": 1,
                  "interval": 0.3
                }
              ]
            }
          },
          {
            "name":"Input",
            "type":"switch",
            "data":{
              "on":"26008403110b0f0e110b0f0e110b0f2a110b0f0e110b0f0e110b0f0e110b0f0e110b0f2a110c0e0e120b0e0e120b0e0e120b0e0e12270f0e11280e0f110b0f0d0e0f110b0e29130b0f2a120b0e0e120b0e0e12270f00097e7239110b0f2a110c0e0e110c0e0e110c0e0e120b0e0e100d0e0e110d0d2a120b0e0e120b0e0e120c100b0f0f100b0f100c2b110b0f0e0e0e110c0e0e110c0e0e120b0e2b110b0f2a120b0e0e110c0e0e0e0e1029120b0f27110e100d0e0e100d0e2b1100097b74370f0e1128110b0f0f100b0f0f100b0f0f0d0e100d0e0e100d0e0e11280e0e120b0e0e120b0e0e120b110b0f0e110b0f2a110c0e0e110c0e0e120b0e0e120b0e0e12270f0e11280e0e120b0e0e110b0f0e11280f0d12270f0e110b0f0e110b0f2a1100097c7239110b0f2a120b0f0d120b0f0e0e0e110c0e0e110b0f0d120b0f0f0d2a110c0e0e110c0e0e110c0e0e120b0e0f110b0e2b0e0e100d0e0e100d0e0e100d0e0f110b0e2b110b0f2a120b110c0f0d0e0e110c0e2a120b0e2b0e0e100d0e0e100d0e2b1100097779360f0f1028100c120c100c0f0e110b0f0e110b0f0e110b0e0f110b0f2a0e0e110c0e0e110c0e0e120b0e0e120b0e0e12270f0e110b0f0e110b0f0e110b0f0e110b0f2a120b0e2b110b0f0f0d0e110b0f0e11280e0e12270f0e110b0f0e110d0d2a1200097b75360e0e12270f0e110b0f0e110b0f0e110b0f0f100b0f0f0d0e110d0d2a120b0e0f110b0e0f110b0e0e120b0f0d120b0f2a0e0e110c0e0e110c0e0e120b0e0e120d0d2a0e0e1029120b100c0e0f110c0f0d0e2a110c0e390e0f100c0e0e120c10280f00097d7239120b0e2b110c0e0f0d0e100d0e0f110b0e100c0f110c0d100d0e10280f0f110b0e0f110e0f0c0f0e100d0e0f100c1028120c100c0f0e0d0e120c0d0f110d0e0d0e2a120b0e2b110c0f0d0e0e110d0d0f0d2b110d0d2811100c0f110c0e0d12280f00097e7239110b0f2a120c0d10100d0f0c0e0e110b0f0f100c100c0e100c1010270f0f100d0f0e0c0f110c100c0e0e110c0e100c2b110c0e100c0f110d0e0d0e0f100c100d0d28120f0d2a110c0e0f0d0e0f100c0e11280f0f10280e0f110c100b0f0f10280f00097d7239120c0e2a0e0e110d0d0f110b0f0e0e0e110c0d100d0f100c0e100c2b110c0e0e110c0f0f0c0e120b0e0f110d0f0c0e2a120c0e0f0d0e110b0f100f0c0e100c0f11270f0e11280e100c0f110c0f0d0e0f10280e0e12270f0e110b0f0f100d0e2912000d0500000000",
              "off":"26008403110b0f0e110b0f0e110b0f2a110b0f0e110b0f0e110b0f0e110b0f0e110b0f2a110c0e0e120b0e0e120b0e0e120b0e0e12270f0e11280e0f110b0f0d0e0f110b0e29130b0f2a120b0e0e120b0e0e12270f00097e7239110b0f2a110c0e0e110c0e0e110c0e0e120b0e0e100d0e0e110d0d2a120b0e0e120b0e0e120c100b0f0f100b0f100c2b110b0f0e0e0e110c0e0e110c0e0e120b0e2b110b0f2a120b0e0e110c0e0e0e0e1029120b0f27110e100d0e0e100d0e2b1100097b74370f0e1128110b0f0f100b0f0f100b0f0f0d0e100d0e0e100d0e0e11280e0e120b0e0e120b0e0e120b110b0f0e110b0f2a110c0e0e110c0e0e120b0e0e120b0e0e12270f0e11280e0e120b0e0e110b0f0e11280f0d12270f0e110b0f0e110b0f2a1100097c7239110b0f2a120b0f0d120b0f0e0e0e110c0e0e110b0f0d120b0f0f0d2a110c0e0e110c0e0e110c0e0e120b0e0f110b0e2b0e0e100d0e0e100d0e0e100d0e0f110b0e2b110b0f2a120b110c0f0d0e0e110c0e2a120b0e2b0e0e100d0e0e100d0e2b1100097779360f0f1028100c120c100c0f0e110b0f0e110b0f0e110b0e0f110b0f2a0e0e110c0e0e110c0e0e120b0e0e120b0e0e12270f0e110b0f0e110b0f0e110b0f0e110b0f2a120b0e2b110b0f0f0d0e110b0f0e11280e0e12270f0e110b0f0e110d0d2a1200097b75360e0e12270f0e110b0f0e110b0f0e110b0f0f100b0f0f0d0e110d0d2a120b0e0f110b0e0f110b0e0e120b0f0d120b0f2a0e0e110c0e0e110c0e0e120b0e0e120d0d2a0e0e1029120b100c0e0f110c0f0d0e2a110c0e390e0f100c0e0e120c10280f00097d7239120b0e2b110c0e0f0d0e100d0e0f110b0e100c0f110c0d100d0e10280f0f110b0e0f110e0f0c0f0e100d0e0f100c1028120c100c0f0e0d0e120c0d0f110d0e0d0e2a120b0e2b110c0f0d0e0e110d0d0f0d2b110d0d2811100c0f110c0e0d12280f00097e7239110b0f2a120c0d10100d0f0c0e0e110b0f0f100c100c0e100c1010270f0f100d0f0e0c0f110c100c0e0e110c0e100c2b110c0e100c0f110d0e0d0e0f100c100d0d28120f0d2a110c0e0f0d0e0f100c0e11280f0f10280e0f110c100b0f0f10280f00097d7239120c0e2a0e0e110d0d0f110b0f0e0e0e110c0d100d0f100c0e100c2b110c0e0e110c0f0f0c0e120b0e0f110d0f0c0e2a120c0e0f0d0e110b0f100f0c0e100c0f11270f0e11280e100c0f110c0f0d0e0f10280e0e12270f0e110b0f0f100d0e2912000d0500000000"
            }
          },
          {
            "name":"TV On/Off",
            "type":"switch",
            "data":{
              "on":"260032017338120b0e2b110b0f0f100d0f0d0d0e120b0e0f110b0e0f110b0e0f11270f0e110c0f0d0e0e110c0e0e110d0d0f100b0f2a120b0f0d120c100b0f0e110b0f0e110b0f2a120c0d2b0e2b10290e2b110c0e0f0d2a100d0e2b11280e2b11280f0d12280f00097c77350f0f10280f0f0d0e110b0f0f100c0e0e0e0f110c0d120f0b0e0f11270f0e110c0f0d0e10100b0e0f0d0e130d0f0c0e2a120d0c0f110c100b0f0f100c0e0f0d0e0f2a120b0f2b0d2b11280e2b110b0f0e11270f0e11280f2b0d2b11280e0f11270f00097d76350f0f10280f0d120b100d0e0e110b0f0f100b0f0e110b0f0e110c1028120b100d0e0e110b0f0e110b0f0e110b0e0f11270f0e110d0e0e0d0f110c0f0d0e0e110b0f2a110d0d2b1128102713280e0f110b0e2b110b0f2a0e2b10290e2b110c0e2a12000d05000000000000",
              "off":"2600320176350f0e11280e0e120b0e0f110c0d0f110b0e0f110b0e0f110b0f0d12270f0e110c0f0d0e0e110c0e0e110c0e0f100b0f2a120b0e0e120c100b0f0e110b0f0e110b0f2a130c0f290e2b11280e2b0e0f100c0e2a120b0e2b11280e2b1128100c0f2a0f00097c77350f100c2b110c0e0f100b0f100c0f110b0e10100c100c0e0e110c0e2b110b0f0e0e0e110d0d0e110c0f0c0f0f100c0e2a120d0d0d120c100b0f100f0c0f0d0e0e1029120b0f2a0e2b11280e2b110b0f0e11270f0f102810290e2b11280e1010270f00097d7338120b0e2b0e0e0f0e0e0f110b0e0e120c0e0d120b0e0f110b0e100d2a100d0e0f110b0e0e120b0e0e120b0e0f100b0f2a120b0e100d0f0d0f110c100d0d0e110b0f2a120c0f290e2b1126102b100c0f0e11270f0e10290e2b11280e2b0e0f10280f000d05000000000000"
            }
          }
        ]
      },

**Comment by cubilon** [comment]
start changing - name":"TV On/Off" - in - name":"TV" - and ask her to turn on "TV".

**Comment by doner005** [comment]
Thank you. This solved it!

**Comment by cubilon** [comment]
u welcome!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
