### ISSUE TITLE
pingIPAddress not working

### ISSUE THREAD

**Issue by kiwi-cam** [lprhodes/homebridge-broadlink-rm#394]
I have this accessory in my config.json:
>{
>				"name": "Radio",
>				"type": "switch",
>				"data": {
>					"on": [{
>							"data": "260056009...",
							"pause": 1
						},
						{
							"data": "26004e009...",
							"sendCount": 2,
							"interval": 3
						}
					],
					"off": "26005600949...",
					"pingIPAddress": "192.168.21.54",
					"pingFrequency": 5,
					"pingIPAddressStateOnly": true
				}
			}

I'm expecting the last three lines to update the status in HomeKit so it's off if the ping fails, or on if it succeeds. I'm finding that the status is set to on regardless of whether the ping is successful or not.  

The logs aren't showing anything obvious.  I see this in the log when homebridge starts:
> [2018-6-28 08:19:57] [Broadlink RM] Radio getSwitchState: true
but nothing is ever logged again.

What else can I check - or have I understood the function of this setting wrong??

**Comment by cubilon** [comment]
correct like follows:

[{
"name": "Radio",
"type": "switch",
"pingIPAddress": "192.168.21.54",
"pingFrequency": 5,
"pingIPAddressStateOnly": true,

"data": {
"on": [{
"data": "260056009...",
"pause": 1
},
{
"data": "26004e009...",
"sendCount": 2,
"interval": 3
}
],
"off": "26005600949...",
}
}](url)

**Comment by kiwi-cam** [comment]
Bingo! Thanks for that. I didn’t expect the order to be important. 

Logs look good now.

**Comment by cubilon** [comment]
it is :)
u welcome!
