### ISSUE TITLE
Sending continious signal

### ISSUE THREAD

**Issue by bmangodt** [lprhodes/homebridge-broadlink-rm#395]
I have 2 RM Mini's up and running with this plugin and it's great. But I just can't figure out how to send a continious signal for a certain duration. I.e.: The Apple TV needs a 5sec press of the "Play/Pause"-button to put it in sleep mode. Is there any way I can achieve this? 
I've tried sending 50 signals (I know) every 0.1 seconds but it just causes spamming...

**Comment by rgerr** [comment]
Interested in this aswell, but it seems signals cannot be send faster than with 0.3 seconds interval. Probably a hardware limitation, I assume.

**Comment by lprhodes** [comment]
It's been a while since I tried but I believe it does support "long" IR codes, it's all in the recording of the IR code, nothing else will fake it.
