### ISSUE TITLE
Request: Reed/Door Sensor Integration

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [lprhodes/homebridge-broadlink-rm#398]
Just wondering if this is possible at all?

I was looking to use these with a relay to send a signal of open or close when a light is on or off, giving me realtime active feedback on the state of a light, it won't give me brightness level, but it will give me the state.

We could use an S1C alarm kit to make this happen, these will run 16 door sensors, I can remove the magnetic contact switch and wire this to the NO/NC circuit on a relay, to mimic open or close, this can then be used to interpret a lights state, these sensors have active monitoring so I believe the S1C poles the sensors periodically.

**Comment by lprhodes** [comment]
Sorry @Kung-Foo-Kamel that's far beyond the scope of this plugin.
