### ISSUE TITLE
ip address of the RM learner

### ISSUE THREAD

**Issue by hkechung** [lprhodes/homebridge-broadlink-rm#4]
I following the 3 steps below

1. Install homebridge using: sudo npm install -g homebridge
2. Install this plugin using: npm install -g homebridge-broadlink-rm
3. Update your configuration file. (See config-sample.json)

in the config.json
I put 

"accessories": [{
		"accessory": "Broadlink RM Learner",
			"name": "Learn IR",
			"host": "10.0.1.61"
		}]}

what is the host ip should I put ? is it where the homebridge ip ?

**Comment by hkechung** [comment]
if I add "Broadlink RM " it will stop teh Docker..

/usr/lib/node_modules/homebridge/lib/api.js:60
stdout
09:45:16
      throw new Error(&quot;The requested accessory '&quot; + name + &quot;' was not registered by any plugin.&quot;);
stdout
09:45:16
      ^
stdout
09:45:16
stdout
09:45:16
Error: The requested accessory 'Broadlink RM ' was not registered by any plugin.
stdout
09:45:16
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:60:13)
stdout
09:45:16
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:254:42)
stdout
09:45:16
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
stdout
09:45:16
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
stdout
09:45:16
    at Object.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
stdout
09:45:16
    at Module._compile (module.js:556:32)
stdout
09:45:16
    at Object.Module._extensions..js (module.js:565:10)
stdout
09:45:16
    at Module.load (module.js:473:32)
stdout
09:45:16
    at tryModuleLoad (module.js:432:12)
stdout
09:45:16
    at Function.Module._load (module.js:424:3)
stdout
09:45:16
    at Module.runMain (module.js:590:10)
stdout
09:45:16
    at run (bootstrap_node.js:394:7)
stdout
09:45:16
    at startup (bootstrap_node.js:149:9)
stdout
09:45:16
    at bootstrap_node.js:509:3

**Comment by lprhodes** [comment]
The IP address should be that of the broadlink device which you can find out from your router or by using the broadlink app

It could be the extra space I had in the example config ("Broadlink RM " rather than "Broadlink RM")

**Comment by londoncalrissian** [comment]
Hi, I have been waiting so long for this plug-in! thank you for your work!

Following on from the previous comment, I am having issues with the Learner. if I set the IP address to that of the RM Mini and try to switch on the learner in the home app, a hex code immediately appears and the learner switches off before I've had a chance to send an IR signal.

**Comment by hkechung** [comment]
so first time setup should be ?

 "accessories": [
     {
         "accessory": "Broadlink RM Learner",
         "name": "Learn IR",
         "host": "`**_RM ip address_**`"
     }

however, still nothing happen after 10s....

**Comment by lprhodes** [comment]
@londoncalrissian can you send the full hex code that appears please

**Comment by lprhodes** [comment]
@hkechung Can you toggle the Learn IR accessory from HomeKit and send the homebridge log please?

**Comment by londoncalrissian** [comment]
@Iprhodes it's 5aa5aa555aa5aa550000000000000000000000000000000000000000000000000dccf9ff2a27ee03fd8228d7e734ea3401000000b2be0000)

Thanks for you help

**Comment by lprhodes** [comment]
@londoncalrissian I've updated to 0.2.8 try updating the module and give it another go.

**Comment by mikecc2008** [comment]
Hi @lprhodes Thanks for your great work. 

I have issues with learner as well. The light of RM Pro was not lit during learning. No code has been learned. 

I tried replacing content of the broadcast packet in learner with mine. 
![screenshot 2017-03-19 08 24 48](https://cloud.githubusercontent.com/assets/4153409/24077147/48d60922-0c7f-11e7-9a8f-2630b5623fce.png)
Then, learner returned with a hex code immediately. The learned code is quite longer than londoncalrissian's though. 
![screenshot 2017-03-19 08 38 24](https://cloud.githubusercontent.com/assets/4153409/24077151/727c202c-0c7f-11e7-85c9-55bba39d2e7d.png)

**Comment by leonardolau** [comment]
@mikecc2008, could you pleae kindly describe the steps to capture the hex and change which file? Thanks

**Comment by lprhodes** [comment]
Interesting thanks @mikecc2008 can you paste it in here please and I'll figure out the difference to create something that works generically.

Was it just he initial learn code you changed or the repeating one?
 
@leonardolau you can use wireshark to get the hex codes

**Comment by lprhodes** [comment]
Also which rm device are you using mike?

**Comment by mikecc2008** [comment]
Hi @leonardolau I captured the packets by tPacketCapture when using Broadlink's e-control app on an Android phone. I changed hex codes in learner.js.

**Comment by mikecc2008** [comment]
Hi @lprhodes 

Broadcast code:
5aa5aa555aa5aa55000000000000000000000000000000000000000000000000c2d200002a276a00d682aafeee0d43b402000000b0be0000cc1f04d07d9303e4ea6fe989ebc59732

Learned code:
5aa5aa555aa5aa55000000000000000000000000000000000000000000000000296e00002a27ee03d682aafeee0d43b40200000059c700008c027c7c93b575c813b05d1c7f35e16a2aad220945d4adb349322dbe76913cc22026b97226d914e8980dde8c0d292238670f04925e71d099888f082a47b243ff57905dc0b0baf2d81de5f06ea08b10725e3d674c6fc58cf6593d4c9429d080bea0ac1a54a607728c3fa9dc600b5725b1497bec737281c0eccd19e14421035041a3c959a90b5d61721c6106685c0e56b5a10b51824e1faaeeecbebdca1e205074c0fd53e780a6f87a7ec85ceed5f7ae6071d93e9395ec24b01cd6886651bbfe051e21a8e6a0d9453cf23e49067b03e89923f1441d641d924d47b2b9d0dbdcb4347a4cf1b5114fbc7ded4f4bf8d5fa5b7d941c5667c44fa3a9092b429ed2ba7beb8b4d0d0b86dec5cac65361a446f49b8a6708cf7024bff6d3fe697fb604552ce6c796f08089f975be88799cf48882007b6577afbc58586a4d2b85a829b54d165dfd77b0cc053ca43e4648da61d466008d

I changed the initial learn code [https://github.com/lprhodes/homebridge-broadlink-rm/blob/master/learner.js#L22](url)
But if I changed getDataHex as well, there seems no difference from just changing learn. 

And I am using RM Pro. Are RM Pro and RM2 the same mode indeed? A bit confused about these different models.

**Comment by mikecc2008** [comment]
When I further tighten up the [length condition](https://github.com/lprhodes/homebridge-broadlink-rm/blob/ecd50933bf4d7fb0c3093941f122993fc5391a21/learner.js#L43) from 144 to say 1000, no learned code will be returned.

**Comment by mikecc2008** [comment]
@lprhodes Perhaps the hex code for each device should be different? 
In [https://github.com/mjg59/python-broadlink/blob/7a852b20840aab131ba59aaf85f5e67831b7ccc3/broadlink/__init__.py#L198-L221](python-broadlink), MAC address is a component of the hex code.

**Comment by lprhodes** [comment]
Yeah I'd seen that but I'm using someone else's broadcast code so had assumed it wasn't being checked. I'm out at the moment so I'll have a look into what works when I get back.

Thanks

Luke

**Comment by leonardolau** [comment]
@mikecc2008 Thanks. May I know the path for the file stored?

**Comment by hkechung** [comment]
EventedHTTPServer [::ffff:192.168.5.102] HTTP request: /characteristics +24s                                                        
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms                                                                
  Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":9,"value":1}] +5ms                                            
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +0ms                                                                  
[3/19/2017, 9:25:37 AM] [Learn IR] Learn IR (ready)                                                                                   
  EventedHTTPServer [::ffff:192.168.5.102] HTTP Response is finished +9ms                                                             
[3/19/2017, 9:25:47 AM] [Learn IR] Learn IR (stopped - 10s timeout)                                                                   
  EventedHTTPServer [::ffff:192.168.5.102] HTTP request: /characteristics +11s                                                        
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms                                                                
  Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":9,"value":0}] +1ms                                            
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +0ms                                                                  
  EventedHTTPServer [::ffff:192.168.5.102] HTTP Response is finished +1ms

**Comment by hkechung** [comment]
when I  toggle the Learn IR accessory from HomeKit,  I should do 1) or 2) 
1) use the real remote and sent it to Broadlink ?
2) turn on the e-control on the iPhone and learn a new code ?

thanks.

**Comment by hkechung** [comment]
I capture it using wireshark
![os x 10 11 el capitan-2017-03-19-20-02-44](https://cloud.githubusercontent.com/assets/9531213/24080661/2f07d9f2-0cdf-11e7-928e-cd885e7dce1f.png)

5aa5aa555aa5aa5500000000000000000000000000000000000000000000000093f9000037276a0095806a33cc0d43b4010000008ec800006361fc102f44e2f8daeed188f1e279f6e062d5c46b23e02a0fa2f5741ed29bdaf0d883d5a17a5e363440977a1845b068c5d7dd1074764d00377f0a12ba27ddd5870608da14ee1cf35533a73bc4488d08955126e9d611f047842ca369caf56e60

**Comment by lprhodes** [comment]
I have an update coming out in the next hour that should fix all of this...you'll need new hex codes but you'll be able to get them direct from the HomeKit Learn IR accessory

**Comment by lprhodes** [comment]
Grab 0.2.12 (just released) and let me know how it goes :)

**Comment by hkechung** [comment]
Cannot find module 'broadlinkjs'
--------------------------------------
[37m[3/19/2017, 2:30:46 PM][39m [1m[31m====================[39m[22m
stdout
14:30:46
[37m[3/19/2017, 2:30:46 PM][39m [1m[31mERROR LOADING PLUGIN homebridge-broadlink-rm:[39m[22m
stdout
14:30:46
[37m[3/19/2017, 2:30:46 PM][39m [1m[31mError: Cannot find module 'broadlinkjs'
stdout
14:30:46
    at Function.Module._resolveFilename (module.js:455:15)
stdout
14:30:46
    at Function.Module._load (module.js:403:25)
stdout
14:30:46
    at Module.require (module.js:483:17)
stdout
14:30:46
    at require (internal/module.js:20:19)
stdout
14:30:46
    at Object.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge-broadlink-rm/devices.js:1:83)
stdout
14:30:46
    at Module._compile (module.js:556:32)
stdout
14:30:46
    at Object.Module._extensions..js (module.js:565:10)
stdout
14:30:46
    at Module.load (module.js:473:32)
stdout
14:30:46
    at tryModuleLoad (module.js:432:12)
stdout
14:30:46
    at Function.Module._load (module.js:424:3)[39m[22m
stdout
14:30:46

**Comment by antoniopll** [comment]
Hello thanks for your contribution.
I have the same problem of @londoncalrissian... All time say in learning:
`
[2017-3-18 20:44:18] [Learn IR] Learn IR (ready)
[2017-3-18 20:44:18] [Learn IR] Learn IR (learned hex code: 5aa5aa555aa5aa550000000000000000000000000000000000000000000000000dccf9ff2a27ee03fd8228d7e734ea3401000000b2be0000)
[2017-3-18 20:44:18] [Learn IR] Learn IR (complete)
`
![sin titulo](https://cloud.githubusercontent.com/assets/7695822/24082004/b2e267d6-0cbe-11e7-98bd-8c2f6d402f1b.jpg)


But now i try to update the plugin and have this problem..

**Comment by lprhodes** [comment]
Sorry - I had broadlinkjs installed globally and forgot to add it to the package.json

You can update to 0.2.13

**Comment by leonardolau** [comment]
@lprhodes it works perfectly. thanks for your hard work. by the way, could it retrieve temperature data from RM Pro?

**Comment by lprhodes** [comment]
@leonardolau Glad to hear - it could if the device supports it but I need to re-work some of the new code I've just added first. It's a bit hacked on at the moment. I should get a chance to work on it later in the week.

**Comment by lprhodes** [comment]
Closing for now - let me know if any of you still have this issue. Feel free to open new ones or submit feature requests.

**Comment by antoniopll** [comment]
Thanks you very much @Iprhodes
Now work perfect. I had configure all my leds and the air conditioner for controller by Apple Watch :D

**Comment by hkechung** [comment]
Thanks @Iprhodes for the update... still error on my side
[3/20/2017, 12:44:07 AM] [Learn IR] LearnIR (no device found at 192.168.5.161)

**Comment by lprhodes** [comment]
Hey @hkechung can you check that you can ping 192.168.5.161 from wherever you're running homebridge please?

**Comment by lprhodes** [comment]
there's a device discovery service running so it'd also be worth checking to make sure you're not using a secondary network or some kind of bonding/vpn software that could be interfering.

**Comment by lprhodes** [comment]
Finally, can you please open /usr/local/lib/node_modules/homebridge-applescript-status/devices.js and add `console.log('FOUND RM DEVICE', device.host.address)` between line 9 and 10 then re-run home bridge

**Comment by hkechung** [comment]
EventedHTTPServer Server listening on port 51826 +0ms                                                         
[3/20/2017, 12:47:47 AM] Homebridge is running on port 51826.                                                   
  EventedHTTPServer [::ffff:192.168.5.102] New connection from client +1s                                       
  EventedHTTPServer [::ffff:192.168.5.102] HTTP server listening on port 59960 +6ms                             
  EventedHTTPServer [::ffff:192.168.5.102] HTTP request: /pair-verify +41ms                                     
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +2ms                                             
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +16ms                                                      
  EventedHTTPServer [::ffff:192.168.5.102] HTTP Response is finished +55ms                                      
  EventedHTTPServer [::ffff:192.168.5.102] HTTP request: /pair-verify +47ms                                     
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms                                             
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +7ms                                                       
  HAPServer [CC:22:3D:E3:CE:30] Client A1AE17B2-149B-4000-A196-2B1F00A94B3D verification complete +11ms         
  EventedHTTPServer [::ffff:192.168.5.102] HTTP Response is finished +5ms                                       
  EventedHTTPServer [::ffff:192.168.5.102] HTTP request: /accessories +7ms                                      
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms                                              
  EventedHTTPServer [::ffff:192.168.5.102] HTTP Response is finished +9ms                                       
  EventedHTTPServer [::ffff:192.168.5.102] HTTP request: /characteristics +41ms                                 
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms                                          
  Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":11,"ev":true},{"aid":6,"iid":14,"ev":tru
e}] +5ms                                                                                                        
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +3ms                                 
  Accessory [Homebridge] Registering Characteristic "Category" for events +1ms                                  
  EventedHTTPServer [::ffff:192.168.5.102] HTTP Response is finished +2ms                                       
  EventedHTTPServer [::ffff:192.168.5.102] HTTP request: /characteristics +67ms                                 
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms                                          
  Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":9,"ev":true}] +3ms                      
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms                                        
  EventedHTTPServer [::ffff:192.168.5.102] HTTP Response is finished +5ms                                       
  EventedHTTPServer [::ffff:192.168.5.102] HTTP request: /characteristics?id=6.9 +17ms                          
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=6.9 +0ms                                   
  Accessory [Homebridge] Getting value for Characteristic "On" +7ms                                             
  Accessory [Homebridge] Got Characteristic "On" value: false +3ms                                              
  EventedHTTPServer [::ffff:192.168.5.102] HTTP Response is finished +1ms

**Comment by hkechung** [comment]
I reset everything and it is done.. **Thank you very much for your support.**
btw, my tv code is something different but start with 

2600600000012a911411141114351535141114111435141xxxx

**Comment by lprhodes** [comment]
Great, I'm glad to hear :)

**Comment by lmarback** [comment]
Hi, it's my first time trying to do anything like this and I'm very stupid in this...

First mistake I got was putting my macOS username at username instead of the Mac Addresss and it took me a week to find it out, I'm from Brazil, and english is not my first language, what makes it harder to find information. 

After some time, this is what I'm using, and I think it still very wrong, so I'm trying to find some help, can anyone please help me with this?

3c:15:c2:e6:20:20{
  "bridge": {
    "name": "Homebridge",
    "username": "3C:15:C2:E6:20:20",
    "pin": "225-86-914"
  },

  "description": "This is an example configuration file with one fake accessory and one fak$
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory $
  },
  "accessories": [
    {
      "accessory": "WeMo",
      "name": "Coffee Maker"
    }
  ],

  "platforms": [
    {
    "hosts": [
    {
    "address": "192.168.68.135",
    "mac": "78:0F:77:00:B3:BD",
    "isRFSupported": true
     }
     ],
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "accessories":[
        {
          "accessory": "Broadlink RM Learner",
          "name": "Learn IR",
          "host": "192.168.68.135"
        }
      ]
    }
  ]
  ]
}
