### ISSUE TITLE
Troubles with setup

### ISSUE THREAD

**Issue by alexeyshulzhenko** [lprhodes/homebridge-broadlink-rm#40]
Hi! Thanks for this great plugin! Unfortunately it doesn't work on my pc. There are some errors. Can you, please, help me with that? (Windows 10, node v 6.10.2)
![3](https://cloud.githubusercontent.com/assets/11439023/24772933/cc333a60-1b1b-11e7-9579-0b57455385fa.png)

**Comment by lprhodes** [comment]
Search is your friend :) https://github.com/lprhodes/homebridge-broadlink-rm/issues/38
