### ISSUE TITLE
temperatureFilePath Temperature Rounding incorrectly

### ISSUE THREAD

**Issue by kiwi-cam** [lprhodes/homebridge-broadlink-rm#401]
cubilon has mentioned this already in #334 but I can't see an associated issue anywhere else. If there is one, let me know.

The issue is that when reading the current temperature from a file there isn't any rounding. The temperature is simply concatenated. For example, if the temperature is 18.9 it shows in the Home App as 18 when it should be rounding up to 19.

I've been able to get around this by adding 0.5 to the temperature when I'm outputting (awk '{print $1+0.5}') it but now I'm wanting to use the same value elsewhere so I'd prefer to have the correct value in the file.

**Comment by cubilon** [comment]
It's not plugin's fault, it's just HomeKit taking the integer part of the value.
which is your source?

**Comment by kiwi-cam** [comment]
That integer rounding doesn’t match the explanation of Homekit’s rounding in the plugin documentation:

> Bare in mind that while the Home app may say 22C, the temperature may actually be 22.4C and if the Home app says 23C then it may actually be 22.5C.

Also, I’m using the homebridge-temperature-file plugin which rounds correctly using the same file.

**Comment by cubilon** [comment]
What I meant is that HomeKit doens't round the value.

**Comment by kiwi-cam** [comment]
Hi @cubilon . I thought I'd give you an update on this. I've been doing a bit of "tweaking" under @AlexanderBabel's fork here: https://github.com/AlexanderBabel/homebridge-broadlink-rm/pull/30. The two main changes I've made are: support for {mode}{temperature} hex codes in the configuration (so you can have a hexcode for cooling to 22, and another for heating to 22) and sorting out this issue. What I've done is update the Broadlink RM platform to pass the temperature to Homebridge with a decimal value so HomeKit can handle the rounding.

If you're interested, take a look at the [fork (which includes TV support)](https://github.com/AlexanderBabel/homebridge-broadlink-rm) and [my Pull Request](https://github.com/AlexanderBabel/homebridge-broadlink-rm/pull/30). You can install straight from my pull request using:
`npm install -g git+https://github.com/AlexanderBabel/homebridge-broadlink-rm#pull/30/head`

@AlexanderBabel has said that he'll merge my changes into his fork in the near future too.

**Comment by lprhodes** [comment]
Fixed in the latest release.
