### ISSUE TITLE
Netatmo thermostat

### ISSUE THREAD

**Issue by requena242** [lprhodes/homebridge-broadlink-rm#403]
Hi, I hope someone can solve this problem.
I have broadlink mini and when I connect the air conditioning it gives me the temperature value 0ºC.
I also have the netatmo thermostat to control the heating through the boiler.
Is it possible that the broadlink read the current temperature through netatmo?
Another problem is that when I ask Siri to turn on the heating at 24ºC, he starts the air conditioning and the boiler, when the only thing I want is for the boiler to start. Is it possible that siri understands that when I want to warm up just turn on the boiler and when I want to cool just turn on the air?
Thanks to all for the help

**Comment by cubilon** [comment]
you may can try to get the temperature using node.red and putting on a MQTT topic - readable, you know, by this plugin.
