### ISSUE TITLE
Example for AC with MQTT

### ISSUE THREAD

**Issue by RealLittleSherman** [lprhodes/homebridge-broadlink-rm#404]
Hi Luke, can you give me an AC with MQTT config example? I make some tests but nothing work for me, always appears "No MQTT value could be found for topic with identifier "temperature"" Message.

I create a topic and publish by hand a value (it is for testing)

mosquitto_pub -d -t devel/temp -m "27"

i put in my config.json

...
"mqttURL":"mqtt://192.168.0.253",
"mqttTopic":"devel/temp", 
...

The No MQTT value... message still appears :(

**Comment by cubilon** [comment]
This is a working configuration for Sonoff TH-16 sensor (Tasmota flashed):

> 			"host": "192.168.1.90",
> 					"preventResendHex": true,
> 					"mqttURL": "mqtt://192.168.1.98",
> 					"mqttTopic": "tele/sensorAngolo/SENSOR",
> 					"temperatureUpdateFrequency": 150,
> 					"debug": false

**Comment by RealLittleSherman** [comment]
Thankyou very much, the value obtained when you query the topic is only a number (float) representing the temperature?

**Comment by asbesto01** [comment]
Guys where is the mistake? this is my config json:

"name": "CondizionatoreCamera",
"type": "air-conditioner",
"host": "192.168.0.177",
"mqttURL": "mqtt://192.168.0.199",
"mqttUsername": "Stefano",
"mqttPassword": "Password",
"mqttTopic": "tele/sonoff/SENSOR/",
"temperatureUpdateFrequency": 150,
"minTemperature": 10,
"maxTemperature": 30,
"defaultCoolTemperature": 23,
"defaultHeatTemperature": 25,
"replaceAutoMode": "cool",

I receive this message:
"No MQTT value could be found for topic with identifier "temperature".

But my TH16 is transmitting telemetry just fine:

00:00:00 CFG: Loaded from flash at F9, Count 43
00:00:00 Project sonoff sonoff Version 6.5.0.16(sonoff)-2_5_2
00:00:00 WIF: Connecting to AP1 PiricipolliHome2.4 in mode 11N as sonoff-0533...
00:00:04 WIF: Connected
00:00:04 HTP: Web server active on sonoff-0533 with IP address 192.168.0.125
11:33:25 MQT: Attempting connection...
11:33:25 MQT: Connected
11:33:25 MQT: tele/sonoff/SENSOR/LWT = Online (retained)
11:33:25 MQT: tele/sonoff/SENSOR/cmnd/POWER = 
11:33:25 MQT: tele/sonoff/SENSOR/INFO1 = {"Module":"Sonoff TH","Version":"6.5.0.16(sonoff)","FallbackTopic":"cmnd/DVES_52C215_fb/","GroupTopic":"sonoffs"}
11:33:25 MQT: tele/sonoff/SENSOR/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoff-0533","IPAddress":"192.168.0.125"}
11:33:25 MQT: tele/sonoff/SENSOR/INFO3 = {"RestartReason":"Software/System restart"}
11:33:25 MQT: tele/sonoff/SENSOR/RESULT = {"POWER":"ON"}
11:33:25 MQT: tele/sonoff/SENSOR/POWER = ON
11:33:33 MQT: tele/sonoff/SENSOR/STATE = {"Time":"2019-06-29T11:33:33","Uptime":"0T00:00:14","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":1,"SSId":"PiricipolliHome2.4","BSSId":"EC:08:6B:37:29:6B","Channel":8,"RSSI":76,"LinkCount":1,"Downtime":"0T00:00:04"}}
**11:33:33 MQT: tele/sonoff/SENSOR/SENSOR = {"Time":"2019-06-29T11:33:33","AM2301":{"Temperature":28.7,"Humidity":49.8},"TempUnit":"C"}**

Help!

**Comment by lprhodes** [comment]
@asbesto01 please open a new issue if you're still experiencing this problem. Thanks!
