### ISSUE TITLE
Configuring AC accessory: AC remote sends different HEX code each time

### ISSUE THREAD

**Issue by gbenamy** [lprhodes/homebridge-broadlink-rm#406]
Hi,
I'm trying to configure simple AC accessory, only "on/off" in a certain state (Cool mode, 24 deg, low fan)
I tried to use 'learn' to get the HEX code for that certain state, but it keeps getting different HEX codes although I just click on the "on/off" toggle button in the remote.

Any idea how to workaround the issue?
The remote is RC-3.
Thanks

**Comment by Elvys8** [comment]
Same issue here. Any solution?

**Comment by lprhodes** [comment]
There's a few different reasons that the RF code may change each time e.g. due to a timestamp being included.

There's no actual issue that's been raised here so I'm closing. Please re-open the issue with more details if you'd like a hand.
