### ISSUE TITLE
[ERROR] Scan RF (RF learning not supported for device (10002) at undefined)

### ISSUE THREAD

**Issue by Uraforclain** [lprhodes/homebridge-broadlink-rm#407]
Hi guys, im in the index.js file in the directory of
node_modules/broadlinkjs-rm/index.js 

and im trying to add my device inside... how do i do that? 

my device is a rm pro + and its serial is starting with a 33220

**Comment by Uraforclain** [comment]
i know im supposed to add a device under "RM devices (with RF support)"
but i don't know the code

like 

rmPlusDeviceTypes[parseInt(?????????, 16)] = 'Broadlink RM3 Pro Plus v2'; //I have a 33220 serial number

**Comment by Uraforclain** [comment]
@lprhodes

**Comment by macinstyle** [comment]
I have the same issue - have you found a solution meanwhile?

**Comment by lprhodes** [comment]
I added a few new devices in the latest version of the plugin.

If you still have an "unknown" device then you should see a message asking you to post the hex code here.
