### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by MsCopernic** [lprhodes/homebridge-broadlink-rm#411]
Hi, today I installed Homebridge and your plugin in my MAC. As soon as I open Homekit in my phone, I get the following error from Homebridge:

[2018-7-24 15:40:59] [Broadlink RM] Scan Frequency getSwitchState: undefined
[2018-7-24 15:40:59] [Broadlink RM] Learn getSwitchState: undefined

Regards.

**Comment by MsCopernic** [comment]
Hi, I will appreciate some help with this.

**Comment by cubilon** [comment]
Post your config, guys

**Comment by MsCopernic** [comment]
Hi Cubillos, following find the content of my config file:

    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Homebridge",

    "accessories": [
    ],

    "platforms": [
      {
        "platform":"BroadlinkRM",
        "name":"Broadlink RM",
        "hideScanFrequencyButton": false,
        "hideLearnButton": false,
        "hideWelcomeMessage": false
      }
    ]
}

Thanks for your time.

**Comment by MsCopernic** [comment]
Hi Cubilon, following find the content of my config file:

    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Homebridge",

    "accessories": [
    ],

    "platforms": [
      {
        "platform":"BroadlinkRM",
        "name":"Broadlink RM",
        "hideScanFrequencyButton": false,
        "hideLearnButton": false,
        "hideWelcomeMessage": true
      }
    ]
}

Thank you for your time.

**Comment by cubilon** [comment]
I would change as follow:

> {
> 	"bridge": {
> 		"name": "Homebridge",
> 		"username": "CC:22:3D:E3:CE:30",
> 		"port": 51826,
> 		"pin": "031-45-154"
> 	},
> 
> 	"description": "Homebridge",
> 
> 	"accessories": [],
> 
> 	"platforms": [{
> 		"platform": "BroadlinkRM",
> 		"name": "Broadlink RM",
> 		"hideScanFrequencyButton": true,
> 		"hideLearnButton": false,
> 
> 		"accessories": [{
> 			"accessory": "Broadlink RM Learner",
> 			"name": "Learn IR",
> 			"type": "learn-code",
> 			"host": "192.168.1.90"
> 		}]
> 	}]
> }

**Comment by MsCopernic** [comment]
Hi Cubilon, works perfect, I have one Broadlink RM Pro Plus, and was discovered as soon as Homebridge launched. Thank you very much. About the host parameter, why do you use that IP? Please excuse my questions, but all this is completely new for me.

**Comment by MsCopernic** [comment]
Never mind. now I know that it's the IP of the Broadlink Device, But now I have another question, I used the learning button and created the following control:

        {
          "name":"TV On/Off",
          "type":"switch",
          "data":
         {
            "on":"26008c0095......",
            "off":"26008c0095......"
          }

After saving my config file and  restarting HomeBridge and HomeKit  where should those buttons appear in HomeKit?

**Comment by MsCopernic** [comment]
Ok, reading somewhere else, and following your instructions, I changed "TV On/Off" with "television". "on" with "encender" and  "off" with "apagar" (my native language is Spanish). So once again, should't I see this buttons in HomeKit before being available via Siri?.

**Comment by cubilon** [comment]
I use the IP just for a fast recognize when I read the config file, btw we can use the MAC address with no problems about it :)

Yes: you should see that new button on favourites items list. If it doesn't happend, remove the bridge on Home app, then re-add it.

**Comment by MsCopernic** [comment]
Hi Cubilon, I did as you told me but the buttons are not there, after re adding the bridge, once again the only I can see is the bridge and the learning button. Something else to check?

![img_0420](https://user-images.githubusercontent.com/359983/43588364-f5fd35b6-9631-11e8-8c96-9565f65254b2.jpg)

**Comment by MsCopernic** [comment]
Solved. Thanks for your help
