### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by jesusmarcos** [lprhodes/homebridge-broadlink-rm#412]
Hi. I have been working with homebridge-broadlink-rm in homebridge installed in windows 10 for a while with no issues.

I decided to move all to Raspberry Pi 3 b+ (with Raspbian) and everything went fine until I installed the plugin.

Everytime I try to install it I get the following error messages:

npm ERR! tar.unpack untar error /root/.npm/chai/4.1.2/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules'
npm ERR! error rolling back  homebridge-broadlink-rm@3.5.5 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.52-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-broadlink-rm"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

I install it with the command "sudo npm install -g homebridge-broadlink-rm".

Any help with that?

Many thanks in advance

**Comment by lumaxis** [comment]
@jesusmarcos Your version of `npm` is ancient, I would highly recommend to try upgrading that first

**Comment by jesusmarcos** [comment]
Hi @lumaxis. Thanks for your reply.

I already tried to update npm with the same result.

Finally I used another image of Raspbian that had homebridge installed and it worked, so I'll close the issue because probably was something related to the version I was using.

Now it's working again as it was in my Windows PC.

Many thanks.

Jesús.

**Comment by jesusmarcos** [comment]
Solved using another version of Raspbian.

**Comment by pablos1rvent** [comment]
I got this error too, I tried to update node and it worked...
