### ISSUE TITLE
anyway to link to accessories? like if then ac is on , the ac fan accessory should be on?

### ISSUE THREAD

**Issue by mahdi89X** [lprhodes/homebridge-broadlink-rm#414]
anyway to link to accessories? like if then ac is on , the ac fan accessory should be on?
it an ir.. so ir cannot know the status of the ac.. in normal circumstances homekit auto detect by the status of the device.. but here there is no feedback
anyway way to link to accessories?
ac+ac fan ?

**Comment by dudusandi** [comment]
Using the homekit automation, like ipad or apple tv
