### ISSUE TITLE
Issue setting AC Temperature

### ISSUE THREAD

**Issue by mj0500** [lprhodes/homebridge-broadlink-rm#415]
Hi, i'm having an issue when trying to set the temperature with an Air Conditioner. Here is the error I am getting:

[8/1/2018, 11:44:04 PM] [Broadlink RM] Bedroom AC setTargetTemperature: 19
[8/1/2018, 11:44:04 PM] [Broadlink RM] Bedroom AC Potential sendTemperature (19)
[8/1/2018, 11:44:05 PM] [Broadlink RM] Bedroom AC sendTemperature (19
(node:1381) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at catchDelayCancelError (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:52:40)
    at catchDelayCancelError (/usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:50:11)
    at AirConAccessory.sendTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:260:16)
    at <anonymous>:null:null

(node:1381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 56)

My config.json is here:

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"platforms": [
    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "accessories":[
        {
          "name":"Bedroom AC",
          "type":"air-conditioner",
          "minTemperature":10,
          "maxTemperature":25,
          "turnOnwhenOff":true,
          "pseudoDeviceTemperature":21,
          "defaultCoolTemperature":21,
          "data":{
            "off":"260076006f33100c100b1027100b1027100b100c100c10261026100c100c$
            "on":"260006016e33100c100b1027100b1027100c100b100c10261027100b100c1$
            "temperature18":"260006016f33100c100b1027100b1027100b100c100c102610$
            "temperature19":"260006016e33100c100b1126100b1126100c100b100c102610$
            "temperature20":"260006016e34100b100c1026100c1026100c100c100b102710$
            "temperature21":"260006016e33100c100c1026100c1026100c100b100c102610$
            "temperature22":"260006016e33110b100c1026100c1026100c100b100c102611$
            "temperature23":"260006016e33100c100c1026100c1026100c100b100c102610$
            "temperature24":"260006016e33100c100c1026100c1026100c100b100c102610$
            "temperature25":"260006016e34100b100c1026100c1026100c100c100b102710$
          }
        }
      ]
    }
  ]
}

Anyone have any ideas?

Thanks!

**Comment by dudusandi** [comment]
You have to create another object with data, inside put the temps.

**Comment by mj0500** [comment]
I'll give that a shot, thank you

**Comment by lululombard** [comment]
I have the exact same issue with [this config](https://pastebin.com/WEYD9d0w).
Here's the traceback:
```
[2018-8-18 23:16:10] [Broadlink RM] Air conditionner sendTemperature (22
(node:6950) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at catchDelayCancelError (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:52:40)
    at catchDelayCancelError (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:50:11)
    at AirConAccessory.sendTemperature (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:260:16)
    at <anonymous>
(node:6950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)
```

**Comment by mj0500** [comment]
Hi dudusandi, could you clarify for me what you mean by a separate object?

The config output that I pasted in my original post truncated the IR codes since they're very long, each code is terminated with ", even though it's not shown there to define each separate code, is there something else I need to insert?

**Comment by dudusandi** [comment]
"name" : "Ar Condicionado",
          "type" : "air-conditioner",
          "maxTemperature" : 24,
          "defaultCoolTemperature" : 19,
          "defaultHeatTemperature" : 23,
          "pseudoDeviceTemperature" : 20,
          "autoHeatTemperature" : 20,
          "data" : {
            "off" : "26004000680001471035101210121013103411121012101210360f35101310121012101310121012101210131012101210130f3510130f35101310121012103411000d050000000000000000",
            "temperature18" : {
              "data" : "26004000680001471034111210130f13103410130f1310121013101210131012111210121035113310130f131034103410130f1311120f130f131034113410130f000d050000000000000000",
              "pseudo-mode" : "cool"
            },
            "temperature19" : {
              "data" : "2600400067000147123310130f13101210351012101310130f1310130f131012101310130f3610341012103510121012111110130f131012101310341035103510000d050000000000000000",
              "pseudo-mode" : "cool"
            },
            "temperature20" : {
              "data" : "260040006800014612341111101310121034111210130f13101310121013111110130f13103510351012103410130f3510130f1310121013103410130f13101211000d050000000000000000 ",
              "pseudo-mode auto" : "cool"
            },
            "temperature21" : {
              "data" : "260040006800014710341112101211120f360f1310121012101210130f13101210121012103510350f1310351035101210130f13101210130f3411121012103510000d050000000000000000",
              "pseudo-mode " : "cool"
            },
            "temperature22" : {
              "data" : "260040006800014711340f1310130f131034111210121013101310121013101210130f13103411341013103411340f35111110130f13101210350f1310350f1310000d050000000000000000",
              "pseudo-mode " : "heat"
            },
            "temperature23" : {
              "data" : "26004000670001461135111110131012103411121013101210130f13101310121013101210341134103510130f1310130f13101211111112103411120f35103411000d050000000000000000",
              "pseudo-mode " : "heat"
            },
            "temperature24" : {
              "data" : "260040006700014611351012101310130f3510121013101210131012101310130f1310121034113411350f13101210341112101310130f13103411341012101310000d050000000000000000",
              "pseudo-mode " : "heat"

**Comment by dudusandi** [comment]
Use JSON editor for windows, or Smart JSON for mac ,it's so much easier.

**Comment by dudusandi** [comment]
![screenshot_1](https://user-images.githubusercontent.com/41707380/44326720-f0cbac80-a432-11e8-8cd6-aca524612b85.jpg)

**Comment by mj0500** [comment]
Thanks so much, this did the trick. Really appreciate your help!
