### ISSUE TITLE
Installing on Raspberry PI

### ISSUE THREAD

**Issue by MsCopernic** [lprhodes/homebridge-broadlink-rm#416]
Hi, after completing my house automation using a MAC, now I pretend to move HomeBridge & this plugin to a Raspberry Pi, makes no sense to me to have a computer running 24/7 just for this service ... I have tried twice the installation, but when trying to install the plugin, the installation fails. Are there version limitations with the latest Raspbian version?

Thanks in advance for any advice you can give me ..

**Comment by dudusandi** [comment]
I use with raspberry pi and everythings works great.. Remember to install with -g like 

sudo npm install -g homebridge-broadlink-rm

**Comment by MsCopernic** [comment]
Perfect !! Thank you very much @dudusandi .
