### ISSUE TITLE
Tv switch not working

### ISSUE THREAD

**Issue by rapsody2000** [lprhodes/homebridge-broadlink-rm#419]
Hi!
After succesfully set up of air conditioner, i added tv switch in my config json

{
          "host" : "10.0.1.80",
          "name" : "TV On/Off",
          "type" : "switch",
          "data " : {
            "on " : "26008c00949115351435153514111411141015101510143614351535141114101510141114111410153514111411141015101411141114351510143614351535143515351436140005f894921435153514351510151014111411141015351435153514111411141015101411141114351510141114111410151014111436141015351436143514361435153514000d05000000000000000000000000",
            "off " : "26008c00949214351535143515101510151014111410153514351535151014111411141015101510143515101510141114111410151015351410153514361435153514351535150005f893921435153515351411141015101510141114351535143515101510141114111410151015351411141015101411141114101535141114351535143515351535143515000d05000000000000000000000000"
          }
        },

Although home app recognize it no hex command are sent by broadlink device to tv... Host address is correct. Where am I wrong??

**Comment by kiwi-cam** [comment]
Have you tried without the Host parameter (using auto discover)? It looks fine to me but that Host parameter is a difference.  I don't supply a host since I only have one Broadlink device.

Do you have it correctly placed inside the BroadlinkRM platform's accessories section?

Here's the config for my TV switch:
`            {
                "name": "TV",
                "type": "switch",
                "pingIPAddress": "192.168.21.55",
                "pingFrequency": 5,
                "pingIPAddressStateOnly": true,
                "disableLogs": true,
                "data": {
                    "on": "2600d200949....",
                    "off": "2600d200949...."
                }
            }`

Note the simpler name too. Siri will work better with "_Turn the TV on_" than "_Turn the TV On/Off On_"

**Comment by dudusandi** [comment]
You need create a object data. Use a smart editor for JSON:

          "name":"TV On/Off",
          "type":"switch",
          "data":{
            "on":"2600500000012...",
            "off":"2600500000012..."

**Comment by rapsody2000** [comment]
what is exactly the difference between my json 
{
 "host" : "10.0.1.80",
 "name" : "TV On/Off",
 "type" : "switch",
 "data " : {
 "on " : "26008c00949115351435153514111411141015101510143614351535141114101510141114111410153514111411141015101411141114351510143614351535143515351436140005f894921435153514351510151014111411141015351435153514111411141015101411141114351510141114111410151014111436141015351436143514361435153514000d05000000000000000000000000",
 "off " : "26008c00949214351535143515101510151014111410153514351535151014111411141015101510143515101510141114111410151015351410153514361435153514351535150005f893921435153515351411141015101510141114351535143515101510141114111410151015351411141015101411141114101535141114351535143515351535143515000d05000000000000000000000000"
 }
 },

and that posted by you?
Json is valid (jsontlint formatted), it simply does not send any on or off code. The broadlink is recognized correctly as it works for Learning codes...

It seems that somewhat prevent switch from sending on and off codes.

**Comment by rapsody2000** [comment]
Nothing to do... I learn codes for MySKY decoder and set up an analogue switch but on/off commands are not sent... orange light of RM pro does not blink. Maybe hex codes are uncorrect? Somewhere I read the doubling the codes (pasting code 2 times) helped but not in my case. RM pro is recognized, in fact learn code was performed with it.

WHY???? :-(

**Comment by Reddyzinho** [comment]
Same problem here. I have the Broadlink RM MINI 3 and RM PRO, and cant get this working. Only the RM PRO uses the RF and not sending the IR frequencies, and the RM 3, sends the IR. 

Any idea?

**Comment by lprhodes** [comment]
@rapsody2000  Hey, the configs look right, if you're still seeing issues let me know and re-open this issue.

@Reddyzinho can you create a new issue please with more detail.
