### ISSUE TITLE
New install problem

### ISSUE THREAD

**Issue by PianSom** [lprhodes/homebridge-broadlink-rm#42]
Hi

I am trying out this plugin for the first time. Even with no amendments to my config.json I get the following errors in my homebridge log output:

Apr 09 18:05:58 raspberrypi homebridge[10067]: [4/9/2017, 6:05:58 PM] ====================
Apr 09 18:05:58 raspberrypi homebridge[10067]: [4/9/2017, 6:05:58 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
Apr 09 18:05:58 raspberrypi homebridge[10067]: [4/9/2017, 6:05:58 PM] /usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:34
Apr 09 18:05:58 raspberrypi homebridge[10067]: async setCharacteristicValue (props, on, callback) {
Apr 09 18:05:58 raspberrypi homebridge[10067]: ^^^^^^^^^^^^^^^^^^^^^^
Apr 09 18:05:58 raspberrypi homebridge[10067]: SyntaxError: Unexpected identifier
Apr 09 18:05:58 raspberrypi homebridge[10067]: at Object.exports.runInThisContext (vm.js:76:16)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at Module._compile (module.js:542:28)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at Object.Module._extensions..js (module.js:579:10)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at Module.load (module.js:487:32)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at tryModuleLoad (module.js:446:12)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at Function.Module._load (module.js:438:3)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at Module.require (module.js:497:17)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at require (internal/module.js:20:19)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:1:92)
Apr 09 18:05:58 raspberrypi homebridge[10067]: at Module._compile (module.js:570:32)
Apr 09 18:05:58 raspberrypi homebridge[10067]: [4/9/2017, 6:05:58 PM] ====================

Any suggestions?

Also - it would be helpful to see a suggestion for config.json for first setup. :) 

Thanks

**Comment by PianSom** [comment]
I should mention - for completeness - that I had attempted to make changes to config.json first, but could not get it to work.

**Comment by danielsamwel** [comment]
I am having the same issue after upgrading to 1.19. I think there's an accidental error in the code.

**Comment by danielsamwel** [comment]
You need to make sure you're running node 7.6.0 or above. Check your version with `node -v`

**Comment by PianSom** [comment]
Ah. You mean like it says, cunningly hidden, at the top of the README.  :) 

Sorry!

**Comment by PianSom** [comment]
Sadly, updating to 7.8 (the current version) of node made homebridge break - 
Apr 10 07:46:35 raspberrypi homebridge[1077]: /usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
Apr 10 07:46:35 raspberrypi homebridge[1077]: throw ex;
Apr 10 07:46:35 raspberrypi homebridge[1077]: ^
Apr 10 07:46:35 raspberrypi homebridge[1077]: Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
Apr 10 07:46:35 raspberrypi homebridge[1077]: was compiled against a different Node.js version using
Apr 10 07:46:35 raspberrypi homebridge[1077]: NODE_MODULE_VERSION 48. This version of Node.js requires
Apr 10 07:46:35 raspberrypi homebridge[1077]: NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
Apr 10 07:46:35 raspberrypi homebridge[1077]: the module (for instance, using `npm rebuild` or`npm install`).
Apr 10 07:46:35 raspberrypi homebridge[1077]: at Object.Module._extensions..node (module.js:598:18)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at Module.load (module.js:488:32)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at tryModuleLoad (module.js:447:12)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at Function.Module._load (module.js:439:3)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at Module.require (module.js:498:17)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at require (internal/module.js:20:19)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at Module._compile (module.js:571:32)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at Object.Module._extensions..js (module.js:580:10)
Apr 10 07:46:35 raspberrypi homebridge[1077]: at Module.load (module.js:488:32)
Apr 10 07:46:35 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE


npm rebuild seemed ineffective. Any suggestions?

**Comment by PianSom** [comment]
Spoke too soon - needed to uninstall and install homebridge

This posted for any other lost souls
