### ISSUE TITLE
Bug with A/C MQTT temperature

### ISSUE THREAD

**Issue by cubilon** [lprhodes/homebridge-broadlink-rm#421]
Hi @lprhodes, seems there's some kind of problem with MQTT temperature in your plugin's a/c accessory.

I got two different accessories: one a/c (defined with your plugin, that gets current temperature from a MQTT sensot's topic) and a temperature sensor defined with this plugin:

https://github.com/MacWyznawca/homebridge-mqtt-temperature-tasmota

Look: with a temperature like 28.8 (as shown below), the temperature sensor in HomeKit shows a correct rounded valure of **29 degrees**, while your a/c accessory show an erroneous integer (seems like a truncated integer value) **of 28**:

![img_0036](https://user-images.githubusercontent.com/32951634/44274071-843d8b80-a241-11e8-8d7a-43cb54325244.PNG)
![img_0035](https://user-images.githubusercontent.com/32951634/44274079-87387c00-a241-11e8-9c6a-4811a8d1dd49.jpg)

Can we solve it?
Let us know, thanks a lot!
cubilon

P.S. don't look at the "tado" temperature. That sensor is another one not placed in the same place of the tasmota one.

**Comment by kiwi-cam** [comment]
Is this not the same rounding issue we discussed in #401 ?

**Comment by cubilon** [comment]
What I really don't understand is WHERE is the problem. I mean: if the problem is that homekit a/c accessory don't round the value but truncate that, a workaround must be rounding that before sending that from the plugin to Home app; if it's a matter of plugin in, that must be solved. In both cases, we need @lprhodes.

**Comment by lprhodes** [comment]
Finally fixed in the latest release
