### ISSUE TITLE
How to make the temperatureFilePath work?

### ISSUE THREAD

**Issue by EthanChoy** [lprhodes/homebridge-broadlink-rm#423]
Hi. Thank you for the plugin you made.
I have a mini3. I have a DHT22 working on my raspberry pi. Could the temperature monitor use its data?
Thanks.

**Comment by dudusandi** [comment]
acc

**Comment by EthanChoy** [comment]
@dudusandi What is acc？

**Comment by dudusandi** [comment]
I'm following your issue, I have the same doubt.

**Comment by kiwi-cam** [comment]
Assuming you can write the temperature data to a file, you should be able to get it to work - and it looks like you could use AdafruitDHT.py to do this.

I use a DS18B20 temperature sensor connected to the GPIO ports on my Homebridge Raspberry Pi to do something similar.  Setup a cron job to write the temperature to a text file, for me I use this:
`*/5 * * * *	tail -n 1 /sys/bus/w1/devices/xxxxxxxxxxxxx/w1_slave | awk -F t= '{print $2/1000}' > /var/tmp/inside.txt`
_This runs every five minutes, gets the first line of output from /sys/bus/w1/devices/xxxxxxxxxxxxx/w1_slave (xxxxxx being a unique code for my device), then awk splits the string and takes the text after t= and devides it by 1000 and pushes it to /var/tmp/inside.txt._

Then setup your config.json to use "temperatureFilePath": "/var/tmp/temperaturefile.txt". Here's mine:
```
 "accessories": [{
                "name": "Heat Pump",
                "type": "air-conditioner",
                "ignoreTemperatureWhenOff": true,
                "temperatureUpdateFrequency": 10,
                "temperatureFilePath": "/var/tmp/inside.txt",
                "turnOnWhenOff": false,
                "allowResend": true,
                "preventResendHex": true,
                "defaultCoolTemperature": 20,
                "defaultHeatTemperature": 22,
                "data": {...
```

**Comment by kiwi-cam** [comment]
Cool, this should be straight forward.  Ignore the /sys/bus/w1/devices/xxxxxxxxxxxxx/w1_slave stuff I use, that for the 1 wire sensor I use.

Assuming that when you run AdafruitDHT.py with the GPIO pins used, you get output like this:
> Temp=18.0 Humidity=46.0%

Then try running `crontab -e` and adding this line:
`*/5 * * * * tail -n 1 AdafruitDHT.py 22 GPIO | awk -F Temp= '{print $2}' | awk -F'[ ]' '{print $1}'> /var/tmp/inside.txt`
This *should* (I can't test this as I don't use a DHT22) run every five minutes getting the DHT Reading. Grab the test after "Temp=", and grab the text before a space, then output it to /var/tmp/inside.txt.

I'm not 100% certain on the arguments AdafruitDHT.py uses so adjust as required - add the GPIO you're using.

**Comment by EthanChoy** [comment]
@kiwi-cam 
I failed.Can you check for me please?Thank you.
![1](https://user-images.githubusercontent.com/42546559/44442100-c3cdf400-a602-11e8-8671-44fd3d59016d.PNG)
![2](https://user-images.githubusercontent.com/42546559/44442106-ca5c6b80-a602-11e8-9aed-8b65230994b5.PNG)
Here is my config.json.



          "name":"Air Conditioner",

          "type":"air-conditioner",
          
          "temperatureFilePath": "/var/tmp/inside.txt",

          "data":{……
And then I got this.
![img_4552](https://user-images.githubusercontent.com/42546559/44442173-16a7ab80-a603-11e8-837b-a29e087f0971.PNG)
How to fix it?

**Comment by kiwi-cam** [comment]
Sorry, I made a late edit which you’ve missed. You won’t need the tail -n 1 part - check my comment above to update it. 

You can try running
 AdafruitDHT.py 22 GPIO | awk -F Temp= '{print $2}' | awk -F * '{print $1}' 
to check that it gives you the temperature number alone. 

Also try running ‘cat /var/tmp/inside.txt’ and make sure the text file is being updated correctly.

**Comment by kiwi-cam** [comment]
I'm finally sitting at a computer to confirm my syntax.  There was an error in the awk syntax but this should work:
`/home/pi/Adafruit_Python_DMT/examples/AdafruitDHT.py 22 4  | awk -F Temp= '{print $2}' | awk -F "*" '{print $1}'`

That should give you just the current temperature. If it does try this in the cron job:
`*/5 * * * *    /home/pi/Adafruit_Python_DMT/examples/AdafruitDHT.py 22 4  | awk -F Temp= '{print $2}' | awk -F "*" '{print $1}' > /var/tmp/inside.txt`
Looking at some python examples you may need to update the cron job to this (adding python):
`*/5 * * * *    python /home/pi/Adafruit_Python_DMT/examples/AdafruitDHT.py 22 4  | awk -F Temp= '{print $2}' | awk -F "*" '{print $1}' > /var/tmp/inside.txt`

**Comment by EthanChoy** [comment]
@kiwi-cam 
Wow!It works.Thank you so much.
But I got a new problem now.
![1](https://user-images.githubusercontent.com/42546559/44445934-90489500-a615-11e8-8508-f19acde23f2a.PNG)
![img_4553](https://user-images.githubusercontent.com/42546559/44445935-92125880-a615-11e8-82c9-b1f05d014f54.PNG)
It seems they don't dispaly the same number.Can it be fixed?

**Comment by EthanChoy** [comment]
@kiwi-cam 
Got it.Thanks a lot for your help.Problem solved.

**Comment by lay55** [comment]
Can I get the data readings from a json file?

**Comment by shadowdavis** [comment]
@EthanChoy
这个问题我碰到了也很棘手，弄了半天也不行，现在那个温度和我的传感器温度冲突了，homekit默认都是显示空调的那个固定温度，想找你请教一下，麻烦能给个你的联系方式吗，万分感谢！或者不方便留这能回我个邮件吗，daixuying@gmail.com 感恩！

**Comment by lprhodes** [comment]
Hey, rounding issue is fixed in the latest release. I'm glad you got a working solution.

**Comment by Naqsaq** [comment]
> Im using a Mi bluetooth sensor which even saves temperature and humidity readings to a json file. I do not know how to get the data readings from that json file?

I'm also interested in this. We need the interaction with Broadlink-RM and https://github.com/hannseman/homebridge-mi-hygrothermograph - how would I go about this? @kiwi-cam any hints?
