### ISSUE TITLE
Total .Json Config file newb. Please help with this config :/

### ISSUE THREAD

**Issue by scoobyed1** [lprhodes/homebridge-broadlink-rm#424]
I apologize as I'm a total newbie when it comes to coding and I've tried for hours. I managed to create a simple config.json that has been working to turn my projector on and off, which is all i needed the broadlink homebridge for.

Now, I'm trying to add my air conditioner unit so I can turn it on and off while I'm away from the house, but I can seem to integrate the two lines of code. I've attached my first, working .json file, and then I'll paste what I'm trying to config.

Please, any help would be appreciated marrying the two so it's a valid .json file ?

Current json file:
[jsonformatter (3).txt](https://github.com/lprhodes/homebridge-broadlink-rm/files/2304747/jsonformatter.3.txt)

trying to add this code:

{
	          "name”:”AC On/Off",
	          "type":"switch",
	          "data":{
	            "on":"260066007036100d0d29100d0e290f0d0e2a0e0d0e290f0e0d290f0e0d290f2a0d0f0d290f0e0d290f290e290f290e0e0e0e0e2a0d290f0e0d0f0d0e0e0e0e290e0e0e0e0e0e0d0f0d290f0e0d290f290e0e0e0e0e290e290f0e0d0f0d0e0e290e2910290e2810000d050000",
	            "off":"260066007036100d0d29100d0e290f0d0e2a0e0d0e290f0e0d290f0e0d290f2a0d0f0d290f0e0d290f290e290f290e0e0e0e0e2a0d290f0e0d0f0d0e0e0e0e290e0e0e0e0e0e0d0f0d290f0e0d290f290e0e0e0e0e290e290f0e0d0f0d0e0e290e2910290e2810000d050000"
	          }
	        },
	        {
	          "name”:”Temp Up",
	          "type":"switch",
	          "data":"2600660070370f0d0e290f0d0f280f0d0f280f0d0f290f0d0e290f0d0e290f290e0d0f290f0d0e290f280f290f280f0d0f0d0f280f290f0d0e0d0f0d0f0e0e280f0d0f0d0f0e0d290f280f0d0f290f280f0d0f0d0e290f290e0d0f0d0f0d0f0e0d290f290e290f000d050000",
	          "enableAutoOff": true,
	          "onDuration": 1
	        },
	        {
	          "name”:”Temp Down",
	          "type":"switch",
	          "enableAutoOff": true,
	          "onDuration": 1,
	          "data":"2600660071360f0c0f290f0d0e290f0d0e290f0d0f280f0d0f290e0d0f290e290f0d0f290e0d0f290e2910280f280f0d0f0d0e2a0e290e0d0f0d0f0d0e0e0e290f0d0e0e0e0d0f0d0f0d0e0e0e290f290e0d0f0d0f280f290e0e0e0e0e0d0f290e0d0f290e290f000d050000"
	        },
	        {
	          "name”:”High”,
	          "type":"switch",
	          "enableAutoOff": true,
	          "onDuration": 1,
	          "data": [
	            {
	              "data": "260066006f380e0d0f280f0d0f290e0d0f290e0e0e2b0c0e0e290f0d0f280f290f0d0e290f0d0e290f290e290f290e0e0e0d0f290e290f0d0f0d0e0e0e0d0f290e0d0f0d0f0d0e290f290e0e0e290f290e290f0d0e290f290e0e0e0d0f0d0e0e0e0d0f290e290f000d050000",
	              "sendCount": 1,
	              "interval": 0.3
	            }
	          ]
	        },
	        {
	          "name”:”Medium“,
	          "type":"switch",
	          "enableAutoOff": true,
	          "onDuration": 1,
	          "data": [
	            {
	              "data": "260066007036100c0f28100c10280f0d0f280f0d0f28100c0f28100c10280f28100c0f28100c0f290f280f280f290f0d0e0e0e290f280f0d0f0d0e0e0e0d0f290e0e0e0e0e0d0f0d0e0e0e290f290e290e2a0e0d0e2a0e290e0e0c100c100d2a0d2a0e0e0d2b0d000d050000.",
	              "sendCount": 1,
	              "interval": 0.3
	            }
	          ]
	        },

{
	          "name": “A/C Fan",
	          "type": "fan",
	          "data": {
	            "on":"260066006f370f0d0e290f0d0f290e0d0f290e0d0f290f0d0e290f0d0e290f290e0e0e290f0d0e290f290e290f290e0e0e0d0f290e290f0d0e0e0e0d0f0d0f290e0d0f0d0f0d0e0e0d2a0f0d0d2a0f290e290d0f0d2a0e2a0c100c0f0e0e0d2b0e0d0e2a0c2b0e000d050000",
	            "off":"260066007036100d0d29100d0e290f0d0e2a0e0d0e290f0e0d290f0e0d290f2a0d0f0d290f0e0d290f290e290f290e0e0e0e0e2a0d290f0e0d0f0d0e0e0e0e290e0e0e0e0e0e0d0f0d290f0e0d290f290e0e0e0e0e290e290f0e0d0f0d0e0e290e2910290e2810000d050000"
	        
	          }

**Comment by dudusandi** [comment]
[config.zip](https://github.com/lprhodes/homebridge-broadlink-rm/files/2304993/config.zip)

**Comment by dudusandi** [comment]
Use an editor like Smart JSON for mac or Json Editor for windows

**Comment by rapsody2000** [comment]
or online editor such Jsonlint
However. I would suggest you to set up clima as "air-conditioner" instead of "switch" type
