### ISSUE TITLE
Temperature from Homekit sensors?

### ISSUE THREAD

**Issue by Partizan7676** [lprhodes/homebridge-broadlink-rm#427]
Luke! Thanks a lot for your plugin!
May be it's time to use temperature data from homekit sensors?

**Comment by rapsody2000** [comment]
Yesss It would be!!
Most of users have at least one of homekit compatible sensor

**Comment by nicknicknickos** [comment]
@Partizan7676 @rapsody2000 I created a solution to this when @lprhodes included an external source for the temp settings in [314](https://github.com/lprhodes/homebridge-broadlink-rm/issues/314). This only works for Hue motion sensors (which include temperature)

**Comment by cubilon** [comment]
you can use node.red to read the value and to be published on MQTT telemetry... than read that telemetry with the plugin.

**Comment by CorcoranEd** [comment]
> you can use node.red to read the value and to publish it as a MQTT telemetry... than can be read with the plugin.

what plugins are you using to do this with node-red?

**Comment by lprhodes** [comment]
Unfortunately this is a limitation in Homekit.
