### ISSUE TITLE
hosts entry crashes plugin

### ISSUE THREAD

**Issue by turbidWaters** [lprhodes/homebridge-broadlink-rm#428]
I am using two broadlink rm pros:
I am trying to use the hosts option to disable discovery and use the mac address for discovery.
I am doing this because I want dynamically assigned (DHCP) ip addresses for the broadlink devices.

ALSO: Note that I want to use the scan frequency and the scan IR, for both the devices. Not sure if I am doing this right in the config. 

Any help is appreciated very much.

Here is my log:
Aug 27 14:10:12 Bridge homebridge[16786]: [8/27/2018, 2:10:12 PM] Loading 1 platforms...
Aug 27 14:10:12 Bridge homebridge[16786]: [8/27/2018, 2:10:12 PM] [Broadlink RM] Initializing BroadlinkRM platform...
Aug 27 14:10:12 Bridge homebridge[16786]: [8/27/2018, 2:10:12 PM] [Broadlink RM] [INFO] Automatic Broadlink RM device discovery has been disabled as the "hosts" option has been set.
Aug 27 14:10:12 Bridge homebridge[16786]: /usr/lib/node_modules/homebridge-broadlink-rm/node_modules/chai/lib/chai/assertion.js:141
Aug 27 14:10:12 Bridge homebridge[16786]:       throw new AssertionError(msg, {
Aug 27 14:10:12 Bridge systemd[1]: homebridge_broadlink.service: Main process exited, code=exited, status=1/FAILURE
Aug 27 14:10:12 Bridge systemd[1]: homebridge_broadlink.service: Unit entered failed state.
Aug 27 14:10:12 Bridge systemd[1]: homebridge_broadlink.service: Failed with result 'exit-code'.

and here is my config.json

{
	"bridge": {
		"name": "Broadlink",
		"username": "xxxxxxxxxx",
		"port": xxxxx,
		"pin": "xxx-xx-xxx",
		"homebridgeDirectory": "/var/lib/homebridge_broadlink"
	},
	"platforms": [{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideScanFrequencyButton": false,
		"hideLearnButton": false,
		"hosts": [
			{			
				"mac": "B4:43:0D:C7:2E:7C",
				"isRFSupported": true
			},
			{
				"mac": "34:EA:34:42:F1:28",
				"isRFSupported": true
			}
		],
	    "accessories": [
			{
				"name": "Living Room Learn",
				"type": "learn-code",
				"host": "B4:43:0D:C7:2E:7C",
				"scanFrequency": false
			},
			{
				"name": "Bedroom Room Learn",
				"type": "learn-code",
				"host": "34:ea:34:42:f1:28",
				"scanFrequency": false
			},
			{
				"name": "Channel Information",
				"type": "switch",
				"host": "0d:43:b4:c7:2e:7c",
				"enableAutoOff": true,
				"onDuration": 6,
				"data": {
					"on": [{
							"data": "260098000...",
							"pause": 4
						},
						{
							"data": "260098000...",
							"pause": 4
						},
						{
							"data": "..."
						}
					]
				}
			},.....

**Comment by cubilon** [comment]
remove:

```
"hosts": [
{
"mac": "B4:43:0D:C7:2E:7C",
"isRFSupported": true
},
{
"mac": "34:EA:34:42:F1:28",
"isRFSupported": true
}
],
```

block.

**Comment by chietanjain** [comment]
thank you @cubilon for the quick response!
its working if I remove the hosts block, but I am not able to get both the IR Learn and the RF learn switches to appear in the home app. I added the hosts entry hoping that both the IR and RF learn buttons would appear. But, only the IR learn buttons for both the devices appear in the home app.

Should I raise another issue?

**Comment by cubilon** [comment]
I think you may add only one learner, try this way
