### ISSUE TITLE
MAC address under "Host" is wrong capture

### ISSUE THREAD

**Issue by lily148** [lprhodes/homebridge-broadlink-rm#43]
I believe the MAC for the 'host' configuration at config.json capture wrongly.
After checking from the error log, it seem like first and third number had been swap.
Actual MAC: AA:BB:CC:DD:EE
At the config reading MAC is : CC:BB:AA:DD:EE

**Comment by lprhodes** [comment]
Thanks lily - my AA and CC are equal hence the mess up!

run `npm i broadlinkjs@"git+https://github.com/lprhodes/broadlinkjs.git" -g` and you should be good to go
