### ISSUE TITLE
Enable AutoOff works randomly

### ISSUE THREAD

**Issue by MsCopernic** [lprhodes/homebridge-broadlink-rm#432]
The following sample is one of many defined switches that I have in which AutoOff is set to true. In many cases, I have noticed that after pressing a switch, it remains on (like this one for example) and the only way to turn it off is by touching it again:

      	{
      	  "name":"TV_1 HDMI2",
      	  "type":"switch",
          "host":"34:ea:34:42:fa:5c",
      	  "enableAutoOff": true,
      	  "onDuration": 0.5,
      	  "data":"0000 006D 0000 0022 00AC 00AC 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 0689"
      	},

Any idea?

Thanks in advance

**Comment by lprhodes** [comment]
Hey @MsCopernic are you still experiencing this? If so, please re-open and I'll work with you to try figure out the issue.
