### ISSUE TITLE
pingIPAdress, pingIPAddressStateOnly

### ISSUE THREAD

**Issue by MsCopernic** [lprhodes/homebridge-broadlink-rm#438]
Hi, has anyone implemented a switch using this keys? How do they work?

**Comment by kiwi-cam** [comment]
Yep. I have them setup for my TV and Home Theatre. For the TV I ping the ChromeCast, powered by the TV's USB port. If the ChromeCast is online, I know that the TV is on.  My Home Theatre is connected to the network too so it is a reliable test to confirm its power status.  What do you want to know?  Below is the config I use for these (The Home Theatre is called Radio and the On sequence powers it on and changes the mode to Radio).

Basically, you supply the pingIPAddress and homebridge will ping this address to query the status of the device. If the device responds, it assumed to be in an "On" state. You can also specify pingFrequency to adjust how many seconds between pings.

My understanding of pingIPAddressStateOnly is that, if true, the ping status takes precedence so no "Off" HEX code is sent if the state is already found to be off.

```
{
                "name": "Radio",
                "type": "switch",
                "pingIPAddress": "192.168.1.4",
                "pingFrequency": 5,
                "pingIPAddressStateOnly": true,
                "disableLogs": true,
                "data": {
                    "on": [{
                            "data": "260056009....",
                            "pause": 8
                        },
                        {
                            "data": "26004e009....",
                            "pause": 5
                        },
                        {
                            "data": "26004e009...."
                        }
                    ],
                    "off": "260056009...."
                }
            },
            {
                "name": "TV",
                "type": "switch",
                "pingIPAddress": "192.168.1.5",
                "pingFrequency": 5,
                "pingIPAddressStateOnly": true,
                "disableLogs": true,
                "data": {
                    "on": "2600d2009....",
                    "off": "2600d2009...."
                }
            }
```

**Comment by MsCopernic** [comment]
Hi Kiwi-Cam, thanks for your response, I have been trying to do is to implement a pseudo IFTTT between switches, but this doesn't seems to be the solution. For testing purposes, I cloned (for control purposes) a switch that turns on/off a TV.

I added to the control one the pingIPAdress, ping Frequency (5 secs) and pingIPAdressStateOnly keys, so if I understand you, In theory, if I turn on the first switch with the original one, and after waiting more than ten seconds, I  turn on the second switch, the HEX code should not be send  (the same if I turn off the TV)?

Switches to true (on)

[9/19/2018, 4:21:51 PM] [Broadlink RM] TV_1 On/Off setSwitchState: true
[9/19/2018, 4:21:51 PM] [Broadlink RM] TV_1 On/Off sendHex (192.168.1.69; 34:ea:34:42:fa:5c) 26008c.....

[9/19/2018, 4:22:31 PM] [Broadlink RM] TestTv setSwitchState: true
[9/19/2018, 4:22:31 PM] [Broadlink RM] TestTv sendHex (192.168.1.69; 34:ea:34:42:fa:5c) 26008c

Switches to false (off)

[9/19/2018, 4:23:52 PM] [Broadlink RM] TV_1 On/Off setSwitchState: false
[9/19/2018, 4:23:52 PM] [Broadlink RM] TV_1 On/Off sendHex (192.168.1.69; 34:ea:34:42:fa:5c) 26008c...

[9/19/2018, 4:24:14 PM] [Broadlink RM] TestTv setSwitchState: false
[9/19/2018, 4:24:14 PM] [Broadlink RM] TestTv sendHex (192.168.1.69; 34:ea:34:42:fa:5c) 26008c...

Am I misunderstanding something? Thanks in advance

**Comment by kiwi-cam** [comment]
If all is working correctly, I'd expect the state of the cloned switch should update to "On" automatically once the original switch powers the device on and the device starts responding to pings.

Have you confirmed that the configured IP address responds to pings when the device is on and not when it's off?

In my house the ping config works well when the TV is turned on with the remote the HomeBridge button updates to reflect this status.

**Comment by MsCopernic** [comment]
Hi @kiwi-cam. Yes, I verified and ping works as expected. What you are getting is exactly what I want. Just curious, do you have one or multiple Broadlink devices?

Off:

iMac-de-Jorge:~ jorgelperez$ ping 192.168.1.67
PING 192.168.1.67 (192.168.1.67): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

On:

iMac-de-Jorge:~ jorgelperez$ ping 192.168.1.67
PING 192.168.1.67 (192.168.1.67): 56 data bytes
64 bytes from 192.168.1.67: icmp_seq=0 ttl=64 time=0.624 ms
64 bytes from 192.168.1.67: icmp_seq=1 ttl=64 time=0.373 ms
64 bytes from 192.168.1.67: icmp_seq=2 ttl=64 time=0.398 ms

This one is my cloned switch code

        {
          "name":"TestTv",
          "type":"switch",
          "host":"34:ea:34:42:fa:5c",
          "pingIPAdress":"192.168.1.67",
          "pingFrequency": 5,
          "pingIPAdressStateOnly": true,
          "data":{
            "on":"26008c",
            "off":"26008c"
          }

**Comment by kiwi-cam** [comment]
Assuming that's a copy and paste, I think I've found your issue. There are two d's in Address.

I kind of hope its just a typo that caused the issue because its easy to fix... but I hate when that happens to me - and it does, a lot.

**Comment by MsCopernic** [comment]
Jajajaja, yup !!! That was the problem. Now it's working. Thank you so much for your time.

**Comment by facutopa** [comment]
Hi, just starting to interact with pingIPAddress and I have one question, is possible to use this to get if the TV is on or off and with that update the status/icon of homekit on iOS. So if someone turn on the TV with the remote and you want to turn off the TV with Homekit you have sync the status of the TV on homekit.
I don't know if I explained well the doubt.
