### ISSUE TITLE
How to address multiple RM Broadlinks?

### ISSUE THREAD

**Issue by booshtukka** [lprhodes/homebridge-broadlink-rm#440]
I have two in different rooms, is there a way to address them by IP or MAC address?

**Comment by PanGuolin** [comment]
"name":"电视",
			"type":"switch",
			"enableAutoOff": true,
			"onDuration": 5,
			"host":"192.168.23.206",
			"data":{
				"on":"",
				"off":""
			}

**Comment by lprhodes** [comment]
No, without host it will broadcast just to the first. If you'd like that feature please create a new issue.
