### ISSUE TITLE
How do I add my Broadlink RM Pro Plus

### ISSUE THREAD

**Issue by ethilanka** [lprhodes/homebridge-broadlink-rm#446]
I have installed Homebridge on Raspberry Pi and the service started. But im confused about the config.json file. How do I add my RM Pro + to it? and how do i add the accessories? do i need to write the code for each accessory or else through the HomeKit App can i add?

**Comment by kiwi-cam** [comment]
The config.json file is where all of your setup is held - there is no avoiding it. It's not as scary as it seems.

Start with the sample found [here](homebridge-broadlink-rm/config-sample.json).  By default, it'll probably find your RM Pro+. You may need to edit the "platforms" section if you have multiple RMs - or the discovery fails. Then you need to edit the section under "accessories". This is where your accessories need to be configured. If you do it right, they'll show up in HomeKit. You can't add them any other way.

Check out this page, it goes into more detail: https://lprhodes.github.io/slate/
Also test your config.json in this site to make sure your parentheses are correct: https://jsonlint.com/

If you're still struggling, share your config.json file here and we'll try to help you out.
