### ISSUE TITLE
Is there a way to overwrite on/off state

### ISSUE THREAD

**Issue by kitsuneDEV** [lprhodes/homebridge-broadlink-rm#448]
Hi, first off thanks for the hard work on this plugin!

For my AC i'm using a "fan" accessory instead of the AC example type.

So I have a switch that sets my AC to timer off after half an hour. Which works fine. But the problem with that is that I can't tell the AC (fan button) in homekit that it the machine is off.

I was wondering if I was missing a feature I might be able to use to overwrite the state of the AC fan button.

Can I from a switch accessory set the state of another accessory?

**Comment by bencharlesrhys** [comment]
I would like this feature as it would be good for those times my A/C turns off from something other than HomeKit such as with the standard IR remote controller. The Panasonic Hex Codes for on and off are the same. So I'm sometimes out of sync and having to tell siri to turn the A/C off to turn it on and vice-versa.
