### ISSUE TITLE
Broadlink RM+ discovers but won't show in Home App

### ISSUE THREAD

**Issue by jblakeney82** [lprhodes/homebridge-broadlink-rm#449]
Here is my Config file. Everything else works perfectly minus Broadlink which doesn't show up in Home App. When running Homebridge it shows discovered with IP and MAC etc.. Any ideas?

Here is what is spit out in terminal, 
Initializing BroadlinkRM platform...
[10/19/2018, 2:14:19 AM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
[10/19/2018, 2:14:19 AM] [Broadlink RM] TV On/Off Accessory Ready
[10/19/2018, 2:14:19 AM] [Broadlink RM] Initializing platform accessory 'Learn'...
[10/19/2018, 2:14:19 AM] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...
[10/19/2018, 2:14:19 AM] [Broadlink RM] Initializing platform accessory 'TV On/Off'...
[10/19/2018, 2:14:20 AM] [Broadlink RM] [INFO] Discovered Broadlink RM3 Pro Plus (279d) at 192.168.7x.xx (xx:xx:xx:xx:xx:xx)

Config:

                                           {

                                           	"bridge": {
                                           		"name": "Homebridge",
                                           		"username": "xxxx",
                                           		"port": 51827,
                                           		"pin": "031-45-154"
                                           	},
                                           	"description": "JSON API",
                                           	"platforms": [{
                                           			"platform": "SmartThings",
                                           			"name": "SmartThings",
                                           			"app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
                                           			"app_id": "xxx",
                                           			"access_token": "xxx"
                                           		},
                                           		{
                                           			"platform": "BroadlinkRM",
                                           			"name": "Broadlink RM",
                                           			"accessories": [{
                                           				"name": "TV On/Off",
                                           				"type": "switch",
                                           				"data": {
                                           					"on": "2600500000012...",
                                           					"off": "2600500000012..."
                                           				},

                                           				"accessories": [{
                                           					"accessory": "MagicHome",
                                           					"name": "LED Strip",
                                           					"ip": "192.168.x.xx",
                                           					"setup": "RGBWW",
                                           					"purewhite": false

                                           				}]
                                           			}]

                                           		}
                                           	]
                                           }

**Comment by kiwi-cam** [comment]
What do you mean by "Broadlink which doesn't show up in Home App"? It looks like it's loading the "TV On/Off" switch correctly, do you see this switch in the Home App?

You've also configured the "MagicHome" accessory under your BroadlinkRM platform which won't work.

**Comment by jblakeney82** [comment]
So, I have just been using jsonlint and it says the code is right so I have just been going with that haha not super smart when it comes to this stuff. 

My magic home Light shows up perfectly as a switch in the home app and I can control and change colors etc.. 

The Broadlink RM shows its loading but will not show up in the home app. I have tried deleting homebridge from the home app and re adding but no dice. Tried rebooting Pi and no dice etc..

**Comment by jblakeney82** [comment]
Perhaps the accessory thing you speak of is conflicting with Magic home? Could you assist me with fixing my config file to appropriately separate the accessory from the Broadlink platform?

Thank you!

**Comment by ifeign** [comment]
Give this a try.

```
                                       {

                                       	"bridge": {
                                       		"name": "Homebridge",
                                       		"username": "xxxx",
                                       		"port": 51827,
                                       		"pin": "031-45-154"
                                       	},
                                       	"description": "JSON API",

                                       	"platforms": [{
                                       			"platform": "SmartThings",
                                       			"name": "SmartThings",
                                       			"app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
                                       			"app_id": "xxx",
                                       			"access_token": "xxx"
                                       		},
                                       		{
                                       			"platform": "BroadlinkRM",
                                       			"name": "Broadlink RM",
                                       			"accessories": [{
                                       				"name": "TV On/Off",
                                       				"type": "switch",
                                       				"data": {
                                       					"on": "2600500000012...",
                                       					"off": "2600500000012..."
                                       				}
                                       			}]
                                       		}
                                       	],
                                       	"accessories": [{
                                       		"accessory": "MagicHome",
                                       		"name": "LED Strip",
                                       		"ip": "192.168.x.xx",
                                       		"setup": "RGBWW",
                                       		"purewhite": false
                                       	}]
                                       }
```
