### ISSUE TITLE
Startup problems

### ISSUE THREAD

**Issue by Patrick1610** [lprhodes/homebridge-broadlink-rm#45]
Hi, 

I keep getting startup errors and I don't know what I'm doing wrong. 
Could you guys help me out?

Thanks!
<img width="532" alt="screen shot 2017-04-13 at 18 17 18" src="https://cloud.githubusercontent.com/assets/6585375/25013836/79304862-2075-11e7-8a3c-5b97ef3190b7.png">

<img width="531" alt="screen shot 2017-04-13 at 18 15 58" src="https://cloud.githubusercontent.com/assets/6585375/25013806/4fef9ed0-2075-11e7-988b-35ce6f556820.png">

**Comment by Patrick1610** [comment]
I've updated node/npm to the latest version thinking that was the Problem, but now homebridge won't start at all.. Little bit of panic right now. Anyone who can help? 

<img width="737" alt="screen shot 2017-04-13 at 22 10 05" src="https://cloud.githubusercontent.com/assets/6585375/25022411/fe2cf6b2-2095-11e7-9de4-0e1cd6e62031.png">

**Comment by astrojetson8** [comment]
try this:
sudo npm r homebridge -g
sudo npm i homebridge -g

**Comment by Patrick1610** [comment]
Another question.
Where can I find the logs with the HEX codes after learning? 
i'm on MacOS.

Patrick

**Comment by astrojetson8** [comment]
they should appear in your terminal window.

**Comment by Patrick1610** [comment]
It works like a charm!! Great app and works perfectly with my RM mini. 

Another question: Is it possible for the RM to check the status of my television. 
The remote has a universal on/off button. Now if my tv is off and the RM/homebridge thinks it is on and I ask Siri to turn off all my devices it turns my tv on.

**Comment by astrojetson8** [comment]
no, it's not possible because ir can't get back current status of your tv. time to get a new smarter tv? 
i've tv on smart plug so it makes 9yr old tv a bit smarter. 

@lprhodes luke has done brilliant work!

**Comment by Patrick1610** [comment]
I've got a 2015 LG OLED SmartTV which is smart enough with WebOS 3 but I can only turn it on with the Broadlink because wake on lan doesn't work

**Comment by astrojetson8** [comment]
cool!
i used to work for company that originally designed webOS.

**Comment by Patrick1610** [comment]
Cool!! Any ideas for making it easy to control the LG tv? Would love to have a reliable way to power on the tv, switch to a particular app/Chanel or input (HDMI) with the push of a button or activating a Apple Home Scene.

**Comment by lprhodes** [comment]
@Patrick1610 you' be better off talking to the guys at https://www.npmjs.com/package/homebridge-lgtv2 if you need to get the power status - you won't find that kind of thing through broadlink
