### ISSUE TITLE
RM Pro seems can not be recognized....

### ISSUE THREAD

**Issue by frankliuwei** [lprhodes/homebridge-broadlink-rm#451]
I am using Raspberry + Homebridge to enable the Homekit function, so far, most of devices have been enabled. 
Just the Broadlink is on testing... 

After installing the plug-in, from the log files, it shows:
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4e68". The device is connected to your network with the IP address "192.168.31.218".
......
[2018-10-28 15:05:29] [Broadlink RM] [INFO] Discovered Broadlink RM2 (2712) at 192.168.31.239 (0d:43:b4:30:4b:9c)
.....
[2018-10-28 15:11:24] [Broadlink RM] Learn getSwitchState: undefined
[2018-10-28 15:11:34] [Broadlink RM] [ERROR] Scan RF (RF learning not supported for device (10002) at undefined)
....

the RM pro I brought for many years, any different version on that? RF and IR function are both fine with Broadlink App.

**Comment by lprhodes** [comment]
Hey @frankliuwei. 4e68 is likely some other Broadlink device that's not an RM, that's been discovered on your network. Any idea what that may be?
