### ISSUE TITLE
"Momentary" switch accessory?

### ISSUE THREAD

**Issue by macaddictcr** [lprhodes/homebridge-broadlink-rm#452]
//Edit: I think what I’m looking for is some sort of “Stateless” switch type. I’ve updated my issue to reflect that. //

I was wondering if its possible to make a "momentary" Stateless switch  or button. Meaning that it doesn't create an On/Off toggle switch in the app, but just is a button that triggers the command. 

I am wanting to control some basic IR commands to my TV like mute, power on/off, and discrete source selection.  My request is purely aesthetic in the app of course and is not detrimental to making my IR commands work.

I hope I am asking the right question.

**Comment by kalleboo** [comment]
It doesn't appear that iOS/HomeKit has a momentary switch type if you look at the list of HomeKit accessory categories. Maybe request this one from Apple? https://developer.apple.com/documentation/homekit/hmaccessorycategory/accessory_category_types?language=objc

**Comment by Trippersgarage** [comment]
I'm looking to do something similar, perhaps a toggle switch? Is this something that has to be implemented in the plugin?

**Comment by lprhodes** [comment]
If I've understood correctly, uou can do this with a normal "switch" accessory with `enableAutoOff` and an `offDuration` of `1`
