### ISSUE TITLE
Homebridge Plugin for Broadlink A1 airquality sensor - config sample json missing, need sample url for getting device data

### ISSUE THREAD

**Issue by danniculae1985** [lprhodes/homebridge-broadlink-rm#454]
Does anyone know how a config json will look like foar the broadlink a1 airquality plugin?
https://npm.runkit.com/homebridge-http-airquality
Homebridge asks for an url (where to get the data from) but i have no idea how that url should look like. 

Thanks

**Comment by lprhodes** [comment]
Hey @danniculae1985, sorry but this is beyond what this plugin supports.

**Comment by bobotzzz** [comment]
> Does anyone know how a config json will look like foar the broadlink a1 airquality plugin?
> https://npm.runkit.com/homebridge-http-airquality
> Homebridge asks for an url (where to get the data from) but i have no idea how that url should look like.
> 
> Thanks

@danniculae1985 did you manage to find some plugin for Broadlink A1 air sensor?
