### ISSUE TITLE
TC2 RF code does not send 

### ISSUE THREAD

**Issue by adityachopra8** [lprhodes/homebridge-broadlink-rm#457]
So i have everything setup and my config file is working with my IR aircon and it works perfectly but with my TC2 i am unable to the the command to go to the broadlink itself. So i got the code from the RM plugin and i added it to the config file but when the switch is added and i try turning it on nothing happens the organge light does not even blink on the broadlink. I’ve tried pasting the code twice but still nothing. Any solutions?

**Comment by lprhodes** [comment]
Hey @adityachopra8, if you didn't manage to fix this yourself please post your config here are re-open the issue.
