### ISSUE TITLE
We've discovered an unknown Broadlink device.

### ISSUE THREAD

**Issue by jakguru** [lprhodes/homebridge-broadlink-rm#458]
We've discovered an unknown Broadlink device.

Device code `27c2`

**Comment by iizotov** [comment]
+1. Confirming the issue. Recently purchased RM Mini 3 with device code `27c2`

**Comment by dodds-1** [comment]
+1. Is anyone else able to get the RM Mini 3 to work after receiving this error? I get:

> [ERROR] Learn Code (Couldn't learn code, device not found

**Comment by iewl** [comment]
+1. Confirming this issue. Anyone found anything yet?

**Comment by SteveCohen** [comment]
I can confirm I have been able to get my RM mini (with device code 27c2) to learn and reuse IR codes for my Daikin air conditioner.  Hitting the “learn” button in home app work as expected, wit the code printing to the console output/logs. Am at work now so I can’t check my plugin version, but would be the latest NPM version (as at the time of my first comment—29 days ago)

**Comment by dvcrn** [comment]
Same issue here. Happy to debug

**Comment by dvcrn** [comment]
I had this issue previously as well. I debugged it a bit and happened because of a firewall problem. Connections were blocked

**Comment by lprhodes** [comment]
I've added support for 27c2 into the latest release.
