### ISSUE TITLE
Can we reset Hex code on Broadlink TC2 switch?

### ISSUE THREAD

**Issue by kamum26** [lprhodes/homebridge-broadlink-rm#459]
I have 4 TC2 switches. 3 of them work just fine. But another one got a problem. this one always listens to other switches. Example, If I turn on the broken one only. It can turn on and off, perfectly. Somehow, if I turn on the broken one and turn on or turn off other switches. The broken one also turns off with a little bit delay every time, on any normal switch. It seems like the broken one will turn off on any RF code that it has received. 

So, Can we reset the hex code on the broken one? or it did like that because it's broken?

Please give me some idea.

Thank you in advance.

**Comment by lprhodes** [comment]
Sounds like you'll need to get in touch with Broadlink sorry!

**Comment by MikhailC** [comment]
> I have 4 TC2 switches. 3 of them work just fine. But another one got a problem. this one always listens to other switches. Example, If I turn on the broken one only. It can turn on and off, perfectly. Somehow, if I turn on the broken one and turn on or turn off other switches. The broken one also turns off with a little bit delay every time, on any normal switch. It seems like the broken one will turn off on any RF code that it has received.
> 
> So, Can we reset the hex code on the broken one? or it did like that because it's broken?
> 
> Please give me some idea.
> 
> Thank you in advance.

@kamum26 Have you solve the issue? I have the same problem and looking for a fix.
