### ISSUE TITLE
Dimmable light

### ISSUE THREAD

**Issue by jacobwhite** [lprhodes/homebridge-broadlink-rm#46]
Could you add a dimmable accessory type?

**Comment by jacobwhite** [comment]
Dimmable light* accessory

**Comment by lprhodes** [comment]
Check out [1.3.0](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.3.0) and let me know how it goes!

**Comment by jacobwhite** [comment]
It's working great!

Just got the RM Pro, any way you can make it learn RF codes?

**Comment by lprhodes** [comment]
Awesome

For learning RF - You can follow the enhancement request at https://github.com/lprhodes/homebridge-broadlink-rm/issues/29

**Comment by jacobwhite** [comment]
Cool, thanks. I don't want to deal with wireshark, so I'll just chill until you get rf learning working :)
