### ISSUE TITLE
Show accesory as no response/offline when “no device found” error raises

### ISSUE THREAD

**Issue by iandronowicz** [lprhodes/homebridge-broadlink-rm#460]
It would be nice that when the no device found errror raises the accesory that was meant to be controlled showed as offline or no response. To prevent inconsistent states: in turning on/off the ac or moving the curtains from another room and I’m thinking that everything is alright until I go to the other room and see that the accessories weren’t controlled at all....

**Comment by peros550** [comment]
+1

**Comment by iandronowicz** [comment]
I think this is an issue with the plugin... just now it started to happen with one broadlink, couldn’t get it to work, I even unplugged it and plugged back to power and it didn’t work. It did work from the broadlink app, but not from the home app. I had to restart homebridge and then it started working.

**Comment by lprhodes** [comment]
Hey @iandronowicz are you still seeing this? I'd love to help figure out the issue.

**Comment by lprhodes** [comment]
Please re-open if you'd still like a hand.
