### ISSUE TITLE
the type of device and its device type code: "947a"

### ISSUE THREAD

**Issue by Vovoronale** [lprhodes/homebridge-broadlink-rm#461]
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "947a". The device is connected to your network with the IP address "192.168.1.16".
Smart plug SP3s

**Comment by S474N** [comment]
Same.

SP3s

**Comment by lprhodes** [comment]
Thanks for reporting! These are now ignored in the latest release.
