### ISSUE TITLE
A re-discovered device line in the console is missing the date, time, and [Broadlink RM]

### ISSUE THREAD

**Issue by vraicovi** [lprhodes/homebridge-broadlink-rm#464]
When the plug-in announces something to the console, everything but a re-discovery is prefaced with the date, time, and [Device Name].  When a device is rediscovered, the message just appears on a new line without the aforementioned items.

![image](https://user-images.githubusercontent.com/11246731/50581738-56d92f00-0e2a-11e9-807b-b7eabfc827ab.png)

**Comment by kiwi-cam** [comment]
Just an FYI, this is fixed in https://github.com/AlexanderBabel/homebridge-broadlink-rm. 

I would recommend moving to that fork for other reasons too. The main one being that it still gets some attention while this one appears to be dead - but it also has several new features.

**Comment by lprhodes** [comment]
Thanks for reporting @vraicovi, minor mistake, I've fixed in the latest release.
