### ISSUE TITLE
RF Scanner Hold Button

### ISSUE THREAD

**Issue by mitch7391** [lprhodes/homebridge-broadlink-rm#465]
Is there a way to scan the RF code without having to hold the button on the device down? I am trying to learn the RF hex code for my ceiling fan remote and the act of holding the ‘on’ button down provides a different action from the remote than just pressing the button once without holding it. I believe this is giving me incorrect hex codes. Any ideas on what to do? TIA.

**Comment by lprhodes** [comment]
Unfortunately not, sorry!
