### ISSUE TITLE
Third-party RF remote

### ISSUE THREAD

**Issue by craigdent** [lprhodes/homebridge-broadlink-rm#469]
Is it possible to use a RF frequency remote to activate scenes or devices?

I have a remote control that works on 433 frequency that was for an alarm system. I don’t use the alarm anymore but the remote still works. 

I’ve gotten it to recognise button presses using the learn RF and also got codes. 

But how could I code into homebridge so that when a button on the remote is pressed that a device/scene will activate according to which button I’ve pressed??

**Comment by lprhodes** [comment]
Unfortunately not, RM devices aren't set to receive at all times. I'd really hoped for this too.
