### ISSUE TITLE
RM Pro v1 Device not found "2797" 

### ISSUE THREAD

**Issue by galfaroth** [lprhodes/homebridge-broadlink-rm#470]
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "2797". The device is connected to your network with the IP address "192.168.1.140".

**Comment by S474N** [comment]
Broadlink RM PRO:
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code:                                                                      "4ead". 


BroadLink-Outlet:
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code:                                                                      "947a".

**Comment by S474N** [comment]
Sorry, "4ead" isn't RM Pro, but Thermostat.

**Comment by lprhodes** [comment]
@galfaroth I've added support for the RM Pro you mentioned.

@S474N the plugin should now ignore those two you provided, thanks!
