### ISSUE TITLE
RM Mini Not discovered

### ISSUE THREAD

**Issue by Crox77** [lprhodes/homebridge-broadlink-rm#471]
hi received my Rm mini 3 today installed the plugin ok, when I run Homebridge it loads the plugin I think but the device is not found in the home app!
Any ideas here is my Config file:
{
	"bridge": {
		"name": "Homebridge2",
		"username": "CC:22:3D:E3:CE:31",
		"port": 51826,
		"pin": "031-45-153"
	},
	"accessories": [{
			"accessory": "HiveThermostat",
			"name": "Hive Thermostat",
			"username": "88888@88888.com",
			"password": "8888888"
		},
		{
			"accessory": "SkyQ",
			"name": "Sky Q Lounge",
			"ipAddress": "192.168.0.11"
		},
		{
			"accessory": "SkyQ",
			"name": "Sky Q Bedroom",
			"ipAddress": "192.168.0.23"
		},
		{
			"accessory": "SamsungTV",
			"name": "Samsung TV",
			"ip": "192.168.0.5",
			"mac": "70:2a:d5:8a:ab:af",
			"type": "power"
		}
	],
	"platforms": [{
		"platform": "Camera-ffmpeg",
		"cameras": [{
				"name": "Kitchen Cam",
				"videoConfig": {
					"source": "http://admin:admin@192.168.0.16/videostream.asf",
					"stillImageSource": "http://admin:admin@192.168.0.16/snapshot.cgi",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				},
				"platform": "Camera-iSight",
				"name": "iMac Camera",
				"video_device": "FaceTime HD Camera (Built-in)",
				"fps": 30
			},
			{
				"platform": "BroadlinkRM",
				"name": "Broadlink RM mini 3",
				"hosts": [{
					"address": "192.168.0.17",
					"mac": "c8:f7:42:16:d6:2d",
					"isRFSupported": true
				}],
				"accessories": [{
					"name": "LG TV",
					"type": "switch"
				}]
			}
		]
	}]
}

Thanks for any help

**Comment by Crox77** [comment]
when running Homebridge I also notice this message 
[2/2/2019, 2:41:48 PM] Loaded config.json with 4 accessories and 1 platforms.
[2/2/2019, 2:41:48 PM] ---
[2/2/2019, 2:41:48 PM] Loaded plugin: homebridge-broadlink-rm
[2/2/2019, 2:41:48 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'

Oddly It should show 3 platforms, doesn't seem to show the Broadlink

**Comment by gargamelonly** [comment]
Did you solve it?
I seem to face the same issue.

**Comment by lprhodes** [comment]
Hey, the latest version of this repo now support the various RM Mini 3's that were introduced.
