### ISSUE TITLE
temperature issue 

### ISSUE THREAD

**Issue by curla92** [lprhodes/homebridge-broadlink-rm#472]
Why my hue sensor get 21.5 and on air cond temp is 21? is there a way to set a temp with 0.5 plus? i checked my path file and logs, I see it all right. thanks

**Comment by kiwi-cam** [comment]
I suspect you're seeing the same issue that has been discussed in #421 and #401. I know that's not much help. 

This branch doesn't appear to be in active development so I don't think we'll ever see a fix. If you can't find a work around, there may be another branch where someone else has fixed this issue.

**Comment by mu2004** [comment]
If you have the output in the txt file, it's easy enough to use awk to round it for you:
awk '{printf "%.0f\n", $1}'

**Comment by huongminh** [comment]
Please add this line: temperature = Math.round(temperature);
in the file "aircon.js". You can find it where you install your plugin. The path should look like:
.../node_modules/homebridge-broadlink-rm/accessories

Here is where I put the line in the original file. After adding it, I got the correct rounding of temp in the home app and siri

if (debug) log(`\x1b[33m[DEBUG]\x1b[0m ${name} onMQTTMessage (raw value 2: ${temperature.trim()})`);

    temperature = parseFloat(temperature);

    if (debug) log(`\x1b[33m[DEBUG]\x1b[0m ${name} onMQTTMessage (parsed temperature: ${temperature})`);
  
    temperature = Math.round(temperature);  // added by Minh to round up the temp to the nearest integer
    this.mqttValues[identifier] = temperature;
    this.updateTemperatureUI();

**Comment by kiwi-cam** [comment]
I've been doing a bit of work on the aircon plugin myself lately.  I started by using @huongminh 's suggestion but I'd suggest a better fix is this.
At the bottom of aircon.js replace this (note the minStep):
```
this.serviceManager
      .getCharacteristic(Characteristic.CurrentTemperature)
      .setProps({
        minValue: minTemperature,
        maxValue: maxTemperature,
        minStep: 1
      });

```
With:
```
this.serviceManager
      .getCharacteristic(Characteristic.CurrentTemperature)
      .setProps({
        minValue: minTemperature,
        maxValue: maxTemperature,
        minStep: 0.1
      });
```

This will get Homebridge to pass the temperature with a decimal place so HomeKit can properly round the temperature, and show 0.5 increments.

Or, I'd suggest checking out @AlexanderBabel's fork and my pull request here: https://github.com/AlexanderBabel/homebridge-broadlink-rm/pull/30. 

If you're interested, take a look at the fork (which also includes TV support) and my Pull Request. You can install straight from my pull request using:
npm install -g git+https://github.com/AlexanderBabel/homebridge-broadlink-rm#pull/30/head

**Comment by lprhodes** [comment]
Fixed in the latest release.
