### ISSUE TITLE
Hide switch in homekit

### ISSUE THREAD

**Issue by PieterDes** [lprhodes/homebridge-broadlink-rm#476]
Hi,

is there an option to hide a switch in homekit but still keep it in the config.json ?

I created a bunch of "test" switches and I want to keep them in the config.json for reference but I don't want to see them in the home app.

Any option like "visible: false"  for the switches ?

thanks a lot.

Homebridge rocks !

**Comment by S474N** [comment]
+1

**Comment by tommyd75** [comment]
What I usually do is create a different room and put them in there, just make sure you turn off the "include in favorites" on each one so they don't show up on the main page in the Home app.

**Comment by S474N** [comment]
I have 12 rooms in HomeKit and about 70pcs of accessories. Want rather "visible: false" :D

**Comment by lprhodes** [comment]
Here you go:

https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/3.5.11
