### ISSUE TITLE
Air purifier accessory 

### ISSUE THREAD

**Issue by roberkane212** [lprhodes/homebridge-broadlink-rm#477]
Can we add air purifier to accessory types since it’s issued on the broadlink?

**Comment by roberkane212** [comment]
@lprhodes can we please get air purifier accessory added??

**Comment by avsurdo** [comment]
I’m also interested in this possible functionality.

**Comment by lprhodes** [comment]
Hey, I've added this accessory but I don't have a purifier to test this out on so let me know how it goes.

**Comment by lprhodes** [comment]
https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/3.6.1

**Comment by roberkane212** [comment]
Thanks so much!!
