### ISSUE TITLE
autoCloseDelay option to not send close data

### ISSUE THREAD

**Issue by djsomi** [lprhodes/homebridge-broadlink-rm#479]
Hi Guys,

I would like to request an option for this feature. 
Do not send close hex signal on the end of the timer, only set the satus for homebridge closing and closed as defined with the other options.

Reason: all of the garage/gate openers has a built in autoclose timer, and if you stopped the gate with an RF remote the timing messed up. It will stop the gate/door in a half closed state and so on.

Sugegstion: if you are using 0 for autoCloseDelay, than do no send close hex singal only send status back to homebridge.

Thanks
Zoltan

**Comment by mu2004** [comment]
It's easy enough to send a dummy code that doesn't do anything.

**Comment by djsomi** [comment]
Yes, that is what I've done, but in this case you are not able to stop the gate with homebridge. Just send an open command and wait until the cycle finish.

**Comment by lprhodes** [comment]
Good idea, I've added it to the latest release:

https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/3.6.4
