### ISSUE TITLE
RM3 MINI + RM3 PRO - Issues

### ISSUE THREAD

**Issue by Reddyzinho** [lprhodes/homebridge-broadlink-rm#480]
I have a issue with using RM3 MINI and RM3 PRO. The RM3 MIni ir in the rest room to control the TV,  and the PRO is in the bedroom to control the other TV there. 
Altouht I have the PRO to control RF functions, like LIVOLO's switches. 

Well, The TVs are both samsung (same code to on and off), and when I try to send the HEX code in the bedroom, the light of PRO doesnt light upsl, only when I comunicate with RF switches. in the Rest-room, all things goes fine, with IR codes in the MINI 3. 

Any help here?

**Comment by lprhodes** [comment]
Hey @Reddyzinho, there's some info in the docs about specifying the IP/Mac address of the device you want to send it to, can you make sure you're following that please?

If you're still having issues please re-open and include your config.
