### ISSUE TITLE
Three different RM Mini in the same setup

### ISSUE THREAD

**Issue by asbesto01** [lprhodes/homebridge-broadlink-rm#481]
Hello everybody,

this is my "simple" question.

I currently have one single RM Mini in my setup, and I want to add two more but I am stuck in configuring the config.json

Could someone please help me in editing it?

This is the working config.json with the single RM Mini.

---

{
 "bridge": {
 "name": "HomeBridge",
 "username": "78:87:72:EA:50:BA",
 "port": 51826,
 "pin": "666-66-326"
 },
 
 "description": "HomePi Homebridge.",
 
  "accessories":[
 {
 "accessory": "MiRobotVacuum",
 "name": "Aspirapolvere",
 "ip": "192.168.0.166",
 "token": "123iuhasdnopuh3i39810283091283901238",
 "pause": false,
 "dock": true
 }
  ],

 "hosts": [{
        "address": "192.168.0.156",
        "mac": "C8:F7:42:21:B0:1C",
        "isRFSupported": true
    }],

  "platforms":[
    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "hideScanFrequencyButton": true,
      "hideLearnButton": true,
      "hideWelcomeMessage": false,
      "accessories":[
{
"name": "Condizionatore",
"type": "air-conditioner",
"minTemperature": 10,
"maxTemperature": 30,
"defaultCoolTemperature": 23,
"defaultHeatTemperature": 25,
"pseudoDeviceTemperature": 24,
"replaceAutoMode": "cool",

"data": {
  "off": "260068011600024964000125130d132f120e130f1110110f120f120f11101130120f120e132f122f130e122f132f123011301230120e1110120f120f120e130e120f120e130e120f120e130e130e120f120f120f11100f11120f1110120e120f120f120e130e130e120f120e130e120f120e130e1210110f1230122f135f65000124132f120f120e130e120f120e130e120f120f12301110110f0f33110f1230122f122f132f122f132f120e130e1210110f120f120f0f11120f120f120f120e130e120f120e130e120f120e130e130e120f120f120f1110110f0f12120f120e120f120f120e130e130e120f120e130e120f126064000125132f120f120f0f111011120f120e130e130e122f130e120f122f130e122f1330110f12300f32122f132f122f132f122f132e130e130e1210113011300f33120e120f120f120f120e132e130e132f122f122f130f122f120f0f12110f132f120f120e130e120f120e130e130e122f132f13000d05",
  "temperature10": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d62000128101010320f111011101110111010101110111031111010101110101110111032103110320f321032110f1011101110101011101110101110101110111011101110110f1110110f12101010111011101011101011101110101011103111101012101011100f120f11103210311131113011626200012612301110101010111011111010110f120f111032101011101032113011301131110f113111310f330f320f32113111301131110f101110111031113110321010101110110f12101010111011101011101032110f1011101110311110101110110f120f1110110f12103111311130113012000d05000000000000"
    },
  "temperature11": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d62000128101010320f111011101110111010101110111031111010101110101110111032103110320f321032110f1011101110101011101110101110101110111011101110110f1110110f12101010111011101011101011101110101011103111101012101011100f120f11103210311131113011626200012612301110101010111011111010110f120f111032101011101032113011301131110f113111310f330f320f32113111301131110f101110111031113110321010101110110f12101010111011101011101032110f1011101110311110101110110f120f1110110f12103111311130113012000d05000000000000"
    },
  "temperature12": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d62000128101010320f111011101110111010101110111031111010101110101110111032103110320f321032110f1011101110101011101110101110101110111011101110110f1110110f12101010111011101011101011101110101011103111101012101011100f120f11103210311131113011626200012612301110101010111011111010110f120f111032101011101032113011301131110f113111310f330f320f32113111301131110f101110111031113110321010101110110f12101010111011101011101032110f1011101110311110101110110f120f1110110f12103111311130113012000d05000000000000"
    },
  "temperature13": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d62000128101010320f111011101110111010101110111031111010101110101110111032103110320f321032110f1011101110101011101110101110101110111011101110110f1110110f12101010111011101011101011101110101011103111101012101011100f120f11103210311131113011626200012612301110101010111011111010110f120f111032101011101032113011301131110f113111310f330f320f32113111301131110f101110111031113110321010101110110f12101010111011101011101032110f1011101110311110101110110f120f1110110f12103111311130113012000d05000000000000"
    },
  "temperature14": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d62000128101010320f111011101110111010101110111031111010101110101110111032103110320f321032110f1011101110101011101110101110101110111011101110110f1110110f12101010111011101011101011101110101011103111101012101011100f120f11103210311131113011626200012612301110101010111011111010110f120f111032101011101032113011301131110f113111310f330f320f32113111301131110f101110111031113110321010101110110f12101010111011101011101032110f1011101110311110101110110f120f1110110f12103111311130113012000d05000000000000"
    },
  "temperature15": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d62000128101010320f111011101110111010101110111031111010101110101110111032103110320f321032110f1011101110101011101110101110101110111011101110110f1110110f12101010111011101011101011101110101011103111101012101011100f120f11103210311131113011626200012612301110101010111011111010110f120f111032101011101032113011301131110f113111310f330f320f32113111301131110f101110111031113110321010101110110f12101010111011101011101032110f1011101110311110101110110f120f1110110f12103111311130113012000d05000000000000"
    },
  "temperature16": {
    "pseudo-mode": "cool",
    "data": "2600f2001400024c63000127101011311011110f11101110110f1110111011301110111011310f120f1110320f32103211301130111011101110110f11101110111010110f120f1110110f120f11111011101110110f11101110110f111011101110110f11110f1110110f120f120f11101110111130113111301130116262000127113011110f1110110f120f120f111011101111301110110f123011301131113011110f320f330f32103111311130113111301110110f1110113110320f320f121011101011101110110f120f1110111011301110110f1111103110110f120f11101110111011110f113111301131113010000d05000000000000"
    },
"temperature17": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d620001271011122f120f10111010111010111011120e1032120e120f1230111011100f321032122f122f132f130e120e120f120f120e130e120f120f120f11100f1110111011120f120e120f120f120e120f120f120f120e120f120f120e12101110110f10110f120f11130e1230122f122f12301261630001251032101011110f120f1110110f12120e120f1032101010111011103110321031101110320f321032122f10321031103111311010111010111031103311300f120f11120f101110101131101110101110103210101011101110320f120f1110110f12120e120f1011103110321031103113000d05000000000000"
  },
"temperature18": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024e620001271110113011101110110f11101110110f1110113111100f120f320f12101110311130123011301131110f11101110111010110f120f1110110f121011101011101110110f111011101110110f11101110110f11110f120f1110110f120f11111011101110110f11101130113111301131106262000128103110110f121010111010111110110f1110113011101110110f1131113110320f110f33103111301230113011311130113111100f1210110f320f321032110f120f11101110110f1110113011101110113110110f1110110f330f1110111110110f111011101110113011301131113110000d05000000000000"
  },
"temperature19": {
    "pseudo-mode": "cool",
    "data": "2600f2001400024e6200012611101131110f1110111110100f120f120f1110321010111011311010111011301131113011320f320f120f11101110111010111011101110110f11101110110f11101110110f11110f120f1110110f120f121010101111101010111011101110110f11101110101011311131103110321161630001261131110f11101110110f111011101110110f1131111010110f3210110f3211311110113011301131113011311131103110320f111011101111301131113011101110110f111011101131103110110f120f3210111110110f1131110f11101110110f120f11101110113110311032103111000d05000000000000"
  },
"temperature20": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d6300012611101130120f11101110110f11101110110f1132101010110f3211101011103111311130113111301110110f11111011101010110f120f12101010111110110f11101110110f120f11101110110f11101111101010110f120f11101110111010120f11101110110f113111301131113010636100012810320f11101110111010111011101110110f1131110f111011101130113111310f120f321031113111301131113011311031111010110f120f32103210311110110f120f11101110110f111011301110113111100f120f120f321011101011101110110f120f1110113011311130113111000d05000000000000"
  },
"temperature21": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024e63000126110f12301110110f11101110111010110f120f320f12101011311110110f1131113011311130113110110f120f1110110f121010111011101110110f11101110110f111011101110110f11110f120f110f120f120f1110111011110f120f11101110110f11101110113011311131103111616300012611311011110f11101110110f120f1110111011301110111010320f1110321031101111301131113011311130113011320f320f120f120f11103211301130120f11101110110f1110103111110f3210110f3210111011111011301110110f111011101110110f11101130113210310f3211000d05000000000000"
  },
"temperature22": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024e6300012610111031111010101110101110111010101110311110111110310f120f1110321031113111301131110f10111011101011101012101010110f120f111011101110111010101110111010111010111011101010111011101110110f120f1110110f121010111010111031113111301131106262000127113110110f120f1110110f12101011101011103111101011103111101031113111100f330f3210311131113011311130122f120f1011101112300f321032101010111011120e130e120f122f1230120e132f120f120f11100f3210110f121010120f120f120e130e132f132e132e132f10000d05000000000000"
  },
"temperature23": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024d62000128101010320f120f111011101110101110111011301110111011301110111010320f320f3310311031111011101110110f11101110101011101110111010110f120f1110110f121011101011101110110f11101110110f120f11101110111010110f120f1110110f120f3210311230113011626200012711301110111011100f120f120f110f120f120f3210111010120f111011301131110f11311130113210310f32103211301131110f11101110113011311031101110110f120f120f11103210311131110f1131110f11101110103111110f1110110f120f120f111011103111311130113111000d05000000000000"
  },
"temperature24": {
    "pseudo-mode": "cool",
    "data": "2600f2001300024e630001261110113011101011101011101110111011100f33101010110f3210111011103111311130113011311110110f11110f120f1110110f120f11101110111010111011101110110f10111110110f11101110101110110f120f120f110f120f12101010111011110f11101032113011301131106361000128103110110f120f12101010111110110f11101032110f111011101130113110320f1110321031113111301130123011301131111010110f120f320f3310311110110f1011111010101110101111101130113110110f120f1110321010111010111011110f11101110103111311130113110000d05000000000000"
  },
"temperature25": {
    "pseudo-mode": "heat",
    "data": "2600f2001200024e6200012710111031111010101110101110111010101110311110101111310f120f1110321031113111301130120f10111011101010111011111010110f120f1110110f1210101110101110111010101110111010111010111011101011111010101110110f120f1110111011103111311130113011626300012611301111101010110f120f111011101110111031111010101110101110311131101110320f320f32103210311131113011301110101110111031113110320f1110111011101011101230120e120f1031132f120f12301110110f10110f3210111011120e130e120f122f1230122f123010000d05000000000000"
  },
"temperature26": {
    "pseudo-mode": "heat",
    "data": "2600f2001600024b64000125130d132f120f120e130e120f120e130f110f12300f12120e1230120f120e132f122f132e132f122f130f110f120f120f0f12120e120f120f120e130e130e120f120e130e120f120e130e120f120f120e130f110f1011120f120f120e130e120f120e130e120f120e132f122f132f12301260640001251230120e130e120f120e130e130e120f120e132f120e130e1210110f12300f321110122f1230122f122f132f122f132f12301110110f111011301230122f130e120f120e130e120f120f122f12101130122f12110d32120f120f120e132f120f120e130e120f120f122f12301230113012000d05000000000000"
  },
"temperature27": {
    "pseudo-mode": "heat",
    "data": "2600f2001600024b64000125130d132f120f120f120f11100f111110120f122f120f120e132f120f120e132f122f12301230122f120f120f120e120f120f120e130e130e120e130e130e130e130d140d130f120e120f120f120e120f120f120e130e130e120f120e130e120f120e140d130e130e132f122f0f331130135f65000124132f130d140d130e130d130e130e130e130e1230120e130e122f1230130d142e130e132e132e142e132e1330122f122f1230120e130e130e132e132f132e130e130d140d130e130e132f122f120f122f132f130d142e130d140d130e132e130e130e130e130e120f1031122f142e132e14000d05000000000000"
  },
"temperature28": {
    "pseudo-mode": "heat",
    "data": "2600f2001500024c64000124140d1230120f120f110f120f0f121110110f1230120e130e1230120e130e122f132f122f12301230120f110f120f120f120e130e120f120e130e130e120f120e130e120f120f120f1110110f120f120f120e130e120f120f120e130e120f120e130e120f120f120e123111300f321230126064000125132e130e120f120e130e130e120f120e130e1230120f1110120e120f122f132f120f122f122f132f122f132f123011301230120f110f120f122f132f132e130e120e130e120f120f120f120f11301230122f120f122f130e120e130e132f130d130e120f120f120f11301032122f123012000d05000000000000"
  },
"temperature29": {
    "pseudo-mode": "heat",
    "data": "2600f2001400024d610001280f120f3210111011110f111011101110110f1131110f1110113110110f120f320f33103110311131110f111011101110110f11101110110f11110f120f1110110f121010111011101110110f11101110110f11101110110f11101110111010110f120f120f1110111031113111301131116163000126113011101110111010110f120f11101110111031111011101130113011101131110f113111310f321032103111301230113011101110110f11311130113110110f120f1210101011113011101130123011301110113110110f120f1110320f11111010111110110f113111301131113010000d05000000000000"
  },
"temperature30": {
    "pseudo-mode": "heat",
    "data": "2600f2001500024c610001271110103210110f120f1110110f12120e101110321010111010311110101110311032103110321032120e10110f121011101010111011101011101011101011101011101110110f120f120f1110110f120f11101110111010111010111011101010111011101011110f3210320f320f331063610001271031101110111010111010111011101010120f320f120f120f320f32111010311110103210311031113110320f321032122f101110111010113110311032101010111011101110110f120f320f33103110311011103111101011101011311011101010120f120f111032122f1031113110000d05000000000000"
  }
}
}
]
    }
  ]
}

---

The other two RM Minis must be a clone of the first RM Mini. I will use them to control two additional air-con splits (identical to the first one), so the only variables within the config should be IP and MAC of the Minis.

Please help!

**Comment by kev0629** [comment]
I'm also interested about config file with another Broadlink RM please

**Comment by asbesto01** [comment]
UP guys please help :)

**Comment by Ledbetter14** [comment]
Just add a host line that correlates with which mini you want to fire the command. You are best to reserve ips for each mini to keep it a little more robust. The plugin will handle the discovery of the minis.

{"name": "Living Apple TV",
                    "type": "switch",
                    "enableAutoOff":true,
                    "onDuration":3,
                    "host":"192.168.1.4",
                    "data":{
                      "on":[
etc..............

**Comment by mu2004** [comment]
the host can be either the IP address or the MAC address. I've tested both and all 3 RM Minis work without much problems. The only issue I have is, occasionally the IR codes were sent but the A/C doesn't receive it.

**Comment by lprhodes** [comment]
It sounds like this is resolved. @mu2004 please crate a separate issue if you're seeing issues with IR not being sent.
