### ISSUE TITLE
MQTT Temperature not picked up for BME280

### ISSUE THREAD

**Issue by mu2004** [lprhodes/homebridge-broadlink-rm#482]
I love your Broadlink plugins and it's working great except one problem on AC.
I am having a problem getting the temperature value picked up from BME280 via MQTT to Soon Basic. According to Homebridge log, it can't find the identifier "temperature" as per the logs below:

[3/19/2019, 6:08:28 PM] [Broadlink RM] [ERROR] BedroomAC No MQTT value could be found for topic with identifier "temperature".
[3/19/2019, 6:08:28 PM] [Broadlink RM] BedroomAC onTemperature (0)
[3/19/2019, 6:08:28 PM] [Broadlink RM] [INFO] Reported temperature (0) is too low, setting to minTemperature (10).

Checking the output from mosquitto, it shows the identifier "Temperature" is used, with a capital T as per the info below:

$mosquitto_sub -h 192.168.0.12 -t tele/sonoff151/SENSOR -C 1 
{"Time":"2019-03-19T10:54:56","BME280":{"Temperature":24.8,"Humidity":72.0,"Pressure":995.5},"PressureUnit":"hPa","TempUnit":"C"}

I am wondering if the upper case T is indeed the cause of the problem. If it is, would you be kind enough to make a quick change for those of us who use Bosch BME280 sensor for humidity and temperature. It's probably the most accurate sensor for the price range, and many people are connecting it on Sonoff Basic running Tasmota. It really works great. 

Alternative method was also tested, but so far without much luck. I've also tried to grab temperature from a crontab to output to a text file and use the "temperatureFilePath" option. It runs successfully from the command line but oddly fails to produce the output from crontab. Rounding can also be achieved by the printf so the fractional degrees C is not truncated.

*/1 * * * * mosquitto_sub -h 192.168.0.12 -t tele/sonoff151/SENSOR -C 1 | awk -F'Temperature":' '{print $2}'|awk -F',"' '{printf "%.0f\n", $1}' > /var/tmp/bedroom.txt

Your help on either options would be greatly appreciated.

**Comment by huongminh** [comment]
if you have a look at the file aircon.js you can see that Temperature with the capital T should be recognized. I do not have a mqtt topic with Temperature. However, I sucessfully add another value of "svalue1" in the definition and it works for my output key word from domoticz/out. Here is how I did:
open aircon.js from the path:
...node_modules/homebridge-broadlink-rm/accessories
add one line:
 if (typeof temperatureJSON === 'object') {
        let values = findKey(temperatureJSON, 'temp');
        if (values.length === 0) values = findKey(temperatureJSON, 'Temp');
        if (values.length === 0) values = findKey(temperatureJSON, 'temperature');
        if (values.length === 0) values = findKey(temperatureJSON, 'Temperature');
        if (values.length === 0) values = findKey(temperatureJSON, 'svalue1'); // added by Minh to read temp from mqtt domoticz (dom$
        if (values.length > 0) {
          temperature = values[0];
        } else {
          temperature = undefined;
        }
      }
    } catch (err) {}

**Comment by huongminh** [comment]
BTW, I found now homekit accept minimum temp > 10 so I modified the same file to accept 18 degree C is the lowest.

**Comment by huongminh** [comment]
// minTemperature can't be more than 10 or HomeKit throws a fit
   // changed by Minh from 11 to 19 in the below line to increase the min temp can be set to 18 since HomeKit now works well with min temp >10
    assert.isBelow(config.minTemperature, 19, `\x1b[31m[CONFIG ERROR] \x1b[33mminTemperature\x1b[0m (${config.minTemperature}) must be <= 10`)

**Comment by asbesto01** [comment]
Guys where is the mistake? this is my config json:

"name": "CondizionatoreCamera",
"type": "air-conditioner",
"host": "192.168.0.177",
"mqttURL": "mqtt://192.168.0.199",
"mqttUsername": "Stefano",
"mqttPassword": "Password",
"mqttTopic": "tele/sonoff/SENSOR/",
"temperatureUpdateFrequency": 150,
"minTemperature": 10,
"maxTemperature": 30,
"defaultCoolTemperature": 23,
"defaultHeatTemperature": 25,
"replaceAutoMode": "cool",

I receive this message:
"No MQTT value could be found for topic with identifier "temperature".

But my TH16 is transmitting telemetry just fine:

00:00:00 CFG: Loaded from flash at F9, Count 43
00:00:00 Project sonoff sonoff Version 6.5.0.16(sonoff)-2_5_2
00:00:00 WIF: Connecting to AP1 PiricipolliHome2.4 in mode 11N as sonoff-0533...
00:00:04 WIF: Connected
00:00:04 HTP: Web server active on sonoff-0533 with IP address 192.168.0.125
11:33:25 MQT: Attempting connection...
11:33:25 MQT: Connected
11:33:25 MQT: tele/sonoff/SENSOR/LWT = Online (retained)
11:33:25 MQT: tele/sonoff/SENSOR/cmnd/POWER = 
11:33:25 MQT: tele/sonoff/SENSOR/INFO1 = {"Module":"Sonoff TH","Version":"6.5.0.16(sonoff)","FallbackTopic":"cmnd/DVES_52C215_fb/","GroupTopic":"sonoffs"}
11:33:25 MQT: tele/sonoff/SENSOR/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoff-0533","IPAddress":"192.168.0.125"}
11:33:25 MQT: tele/sonoff/SENSOR/INFO3 = {"RestartReason":"Software/System restart"}
11:33:25 MQT: tele/sonoff/SENSOR/RESULT = {"POWER":"ON"}
11:33:25 MQT: tele/sonoff/SENSOR/POWER = ON
11:33:33 MQT: tele/sonoff/SENSOR/STATE = {"Time":"2019-06-29T11:33:33","Uptime":"0T00:00:14","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":1,"SSId":"PiricipolliHome2.4","BSSId":"EC:08:6B:37:29:6B","Channel":8,"RSSI":76,"LinkCount":1,"Downtime":"0T00:00:04"}}
**11:33:33 MQT: tele/sonoff/SENSOR/SENSOR = {"Time":"2019-06-29T11:33:33","AM2301":{"Temperature":28.7,"Humidity":49.8},"TempUnit":"C"}**

Help!

**Comment by lprhodes** [comment]
@asbesto01 note that it's "Temperature" not "temperature" that you should be using
