### ISSUE TITLE
Is there a way to pick temperature from existing homekit devices?

### ISSUE THREAD

**Issue by asbesto01** [lprhodes/homebridge-broadlink-rm#486]
I use Broadlink RM Mini to manage an aircon, with fixed temperature.
I was wondering if there is a way to pick temperature from an existing Homekit device already set up within my home

thanks :)

**Comment by asbesto01** [comment]
up.. help please :)

**Comment by womby1** [comment]
up

**Comment by soukron** [comment]
It's a dirty workaround but you can do it if the device is controlled by homebridge:
 - create a cronjob to querying the HomeBridge API to get the value and saving the value to a text file
 - configure homebridge-broadlink-rm plugin to read the value from the text file

I know, it's ugly, but it works.

**Comment by lprhodes** [comment]
@soukron's solution is the best that we can do at this point, devices don't really know about one another unfortunately.
