### ISSUE TITLE
Guessing this isn't maintained anymore?

### ISSUE THREAD

**Issue by Trippersgarage** [lprhodes/homebridge-broadlink-rm#487]
As above, seeing as how the last update was sometime back, is it still being maintained?

**Comment by ifeign** [comment]
Check out this fork. They've added homekit TV support https://github.com/AlexanderBabel/homebridge-broadlink-rm

**Comment by lprhodes** [comment]
It is being supported again, any missing functionality will be added over the next couple of days.
