### ISSUE TITLE
Homekit Air-conditioner Layout 

### ISSUE THREAD

**Issue by jeylites** [lprhodes/homebridge-broadlink-rm#490]
Hey Guys,

I'm just getting started with the Air Conditioning control. Any idea how to get pretty layouts like below to show up on Homekit?

![C74B04E2-5FCA-4A2F-8798-3EB8D90C4917](https://user-images.githubusercontent.com/9190080/56595082-936ea780-6620-11e9-8f60-8b9c2bfe11a1.png)
![6B62961C-2293-4D31-A1DC-DE8CE4152504](https://user-images.githubusercontent.com/9190080/56595083-94073e00-6620-11e9-9aa3-bc69732acfc0.png)

**Comment by womby1** [comment]
It's quite easy - within this plugin, just define the "type" as air conditioner and home kit will you show you this nice interface. You can check the documentation and sample config.json for reference. Helped me a lot to get started :)

**Comment by jeylites** [comment]
Thank you. I will give it a try.
