### ISSUE TITLE
A window accessory

### ISSUE THREAD

**Issue by Ikinisp** [lprhodes/homebridge-broadlink-rm#494]
Hello.

Could you add a new accessory, in this case the "window" one.
It is part of apple Homekit standard and the functionality is the same of the "window covering" accessory that you have already done. 
I have seen your code but I don't know enough javascript either the structure of homebridge modules.

I have installed your module for two Velux ([https://www.velux.com/products/roof-windows]) windows and their blinds and it works great.
Thanks.

**Comment by lprhodes** [comment]
Hey @Ikinisp, you can now add a "window" type in the latest version:

https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/3.5.10
