### ISSUE TITLE
New device "27de" and i'm not able to learn RF

### ISSUE THREAD

**Issue by scorpio207** [lprhodes/homebridge-broadlink-rm#496]
We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "27de".

**Comment by fooozhe** [comment]
same here

**Comment by ychongsaytc** [comment]
```
[7/10/2019, 2:08:49 PM] [Broadlink] [INFO] Automatically discovering Broadlink RM devices.
[7/10/2019, 2:08:49 PM] [Broadlink] [INFO] Running Homebridge Broadlink RM Plugin version 3.5.5
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "27de". The device is connected to your network with the IP address "10.0.0.172".

[7/10/2019, 2:08:49 PM] [Broadlink] [INFO] Discovered Broadlink RM2 Pro Plus (272a) at 10.0.0.171 (34:ea:34:c7:68:e6)
```

`10.0.0.171` is RM pro and `10.0.0.172` is RM Mini 3.

**Comment by foretony5211** [comment]
@ychongsaytc pro is ok , mini is not ok? my device is 27de too, I try a lot but no result.

**Comment by foretony5211** [comment]
@scorpio207 @fooozhe you must add hosts in your config.json , and most important, hosts must in your planform,like this
{
  "bridge":{
    "name":"Homebridge",
    "username":"***",
    "port":***,
    "pin":"***"
  },
  "description":"Homebridge",
  "accessories":[

  ],
  "platforms":[
    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "hosts":{
           "address":"",
           "mac": "",
           "isRFSupported": true/fase 
      },
      "hideLearnButton": false,
      "hideWelcomeMessage": false,
      "accessories":[
        {
        ……
        ……

**Comment by scorpio207** [comment]
@foretony5211  Thanks, that solved to problem :)

**Comment by gncorbin** [comment]
Hi @scorpio207 and @foretony5211 
I think I’ve tried everything, including what you advised above—which partially worked. I too was getting the error that the “27de” device was an unknown broadlink device. I added the host information to my config.json. That made that error go away, but left me with the error: 
`[Homebridge] [12/21/2019, 18:06:23] [BroadlinkRM] Learn getSwitchState: undefined
[Homebridge] [12/21/2019, 18:06:23] [BroadlinkRM] Scan Frequency getSwitchState: undefined`

I’m not sure what to do with this. The only thing I can think is a firewall issue with my eero router or something to do with running homebridge on raspberry pi. Any thoughts?

Thanks for your help in advance.

**Comment by lprhodes** [comment]
27de is supported in the latest version

**Comment by gncorbin** [comment]
Thanks!! For anyone else, I also had to update my node to 12.14.0
`wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/upgrade-node.sh | sudo bash - `
And I had to install the module ‘chai’ with the command:
`npm install chai`

Hope that helps anyone else experiencing these issues. 
Thanks again for the plugin!
