### ISSUE TITLE
my AC won't work

### ISSUE THREAD

**Issue by platini76** [lprhodes/homebridge-broadlink-rm#497]
my config:

    {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideLearnButton": true,
            "hideWelcomeMessage": false,
            "accessories": [
                {
                    "name": "Condizionatore",
                    "type": "air-conditioner",
                    "data": {
                        "off": "2600500000012...",
                        "temperature30": {
                            "pseudo-mode": "heat",
                            "data": "2600500000012..."
                        },
                        "temperature16": {
                            "pseudo-mode": "cool",
                            "data": "2600500000012..."
                        }
                    }
                },
                {
                    "name": "A/C Auto Switch",
                    "type": "switch"
                },
                {
                    "name": "Fan",
                    "type": "fan",
                    "data": {
                        "on": "2600500000012...",
                        "off": "2600500000012...",
                        "swingToggle": "2600500000012...",
                        "fanSpeed10": "2600500000012...",
                        "fanSpeed20": "2600500000012...",
                        "fanSpeed30": "2600500000012...",
                        "fanSpeed40": "2600500000012...",
                        "fanSpeed50": "2600500000012...",
                        "fanSpeed60": "2600500000012...",
                        "fanSpeed70": "2600500000012...",
                        "fanSpeed80": "2600500000012...",
                        "fanSpeed90": "2600500000012...",
                        "fanSpeed100": "2600500000012..."
                    }
                }
            ]
        },

is it ok? 
my daikin won't switch on or off.

**Comment by lprhodes** [comment]
Hi @platini76 did you get this working? Try with a simple switch first to rule out any issues.

Also, the codes in the "data" area all need to be replaced with real RF or IR codes (i.e. not "2600500000012...")
