### ISSUE TITLE
iOS 13 Beta

### ISSUE THREAD

**Issue by marcodesantis71** [lprhodes/homebridge-broadlink-rm#498]
Hi All,

I've installed iOS 13 Beta 1 and now the plugins does not work.

I know it's normal.

But any news about compatibility with the new iOS version?

**Comment by rvanbaalen** [comment]
I'm running public beta 1 and this is working just fine. Maybe one of us got (un)lucky or there's something else going on in your setup.

**Comment by lprhodes** [comment]
@marcodesantis71  please re-open if you're still seeing issues in the released iOS 13 versions.
