### ISSUE TITLE
Aircondition auto turned on when I'm not at home

### ISSUE THREAD

**Issue by Itzamna44** [lprhodes/homebridge-broadlink-rm#499]
Hello.
I have a problem with Aircondition. It auto turned on to default temperature.
This is my config:
`                {
                        "platform": "BroadlinkRM",
                        "name": "Broadlink RM",
                        "hideScanFrequencyButton": true,
                        "hideLearnButton": false,
                        "accessories": [
                                {
                                        "name": "Air Conditioner",
                                        "type": "air-conditioner",
                                        "minTemperature": 10,
                                        "maxTemperature": 30,
                                        "defaultCoolTemperature": 25,
                                        "temperatureFilePath": "/var/homebridge/temp_current",
                                        "data": {
                                                "off":  ""
                                                "temperature16": {
                                                        "pseudo-mode": "cool",
                                                        "data": ""
                                                        },
                                                "temperature17": {
                                                        "pseudo-mode": "cool",
                                                        "data": ""
                                                        },
                                                "temperature18": {
                                                        "pseudo-mode": "cool",
                                                        "data": ""
                                                   }
                                   }
               }
}`

This is log:
`Jun 18 21:23:17 homebridge homebridge[27338]: [6/18/2019, 9:23:17 PM] [Efergy] Read Current Consumption: 554 W
Jun 18 21:27:16 homebridge homebridge[27338]: [6/18/2019, 9:27:16 PM] [eveatmo platform] Loading new data from API for: weatherstation
Jun 18 21:28:17 homebridge homebridge[27338]: [6/18/2019, 9:28:17 PM] [Efergy] Read Current Consumption: 332 W
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner setTargetTemperature: 25
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner Potential sendTemperature (25)
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner setTargetHeatingCoolingState: 0
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner sendHex (192.168.0.103; 34:ea:34:43:1a:9a) 26006001000128931535143614101410151
01410151014361410143614361410141015101410151014351535153515101410141015101410150f1535150f15101410143615101436141014101410150f1510141015101410150f1410150f15101410141015101410140001
05141014101410141015101410151014361410143614101436141015361410150f150f150f1510141014101510141015101410141014101410141015101411141014101410141014101510141015101410141014101410150f1
510141015101410150f150f150f1510141014111410150f1535153514361436151014101411140f15000104150f1510141014101410151014101510143515101410141014101510141015101410141014101410151014101510
1410141014101410150f1510141015101410150f150f150f15351510143615101410141014101410150f15101410151014101535141014101535151014361510140f15000d050000000000000000
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner setCurrentHeatingCoolingState: 0
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner setCurrentHeatingCoolingState: already 0 (no data sent - B)
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner sendTemperature (25
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner sendHex (192.168.0.103; 34:ea:34:43:1a:9a) 2600600100012a911238123812121312131
11114111411381212133712381212121313121114111312371238123812121411111411131312121211381213111313371114121213371213111311121213131211131312111311131113111311141113121212131113120001
06143613121113111311141113111411381238121311131139113912131114111311121212121311131212121312131113111311131113121311131114111311141113111311121213111312131113121212131112121311131
21212131213111311131113111312131113111312131212123812121238123812131113121311131100010811131114101312131113111411131113123812121213111212131212121312131112121311131113111411131113
12131113111311131213111311141113111411121213111311381239113912131113121211131213111311131114111411131138121311131138133813371213121211000d050000000000000000
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner sendTemperature (set mode to cool
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner getCurrentHeatingCoolingState: 0
Jun 18 21:29:53 homebridge homebridge[27338]: [6/18/2019, 9:29:53 PM] [Broadlink RM] Air Conditioner getTargetHeatingCoolingState: 2
Jun 18 21:29:54 homebridge homebridge[27338]: [6/18/2019, 9:29:54 PM] [Broadlink RM] Air Conditioner setCurrentHeatingCoolingState: 2
Jun 18 21:33:17 homebridge homebridge[27338]: [6/18/2019, 9:33:17 PM] [Efergy] Read Current Consumption: 659 W
Jun 18 21:36:16 homebridge homebridge[27338]: [6/18/2019, 9:36:16 PM] [eveatmo platform] Loading new data from API for: weatherstation
Jun 18 21:38:17 homebridge homebridge[27338]: [6/18/2019, 9:38:17 PM] [Efergy] Read Current Consumption: 611 W
Jun 18 21:43:17 homebridge homebridge[27338]: [6/18/2019, 9:43:17 PM] [Efergy] Read Current Consumption: 532 W
Jun 18 21:45:16 homebridge homebridge[27338]: [6/18/2019, 9:45:16 PM] [eveatmo platform] Loading new data from API for: weatherstation
Jun 18 21:48:17 homebridge homebridge[27338]: [6/18/2019, 9:48:17 PM] [Efergy] Read Current Consumption: 340 W
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner setTargetTemperature: 25
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner Potential sendTemperature (25)
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner setTargetHeatingCoolingState: 0
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner sendHex (192.168.0.103; 34:ea:34:43:1a:9a) 2600600100012893153514361410141015101410151014361410143614361410141015101410151014351535153515101410141015101410150f1535150f15101410143615101436141014101410150f1510141015101410150f1410150f1510141014101510141014000105141014101410141015101410151014361410143614101436141015361410150f150f150f1510141014101510141015101410141014101410141015101411141014101410141014101510141015101410141014101410150f1510141015101410150f150f150f1510141014111410150f1535153514361436151014101411140f15000104150f15101410141014101510141015101435151014101410141015101410151014101410141014101510141015101410141014101410150f1510141015101410150f150f150f15351510143615101410141014101410150f15101410151014101535141014101535151014361510140f15000d050000000000000000
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner setCurrentHeatingCoolingState: 0
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner sendTemperature (25
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner sendHex (192.168.0.103; 34:ea:34:43:1a:9a) 2600600100012a91123812381212131213111114111411381212133712381212121313121114111312371238123812121411111411131312121211381213111313371114121213371213111311121213131211131312111311131113111311141113121212131113120001061436131211131113111411131114113812381213111311391139121311141113111212121213111312121213121311131113111311131213111311141113111411131113111212131113121311131212121311121213111312121213121311131113111311131213111311131213121212381212123812381213111312131113110001081113111410131213111311141113111312381212121311121213121212131213111212131113111311141113111312131113111311131213111311141113111411121213111311381239113912131113121211131213111311131114111411131138121311131138133813371213121211000d050000000000000000
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner sendTemperature (set mode to cool
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner getCurrentHeatingCoolingState: 0
Jun 18 21:52:56 homebridge homebridge[27338]: [6/18/2019, 9:52:56 PM] [Broadlink RM] Air Conditioner getTargetHeatingCoolingState: 2
Jun 18 21:52:57 homebridge homebridge[27338]: [6/18/2019, 9:52:57 PM] [Broadlink RM] Air Conditioner setCurrentHeatingCoolingState: 2
Jun 18 21:53:17 homebridge homebridge[27338]: [6/18/2019, 9:53:17 PM] [Efergy] Read Current Consumption: 349 W
Jun 18 21:54:16 homebridge homebridge[27338]: [6/18/2019, 9:54:16 PM] [eveatmo platform] Loading new data from API for: weatherstation
Jun 18 21:58:17 homebridge homebridge[27338]: [6/18/2019, 9:58:17 PM] [Efergy] Read Current Consumption: 560 W
Jun 18 21:58:51 homebridge homebridge[27338]: [6/18/2019, 9:58:51 PM] [Broadlink RM] Air Conditioner setTargetHeatingCoolingState: 0
Jun 18 21:58:51 homebridge homebridge[27338]: [6/18/2019, 9:58:51 PM] [Broadlink RM] Air Conditioner sendHex (192.168.0.103; 34:ea:34:43:1a:9a) 2600600100012893153514361410141015101410151014361410143614361410141015101410151014351535153515101410141015101410150f1535150f15101410143615101436141014101410150f1510141015101410150f1410150f1510141014101510141014000105141014101410141015101410151014361410143614101436141015361410150f150f150f1510141014101510141015101410141014101410141015101411141014101410141014101510141015101410141014101410150f1510141015101410150f150f150f1510141014111410150f1535153514361436151014101411140f15000104150f15101410141014101510141015101435151014101410141015101410151014101410141014101510141015101410141014101410150f1510141015101410150f150f150f15351510143615101410141014101410150f15101410151014101535141014101535151014361510140f15000d050000000000000000
Jun 18 21:58:52 homebridge homebridge[27338]: [6/18/2019, 9:58:52 PM] [Broadlink RM] Air Conditioner setCurrentHeatingCoolingState: 0
`

**Comment by kiwi-cam** [comment]
I'm not sure if you've resolved this by now, but this may help others. For me, my Temperature hex code will also turn on my AC. This means that if the temperature hex code is sent, the AC will turn on - and this can happen.  I set `"ignoreTemperatureWhenOff": true` to stop temperature codes being sent when the AC is off. This solved a similar issue I was having.

**Comment by lprhodes** [comment]
Thanks @kiwi-cam! @Itzamna44 was that the issue?

Closing the issue for now, feel free to re-open if you're still having issues and I'll take a closer look.
