### ISSUE TITLE
Cannot start home bridge with 

### ISSUE THREAD

**Issue by tengelmeier** [lprhodes/homebridge-broadlink-rm#5]
As soon as I add any of the two config entries to my config.json starting home bridge fails:

````
Initializing AquaraPlatform platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:104
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:104:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```
`

My home bridge version is:

`
~/.homebridge $ homebridge --version
....
0.4.16`

**Comment by lprhodes** [comment]
Can you post the relevant section of your config please?

**Comment by hkechung** [comment]
# more config.json
{
    "bridge": {
    "name": "Homebridge",
    "username": "xxxxx",
    "port": xxxx,
    "pin": "xxxx"
        },

        "accessories": [
            {
                        "accessory": "Broadlink RM Learner",
                        "name": "Learn IR",
                        "host": "192.168.5.161"
                },

                {
                        "accessory": "Broadlink RM",
                        "name": "Broadlink RM Mini 3",
                        "host": "192.168.5.161",
                        "data": [
                                {
                                  "name": "TV",
                                  "type": "on",
361fc102f44e2f8daeed188f1e279f6e062d5c46b23e02a0fa2f5741ed29bdaf0d883d5a17a5e363
440977a1845b068c5d7dd1074764d00377f0a12ba27ddd5870608da14ee1cf35533a73bc4488d089
55126e9d611f047842ca369caf56e60",

                                        "off": "5aa5aa555aa5aa55020009004c65cc00
02000900000000000d71680414070000dcfb00003727ee035a826a33cc0d43b4010000008fc80000
4d981b1c37e8bde81a19f45a786a90503ecaac51d9709780e877a53d62e27ee5f1400bf3e97ca9fc
995e027f6640436106df44dde86942124107ba903df48161e54e18c089648cde38c9fe86d9c0e858
b464699b99160020ea6319a281734ff8"
                                }


                        ]

**Comment by tengelmeier** [comment]
Sure.

I tried either 

`
{
	"accessory": "Broadlink RM Learner",
	"name": "Learn IR",
	"host": "192.168.11.11"
} 
`

or 

`
{
	"accessory": "Broadlink RM",
	"name": "Wohnzimmer Remote",
	"host": "192.168.11.11",
	"data": [{
				"name": "TV",
				"type": "on",
				"on": "5aa5aa555aa5aa55000000000000000000000000000000000000000000000000e5fa00002a276a00608328d7e734ea340100000080c80000dee59f6ebfd9fcbc56f9ca6d5368cec9ff5b5afc86ff3feb6fbdb113671d2be9d9203f369f41fe5ffe152729318e9947e426608adb47c59b9ff744b987f398bfd4301f34021991f124801410164e740bc4a92d87bcd3365aef16b660c2fb936b",
				"off": "5aa5aa555aa5aa55000000000000000000000000000000000000000000000000d3fa00002a276a004f8228d7e734ea340100000080c80000dee59f6ebfd9fcbc56f9ca6d5368cec9ff5b5afc86ff3feb6fbdb113671d2be9d9203f369f41fe5ffe152729318e9947e426608adb47c59b9ff744b987f398bfd4301f34021991f124801410164e740bc4a92d87bcd3365aef16b660c2fb936b"
	}
`

**Comment by lprhodes** [comment]
I think I'm going to need the full config, sorry.

Also make sure you're on the latest version (0.2.13)

**Comment by tengelmeier** [comment]
{

			"bridge": {
				"name": "Homebridge",
				"username": "CC:22:XX:XX:XX:XX",
				"port": 51826,
				"pin": "XXXXX"
			},

			"description": "My Config",

			"accessories": [],
			"platforms": [
			 {
				"platform": "AquaraPlatform",
				"sid": ["YYY"],
				"password": ["XXX"]
			},
			{
					"accessory": "Broadlink RM Learner",
					"name": "Learn IR",
					"host": "192.168.1.1"
				}
			],
			"disabled": [{
					"accessory": "Broadlink RM Learner",
					"name": "Learn IR",
					"host": "192.168.178.26"
				}, {
					"accessory": "Broadlink RM",
					"name": "Wohnzimmer Remote",
					"host": "192.168.178.26",
					"data": [{
						"name": "TV",
						"type": "on",
						"on": "5aa5aa555aa5aa55000000000000000000000000000000000000000000000000e5fa00002a276a00608328d7e734ea340100000080c80000dee59f6ebfd9fcbc56f9ca6d5368cec9ff5b5afc86ff3feb6fbdb113671d2be9d9203f369f41fe5ffe152729318e9947e426608adb47c59b9ff744b987f398bfd4301f34021991f124801410164e740bc4a92d87bcd3365aef16b660c2fb936b",
						"off": "5aa5aa555aa5aa55000000000000000000000000000000000000000000000000d3fa00002a276a004f8228d7e734ea340100000080c80000dee59f6ebfd9fcbc56f9ca6d5368cec9ff5b5afc86ff3feb6fbdb113671d2be9d9203f369f41fe5ffe152729318e9947e426608adb47c59b9ff744b987f398bfd4301f34021991f124801410164e740bc4a92d87bcd3365aef16b660c2fb936b"
					}]
				}
			]
		}

**Comment by lprhodes** [comment]
They need to go underneath accessories rather than platforms

**Comment by tengelmeier** [comment]
Perfect - that was it. Thanks a lot!
