### ISSUE TITLE
Feasibility of temperature sensor as an accessory

### ISSUE THREAD

**Issue by leonardolau** [lprhodes/homebridge-broadlink-rm#50]
Is it possible to add the temperature sensor as an accessory for triggering air con on or off when defined temperature hits?

**Comment by lprhodes** [comment]
Certainly possible - there'd need to be more to it that that though as you'd need to have upper and lower temperatures which then turn on heating or cooling.

I'll work on this later in the week.

**Comment by FradSer** [comment]
So do any other sensor?

**Comment by lprhodes** [comment]
@FradSer 
> So do any other sensor?

Not at this time - hom bridge doesn't support the communication between two accessories very well yet.

**Comment by FradSer** [comment]
@lprhodes Thank you.

**Comment by lprhodes** [comment]
Check out release (2.0.9)[https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.0.9] for this - let me know if you have any issues.
