### ISSUE TITLE
Error Hex value missing

### ISSUE THREAD

**Issue by mitch7391** [lprhodes/homebridge-broadlink-rm#501]
Hi,

I bought a new light that uses RF but the seller could not confirm the frequency it emits. Is this an error in something I have done in setup or does this confirm that the RF is a band that Broadlink does not use? Error messages below for me trying to send an ON command after learning its code:

Jul 12 18:46:46 homebridge homebridge[1377]: (node:1377) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: [ERROR]: Fish Light sendData (HEX value is missing)
Jul 12 18:46:46 homebridge homebridge[1377]:     at module.exports (/opt/node/lib/node_modules/homebridge-broadlink-rm/helpers/sendData.js:7:3)
Jul 12 18:46:46 homebridge homebridge[1377]:     at LightAccessory.performSend (/opt/node/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:45:7)
Jul 12 18:46:46 homebridge homebridge[1377]:     at catchDelayCancelError (/opt/node/lib/node_modules/homebridge-broadlink-rm/accessories/light.js:138:20)
Jul 12 18:46:46 homebridge homebridge[1377]:     at catchDelayCancelError (/opt/node/lib/node_modules/homebridge-broadlink-rm/helpers/catchDelayCancelError.js:8:20)
Jul 12 18:46:46 homebridge homebridge[1377]:     at LightAccessory.setBrightness (/opt/node/lib/node_modules/homebridge-broadlink-rm/accessories/light.js:94:11)
Jul 12 18:46:46 homebridge homebridge[1377]:     at LightAccessory.setCharacteristicValue (/opt/node/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:139:10)
Jul 12 18:46:46 homebridge homebridge[1377]:     at Characteristic.Brightness.emit (events.js:193:13)
Jul 12 18:46:46 homebridge homebridge[1377]:     at Characteristic.Brightness.Characteristic.setValue (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Jul 12 18:46:46 homebridge homebridge[1377]:     at Service.Lightbulb.Service.setCharacteristic (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:183:32)
Jul 12 18:46:46 homebridge homebridge[1377]:     at ServiceManager.setCharacteristic (/opt/node/lib/node_modules/homebridge-broadlink-rm/helpers/serviceManager.js:19:18)
Jul 12 18:46:46 homebridge homebridge[1377]:     at LightAccessory.setSwitchState (/opt/node/lib/node_modules/homebridge-broadlink-rm/accessories/light.js:41:24)
Jul 12 18:46:46 homebridge homebridge[1377]:     at LightAccessory.setCharacteristicValue (/opt/node/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:139:10)
Jul 12 18:46:46 homebridge homebridge[1377]:     at Characteristic.On.emit (events.js:193:13)
Jul 12 18:46:46 homebridge homebridge[1377]:     at Characteristic.On.Characteristic.setValue (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Jul 12 18:46:46 homebridge homebridge[1377]:     at Bridge.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
Jul 12 18:46:46 homebridge homebridge[1377]:     at Array.forEach (<anonymous>:null:null)
Jul 12 18:46:46 homebridge homebridge[1377]:     at Bridge.Accessory._handleSetCharacteristics (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
Jul 12 18:46:46 homebridge homebridge[1377]:     at HAPServer.emit (events.js:193:13)
Jul 12 18:46:46 homebridge homebridge[1377]:     at HAPServer._handleCharacteristics (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
Jul 12 18:46:46 homebridge homebridge[1377]:     at HAPServer.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jul 12 18:46:46 homebridge homebridge[1377]:     at IncomingMessage.emit (events.js:193:13)
Jul 12 18:46:46 homebridge homebridge[1377]:     at endReadableNT (_stream_readable.js:1139:12)
Jul 12 18:46:46 homebridge homebridge[1377]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)
Jul 12 18:46:46 homebridge homebridge[1377]: (node:1377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
Jul 12 18:46:47 homebridge homebridge[1377]: [7/12/2019, 6:46:47 PM] [Broadlink RM] TV getSwitchState: true

Thanks in advance for any suggestions :)

**Comment by mitch7391** [comment]
Hmm I have confirmed it’s not a problem with the RF band, I changed the config to make it just a switch with an ON and OFF command and that works fine. The problem must be with how I am setting up the config for a ‘light’ with ON, OFF, Brightness and Hue. Does someone have an example to follow? I tried the example config here, but it didn’t have an ON command in it. Also not sure how to do the Hue config (I have 15 colours and white).

**Comment by lprhodes** [comment]
Hi @mitch7391 

The sample config assumes that sending any brightness will turn on the light but that's not always the case, you can definitely use an "on" code.

Closing this for now but feel free to re-open with your config and I'll take a look.
