### ISSUE TITLE
setFanSpeed

### ISSUE THREAD

**Issue by pootney0806** [lprhodes/homebridge-broadlink-rm#503]
Hi, whenever I turn the fan on, it instantly goes to 100% in the Home App. By default, on the actual fan itself, when you turn it on it goes to a speed of 10% and then allows you to increase as necessary. 

Is there anyway to have it so that when I turn the fan on in the Home App, the speed is set to 10% and not 100%? Have tried looking for the setFanSpeed and getFanSpeed code, but i'm not having much luck

**Comment by mitch7391** [comment]
I was about to post the same issue. My fan when turned on defaults to fan speed 3 out of 6 and was wondering if there was a ‘set default speed’ like how there is ‘set default brightness’ for the light accessory.

**Comment by mitch7391** [comment]
@Iprhodes is this something that could be added to a future update or maybe already is a part of it?

**Comment by lprhodes** [comment]
Here you go:

https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/3.5.9
