### ISSUE TITLE
I get different HEX Code for IR Scan with differents remote

### ISSUE THREAD

**Issue by xaviplazas** [lprhodes/homebridge-broadlink-rm#504]
Hi, I've a RM Mini 3. When I active the Learn Accessory in homekit and press a button in the remote control (for example TV), i get the Hex Code. But when i try again for the same button, i get another different Hex Code. 

I try with different remote control and I get the same problem. 

I try with long press in the remote control with a shot press, I don't have no idea.

Can you help me? Some idea?

Thanks and best regards.

**Comment by smellypoops** [comment]
I am also having the same problem with my RF scanning. I am able to add to my IHC app but the hex data on the plugin keeps changing

**Comment by st3v3nFr** [comment]
I also have the same issue. Can’t figure out what i need to do. If you have any help, please share with us :)

**Comment by lprhodes** [comment]
The IR code won't necessarily be identical each time you learn it. Happy to re-open if there's an actual issue here.

For RF issues please @smellypoops please open a new issue, thanks!
