### ISSUE TITLE
RM Mini 3 not detected

### ISSUE THREAD

**Issue by patrickchoi** [lprhodes/homebridge-broadlink-rm#505]
SN: RM5Bxxxxxx (can provide more digits if needed)
Bought this last week off Amazon, homebridge doesn't seem to detect it

config.json:

> {
>   "bridge": {
>     "name": "Meow",
>     "username": "CC:22:3D:E3:CE:30",
>     "pin": "031-45-154"
>   },
> 
>   "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
>   "ports": {
>     "start": 52100,
>     "end": 52150,
>     "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
>   },
> 
>   "hosts": [{
>           "address": "10.0.0.63",
>           "mac": "c8:f7:42:75:06:0f",
>           "isRFSupported": true
>       }],
>   "platforms": [{
>     "platform": "TplinkSmarthome",
>     "name": "TplinkSmarthome"
>   },
>   {
>     "platform":"BroadlinkRM",
>     "name":"Broadlink RM",
>     "hideScanFrequencyButton": true,
>     "hideLearnButton": false,
>     "hideWelcomeMessage": true
>   }]
> }
> 

And the console:

> 
> [8/3/2019, 7:18:52 AM] Loaded config.json with 0 accessories and 2 platforms.
> [8/3/2019, 7:18:52 AM] ---
> [8/3/2019, 7:18:52 AM] Loaded plugin: homebridge-broadlink-rm
> [8/3/2019, 7:18:52 AM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
> [8/3/2019, 7:18:52 AM] ---
> [8/3/2019, 7:18:52 AM] Loaded plugin: homebridge-tplink-smarthome
> [8/3/2019, 7:18:52 AM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
> [8/3/2019, 7:18:52 AM] ---
> [8/3/2019, 7:18:52 AM] Loading 2 platforms...
> [8/3/2019, 7:18:52 AM] [TplinkSmarthome] Initializing TplinkSmarthome platform...
> [8/3/2019, 7:18:52 AM] [TplinkSmarthome] homebridge-tplink-smarthome v4.0.1, node v12.6.0, homebridge v0.4.50
> [8/3/2019, 7:18:52 AM] [Broadlink RM] Initializing BroadlinkRM platform...
> [8/3/2019, 7:18:52 AM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
> [8/3/2019, 7:18:52 AM] [Broadlink RM] [INFO] Running Homebridge Broadlink RM Plugin version 3.5.5
> [8/3/2019, 7:18:52 AM] [Broadlink RM] No accessories have been added to the "Broadlink RM" platform config.
> [8/3/2019, 7:18:52 AM] [Broadlink RM] Initializing platform accessory 'Learn'...

And that's it, it doesn't seem to detect the RM Mini

**Comment by patrickchoi** [comment]
Got it resolved. Downloaded the IHC app from App Store instead of the Broadlink iOS app on their webpage. Re-did the setup using IHC and it is being detected and able to learn IR codes!

**Comment by nickv2002** [comment]
Thanks for the tip @patrickchoi this unblocked me.
Link to iOS app for North America on the app store:
https://apps.apple.com/us/app/intelligent-home-center/id1084990073
