### ISSUE TITLE
projector screen switch

### ISSUE THREAD

**Issue by pratkai** [lprhodes/homebridge-broadlink-rm#512]
Hello,

I have a projector screen that needs to be stopped 20 seconds after ON hex is sent.  I guess I need to send a stop command after 20 sec the On hex data is sent but I'm a newbie and I cannot figure out how :) any suggestions please? Thanks a lot.

{
				"name": "Screen Down",
				"type": "switch",
				"sendCount": 1,
				"interval": 20,
				"enableAutoOff": true,
                               "data": "b2001202a7"
}

**Comment by nickkkk72** [comment]
@pratkai why did you close this issue ? Have you find an answer ? if yes, why not share it ?

**Comment by pratkai** [comment]
Sure, I could figure out. here it is:
           {
                "name": "Movie Screen",
                "type": "switch",
                "data": {
                    "on": [
                        {
                    "data": "b2001202a7...",
                    "pause": 23
                    },
                    {
                    "data": "b2001202a",
                    "pause": 0.3
                    }
                ],
           "off": [
                        {
                    "data": "b2001202a9",
                    "pause": 24
                    },
                    {
                    "data": "b2001202a",
                    "pause": 0.3
                    }
                ]
           
           
           
            }
        },

**Comment by nickkkk72** [comment]
Sorry. Thank you. Really, I don't need that, but just thinking about frustration of people who will google your exact same issue, see that you seem finded a solution, and keep it just for you…
We can ask..., but we must share... Thanks for them.

**Comment by pratkai** [comment]
You're totally right, I should have done that.

**Comment by nickkkk72** [comment]
👍
