### ISSUE TITLE
Broadlink RM mini 3 - unknown device 5f36

### ISSUE THREAD

**Issue by SSpecken** [lprhodes/homebridge-broadlink-rm#515]
Just bought a Broadlink RM mini 3 and integrated it into my network successfully. But the homebridge-broadlink-rm module doesn‘t recognize it: 

``` Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "5f36". The device is connected to your network with the IP address "x.x.x.x"```

**Comment by stevenliuyi** [comment]
I actually encountered the same problem. The device I had with device code `5f36` was the new Red Bean version of Broadlink RM Mini3. I cannot learn code using it, so I returned it and bought the original Black Bean version (with device code `2737`), and it works perfectly. According to #513, this plugin doesn't support new Broadlink devices, which may also includes the new version of RM Mini3.
