### ISSUE TITLE
 Can’t install 3.6.13

### ISSUE THREAD

**Issue by cilianospina** [lprhodes/homebridge-broadlink-rm#525]
> sudo npm install -g homebridge-broadlink-rm

> raw-socket@1.7.0 install /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
> node-gyp rebuild

>gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/10.18.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/.node-gyp'
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
gyp ERR! node -v v10.18.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raw-socket@1.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by marcoschmidt79** [comment]
sudo npm install -g --unsafe-perm homebridge-broadlink-rm@3.6.11

**Comment by cilianospina** [comment]
> sudo npm install -g --unsafe-perm homebridge-broadlink-rm@3.6.11

I use sudo npm install -g --unsafe-perm homebridge-broadlink-rm
Work fine.
