### ISSUE TITLE
any queue issue?

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#53]
I'm using UDP sender to communicate with my broadlink these days. I found out that when setting up a scene with a lot of accessories, some of the packets codes are not being sent (or received by broadlink device).
have you encountered this problem with your plugin? have you managed to make a queue of commands so that no code will be lost when using multiple devices in a scene?
Homebridge does not let the code of one accessory to be related to another so I found no reasonable way of making up a queue, though I found a tricky way around it. But I'm a noob so I hope you could do that better cause I'm considering changing all my accessories to use your plugin :)

**Comment by lprhodes** [comment]
I've not encountered this issue, no - and if things don't work out for you then I can add a configuration that adds a slight delay before each command.

**Comment by nitaybz** [comment]
adding a delay at the beginning of each command will send the commands all together after that specific time of delay so it won't solve the issue, anyway, can you confirm you are working with multiple accessories in a scene using the same broadlink device and it's working right?
can it be because i'm using each as an accessory and you've done it as a platform? is it possible that homebridge know's how to send commands in a queue for platforms?
or could it be because i'm using the old codes with a lot of "5" and "a" at the beginning....
Thanks!
