### ISSUE TITLE
Seeing shade stuck on opening…

### ISSUE THREAD

**Issue by webpablo** [lprhodes/homebridge-broadlink-rm#54]
I think I saw in another thread that you fixed an issue around the constant opening or closing status. I have updated to the latest with NPM but still seeing the issue. It is possible this is related to the fact I do not have a programmed stop button yet?

**Comment by lprhodes** [comment]
You're definitely using 1.4.1?

**Comment by webpablo** [comment]
Yeah I am actual on 2.0.4 now and still seeing the icon spin on opening forever. Even when the log state reaches 100.

**Comment by webpablo** [comment]
I was finally able to add the stop command and I don't think the issue is occurring now. As soon as I added the stop command things started behaving.
