### ISSUE TITLE
device not found RM mini 3

### ISSUE THREAD

**Issue by sanchj** [lprhodes/homebridge-broadlink-rm#541]
Homebridge can not discover my RM mini 3. I had checked it using auto-discovery by default and adding Host IP and MAC manually in config.json. could someone help me ? Thanks !!

**Comment by sanchj** [comment]
My current config:

{
  "bridge":{
    "name":"HomebridgeIR1",
    "username":"CD:22:3D:E3:CE:35",
    "port":51826,
    "pin":"031-45-154"
  },
  "description":"Homebridge",
  "accessories":[

  ],
  "platforms":[
    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false,
      "hideWelcomeMessage": false,

"hosts": [
  {
    "address": "192.168.1.95",
    "mac": "24:df:a7:7a:98:81",
    "isRFSupported": true
  }
],


      "accessories":[
        {
          "name":"Blind",
          "type":"window-covering",
          "totalDurationOpen": 45,
          "totalDurationClose": 40,
          "data":{
            "open":"2600500000012...",
            "close":"2600500000012...",
            "stop":"2600500000012..."
          }
        }
      ]
    }
  ]
}

**Comment by sanchj** [comment]
Error:
[2020-1-17 13:04:28] [Broadlink RM] [INFO] Learn Code initializing (undefined)
[2020-1-17 13:04:28] [Broadlink RM] [ERROR] Learn Code (Couldn't learn code, device not found)

**Comment by lpettinati** [comment]
I'm having the same issue as @sanchj... using a brand new RM Mini 3.

My network allows UDP traffic but auto discovery is not working. I had no issues setting up the device using the Broadlink app on my iPhone.

I am able to ping the IP address for the RM Mini 3 (192.168.1.48) with no problem.
**IP Ping**
```
PING 192.168.1.48 (192.168.1.48) 56(84) bytes of data.
64 bytes from 192.168.1.48: icmp_seq=1 ttl=255 time=9.28 ms
64 bytes from 192.168.1.48: icmp_seq=2 ttl=255 time=4.97 ms
```

**Hostname Ping**
```
PING rm3-40-b3-8d.localdomain (192.168.1.48) 56(84) bytes of data.
64 bytes from RM3-40-b3-8d.localdomain (192.168.1.48): icmp_seq=1 ttl=255 time=3.83 ms
64 bytes from RM3-40-b3-8d.localdomain (192.168.1.48): icmp_seq=2 ttl=255 time=3.93 ms
```

@lprhodes — any insights would be appreciated.

Here's my config file:
```
{
    "bridge": {
        "name": "Homebridge Pi",
        "username": "FF:FF:FF:FF:FF:FF",
        "port": 25290,
        "pin": "123-45-678"
    },
    "platforms": [
	{
	 	"platform":"BroadlinkRM",
		"name":"Broadlink RM",
		
		"hosts": [
		{
			"address": "192.168.1.48",
			"mac": "c8:f7:42:40:b3:8d",
			"isRFSupported": false
		}
		],

		"accessories": [
        {
			"name": "Living Room A/C",
			"type": "switch",
			"data": {
				"off": "23CB2621000073C10400000071C1040000",
				"on":  "23CB2621002073C10400002071C1040000"
			}
		}
		]
	}
	]
}

```

On Homebridge startup, I see the following:
```
[1/19/2020, 2:49:26 PM] [Broadlink RM] Initializing BroadlinkRM platform...
[1/19/2020, 2:49:26 PM] [Broadlink RM] [INFO] Automatic Broadlink RM device discovery has been disabled as the "hosts" option has been set.
[1/19/2020, 2:49:26 PM] [Broadlink RM] Living Room A/C Accessory Ready
[1/19/2020, 2:49:26 PM] [Broadlink RM] Initializing platform accessory 'Learn'...
[1/19/2020, 2:49:26 PM] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...
[1/19/2020, 2:49:26 PM] [Broadlink RM] Initializing platform accessory 'Living Room A/C'...
Setup Payload:
X-HM://0024B8S1TB8OO
```

When I try to toggle the switch in the Home app, the following show in the log:
```
[1/19/2020, 2:49:40 PM] [Broadlink RM] Learn getSwitchState: undefined
[1/19/2020, 2:49:40 PM] [Broadlink RM] Scan Frequency getSwitchState: undefined
[1/19/2020, 2:49:40 PM] [Broadlink RM] Living Room A/C getSwitchState: false
[1/19/2020, 2:49:43 PM] [Broadlink RM] Living Room A/C setSwitchState: true
[1/19/2020, 2:49:43 PM] [Broadlink RM] [ERROR] Living Room A/C sendData (no device found)
```

Error Log shows the following when the switch is toggled:
192.168.1.14 is the IP for my iPhone, making the request
192.168.1.26 is the IP for my HomePod, used as a Homekit Hub
```
Sun, 19 Jan 2020 23:12:00 GMT EventedHTTPServer [::ffff:192.168.1.14] HTTP request: /characteristics
Sun, 19 Jan 2020 23:12:00 GMT HAPServer [B8:27:EB:99:FA:92] HAP Request: PUT /characteristics
Sun, 19 Jan 2020 23:12:00 GMT Accessory [Homebridge Pi] Processing characteristic set: [{"aid":8,"iid":17,"value":0}]
Sun, 19 Jan 2020 23:12:00 GMT Accessory [Homebridge Pi] Setting Characteristic "On" to value 0
Sun, 19 Jan 2020 23:12:00 GMT EventedHTTPServer [::ffff:192.168.1.26] Sending HTTP event '8.17' with data: {"characteristics":[{"aid":8,"iid":17,"value":false}]}
Sun, 19 Jan 2020 23:12:00 GMT EventedHTTPServer [::ffff:192.168.1.14] Muting event '8.17' notification for this connection since it originated here.
Sun, 19 Jan 2020 23:12:00 GMT EventedHTTPServer [::ffff:192.168.1.14] HTTP Response is finished
```

**Comment by shidevil** [comment]
Check if it’s an unidentified device ID. 

I have made a pull request to the library. Rm mini 3 with device ID 27d0.

**Comment by lpettinati** [comment]
Hi @shidevil — thanks for the suggestion!

Noob question, how do I check if I have an unidentified device ID?

**Comment by sanchj** [comment]
Hi @lpettinati,
As far as I know, the devide ID appears when the broadlink is found. Example ...
[Broadlink RM] [INFO] Discovered Broadlink RM Mini 3 D (5f36) at 192.168.1.8 (a7:df:24:xx:xx:xx)
In this case (my case), the device ID is 5f36

**Comment by sanchj** [comment]
Now, I'm able to discover my broadlink device. I had to unlink my device from the broadlink IOS app, reset the rm Mini, and link it to IHC for EU app. This way, my rm Mini is now discovered by homebridge.

**Comment by sanchj** [comment]
But, now I have another issue ... The IR code learn does not work ... When you press the learn button in home app, the front led in rm Mini does not turn on. And nothing happen in homebridge. Wait for 10 seconds and no results. Does somebody has a Broadlink Mini 5f36 working fine ? It seems to be some protocol issues with this model ...

**Comment by lpettinati** [comment]
Thanks @sanchj and @shidevil for your help!
I unlinked from the iOS app, reset, and used IHC to configure my RM mini3. It was auto discovered and everything seems to be working.

My device ID is 2737 all's working fine
