### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by eawystr** [lprhodes/homebridge-broadlink-rm#544]
Hi you all,

Installing the last version, I’ve had an error:

48 error code ENOENT
49 error syscall spawn git
50 error path git 
51 error errno ENOENT
52 error enoent Error while executing:
52 error enoent undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
52 error enoent 
52 error enoent
52 error enoent spawn git ENOENT
53 error enoent This is related to npm not being able to find a file.
54 verbose exit [ 1, true ]

Any ideas?

**Comment by AlistinnieTukimin-KSO** [comment]
You need to install git. Relevant line in the error:

```
50 error path git
```

**Comment by wailuen** [comment]
Thanks.. was having the same issue and did not notice that line.

**Comment by eawystr** [comment]
Thanks a lot! Everything solved now.
