### ISSUE TITLE
error at start

### ISSUE THREAD

**Issue by det-box** [lprhodes/homebridge-broadlink-rm#545]
Hello, since 3.6.21 comes at start: 
```
Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
Jan 18 18:44:17 hbridge3 homebridge[13654]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
Jan 18 18:44:17 hbridge3 homebridge[13654]:     at Server._loadPlatforms 
```

with 3.6.18 everything works
Im back to 3.6.18
node: 13.6.0
nem:6.13.6
Thanks

**Comment by gladiatormax** [comment]
Hi, same issue here.

**Comment by tawagny** [comment]
ERROR LOADING PLUGIN homebridge-broadlink-rm: Jan 20 16:12:54 kali homebridge[84427]: [1/20/2020, 4:12:54 PM] Error: Cannot find module 'hap-nodejs'

**Comment by det-box** [comment]
@tawagny 
Make this
sudo npm install -g --unsafe-perm hap-nodejs@latest

**Comment by daitium** [comment]
@tawagny thanks, it solved my problem as well.

**Comment by gintonic4all** [comment]
Installation of hap-nodejs didn’t solve problem for me. Same error.

**Comment by cmh-maker** [comment]
@gintonic4all try downgrading to 3.6.16 

sudo npm install -g --unsafe-perm homebridge-broadlink-rm@3.6.16

**Comment by grabson79** [comment]
I have the same issue, tried downgrading and have the following
+ homebridge-broadlink-rm@3.6.16
updated 1 package in 11.305s

but no plugin appears
I am using HOOBS

**Comment by det-box** [comment]
New install, now is Fine
