### ISSUE TITLE
Permission error on new release 

### ISSUE THREAD

**Issue by Scialla** [lprhodes/homebridge-broadlink-rm#547]
i'm trying to upgrade (on Jessie) from 3.6.18 (work perfectly) to 3.6.22 and this is result:

```sudo npm i homebridge-broadlink-rm

> raw-socket@1.7.0 install /home/pi/node_modules/raw-socket
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/node_modules/raw-socket/build'
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/raw-socket
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raw-socket@1.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-20T22_10_10_136Z-debug.log
```
Upgrade other plugin work fine

What can i do?
Thanks

**Comment by cilianospina** [comment]
Same problem but solved with 

`sudo npm install -g npm`

`sudo reboot`

and try again

**Comment by Scialla** [comment]
some warning but, works!!!
Thanks!!!!!!!

**Comment by Scialla** [comment]
sorry but I was wrong, now I'm giving this error and HB no longer starts:
`npm WARN notsup Unsupported engine for semver@7.1.1: wanted: {"node":">=10"} (current: {"node":"8.16.1","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.1.1`

**Comment by cilianospina** [comment]
I need downgrade Node to 10.12.0
`sudo n 10.12.0`

**Comment by Scialla** [comment]
i've Jessie; my nodes version is 8.16.1

**Comment by cilianospina** [comment]
you need update, can use
`sudo n 10.12.0`

**Comment by Scialla** [comment]
i need to make new backup because last time i've tried to update nodejs (with jessie) HB no start more.
i think is impossibile for me update nodejs, HB don't start anymore

**Comment by Scialla** [comment]
i've tried, after update npm, to install differente version of plugin; all the time i've same last error BUT, with version until 3.6.18, plugin work and HB start, from 3.6.20 plugin don't work and HB don't start anymore

i will remain with 3.6.18, new version make me crash HB

**Comment by Scialla** [comment]
i tried with `sudo npm install -g --unsafe-perm hap-nodejs@latest` and now latest broad link plugin work
Error `sorry but I was wrong, now I'm giving this error and HB no longer starts:
npm WARN notsup Unsupported engine for semver@7.1.1: wanted: {"node":">=10"} (current: {"node":"8.16.1","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.1.1` persist but plugin work
nodejs version remain v8.16.1 and i've not problem with jessie :)
