### ISSUE TITLE
TypeError:dev.device is not a function

### ISSUE THREAD

**Issue by Warden630** [lprhodes/homebridge-broadlink-rm#55]
I got the same problem.
It still go like this after run `npm i broadlinkjs@"git+https://github.com/lprhodes/broadlinkjs.git" -g`
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98 dev.device();
^
TypeError:dev.device is not a function at module.exports.Broadlink.genDevice (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98:13)
at Socket.cs.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:187:29) at emitTwo (events.js:106:13)
at Socket.emit (events.js:194:7) at UDP.onMessage [as onmessage] (dgram.js:545:8)

maybe because I got an Glanz airconditioner oemed by broadlink?

**Comment by Warden630** [comment]
it's this device BROADLINK_OEM-T1-E4-6C-46 , a Glanz Airconditioner.
after I turned it off, it all works. could it be supported?

**Comment by lprhodes** [comment]
I can support it in a way that it doesn't crash the code but there'd be no direct support for the air conditioner this module is for controlling Broadlink's RM devices which support the transmission of RF and IR hex codes.

**Comment by Warden630** [comment]
yes，it will be great if it doesnt crash. i just want to ignore it

**Comment by lprhodes** [comment]
The code that's already there should get rid of that error...

You removed it first?
```
npm r broadlinkjs -g
npm i broadlinkjs@"git+https://github.com/lprhodes/broadlinkjs.git" -g
```

**Comment by Warden630** [comment]
ok i see. i didn't r it

thx
