### ISSUE TITLE
Error when installing plugin.

### ISSUE THREAD

**Issue by DCMarine** [lprhodes/homebridge-broadlink-rm#550]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

I have installed the platform helper separately so I now it is there.

**Comment by DCMarine** [comment]
Resolved my own issue with install git client.

**Comment by Faisalthe01** [comment]
how did you install Git Client?
