### ISSUE TITLE
Error installing 3.6.22

### ISSUE THREAD

**Issue by HP246** [lprhodes/homebridge-broadlink-rm#556]
I have an issue and I don't know how to solve it.

I can+t get the plugin to start...

Here is the log...

Platform helper tools installed...

hab-nodejs installed...

Node Version: 11.13.0

git installed...

LOG:
pi@hbridge2:~ $ sudo npm install -g --unsafe-perm homebridge-broadlink-rm@latest -g
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b feature/typescript git://github.com/lprhodes/homebridge-platform-helper.git /root/.npm/_cacache/tmp/git-clone-1c72929d
npm ERR! fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-1c72929d' nicht erstellen.: Keine Berechtigung
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-01T09_44_03_730Z-debug.log

Any ideas?

I try as root too. No changes

**Comment by SerhiiAksiutin** [comment]
```
user@raspberrypi:~$ sudo npm install homebridge-broadlink-rm@3.6.22
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b feature/typescript git://github.com/lprhodes/homebridge-platform-helper.git /root/.npm/_cacache/tmp/git-clone-06abbce9
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-06abbce9': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-04T07_37_09_361Z-debug.log
```

```
user@raspberrypi:~$ cat /root/.npm/_logs/2020-02-04T07_37_09_361Z-debug.log
cat: /root/.npm/_logs/2020-02-04T07_37_09_361Z-debug.log: Permission denied
pi@raspberrypi:~$ sudo cat /root/.npm/_logs/2020-02-04T07_37_09_361Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'homebridge-broadlink-rm@3.6.22' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session 03a0f7877e51f8ea
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-broadlink-rm 512ms (from cache)
8 silly pacote version manifest for homebridge-broadlink-rm@3.6.22 fetched in 602ms
9 timing stage:loadCurrentTree Completed in 723ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-broadlink-rm@3.6.22 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/broadlinkjs-rm 378ms (from cache)
18 silly pacote range manifest for broadlinkjs-rm@^0.7.6 fetched in 446ms
19 silly resolveWithNewModule broadlinkjs-rm@0.7.6 checking installable status
20 silly fetchPackageMetaData error for homebridge-platform-helper@github:lprhodes/homebridge-platform-helper#feature/typescript Command failed: git clone --depth=1 -q -b feature/typescript git://github.com/lprhodes/homebridge-platform-helper.git /root/.npm/_cacache/tmp/git-clone-06abbce9
20 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-06abbce9': Permission denied
21 http fetch GET 304 https://registry.npmjs.org/find-key 608ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/net-ping 566ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/github-version-checker 614ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/uuid 566ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/chai 665ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/ping 616ms (from cache)
27 silly pacote range manifest for find-key@^2.0.1 fetched in 676ms
28 silly resolveWithNewModule find-key@2.1.3 checking installable status
29 silly pacote range manifest for net-ping@^1.2.3 fetched in 637ms
30 silly resolveWithNewModule net-ping@1.2.3 checking installable status
31 silly pacote range manifest for github-version-checker@^1.2.0 fetched in 706ms
32 silly resolveWithNewModule github-version-checker@1.2.0 checking installable status
33 silly pacote range manifest for uuid@^3.3.3 fetched in 662ms
34 silly resolveWithNewModule uuid@3.4.0 checking installable status
35 silly pacote range manifest for chai@^4.2.0 fetched in 729ms
36 silly resolveWithNewModule chai@4.2.0 checking installable status
37 silly pacote range manifest for ping@^0.2.2 fetched in 680ms
38 silly resolveWithNewModule ping@0.2.2 checking installable status
39 timing stage:rollbackFailedOptional Completed in 3ms
40 timing stage:runTopLevelLifecycles Completed in 1551ms
41 silly saveTree pi
41 silly saveTree └─┬ homebridge-broadlink-rm@3.6.22
41 silly saveTree   ├── broadlinkjs-rm@0.7.6
41 silly saveTree   ├── chai@4.2.0
41 silly saveTree   ├── find-key@2.1.3
41 silly saveTree   ├── github-version-checker@1.2.0
41 silly saveTree   ├── net-ping@1.2.3
41 silly saveTree   ├── ping@0.2.2
41 silly saveTree   └── uuid@3.4.0
42 verbose stack Error: Command failed: git clone --depth=1 -q -b feature/typescript git://github.com/lprhodes/homebridge-platform-helper.git /root/.npm/_cacache/tmp/git-clone-06abbce9
42 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-06abbce9': Permission denied
42 verbose stack
42 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
42 verbose stack     at ChildProcess.emit (events.js:198:13)
42 verbose stack     at maybeClose (internal/child_process.js:982:16)
42 verbose stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
42 verbose stack     at Socket.emit (events.js:198:13)
42 verbose stack     at Pipe._handle.close (net.js:606:12)
43 verbose cwd /home/pi
44 verbose Linux 4.19.75-v7+
45 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "homebridge-broadlink-rm@3.6.22"
46 verbose node v10.16.3
47 verbose npm  v6.9.0
48 error code 128
49 error Command failed: git clone --depth=1 -q -b feature/typescript git://github.com/lprhodes/homebridge-platform-helper.git /root/.npm/_cacache/tmp/git-clone-06abbce9
49 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-06abbce9': Permission denied
50 verbose exit [ 1, true ]
```

**Comment by SerhiiAksiutin** [comment]
3.6.16 still works:
`sudo npm install -g --unsafe-perm homebridge-broadlink-rm@3.6.16`

**Comment by HP246** [comment]
I have the nearly the same... :(

1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'homebridge-broadlink-rm@latest',
1 verbose cli   '-g' ]
2 info using npm@6.13.7
3 info using node@v11.13.0
4 verbose npm-session 91fd74babfa93d7c
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-broadlink-rm 1225ms (from cache)
8 silly pacote tag manifest for homebridge-broadlink-rm@latest fetched in 1297ms
9 timing stage:loadCurrentTree Completed in 2901ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 18ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 331ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-broadlink-rm@3.6.22 checking installable status
17 silly removeObsoleteDep removing homebridge-broadlink-rm@3.6.18 from the tree as its been replaced by a newer version or is no longer required
18 silly removeObsoleteDep removing broadlinkjs-rm@0.7.6 from the tree as its been replaced by a newer version or is no longer required
19 silly removeObsoleteDep removing chai@4.2.0 from the tree as its been replaced by a newer version or is no longer required
20 silly removeObsoleteDep removing assertion-error@1.1.0 from the tree as its been replaced by a newer version or is no longer required
21 silly removeObsoleteDep removing check-error@1.0.2 from the tree as its been replaced by a newer version or is no longer required
22 silly removeObsoleteDep removing deep-eql@3.0.1 from the tree as its been replaced by a newer version or is no longer required
23 silly removeObsoleteDep removing type-detect@4.0.8 from the tree as its been replaced by a newer version or is no longer required
24 silly removeObsoleteDep removing get-func-name@2.0.0 from the tree as its been replaced by a newer version or is no longer required
25 silly removeObsoleteDep removing pathval@1.1.0 from the tree as its been replaced by a newer version or is no longer required
26 silly removeObsoleteDep removing find-key@2.1.3 from the tree as its been replaced by a newer version or is no longer required
27 silly removeObsoleteDep removing github-version-checker@1.2.0 from the tree as its been replaced by a newer version or is no longer required
28 silly removeObsoleteDep removing chalk@1.1.3 from the tree as its been replaced by a newer version or is no longer required
29 silly removeObsoleteDep removing ansi-styles@2.2.1 from the tree as its been replaced by a newer version or is no longer required
30 silly removeObsoleteDep removing escape-string-regexp@1.0.5 from the tree as its been replaced by a newer version or is no longer required
31 silly removeObsoleteDep removing has-ansi@2.0.0 from the tree as its been replaced by a newer version or is no longer required
32 silly removeObsoleteDep removing ansi-regex@2.1.1 from the tree as its been replaced by a newer version or is no longer required
33 silly removeObsoleteDep removing strip-ansi@3.0.1 from the tree as its been replaced by a newer version or is no longer required
34 silly removeObsoleteDep removing supports-color@2.0.0 from the tree as its been replaced by a newer version or is no longer required
35 silly removeObsoleteDep removing coffeescript@1.12.7 from the tree as its been replaced by a newer version or is no longer required
36 silly removeObsoleteDep removing got@7.1.0 from the tree as its been replaced by a newer version or is no longer required
37 silly removeObsoleteDep removing decompress-response@3.3.0 from the tree as its been replaced by a newer version or is no longer required
38 silly removeObsoleteDep removing mimic-response@1.0.1 from the tree as its been replaced by a newer version or is no longer required
39 silly removeObsoleteDep removing duplexer3@0.1.4 from the tree as its been replaced by a newer version or is no longer required
40 silly removeObsoleteDep removing get-stream@3.0.0 from the tree as its been replaced by a newer version or is no longer required
41 silly removeObsoleteDep removing is-plain-obj@1.1.0 from the tree as its been replaced by a newer version or is no longer required
42 silly removeObsoleteDep removing is-retry-allowed@1.2.0 from the tree as its been replaced by a newer version or is no longer required
43 silly removeObsoleteDep removing is-stream@1.1.0 from the tree as its been replaced by a newer version or is no longer required
44 silly removeObsoleteDep removing isurl@1.0.0 from the tree as its been replaced by a newer version or is no longer required
45 silly removeObsoleteDep removing has-to-string-tag-x@1.4.1 from the tree as its been replaced by a newer version or is no longer required
46 silly removeObsoleteDep removing has-symbol-support-x@1.4.2 from the tree as its been replaced by a newer version or is no longer required
47 silly removeObsoleteDep removing is-object@1.0.1 from the tree as its been replaced by a newer version or is no longer required
48 silly removeObsoleteDep removing lowercase-keys@1.0.1 from the tree as its been replaced by a newer version or is no longer required
49 silly removeObsoleteDep removing p-cancelable@0.3.0 from the tree as its been replaced by a newer version or is no longer required
50 silly removeObsoleteDep removing p-timeout@1.2.1 from the tree as its been replaced by a newer version or is no longer required
51 silly removeObsoleteDep removing p-finally@1.0.0 from the tree as its been replaced by a newer version or is no longer required
52 silly removeObsoleteDep removing timed-out@4.0.1 from the tree as its been replaced by a newer version or is no longer required
53 silly removeObsoleteDep removing url-parse-lax@1.0.0 from the tree as its been replaced by a newer version or is no longer required
54 silly removeObsoleteDep removing prepend-http@1.0.4 from the tree as its been replaced by a newer version or is no longer required
55 silly removeObsoleteDep removing url-to-options@1.0.1 from the tree as its been replaced by a newer version or is no longer required
56 silly removeObsoleteDep removing semver@5.7.1 from the tree as its been replaced by a newer version or is no longer required
57 silly removeObsoleteDep removing homebridge-platform-helper@1.2.1 from the tree as its been replaced by a newer version or is no longer required
58 silly removeObsoleteDep removing mqtt@3.0.0 from the tree as its been replaced by a newer version or is no longer required
59 silly removeObsoleteDep removing base64-js@1.3.1 from the tree as its been replaced by a newer version or is no longer required
60 silly removeObsoleteDep removing commist@1.1.0 from the tree as its been replaced by a newer version or is no longer required
61 silly removeObsoleteDep removing leven@2.1.0 from the tree as its been replaced by a newer version or is no longer required
62 silly removeObsoleteDep removing minimist@1.2.0 from the tree as its been replaced by a newer version or is no longer required
63 silly removeObsoleteDep removing concat-stream@1.6.2 from the tree as its been replaced by a newer version or is no longer required
64 silly removeObsoleteDep removing buffer-from@1.1.1 from the tree as its been replaced by a newer version or is no longer required
65 silly removeObsoleteDep removing inherits@2.0.4 from the tree as its been replaced by a newer version or is no longer required
66 silly removeObsoleteDep removing readable-stream@2.3.7 from the tree as its been replaced by a newer version or is no longer required
67 silly removeObsoleteDep removing core-util-is@1.0.2 from the tree as its been replaced by a newer version or is no longer required
68 silly removeObsoleteDep removing isarray@1.0.0 from the tree as its been replaced by a newer version or is no longer required
69 silly removeObsoleteDep removing process-nextick-args@2.0.1 from the tree as its been replaced by a newer version or is no longer required
70 silly removeObsoleteDep removing safe-buffer@5.1.2 from the tree as its been replaced by a newer version or is no longer required
71 silly removeObsoleteDep removing string_decoder@1.1.1 from the tree as its been replaced by a newer version or is no longer required
72 silly removeObsoleteDep removing safe-buffer@5.1.2 from the tree as its been replaced by a newer version or is no longer required
73 silly removeObsoleteDep removing util-deprecate@1.0.2 from the tree as its been replaced by a newer version or is no longer required
74 silly removeObsoleteDep removing typedarray@0.0.6 from the tree as its been replaced by a newer version or is no longer required
75 silly removeObsoleteDep removing end-of-stream@1.4.4 from the tree as its been replaced by a newer version or is no longer required
76 silly removeObsoleteDep removing once@1.4.0 from the tree as its been replaced by a newer version or is no longer required
77 silly removeObsoleteDep removing wrappy@1.0.2 from the tree as its been replaced by a newer version or is no longer required
78 silly removeObsoleteDep removing es6-map@0.1.5 from the tree as its been replaced by a newer version or is no longer required
79 silly removeObsoleteDep removing es6-set@0.1.5 from the tree as its been replaced by a newer version or is no longer required
80 silly removeObsoleteDep removing es6-symbol@3.1.1 from the tree as its been replaced by a newer version or is no longer required
81 silly removeObsoleteDep removing event-emitter@0.3.5 from the tree as its been replaced by a newer version or is no longer required
82 silly removeObsoleteDep removing help-me@1.1.0 from the tree as its been replaced by a newer version or is no longer required
83 silly removeObsoleteDep removing callback-stream@1.1.0 from the tree as its been replaced by a newer version or is no longer required
84 silly removeObsoleteDep removing glob-stream@6.1.0 from the tree as its been replaced by a newer version or is no longer required
85 silly removeObsoleteDep removing extend@3.0.2 from the tree as its been replaced by a newer version or is no longer required
86 silly removeObsoleteDep removing glob@7.1.6 from the tree as its been replaced by a newer version or is no longer required
87 silly removeObsoleteDep removing fs.realpath@1.0.0 from the tree as its been replaced by a newer version or is no longer required
88 silly removeObsoleteDep removing inflight@1.0.6 from the tree as its been replaced by a newer version or is no longer required
89 silly removeObsoleteDep removing minimatch@3.0.4 from the tree as its been replaced by a newer version or is no longer required
90 silly removeObsoleteDep removing brace-expansion@1.1.11 from the tree as its been replaced by a newer version or is no longer required
91 silly removeObsoleteDep removing balanced-match@1.0.0 from the tree as its been replaced by a newer version or is no longer required
92 silly removeObsoleteDep removing concat-map@0.0.1 from the tree as its been replaced by a newer version or is no longer required
93 silly removeObsoleteDep removing path-is-absolute@1.0.1 from the tree as its been replaced by a newer version or is no longer required
94 silly removeObsoleteDep removing glob-parent@3.1.0 from the tree as its been replaced by a newer version or is no longer required
95 silly removeObsoleteDep removing is-glob@3.1.0 from the tree as its been replaced by a newer version or is no longer required
96 silly removeObsoleteDep removing is-extglob@2.1.1 from the tree as its been replaced by a newer version or is no longer required
97 silly removeObsoleteDep removing path-dirname@1.0.2 from the tree as its been replaced by a newer version or is no longer required
98 silly removeObsoleteDep removing is-negated-glob@1.0.0 from the tree as its been replaced by a newer version or is no longer required
99 silly removeObsoleteDep removing ordered-read-streams@1.0.1 from the tree as its been replaced by a newer version or is no longer required
100 silly removeObsoleteDep removing pumpify@1.5.1 from the tree as its been replaced by a newer version or is no longer required
101 silly removeObsoleteDep removing duplexify@3.7.1 from the tree as its been replaced by a newer version or is no longer required
102 silly removeObsoleteDep removing stream-shift@1.0.1 from the tree as its been replaced by a newer version or is no longer required
103 silly removeObsoleteDep removing pump@2.0.1 from the tree as its been replaced by a newer version or is no longer required
104 silly removeObsoleteDep removing remove-trailing-separator@1.1.0 from the tree as its been replaced by a newer version or is no longer required
105 silly removeObsoleteDep removing to-absolute-glob@2.0.2 from the tree as its been replaced by a newer version or is no longer required
106 silly removeObsoleteDep removing is-absolute@1.0.0 from the tree as its been replaced by a newer version or is no longer required
107 silly removeObsoleteDep removing is-relative@1.0.0 from the tree as its been replaced by a newer version or is no longer required
108 silly removeObsoleteDep removing is-unc-path@1.0.0 from the tree as its been replaced by a newer version or is no longer required
109 silly removeObsoleteDep removing unc-path-regex@0.1.2 from the tree as its been replaced by a newer version or is no longer required
110 silly removeObsoleteDep removing is-windows@1.0.2 from the tree as its been replaced by a newer version or is no longer required
111 silly removeObsoleteDep removing unique-stream@2.3.1 from the tree as its been replaced by a newer version or is no longer required
112 silly removeObsoleteDep removing json-stable-stringify-without-jsonify@1.0.1 from the tree as its been replaced by a newer version or is no longer required
113 silly removeObsoleteDep removing through2-filter@3.0.0 from the tree as its been replaced by a newer version or is no longer required
114 silly removeObsoleteDep removing through2@2.0.5 from the tree as its been replaced by a newer version or is no longer required
115 silly removeObsoleteDep removing xtend@4.0.2 from the tree as its been replaced by a newer version or is no longer required
116 silly removeObsoleteDep removing mqtt-packet@6.3.0 from the tree as its been replaced by a newer version or is no longer required
117 silly removeObsoleteDep removing bl@1.2.2 from the tree as its been replaced by a newer version or is no longer required
118 silly removeObsoleteDep removing safe-buffer@5.2.0 from the tree as its been replaced by a newer version or is no longer required
119 silly removeObsoleteDep removing pump@3.0.0 from the tree as its been replaced by a newer version or is no longer required
120 silly removeObsoleteDep removing reinterval@1.1.0 from the tree as its been replaced by a newer version or is no longer required
121 silly removeObsoleteDep removing split2@3.1.1 from the tree as its been replaced by a newer version or is no longer required
122 silly removeObsoleteDep removing readable-stream@3.5.0 from the tree as its been replaced by a newer version or is no longer required
123 silly removeObsoleteDep removing websocket-stream@5.5.0 from the tree as its been replaced by a newer version or is no longer required
124 silly removeObsoleteDep removing ws@3.3.3 from the tree as its been replaced by a newer version or is no longer required
125 silly removeObsoleteDep removing async-limiter@1.0.1 from the tree as its been replaced by a newer version or is no longer required
126 silly removeObsoleteDep removing safe-buffer@5.1.2 from the tree as its been replaced by a newer version or is no longer required
127 silly removeObsoleteDep removing ultron@1.1.1 from the tree as its been replaced by a newer version or is no longer required
128 silly removeObsoleteDep removing node-persist@2.1.0 from the tree as its been replaced by a newer version or is no longer required
129 silly removeObsoleteDep removing is-absolute@0.2.6 from the tree as its been replaced by a newer version or is no longer required
130 silly removeObsoleteDep removing is-relative@0.2.1 from the tree as its been replaced by a newer version or is no longer required
131 silly removeObsoleteDep removing is-unc-path@0.1.2 from the tree as its been replaced by a newer version or is no longer required
132 silly removeObsoleteDep removing is-windows@0.2.0 from the tree as its been replaced by a newer version or is no longer required
133 silly removeObsoleteDep removing mkdirp@0.5.1 from the tree as its been replaced by a newer version or is no longer required
134 silly removeObsoleteDep removing minimist@0.0.8 from the tree as its been replaced by a newer version or is no longer required
135 silly removeObsoleteDep removing semver@7.1.2 from the tree as its been replaced by a newer version or is no longer required
136 silly removeObsoleteDep removing net-ping@1.2.3 from the tree as its been replaced by a newer version or is no longer required
137 silly removeObsoleteDep removing raw-socket@1.7.0 from the tree as its been replaced by a newer version or is no longer required
138 silly removeObsoleteDep removing nan@2.14.0 from the tree as its been replaced by a newer version or is no longer required
139 silly removeObsoleteDep removing ping@0.2.2 from the tree as its been replaced by a newer version or is no longer required
140 silly removeObsoleteDep removing q@1.1.2 from the tree as its been replaced by a newer version or is no longer required
141 silly removeObsoleteDep removing underscore@1.9.2 from the tree as its been replaced by a newer version or is no longer required
142 silly removeObsoleteDep removing uuid@3.4.0 from the tree as its been replaced by a newer version or is no longer required
143 http fetch GET 304 https://registry.npmjs.org/chai 540ms (from cache)
144 http fetch GET 304 https://registry.npmjs.org/ping 500ms (from cache)
145 silly pacote range manifest for chai@^4.2.0 fetched in 569ms
146 silly resolveWithNewModule chai@4.2.0 checking installable status
147 silly pacote range manifest for ping@^0.2.2 fetched in 540ms
148 silly resolveWithNewModule ping@0.2.2 checking installable status
149 http fetch GET 304 https://registry.npmjs.org/uuid 585ms (from cache)
150 silly pacote range manifest for uuid@^3.3.3 fetched in 618ms
151 silly resolveWithNewModule uuid@3.4.0 checking installable status
152 silly fetchPackageMetaData error for homebridge-platform-helper@github:lprhodes/homebridge-platform-helper#feature/typescript Command failed: git clone --depth=1 -q -b feature/typescript git://github.com/lprhodes/homebridge-platform-helper.git /root/.npm/_cacache/tmp/git-clone-e5a787bc
152 silly fetchPackageMetaData fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-e5a787bc' nicht erstellen.: Keine Berechtigung
153 http fetch GET 304 https://registry.npmjs.org/find-key 1337ms (from cache)
154 http fetch GET 304 https://registry.npmjs.org/net-ping 1307ms (from cache)
155 silly pacote range manifest for find-key@^2.0.1 fetched in 1383ms
156 silly resolveWithNewModule find-key@2.1.3 checking installable status
157 silly pacote range manifest for net-ping@^1.2.3 fetched in 1355ms
158 silly resolveWithNewModule net-ping@1.2.3 checking installable status
159 http fetch GET 304 https://registry.npmjs.org/broadlinkjs-rm 1411ms (from cache)
160 http fetch GET 304 https://registry.npmjs.org/github-version-checker 1392ms (from cache)
161 silly pacote range manifest for broadlinkjs-rm@^0.7.6 fetched in 1455ms
162 silly resolveWithNewModule broadlinkjs-rm@0.7.6 checking installable status
163 silly pacote range manifest for github-version-checker@^1.2.0 fetched in 1438ms
164 silly resolveWithNewModule github-version-checker@1.2.0 checking installable status
165 timing stage:rollbackFailedOptional Completed in 2ms
166 timing stage:runTopLevelLifecycles Completed in 4795ms
167 verbose stack Error: Command failed: git clone --depth=1 -q -b feature/typescript git://github.com/lprhodes/homebridge-platform-helper.git /root/.npm/_cacache/tmp/git-clone-e5a787bc
167 verbose stack fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-e5a787bc' nicht erstellen.: Keine Berechtigung
167 verbose stack
167 verbose stack     at ChildProcess.exithandler (child_process.js:297:12)
167 verbose stack     at ChildProcess.emit (events.js:193:13)
167 verbose stack     at maybeClose (internal/child_process.js:1001:16)
167 verbose stack     at Socket.stream.socket.on (internal/child_process.js:405:11)
167 verbose stack     at Socket.emit (events.js:193:13)
167 verbose stack     at Pipe._handle.close (net.js:614:12)
168 verbose cwd /home/pi
169 verbose Linux 4.14.20-v7+
170 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-broadlink-rm@latest" "-g"
171 verbose node v11.13.0
172 verbose npm  v6.13.7
173 error code 128
174 error Command failed: git clone --depth=1 -q -b feature/typescript git://github.com/lprhodes/homebridge-platform-helper.git /root/.npm/_cacache/tmp/git-clone-e5a787bc
174 error fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-e5a787bc' nicht erstellen.: Keine Berechtigung
175 verbose exit [ 1, true ]

**Comment by pax0707** [comment]
v3.6.18 is latest that work for me.

**Comment by HP246** [comment]
> v3.6.18 is latest that work for me.

Me 2... This is the last working version on my Rasp

**Comment by DmitryDemidov** [comment]
Same problem

**Comment by soorb** [comment]
sudo xcode-select --install

**Comment by HP246** [comment]
> sudo xcode-select --install

Doesn't work. 

sudo: xcode: command not found

**Comment by soorb** [comment]
install homebrew. this is for OS X Catalina in terminal, and the comment before also apply.

**Comment by HP246** [comment]
Doesn´t work...

sudo xcode-select --install
Password:
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

After I loged in on raspberry:

sudo xcode-select --install

sudo: xcode: command not found

**Comment by bday1978** [comment]
same here..

**Comment by dcon7776** [comment]
Same here. I tried installing v.22 on two different PIs and I got the same problem.

**Comment by kiwi-cam** [comment]
It looks like around version 3.6.17 @lprhodes switched to using a typescript version of the platform-helper. This version is not installed via npm, it's installed from git. The problem is that you're running git with sudo and root doesn't have permission to extract the git clone.  Try installing without sudo and if that doesn't work the best option is to fix your permissions so you don't have to run with sudo... or stick with an older version until npm is updated.

I spent a bit of time working through this issue with someone here: https://github.com/AlexanderBabel/homebridge-broadlink-rm/issues/64#issuecomment-574333176

**Comment by dcon7776** [comment]
I was able to install v3.6.18 with sudo without having to change permission. However, the install was not clean as I had several typescript related warnings. Version 3.6.22 just didn’t work at all with sudo. I had several fatal and permission errors. I will try your suggestion and see if I can get it to work. Thank you!

**Comment by HP246** [comment]
Yes that work 4 me...
i install it without sudo rights and that works 4 me without any problem.

Can't believe 🗡 
I´m so happy ....
