### ISSUE TITLE
error when start rm plugin

### ISSUE THREAD

**Issue by hkechung** [lprhodes/homebridge-broadlink-rm#56]
[37m[4/25/2017, 2:01:31 PM][39m [1m[31m====================[39m[22m
stdout
14:01:31
[37m[4/25/2017, 2:01:31 PM][39m [1m[31mERROR LOADING PLUGIN homebridge-broadlink-rm:[39m[22m
stdout
14:01:31
[37m[4/25/2017, 2:01:31 PM][39m [1m[31m/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:74
stdout
14:01:31
  async setCharacteristicValue (props, value, callback) {
stdout
14:01:31
        ^^^^^^^^^^^^^^^^^^^^^^
stdout
14:01:31
SyntaxError: Unexpected identifier
stdout
14:01:31
    at Object.exports.runInThisContext (vm.js:76:16)
stdout
14:01:31
    at Module._compile (module.js:528:28)
stdout
14:01:31
    at Object.Module._extensions..js (module.js:565:10)
stdout
14:01:31
    at Module.load (module.js:473:32)
stdout
14:01:31
    at tryModuleLoad (module.js:432:12)
stdout
14:01:31
    at Function.Module._load (module.js:424:3)
stdout
14:01:31
    at Module.require (module.js:483:17)
stdout
14:01:31
    at require (internal/module.js:20:19)
stdout
14:01:31
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:1:92)
stdout
14:01:31
    at Module._compile (module.js:556:32)[39m[22m
stdout
14:01:31
[37m[4/25/2017, 2:01:31 PM][39m [1m[31m====================[39m[22m
stdout
14:01:32
[37m[4/25/2017, 2:01:32 PM][39m Loaded plugin: homebridge-synology
stdout
14:01:32
[37m[4/25/2017, 2:01:32 PM][39m Registering accessory 'homebridge-synology.Synology'
stdout
14:01:32
[37m[4/25/2017, 2:01:32 PM][39m ---
stdout
14:01:32
[37m[4/25/2017, 2:01:32 PM][39m Loaded config.json with 0 accessories and 1 platforms.
stdout
14:01:32
[37m[4/25/2017, 2:01:32 PM][39m ---

any hint ?
Thanks

**Comment by lprhodes** [comment]
It's worth trying searching existing issues first:
https://github.com/lprhodes/homebridge-broadlink-rm/issues/38
https://github.com/lprhodes/homebridge-broadlink-rm/issues/42
https://github.com/lprhodes/homebridge-broadlink-rm/issues/48
