### ISSUE TITLE
v3.6.22 Error on Synology Docker/ The requested platform was not registered by any plugin

### ISSUE THREAD

**Issue by ishiigenji** [lprhodes/homebridge-broadlink-rm#568]
[homebridge.log](https://github.com/lprhodes/homebridge-broadlink-rm/files/4245831/homebridge.log)

Hi Guys, this is my first post on github, and I need your help figuring out how to get broadlink rm to work on my homebridge installed on a Synology Diskstation Docker environment. 
Since the last update to version 3.6.22, I keep getting the error "The requested platform 'BroadlinkRM' was not registered by any plugin." preventing Homebridge from running properly (I have attached the full log during the last boot)

I have no experience in coding, but have tried using most of the solutions seen in the other threads, which include downgrading to an older version, and "sudo npm install -g --unsafe-perm hap-nodejs@latest", without avail...

I kept my config.json to the bare minimum, as below:

```
{
    "bridge": {
        "name": "Homebridge CC92",
        "username": "0E:48:A4:62:CC:92",
        "port": 53897,
        "pin": "031-45-154"
    },
    "platforms": [
      {
        "platform": "BroadlinkRM",
        "name": "Broadlink RM",
        "hideScanFrequencyButton": false,
        "hideLearnButton": false
      }
    ]
}
```

My environment is:
Synology DS918+: DSM 6.2.2-24922 Update 4
Docker: v18.09.0-0506
Homebridge: v0.4.50
Node.js: v12.16.1
npm: v6.13.4
homebridge-broadlink-rm: v3.6.22 
 *I unfortunately cannot remember which version of BroadlinkRM I updated from, but it used to work seamlessly until then. 
 (please let me know if I should add anything to the list)

How can I fix this issue and get Broadlink RM to work again?

**Comment by danewallace** [comment]
I was having a similar issue on a macOS system using a previously functioning json configuration. I rolled back to an earlier version and the issue was resolved. I uninstalled the plugin via npm uninstall -g homebridge-broadlink-rm and then chose an older version and installed that via npm install -g homebridge-broadlink-rm@3.6.10.

**Comment by ishiigenji** [comment]
IT WORKED!! Thank you @danewallace for letting me know which version to go to. I guess I'll keep myself on this version for another while.
