### ISSUE TITLE
Unable to start plugin

### ISSUE THREAD

**Issue by mrblack7** [lprhodes/homebridge-broadlink-rm#58]
Hi Everyone,

Just installed the plugin on my Raspberry Pi HomeBridge setup and getting the following error when loading HomeBridge. Any help?

Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] ====================
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] /usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:74
Apr 26 12:54:13 raspberrypi homebridge[705]: async setCharacteristicValue (props, value, callback) {
Apr 26 12:54:13 raspberrypi homebridge[705]: ^^^^^^^^^^^^^^^^^^^^^^
Apr 26 12:54:13 raspberrypi homebridge[705]: SyntaxError: Unexpected identifier
Apr 26 12:54:13 raspberrypi homebridge[705]: at createScript (vm.js:56:10)
Apr 26 12:54:13 raspberrypi homebridge[705]: at Object.runInThisContext (vm.js:97:10)
Apr 26 12:54:13 raspberrypi homebridge[705]: at Module._compile (module.js:542:28)
Apr 26 12:54:13 raspberrypi homebridge[705]: at Object.Module._extensions..js (module.js:579:10)
Apr 26 12:54:13 raspberrypi homebridge[705]: at Module.load (module.js:487:32)
Apr 26 12:54:13 raspberrypi homebridge[705]: at tryModuleLoad (module.js:446:12)
Apr 26 12:54:13 raspberrypi homebridge[705]: at Function.Module._load (module.js:438:3)
Apr 26 12:54:13 raspberrypi homebridge[705]: at Module.require (module.js:497:17)
Apr 26 12:54:13 raspberrypi homebridge[705]: at require (internal/module.js:20:19)
Apr 26 12:54:13 raspberrypi homebridge[705]: at Object. (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:1:92)
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] ====================
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] Loaded plugin: homebridge-hs100
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] Registering platform 'homebridge-hs100.Hs100'
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] ---
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] Loaded plugin: homebridge-server
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] Registering platform 'homebridge-server.Server'
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] ---
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] Loaded config.json with 0 accessories and 2 platforms.
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] ---
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] Loading 2 platforms...
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] Initializing Hs100 platform...
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] [Homebridge Server] Initializing Server platform...
Apr 26 12:54:13 raspberrypi homebridge[705]: [4/26/2017, 12:54:13 PM] Loading 0 accessories...
Apr 26 12:54:13 raspberrypi homebridge[705]: Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

**Comment by lprhodes** [comment]
https://github.com/lprhodes/homebridge-broadlink-rm/issues/56#issuecomment-297158522

**Comment by mrblack7** [comment]
Ok, I updated Node to latest version, but I seem to have a new issue now and I can't see an existing issue for it....

Apr 26 15:55:45 raspberrypi homebridge[701]: [4/26/2017, 3:55:45 PM] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-broadlink-rm' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-broadlink-rm'.
Apr 26 15:55:46 raspberrypi homebridge[701]: [4/26/2017, 3:55:46 PM] ====================
Apr 26 15:55:46 raspberrypi homebridge[701]: [4/26/2017, 3:55:46 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
Apr 26 15:55:46 raspberrypi homebridge[701]: [4/26/2017, 3:55:46 PM] Error: EACCES: permission denied, mkdir '/.node-persist'
Apr 26 15:55:46 raspberrypi homebridge[701]: at Object.fs.mkdirSync (fs.js:895:18)
Apr 26 15:55:46 raspberrypi homebridge[701]: at sync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:71:13)
Apr 26 15:55:46 raspberrypi homebridge[701]: at Function.sync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:77:24)
Apr 26 15:55:46 raspberrypi homebridge[701]: at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:600:20)
Apr 26 15:55:46 raspberrypi homebridge[701]: at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:141:14)
Apr 26 15:55:46 raspberrypi homebridge[701]: at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/node-persist.js:37:32)
Apr 26 15:55:46 raspberrypi homebridge[701]: at Object. (/usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/persistentState.js:2:13)
Apr 26 15:55:46 raspberrypi homebridge[701]: at Module._compile (module.js:571:32)
Apr 26 15:55:46 raspberrypi homebridge[701]: at Object.Module._extensions..js (module.js:580:10)
Apr 26 15:55:46 raspberrypi homebridge[701]: at Module.load (module.js:488:32)
Apr 26 15:55:46 raspberrypi homebridge[701]: [4/26/2017, 3:55:46 PM] ====================
Apr 26 15:55:46 raspberrypi homebridge[701]: [4/26/2017, 3:55:46 PM] Loaded plugin: homebridge-hs100

**Comment by lprhodes** [comment]
Can you submit as a new issue please
