### ISSUE TITLE
The thermometer could not run for multi RM devices

### ISSUE THREAD

**Issue by leonardolau** [lprhodes/homebridge-broadlink-rm#59]
Thanks Luke for the update. I discovered that the temperature could not be shown if I have multi RM devices after the latest update. The log shows the temperature value by one of them only.

**Comment by lprhodes** [comment]
The log is showing the temperature for any air-conditioner accessories...not rm devices.

**Comment by leonardolau** [comment]
yes, I have 2 air-conditioner accessories, which are pointed to different RM devices. Before the update, temperature would be shown on those 2 accessories, but now it just shows one of them.

**Comment by lprhodes** [comment]
odd - accessories are completely independent of one another.

I've setup two air conditioners myself (though reading from the same RM device) and I don't see the issue...both report their temperature.

Can you try pointing both accessories to the same RM device and make sure that both return the temperature (as it the case in my test).

Can you also try removing the accessory that does show the temperature and make sure that the one that currently isn't showing a temperature then works.

**Comment by leonardolau** [comment]
oh, found that the mac address was the old one. fixed it after replacing with IP.
By the way, sometimes the plugin could not discover the RM devices, for example, I have 4 RM devices, normally it starts up with the log below
Discovered Broadlink RM device at 192.168.1.12X (b4:43:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.12Y (b4:43:0d:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.11X (b4:43:0d:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.12Y (b4:43:0d:XX:XX:XX)

But sometimes after restart, it shows 
 Discovered Broadlink RM device at 192.168.1.12X (b4:43:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.12Y (b4:43:0d:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.11X (b4:43:0d:XX:XX:XX)

and then I couldn't control 192.168.1.12Y.

Could any enhancement be made even the plugin could not discover the RM device initially? Thanks.

**Comment by lprhodes** [comment]
Closing - can you submit that as a new issue please
