### ISSUE TITLE
Device discoverable, no code learned

### ISSUE THREAD

**Issue by mikecc2008** [lprhodes/homebridge-broadlink-rm#6]
Hi Luke,

With the latest 0.2.13, my RM Pro is discoverable and the device does enter learning mode (with orange indicator on). However, no code has been learned. 

For the main plugin, it works like a charm with codes previously obtained using python-broadlink. Thanks for your great work!

**Comment by lprhodes** [comment]
I somehow managed to get the device into a state that would stop learning codes, I had to re-plug it in. Can you give that a go and let me know please?

**Comment by lprhodes** [comment]
...then restart homebridge

**Comment by mikecc2008** [comment]
Thanks for your advice. After rebooting RM and restarting homebridge, everything including the learner works!

**Comment by lprhodes** [comment]
Awesome - please let me know if you happen to notice when/why that happens. I'll be keeping an eye out for it too, hopefully it won't happen again (could be due to an older version of the code).
