### ISSUE TITLE
Discover RM device when startup

### ISSUE THREAD

**Issue by leonardolau** [lprhodes/homebridge-broadlink-rm#61]
Sometimes the plugin could not discover the RM devices, for example, I have 4 RM devices, normally it starts up with the log below
Discovered Broadlink RM device at 192.168.1.12X (b4:43:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.12Y (b4:43:0d:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.11X (b4:43:0d:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.12Y (b4:43:0d:XX:XX:XX)

But sometimes after restart, it shows
Discovered Broadlink RM device at 192.168.1.12X (b4:43:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.12Y (b4:43:0d:XX:XX:XX)
Discovered Broadlink RM device at 192.168.1.11X (b4:43:0d:XX:XX:XX)

and then I couldn't control 192.168.1.12Y.

Could any enhancement be made even the plugin could not discover the RM device initially? Thanks.

**Comment by lprhodes** [comment]
I just pushed 2.0.13 - check out the [release notes](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.0.13)

**Comment by lprhodes** [comment]
...let me know if that works better. I know it's not exactly what you're after but it's all I have right now.

**Comment by leonardolau** [comment]
Cool, that's better! Thanks Luke
