### ISSUE TITLE
Learn-Code switch duration time add to Config

### ISSUE THREAD

**Issue by SeanJohn888** [lprhodes/homebridge-broadlink-rm#62]
Is it possible to include the duration of activating the learn switch into the config?

Then it would be possible to learn full scenes from the Logitech Harmony in the future?

These scenes usually last longer than 10 sec since several device commands get over IR.

Then you do not need the HarmonyHub any longer.

**Comment by lprhodes** [comment]
It's more than just configuring the seconds. I likely won't be working on this any time soon. Happy to receive a pull request.

**Comment by lprhodes** [comment]
I don't see how this would ever work - I doubt this even works in the broadlink app?

**Comment by SeanJohn888** [comment]
Is it not possible to extend the learn time? I thought it was a small thing.

**Comment by lprhodes** [comment]
No - does this even work in broadlink app?

**Comment by SeanJohn888** [comment]
I have not tested it yet whether in the app the duration for learning an IR command is longer. I am the assumes that the learn time with the switch in your plugin is given by you

Do you mean in the app is this learning time bigger?

Do you have a Logitech Harmony FB?

**Comment by lprhodes** [comment]
I don’t have a Logitech Harmony

I mean can you actually achieve what you’re trying to do with the broadlink app.

As far as I know the IR learns one code at a time not a series of codes.

**Comment by lprhodes** [comment]
Both the app and plugin work like this:

- Enable learn mode
- Wait 1s
- Check for data
- Wait 1s
- Check for data
- Wait 1s
- Check for data
- Wait 1s
- Check for data
- Wait 1s
- Check for data
- Timeout

**Comment by SeanJohn888** [comment]
The Logitech Harmony also sends a chain of commands. My idea has been this chain from individual harmony commands to record with your plugin.

After this was the idea its only one command as hex code present.

I have it with the Broadlink app yet not tested only with your plugin.

With your plugin it has worked up to half. Then the time has expired for record.

**Comment by lprhodes** [comment]
I'm not convinced this will work but you can disable the timeout as of 2.1.0 - [release notes](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.1.0)

**Comment by SeanJohn888** [comment]
Cool, I'll test it right now and tell you if it works.

I now have the automatic learn code switch again.

To create the own switch, I just have to expand the config?

How does it have to look?

**Comment by SeanJohn888** [comment]
Maybe you can include it in the example config

**Comment by SeanJohn888** [comment]
I installed your update, and I just wanted to test the window cover switch.

No RF signal will be sent after the update?

It does not work anymore.

![ohne titel](https://cloud.githubusercontent.com/assets/27686185/25469096/830fcf06-2b1a-11e7-960f-7991d97514fd.jpeg)

**Comment by SeanJohn888** [comment]
I am now changed to version 2.0.15 again there it works again

**Comment by lprhodes** [comment]
The example config is for common configurations. It may be worth spending some time reading through the README so you can figure things out.

```
            {
              "name":"Scan RF",
              "type":"learn-code",
              "scanRF": true
            },
            {
              "name":"Learn Code",
              "type":"learn-code"
              "disableAutomaticOff":true
            }
```

**Comment by SeanJohn888** [comment]
Hello, I have now tested a command chain from the Harmony to learn.

Unfortunately it does not work yet.

When the first command is sent by the Harmony and is received by Broadlink Hub, the switch for IR Learn turns off automatically.

Only the first command is learned. All those who come after it are not learned.

Is there a possibility to change this?


Example:

Harmony command chain:

Start TV - Start Soundsystem - switsch to HDMI 3
(Only Start TV is learned)

**Comment by lprhodes** [comment]
This is as I expected would happen - it's only designed to learn the one code as far as I can tell.

**Comment by SeanJohn888** [comment]
Real stupid.

Then it will probably not work to replace the Harmony completely.

Thanks for the quick reply and your great work.

**Comment by lprhodes** [comment]
Why don't you just learn each code and use the switch-multi accessory?

**Comment by SeanJohn888** [comment]
The same idea I had at the same time. I'll try it out later. Thank you.
