### ISSUE TITLE
READ THIS ☞ "fan" and "garage-door-opener" accessories shows up as thermostat

### ISSUE THREAD

**Issue by ffaamm** [lprhodes/homebridge-broadlink-rm#625]
Lately a number of new issues complain that the accessories `fan` and `garage-door-opener` are wrongly showing up as a thermostat.

See #594, #602, #616, #623, and #624.

**It's a bug introduced after 3.6.18** (as today 3.6.22) in these files:
```
accessories/fan.js
accessories/garageDoorOpener.js
```

**Until the plugin maintainer fixes this bug, downgrading to 3.6.18 is the temporary workaround:**
`npm install homebridge-broadlink-rm@3.6.18`
(add `-g` / `--global` if you need it of course).

**Comment by cclarke99** [comment]
I'm beginning to think this plugin has been abandoned.

**Comment by Naqsaq** [comment]
You need to uninstall the existing installation before downgrading. During the installation of the 3.6.18, I got multiple weird problems. Not sure what worked, but at least at the end I needed to do the installation with sudo and --unsafe-perm and restart Homebridge with flag -R (not sure why, as it should be on by default: https://github.com/homebridge/homebridge/pull/2528).

**Comment by ffaamm** [comment]
I don't recall to have installed this plugin with `--unsafe-perm`, and neither its documentation advises it:
[https://lprhodes.github.io/slate/#installation](https://lprhodes.github.io/slate/#installation)
> Install this plugin using: `npm install -g homebridge-broadlink-rm`

And, my addition, if you run this plugin in a Docker image even `-g/--global` is not necessary.

I would suppose that you installed this plugin with `--unsafe-perm`, just because others require it, and therefore now you need it also for proper upgrade/downgrade/uninstall.
Otherwise, just (re)installing over an existing installation by forcing the version number should be enough.

**Comment by calhounfournier** [comment]
I have the same issue. Rolling back to  3.6 fixes it. I hope it will me maintained in the future.

**Comment by Crox77** [comment]
Im struggling to Roll back, ive ran the install command for the earlier version, still shows as a Thermostat, ive also tried installing and installing the specific version, but then when home bridge tries to start it says Broadlink RM is not registered to a plugin. Any help Guys please?

**Comment by ffaamm** [comment]
This plugin is dead, move to [kiwi-cam/homebridge-broadlink-rm](https://github.com/kiwi-cam/homebridge-broadlink-rm).
