### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by jeylites** [lprhodes/homebridge-broadlink-rm#63]
@lprhodes Ran the install and followed by an error. Is this normal?

pi@raspberrypi:~ $ npm install -g homebridge-broadlink-rm
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└─┬ homebridge-broadlink-rm@2.0.15
├─┬ broadlinkjs@0.1.0 (git+https://github.com/lprhodes/broadlinkjs.git#4a90e87230c024cde83f506ad12d606d41ac0d58)
│ └── @types/node@7.0.14
├─┬ node-persist@2.0.11
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── q@1.1.2
└── semver@5.3.0

npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-broadlink-rm"
npm ERR! node v7.6.0
npm ERR! npm v4.1.2
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR! { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'access',
npm ERR! path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR! /home/pi/npm-debug.log
pi@raspberrypi:~ $

**Comment by lprhodes** [comment]
This doesn't look to be specific to this plugin so it'd be worth asking on Stackoverflow however you could likely do as it says: "Please try running this command again as root/Administrator."

`sudo npm install -g homebridge-broadlink-rm` (note the "sudo")
