### ISSUE TITLE
After Update to Version 2.1.0 no RF signal be sent

### ISSUE THREAD

**Issue by SeanJohn888** [lprhodes/homebridge-broadlink-rm#64]
I installed your update, and I just wanted to test the window cover switch.

No RF signal will be sent after the update?

It does not work anymore.

This is normal switch, this I have additionally created. None of these will send a command since the update

![ohne titel](https://cloud.githubusercontent.com/assets/27686185/25469707/2fdb79bc-2b1e-11e7-9200-546257361312.jpeg)

**Comment by SeanJohn888** [comment]
I am now changed to version 2.0.15 again there it works again

**Comment by SeanJohn888** [comment]
Do you already know where the problem is?

**Comment by lprhodes** [comment]
Sorry

**Comment by leonardolau** [comment]
Me too, IR could not be sent off after updated. Works fine with 2.0.14.

**Comment by lprhodes** [comment]
Fixed in [2.1.1](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.1.1)
