### ISSUE TITLE
mkdirp issue!

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#65]
Hi,
I have some issue installing your plugin, I'm getting the following error:

```
Apr 27 17:50:09 raspberrypi homebridge[30913]: [4/27/2017, 5:50:09 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
Apr 27 17:50:09 raspberrypi homebridge[30913]: [4/27/2017, 5:50:09 PM] Error: EACCES: permission denied, mkdir '/home/homebridge'
Apr 27 17:50:09 raspberrypi homebridge[30913]: at Object.fs.mkdirSync (fs.js:895:18)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:71:13)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:77:24)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:77:24)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at Function.sync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/mkdirp/index.js:77:24)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at LocalStorage.parseStorageDirSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:600:20)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at LocalStorage.initSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:141:14)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/node-persist.js:37:32)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/persistentState.js:7:13)
Apr 27 17:50:09 raspberrypi homebridge[30913]: at Module._compile (module.js:571:32)
```

I looked at issue #60 and installed your latest release but i can't get ahead of this.
maybe it's necessary for you to know, I'm using damien to load homebridge on boot and my config and persist folders are at `/var/homebridge/` and not `/home/homebridge` like it's trying to access.

Please help!

**Comment by lprhodes** [comment]
Hi @nitaybz where are you placing your config.json?

The plugin is meant to use the same directory as that - usually this would be ~/.homebridge/

This is the code (which is the same as the homebridge uses):
```
var home = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
home = path.join(home, ".homebridge");

nodePersist.initSync({ dir: `${home}/plugin-persist/homebridge-broadlink-rm` });
```

I'm guessing you've created a user called homebridge? 

Can you let me know the output of the following please:
```
echo $HOME
echo $HOMEPATH
echo $USERPROFILE
```

**Comment by lprhodes** [comment]
I've added the ability to set the directory manually in version 2.2.2 by setting a config value for "homebridgeDirectory". The README has been updated with relevant information.

**Comment by wadjj** [comment]
I have run into this issue as well.
Homebridge runs just fine manually, but when it autostarts as a daemon, it throws the error just like above.(before updating this worked fine)

I set up the autostart following the setup https://timleland.com/setup-homebridge-to-start-on-bootup/

I haven't found any config sample regarding "homebridgeDirectory", so I'm bit confused as to how I should change the config file in /var/homebridge , or how should I change my setup altogether to avoid problems like these?

**Comment by lprhodes** [comment]
If your config.json is in /var/homebridge/ then you can put

      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "homebridgeDirectory": "/var/homebridge/"

**Comment by wadjj** [comment]
Thanks for being so responsive!
That solved the problem for me.
