### ISSUE TITLE
RM3 Couldn't learn code, device not found

### ISSUE THREAD

**Issue by e1l52** [lprhodes/homebridge-broadlink-rm#650]
After hours of trying to get my new RM3 device running, I am totally confused.
I tried this plugin and all other forks without success.
Mostly I get this "Couldn't learn code, device not found" error message.
I got once the state, that the device was found, but could not learn and ran in a timeout.
Any idea if I got a faulty device ? Or should I try to buy another type ?

**Comment by kiwi-cam** [comment]
What app did you use to configure your RM3? There are a lot of reports of issues if you use the IHC app and finish the setup completely. Try resetting your RM3 and reconfiguring it but quit the setup in IHC when you get to assigning it to a room.

**Comment by e1l52** [comment]
Hi kiwi-cam,

Thanks a lot for your fast answer ! I did as you suggested and quit the setup before assigning a room. I used https://github.com/lprhodes/homebridge-broadlink-rm. It detects the device, but is unable to learn a code :

_Jun 21 04:24:53 hoobs hoobs[578]: [BroadlinkRM] #033[35m[INFO]#033[0m Learn Code initializing (undefined)
Jun 21 04:24:53 hoobs hoobs[578]: [BroadlinkRM] Learn Code (ready)
Jun 21 04:25:03 hoobs hoobs[578]: [BroadlinkRM] #033[35m[INFO]#033[0m Learn Code (stopped - 10s timeout)
Jun 21 04:25:03 hoobs hoobs[578]: [BroadlinkRM] #033[35m[INFO]#033[0m Learn Code (stopped)_

Fortunately your fork https://github.com/kiwi-cam/homebridge-broadlink-rm detects the device and shows codes in learning mode.

Thanks a lot for the great work !
