### ISSUE TITLE
Device state ping issue

### ISSUE THREAD

**Issue by Ledbetter14** [lprhodes/homebridge-broadlink-rm#653]
I'm trying to setup state monitoring on a device i'm controlling. I can ping a reply from the command line when its powered on & no reply if off. My understanding is that if I feed the ip Address to the switch in my config it should update the state? I am not seeing any change unless I use the switch in the home app. I see nothing in the homebridge console relating to ping attempts.

  {
                      "name": "Projector",
                      "type": "switch",
                      "host": "192.168.1.xx",
                      "pingIPAddressStateOnly": "192.168.1.yy",
                      "pingFrequency": 2,
                      "debug": true,
                      "data": {
                          "on": "xxxx",
                          "off":[
                            {
                              "data": "xxxx",
                              "pause": 0.5
                            },
                            {
                              "data": "xxxx"
                            }
                      ]
                    }
                  },

**Comment by kiwi-cam** [comment]
Feel free to take a look at my config [here](https://github.com/kiwi-cam/MyHomeBridge/blob/master/var/homebridge/config.json). You're close but not setting the fields quite right. Try this:
`{

	"name": "Projector",

	"type": "switch",

	"host": "192.168.1.xx",

	"pingIPAddress": "192.168.1.yy",

	"pingFrequency": 2,

	"pingIPAddressStateOnly": true,

	"debug": true,

	"data": {

		"on": "xxxx",

		"off": [{

				"data": "xxxx",

				"pause": 0.5

			},

			{

				"data": "xxxx"

			}

		]

	}`

**Comment by Ledbetter14** [comment]
Perfect, thank you very much!
