### ISSUE TITLE
mac address is wrong!

### ISSUE THREAD

**Issue by sankooki** [lprhodes/homebridge-broadlink-rm#66]
Hi,
 
In the log

Apr 28 15:04:47 raspberrypi homebridge[6090]: [4/28/2017, 3:04:47 PM] Homebridge is running on port 51826.
Apr 28 15:04:47 raspberrypi homebridge[6090]: Discovered Broadlink RM device at 10.0.1.9 (0d:43:b4:ee:d9:3e)
Apr 28 15:04:47 raspberrypi homebridge[6090]: Discovered Broadlink RM device at 10.0.1.13 (34:ea:34:e0:b3:ac)
Apr 28 15:04:47 raspberrypi homebridge[6090]: Discovered Broadlink RM device at 10.0.1.17 (0d:43:b4:f0:9c:37)

.....

Apr 28 15:14:55 raspberrypi homebridge[6090]: [4/28/2017, 3:14:55 PM] [Broadlink RM] TV setSwitchState: 1
Apr 28 15:14:55 raspberrypi homebridge[6090]: [4/28/2017, 3:14:55 PM] [Broadlink RM] TV sendData(no device found at b4:43:0d:f0:9c:37)
Apr 28 15:14:55 raspberrypi homebridge[6090]: [4/28/2017, 3:14:55 PM] [Broadlink RM] TV setSwitchState: 0

10.0.1.9 is sp3,  1.13 and 1.19 are rm mini3.

1.13 has right mac address but 1.9 and 1.19 have wrong address.

The right address is   1.9 (b4:43:0d:ee:d9:3e), 1.19(b4:43:0d:f0:9c:37)

**Comment by lprhodes** [comment]
Unfortunately it seems that broadlink is inconsistent in how they broadcast the Mac addresses.

You can still reference those addresses though so they're still useful...
