### ISSUE TITLE
I can install the plugin.

### ISSUE THREAD

**Issue by masterfordev** [lprhodes/homebridge-broadlink-rm#672]
Hello, i tried install the plugin but shot this error:

npm WARN deprecated github-version-checker@1.2.0: Versions below v2.0.0 are outdated and should not be used anymore. Please consider upgrading to the latest release, which is v2.2.0 at this time.
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-08-13T01_01_53_539Z-debug.log

anyone can help me please?

**Comment by silverhack77** [comment]
I am also having this error

**Comment by masterfordev** [comment]
> I am also having this error

i fixed installing git again, i wish this help you:

https://git-scm.com/download/linux
