### ISSUE TITLE
Plugin 'homebridge-broadlink-rm-pro' tried to register with an incorrect plugin identifier: 

### ISSUE THREAD

**Issue by Chicayban** [lprhodes/homebridge-broadlink-rm#676]
I was looking my home bridge logs and find it: "Plugin 'homebridge-broadlink-rm-pro' tried to register with an incorrect plugin identifier: 'homebridge-broadlink-rm'. Please report this to the developer!

Any idea?

**Comment by kiwi-cam** [comment]
That's my fault, not @lprhodes :-)

To make my fork compatible with the existing config.json, I use the same identifier.... Homebridge has recently started complain about that. I have no plans to change this as it's likely to cause more issues than it solves (none to my knowledge).
