### ISSUE TITLE
Suport for Device 62bc  RM4

### ISSUE THREAD

**Issue by isvaldo** [lprhodes/homebridge-broadlink-rm#678]
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "62bc". The device is connected to your network with the IP address "192.168.0.204".

**Comment by kiwi-cam** [comment]
This fork isn't being developed anymore unfortunately. Fortunately there are forks which was still being worked on. I personally have done work on [homebirdge-broadlink-rm-pro](https://github.com/kiwi-cam/homebridge-broadlink-rm) which does support these devices.

**Comment by isvaldo** [comment]
Okay my friend, thank you!
