### ISSUE TITLE
Add multiple RM controllers feasibility 

### ISSUE THREAD

**Issue by leonardolau** [lprhodes/homebridge-broadlink-rm#7]
Is it possible to add multiple RM products in config.json? such as:
{
	"bridge": {
		"name": "Homebridge",
		"username": "CD:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-156"
	},

	"description": "Homebridge",

	"platforms": [],

	"accessories": [{
		"accessory": "Broadlink RM Learner",
			"name": "Learn IR",
			"host": "192.168.1.100"
		},
		{
			"accessory": "Broadlink RM",
			"name": "Broadlink RM Pro 3",
			"host": "192.168.1.100",
			"data": [
				{
				  "name": "TV",
				  "type": "on",
					"on": "260054005211291217XXXX",
					"off": "260054005211291216XXX"
				},
                                ]
                  },
                  {
			"accessory": "Broadlink RM",
			"name": "Broadlink RM Pro 3",
			"host": "192.168.1.101",
			"data": [
				{
				  "name": "TV",
				  "type": "on",
					"on": "260054005211291217XXXX",
					"off": "260054005211291216XXX"
				},
                                 ]
                  }
                 ]
}

**Comment by lprhodes** [comment]
There's nothing that I can think of that would stop that from working - have you tried already?

If you're thinking about buying a second one then I'm happy to work with you to fix any issues around using two.

Thanks

Luke

**Comment by leonardolau** [comment]
I just think about it on my way to work. I have 2 RM pro and a mini 3, wanna control them by one config. Let me try it tonight.

**Comment by leonardolau** [comment]
It works with 3 devices without issue. thanks.
