### ISSUE TITLE
keep getting current tempreture

### ISSUE THREAD

**Issue by Warden630** [lprhodes/homebridge-broadlink-rm#70]

**Comment by lprhodes** [comment]
This is expected

**Comment by Warden630** [comment]
I upgraded the newest version and the aircon just keep getting current tempreture for every 10secs

**Comment by lprhodes** [comment]
Yeah  it's used for automatic turn on / turn off features. You can disable logs for the accessory if you need

**Comment by Warden630** [comment]
Can i disable the automatic turn on/off function?

**Comment by lprhodes** [comment]
It's not on by default but the get temperature is. Why is it an issue for you?

**Comment by Warden630** [comment]
It seems to use more cpu resources, doesnt it?

发自我的 iPhone

> 在 2017年4月30日，下午12:43，Luke Rhodes <notifications@github.com> 写道：
> 
> It's not on by default but the get temperature is. Why is it an issue for you?
>

**Comment by lprhodes** [comment]
A negligible amount - it's sending a single packet and getting a single packet back.
