### ISSUE TITLE
IR signal doesn't always turn device on.

### ISSUE THREAD

**Issue by jat80** [lprhodes/homebridge-broadlink-rm#71]
I'm noticing that sometimes the IR signal won't work and i'll have to ask siri or turn the switch on and off 2-3 times before it actually works?  I have the latest build.  How do I debug this?

**Comment by lprhodes** [comment]
You should see messages that says sendHex whenever the IR is actually being sent.

**Comment by lprhodes** [comment]
Closing - feel free to reopen if you need more help
