### ISSUE TITLE
Support for node 4.5.0

### ISSUE THREAD

**Issue by kapps7** [lprhodes/homebridge-broadlink-rm#72]
Hi,

I am having trouble updating node from 4.5.0 to 7.6.0. It is causing a conflict in the mdns mode. I have created an issue here https://github.com/nfarina/homebridge/issues/1267

Is it possible for me to modify this plugin to run it on my current node version.

**Comment by lprhodes** [comment]
I've replied to the homebridge issue you raised. I've seen the problem reported various times (for other modules).

I won't be supporting older versions sorry

**Comment by kapps7** [comment]
Luke, thanks that those instructions will be handy to know. I'll close this and the other one and get to configuration of your plugin.

Thanks again mate!
