### ISSUE TITLE
Scan Frequency

### ISSUE THREAD

**Issue by mrblack7** [lprhodes/homebridge-broadlink-rm#76]
Trying to learn a new RF powerpoint but when learning the code, it seems to crash homebridge

> May 02 15:34:30 raspberrypi homebridge[2282]: [5/2/2017, 3:34:30 PM] [Broadlink RM] Scan RF (scanning)
May 02 15:34:30 raspberrypi homebridge[2282]: [5/2/2017, 3:34:30 PM] [Broadlink RM] [Hold down the button that sends the RF frequency]
May 02 15:34:32 raspberrypi homebridge[2282]: [5/2/2017, 3:34:32 PM] [Broadlink RM] Scan RF (found frequency - 1 of 2)
May 02 15:34:32 raspberrypi homebridge[2282]: [5/2/2017, 3:34:32 PM] [Broadlink RM] [Keep holding that button!]
May 02 15:34:33 raspberrypi homebridge[2282]: [5/2/2017, 3:34:33 PM] [Broadlink RM] Scan RF (found frequency - 2 of 2)
May 02 15:34:33 raspberrypi homebridge[2282]: [5/2/2017, 3:34:33 PM] [Broadlink RM] [Press the RF button multiple times with a pause between them]
May 02 15:34:51 raspberrypi homebridge[2282]: [5/2/2017, 3:34:51 PM] [Broadlink RM] Scan RF (stopped - 20s timeout)
May 02 15:34:51 raspberrypi homebridge[2282]: /usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/learnRFData.js:19
May 02 15:34:51 raspberrypi homebridge[2282]: closeClient();
May 02 15:34:51 raspberrypi homebridge[2282]: ^
May 02 15:34:51 raspberrypi homebridge[2282]: TypeError: closeClient is not a function
May 02 15:34:51 raspberrypi homebridge[2282]: at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/learnRFData.js:19:7)
May 02 15:34:51 raspberrypi homebridge[2282]: at ontimeout (timers.js:386:14)
May 02 15:34:51 raspberrypi homebridge[2282]: at tryOnTimeout (timers.js:250:5)
May 02 15:34:51 raspberrypi homebridge[2282]: at Timer.listOnTimeout (timers.js:214:5)
May 02 15:34:51 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
May 02 15:34:51 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
May 02 15:35:01 raspberrypi systemd[1]: homebridge.service holdoff time over, scheduling restart.
May 02 15:35:01 raspberrypi systemd[1]: Stopping Node.js HomeKit Server...
May 02 15:35:01 raspberrypi systemd[1]: Starting Node.js HomeKit Server...

**Comment by lprhodes** [comment]
I'll fix that issue but it still doesn't look like it'll learn the code: "Scan RF (stopped - 20s timeout)"

**Comment by mrblack7** [comment]
Yeah, its weird.

I managed to get it working for one of the power points though Scan Frequency. When I am trying to add a second one, it doesn't seem to find it.
Both work fine in the Broadlink app.

http://wiki.beyondlogic.org/i/RF3399/RF3672.jpg

**Comment by lprhodes** [comment]
What happens if you restart homebvridge in-between learning devices? Maybe something gets broken after the first one.
