### ISSUE TITLE
Questions regarding multiple Broadlink Mini RM3

### ISSUE THREAD

**Issue by astrojetson8** [lprhodes/homebridge-broadlink-rm#77]
@lprhodes Hi Luke

I now have 2 Broadlink Mini RM3 in different rooms.

By default, it's now using the recent Broadlink Mini RM3.
Unless I'm missing something, is following best way to go about it or is it possible to send same IR codes from multiple Broadlink Mini RM3's?
 
https://github.com/lprhodes/homebridge-broadlink-rm/issues/7

**Comment by lprhodes** [comment]
You can set a "host" value on each accessory with the IP or MAC address (as displayed by the logs) of the RM device you wish to use for that accessory

**Comment by astrojetson8** [comment]
yes, that's the plan.
maybe future iteration could have a universal broadcast option?
