### ISSUE TITLE
Can the scene function be realized?

### ISSUE THREAD

**Issue by eviewei** [lprhodes/homebridge-broadlink-rm#78]
Can add a accessory like "Switch-muti", but each step interval can adjust, because many equipment start-up time has several minutes (for example, the player, STB etc.), then will open the app and so on. This feature can be implemented in the Broadlink app scenario (for example: Watch sports channel: Turn on the power--0.5s--turn off the curtain--0.5s--turn on the TV--0.5s--open the Set-top box--60s--switch to the sports channel--30s--turn off the ceiling lamp)

**Comment by Guoer-xz** [comment]
{
                    "platform": "BroadlinkRM",
                    "name": "RM pro",
                    "host": "34:ea:34:e7:ed:bd",
                    "accessories": [
                                    {
                                    "name": "Air Conditioner",
                                    "type": "air-conditioner",
                                    "host": "34:ea:34:e7:ed:bd",
                                    "replaceAutoMode": "cool",
                                    "pseudoDeviceTemperature": 24,
                                    "defaultCoolTemperature": 22,
                                    "defaultheatTemperature": 28,
                                    "minTemperature": 16,
                                    "maxTemperature": 30,
                                    "data": {
                                    "off": "2600920000012890173417111710171017111611171017101711171017101734171117101710171017111710171017111710173417101711163517101710171017341711173417101710173417111700028b1710171017111611171017101711171017101711161117101710173417111710171017111710171017101711171017101711161117101710171117341734171017000d05000000000000",
                                    "temperature16": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890163616111710173417111611171017101711161117101711161117101611171116111710171115121710173417341711163516111710171017341711173417101710173515121700028b1611171017111512171017101711161117101711161117101711163516111611171017111512171017111611171016111711161117101711161115361635171016000d05000000000000"
                                    },
                                    "temperature17": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012593153615121711163516111512171116111437151215121711141315121711141316111710151316111512173415371413143716111512171114371611153615131611163516111500028d1611171114131611151314131611161117111413141317101711143714131710171116111611151314131611171017111413151217111611143715361635171015000d05000000000000"
                                    },
                                    "temperature18": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890173417111710173417101711161117101710173417111710171017111710171017111611171017101711163517341710173417101711171017341710173417111710173417101700028b1711171017101711161117101710171117101710171116111710173417101711171017101711171017101710171117101710171116111710171017111710173417000d05000000000000"
                                    },
                                    "temperature19": {
                                    "pseudo-mode": "cool",
                                    "data": "26009200000127911734171017111734171017101710171117341734171017111611171017101711171017101711161117101b3017341711163517101a0d171017341711173417101710173516111700028b1a0d171017111710171017111611171017101711171017101711163517101710171017111710171017111710171017101711171017101711173417101710173417000d05000000000000"
                                    },
                                    "temperature20": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791173417101710173417111710171017111710171017341711171017101710171117101710171117101710173417341711163517101710171116351710173417101711163517101700028b1710171017111710171017111611171017101711171017101711173417101710171017111710171017111710171017111611171017101711171017341710173417000d05000000000000"
                                    },
                                    "temperature21": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791163517101710163517111611171017111635161117341710171116111710171016121710171017111611173417341710173417111611171017341711163517101611173417111600028b1711171017101711171017101711171017101710171117101710173417111611171017111611171017101711171017101711161117101710173417341711173417000d05000000000000"
                                    },
                                    "temperature22": {
                                    "pseudo-mode": "cool",
                                    "data": "26009200000127911734171017101734171117101710171116111734173417101711161117101710171117101710171116111734173417101b3017111710171017341711173417101710173417111700028a1711171017101711171017101711161117101710171117101710173417111710171017101711171017101711171017101710171117101710171117101734173417000d05000000000000"
                                    },
                                    "temperature23": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791173417111710173417101711161117101734173417341711161117101710171117101710171117101710173417341711173417101710171117341710173417101711173417101700028b1710171017111710171017111710171017111611171017101711173417101710171116111710171017111710171017111710171017101711173417101734173417000d05000000000000"
                                    },
                                    "temperature24": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890173417111710173417101711171017101710171117101734171017111a0d171017111611171017101711173417341710173417111611171017341710173417111710173417101700028b1711171017101711161117101710171117101a0d171116111710173417111611171017101711171017101711161117101710171117101710171017351635173417000d05000000000000"
                                    },
                                    "temperature25": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012790171116111734173417111611171017101635171116111635171017111611161116121611161117101711173416351611173417111611161116351710173416121611173416111700028b1612161117101612161117101611161215121710161215121611173417111512171017101612161117101612151216111611161215121710171016361512171017000d05000000000000"
                                    },
                                    "temperature26": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012593151215131437143714131512151314131413153615121536151314131512151314131512151314131413153615361513143714131413151314361513143715121512153714131400028e1413151215131413151215131413141315121513141315121513143714131413151314131413151215131413141315121513141315121513143714371413151215000d05000000000000"
                                    },
                                    "temperature27": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171017111635163517101710171116111833173417101734171117101710171017111710171017111611173417341710183317111710171017341711173417101611173417111700028b1611171017111611171017101711171017101711161117101710173417111611171017111611171017101711171017101711161117101710171117101734171017000d05000000000000"
                                    },
                                    "temperature28": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171117101734173417101711171016111711161117341635171017111611171017111611151217101711153616351710163517101711161117341710163517111710173417101700028b1711171016111710171116111710171116111710161117111710163517101711171016111711161117101710171116111710161216111710173417101734161217000d05000000000000"
                                    },
                                    "temperature29": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171017101734173417111710171017111734171017341734171017111710171017111710171017101711173417341710173417111611171017341710173516111710173417111600028b1711171017101711171017101710171117101710171116111710173417111611171017101711171017101711161117101710171116111710171116351635171017000d05000000000000"
                                    },
                                    "temperature30": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012890171117101734173417111611171017101711173417341734171017101711171017101711171017101711163417351710173417101711161117341710173417111611173417101700028b1710171117101710171117101710171017111710171016121611173417101710171117101710171117101710171116111710171017111710173417341734171017000d05000000000000"
                                    }
                                    }

**Comment by lprhodes** [comment]
I've just published version 2.3.6 which includes a new "pause" option for the "switch-multi-repeat" accessory.

You can see an example in the config-sample.json - the accessory is called "Entertainment 2"

**Comment by eviewei** [comment]
All steps and equipment are perfectly functioning, thanks!
