### ISSUE TITLE
About air conditioning temperature regulation

### ISSUE THREAD

**Issue by Guoer-xz** [lprhodes/homebridge-broadlink-rm#79]
Air conditioning temperature regulation can not be used continuously, although the HB see this temperature settings are identified but only shut down or change the cooling system after setting the first temperature settings will send hex code (I have 16 to every 30 temperature setting have code.)

**Comment by Guoer-xz** [comment]
{
                    "platform": "BroadlinkRM",
                    "name": "RM pro",
                    "host": "34:ea:34:e7:ed:bd",
                    "accessories": [
                                    {
                                    "name": "Air Conditioner",
                                    "type": "air-conditioner",
                                    "host": "34:ea:34:e7:ed:bd",
                                    "replaceAutoMode": "cool",
                                    "pseudoDeviceTemperature": 24,
                                    "defaultCoolTemperature": 22,
                                    "defaultheatTemperature": 28,
                                    "minTemperature": 16,
                                    "maxTemperature": 30,
                                    "data": {
                                    "off": "2600920000012890173417111710171017111611171017101711171017101734171117101710171017111710171017111710173417101711163517101710171017341711173417101710173417111700028b1710171017111611171017101711171017101711161117101710173417111710171017111710171017101711171017101711161117101710171117341734171017000d05000000000000",
                                    "temperature16": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890163616111710173417111611171017101711161117101711161117101611171116111710171115121710173417341711163516111710171017341711173417101710173515121700028b1611171017111512171017101711161117101711161117101711163516111611171017111512171017111611171016111711161117101711161115361635171016000d05000000000000"
                                    },
                                    "temperature17": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012593153615121711163516111512171116111437151215121711141315121711141316111710151316111512173415371413143716111512171114371611153615131611163516111500028d1611171114131611151314131611161117111413141317101711143714131710171116111611151314131611171017111413151217111611143715361635171015000d05000000000000"
                                    },
                                    "temperature18": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890173417111710173417101711161117101710173417111710171017111710171017111611171017101711163517341710173417101711171017341710173417111710173417101700028b1711171017101711161117101710171117101710171116111710173417101711171017101711171017101710171117101710171116111710171017111710173417000d05000000000000"
                                    },
                                    "temperature19": {
                                    "pseudo-mode": "cool",
                                    "data": "26009200000127911734171017111734171017101710171117341734171017111611171017101711171017101711161117101b3017341711163517101a0d171017341711173417101710173516111700028b1a0d171017111710171017111611171017101711171017101711163517101710171017111710171017111710171017101711171017101711173417101710173417000d05000000000000"
                                    },
                                    "temperature20": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791173417101710173417111710171017111710171017341711171017101710171117101710171117101710173417341711163517101710171116351710173417101711163517101700028b1710171017111710171017111611171017101711171017101711173417101710171017111710171017111710171017111611171017101711171017341710173417000d05000000000000"
                                    },
                                    "temperature21": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791163517101710163517111611171017111635161117341710171116111710171016121710171017111611173417341710173417111611171017341711163517101611173417111600028b1711171017101711171017101711171017101710171117101710173417111611171017111611171017101711171017101711161117101710173417341711173417000d05000000000000"
                                    },
                                    "temperature22": {
                                    "pseudo-mode": "cool",
                                    "data": "26009200000127911734171017101734171117101710171116111734173417101711161117101710171117101710171116111734173417101b3017111710171017341711173417101710173417111700028a1711171017101711171017101711161117101710171117101710173417111710171017101711171017101711171017101710171117101710171117101734173417000d05000000000000"
                                    },
                                    "temperature23": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791173417111710173417101711161117101734173417341711161117101710171117101710171117101710173417341711173417101710171117341710173417101711173417101700028b1710171017111710171017111710171017111611171017101711173417101710171116111710171017111710171017111710171017101711173417101734173417000d05000000000000"
                                    },
                                    "temperature24": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890173417111710173417101711171017101710171117101734171017111a0d171017111611171017101711173417341710173417111611171017341710173417111710173417101700028b1711171017101711161117101710171117101a0d171116111710173417111611171017101711171017101711161117101710171117101710171017351635173417000d05000000000000"
                                    },
                                    "temperature25": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012790171116111734173417111611171017101635171116111635171017111611161116121611161117101711173416351611173417111611161116351710173416121611173416111700028b1612161117101612161117101611161215121710161215121611173417111512171017101612161117101612151216111611161215121710171016361512171017000d05000000000000"
                                    },
                                    "temperature26": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012593151215131437143714131512151314131413153615121536151314131512151314131512151314131413153615361513143714131413151314361513143715121512153714131400028e1413151215131413151215131413141315121513141315121513143714131413151314131413151215131413141315121513141315121513143714371413151215000d05000000000000"
                                    },
                                    "temperature27": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171017111635163517101710171116111833173417101734171117101710171017111710171017111611173417341710183317111710171017341711173417101611173417111700028b1611171017111611171017101711171017101711161117101710173417111611171017111611171017101711171017101711161117101710171117101734171017000d05000000000000"
                                    },
                                    "temperature28": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171117101734173417101711171016111711161117341635171017111611171017111611151217101711153616351710163517101711161117341710163517111710173417101700028b1711171016111710171116111710171116111710161117111710163517101711171016111711161117101710171116111710161216111710173417101734161217000d05000000000000"
                                    },
                                    "temperature29": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171017101734173417111710171017111734171017341734171017111710171017111710171017101711173417341710173417111611171017341710173516111710173417111600028b1711171017101711171017101710171117101710171116111710173417111611171017101711171017101711161117101710171116111710171116351635171017000d05000000000000"
                                    },
                                    "temperature30": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012890171117101734173417111611171017101711173417341734171017101711171017101711171017101711163417351710173417101711161117341710173417111611173417101700028b1710171117101710171117101710171017111710171016121611173417101710171117101710171117101710171116111710171017111710173417341734171017000d05000000000000"
                                    }
                                    }

**Comment by Guoer-xz** [comment]
{
                    "platform": "BroadlinkRM",
                    "name": "RM pro",
                    "host": "xx:xx:xx:xx:xx:xx",
                    "accessories": [
                                    {
                                    "name": "Air Conditioner",
                                    "type": "air-conditioner",
                                    "host": "xx:xx:xx:xx:xx:xx",
                                    "replaceAutoMode": "cool",
                                    "pseudoDeviceTemperature": 24,
                                    "defaultCoolTemperature": 22,
                                    "defaultheatTemperature": 28,
                                    "minTemperature": 16,
                                    "maxTemperature": 30,
                                    "data": {
                                    "off": "2600920000012890173417111710171017111611171017101711171017101734171117101710171017111710171017111710173417101711163517101710171017341711173417101710173417111700028b1710171017111611171017101711171017101711161117101710173417111710171017111710171017101711171017101711161117101710171117341734171017000d05000000000000",
                                    "temperature16": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890163616111710173417111611171017101711161117101711161117101611171116111710171115121710173417341711163516111710171017341711173417101710173515121700028b1611171017111512171017101711161117101711161117101711163516111611171017111512171017111611171016111711161117101711161115361635171016000d05000000000000"
                                    },
                                    "temperature17": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012593153615121711163516111512171116111437151215121711141315121711141316111710151316111512173415371413143716111512171114371611153615131611163516111500028d1611171114131611151314131611161117111413141317101711143714131710171116111611151314131611171017111413151217111611143715361635171015000d05000000000000"
                                    },
                                    "temperature18": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890173417111710173417101711161117101710173417111710171017111710171017111611171017101711163517341710173417101711171017341710173417111710173417101700028b1711171017101711161117101710171117101710171116111710173417101711171017101711171017101710171117101710171116111710171017111710173417000d05000000000000"
                                    },
                                    "temperature19": {
                                    "pseudo-mode": "cool",
                                    "data": "26009200000127911734171017111734171017101710171117341734171017111611171017101711171017101711161117101b3017341711163517101a0d171017341711173417101710173516111700028b1a0d171017111710171017111611171017101711171017101711163517101710171017111710171017111710171017101711171017101711173417101710173417000d05000000000000"
                                    },
                                    "temperature20": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791173417101710173417111710171017111710171017341711171017101710171117101710171117101710173417341711163517101710171116351710173417101711163517101700028b1710171017111710171017111611171017101711171017101711173417101710171017111710171017111710171017111611171017101711171017341710173417000d05000000000000"
                                    },
                                    "temperature21": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791163517101710163517111611171017111635161117341710171116111710171016121710171017111611173417341710173417111611171017341711163517101611173417111600028b1711171017101711171017101711171017101710171117101710173417111611171017111611171017101711171017101711161117101710173417341711173417000d05000000000000"
                                    },
                                    "temperature22": {
                                    "pseudo-mode": "cool",
                                    "data": "26009200000127911734171017101734171117101710171116111734173417101711161117101710171117101710171116111734173417101b3017111710171017341711173417101710173417111700028a1711171017101711171017101711161117101710171117101710173417111710171017101711171017101711171017101710171117101710171117101734173417000d05000000000000"
                                    },
                                    "temperature23": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012791173417111710173417101711161117101734173417341711161117101710171117101710171117101710173417341711173417101710171117341710173417101711173417101700028b1710171017111710171017111710171017111611171017101711173417101710171116111710171017111710171017111710171017101711173417101734173417000d05000000000000"
                                    },
                                    "temperature24": {
                                    "pseudo-mode": "cool",
                                    "data": "2600920000012890173417111710173417101711171017101710171117101734171017111a0d171017111611171017101711173417341710173417111611171017341710173417111710173417101700028b1711171017101711161117101710171117101a0d171116111710173417111611171017101711171017101711161117101710171117101710171017351635173417000d05000000000000"
                                    },
                                    "temperature25": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012790171116111734173417111611171017101635171116111635171017111611161116121611161117101711173416351611173417111611161116351710173416121611173416111700028b1612161117101612161117101611161215121710161215121611173417111512171017101612161117101612151216111611161215121710171016361512171017000d05000000000000"
                                    },
                                    "temperature26": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012593151215131437143714131512151314131413153615121536151314131512151314131512151314131413153615361513143714131413151314361513143715121512153714131400028e1413151215131413151215131413141315121513141315121513143714131413151314131413151215131413141315121513141315121513143714371413151215000d05000000000000"
                                    },
                                    "temperature27": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171017111635163517101710171116111833173417101734171117101710171017111710171017111611173417341710183317111710171017341711173417101611173417111700028b1611171017111611171017101711171017101711161117101710173417111611171017111611171017101711171017101711161117101710171117101734171017000d05000000000000"
                                    },
                                    "temperature28": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171117101734173417101711171016111711161117341635171017111611171017111611151217101711153616351710163517101711161117341710163517111710173417101700028b1711171016111710171116111710171116111710161117111710163517101711171016111711161117101710171116111710161216111710173417101734161217000d05000000000000"
                                    },
                                    "temperature29": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012791171017101734173417111710171017111734171017341734171017111710171017111710171017101711173417341710173417111611171017341710173516111710173417111600028b1711171017101711171017101710171117101710171116111710173417111611171017101711171017101711161117101710171116111710171116351635171017000d05000000000000"
                                    },
                                    "temperature30": {
                                    "pseudo-mode": "heat",
                                    "data": "2600920000012890171117101734173417111611171017101711173417341734171017101711171017101711171017101711163417351710173417101711161117341710173417111611173417101700028b1710171117101710171117101710171017111710171016121611173417101710171117101710171117101710171116111710171017111710173417341734171017000d05000000000000"
                                    }
                                    }

**Comment by lprhodes** [comment]
I'd like to make sure I understand.

Can you write step-by-step what's happening and then what you expect to happen please?

Also make sure it's not this issue:

> Air Conditioner Notes
There looks to be a glitch in the Apple Home app in that nothing happens when setting the mode to Off when you've turned the thermostat on by setting a specific temperature. Siri and other HomeKit apps don't have the same glitch. As a work-around you can just select a different mode and then press Off. This only happens the first time after launching homebridge.

**Comment by Guoer-xz** [comment]
Discovered Broadlink RM device at 192.168.1.62 (xx:xx:xx:xx:xx:xx)
Discovered Broadlink RM device at 192.168.1.33 (xx:xx:xx:xx:xx:xx)
[2017-5-4 23:33:55] [RM pro] Air Conditioner setCurrentHeatingCoolingState: 0
[2017-5-4 23:33:55] [RM pro] Air Conditioner setCurrentHeatingCoolingState: already 0
[2017-5-4 23:33:55] [RM pro] Air Conditioner setTargetHeatingCoolingState: 0
[2017-5-4 23:33:55] [RM pro] Air Conditioner setTargetHeatingCoolingState: already 0
[2017-5-4 23:34:11] [RM Mini3] Light getLightState: 0
[2017-5-4 23:34:11] [RM Mini3] Fan getSwitchState: 0
[2017-5-4 23:34:11] [RM pro] Air Conditioner getCurrentTemperature (using 24 from config)
[2017-5-4 23:34:11] [RM pro] Air Conditioner getTargetHeatingCoolingState: 0
[2017-5-4 23:34:11] [RM pro] Air Conditioner getTargetTemperature: 16
[2017-5-4 23:34:11] [RM pro] Air Conditioner getCurrentHeatingCoolingState: 0
[2017-5-4 23:34:16] [RM pro] Air Conditioner setTargetHeatingCoolingState: 2
[2017-5-4 23:34:16] [RM pro] Potential Air Conditioner sendTemperature (22)
[2017-5-4 23:34:16] [RM pro] Air Conditioner sendTemperature (22, cool)
[2017-5-4 23:34:16] [RM pro] Air Conditioner setTargetTemperature: 22
[2017-5-4 23:34:16] [RM pro] Air Conditioner setTargetTemperature: already 22
[2017-5-4 23:34:16] [RM pro] Air Conditioner sendHex (192.168.1.62; xx:xx:xx:xx:xx:xx)
[2017-5-4 23:34:17] [RM pro] Air Conditioner setCurrentHeatingCoolingState: 2
[2017-5-4 23:34:17] [RM pro] Air Conditioner setTargetHeatingCoolingState: 2
[2017-5-4 23:34:17] [RM pro] Air Conditioner setTargetHeatingCoolingState: already 2
[2017-5-4 23:34:20] [RM pro] Air Conditioner setTargetTemperature: 19
[2017-5-4 23:34:20] [RM pro] Potential Air Conditioner sendTemperature (19)
[2017-5-4 23:34:22] [RM pro] Air Conditioner setTargetTemperature: 22
[2017-5-4 23:34:22] [RM pro] Potential Air Conditioner sendTemperature (22)
[2017-5-4 23:34:24] [RM pro] Air Conditioner setTargetTemperature: 20
[2017-5-4 23:34:24] [RM pro] Potential Air Conditioner sendTemperature (20)
[2017-5-4 23:34:28] [RM pro] Air Conditioner setTargetHeatingCoolingState: 0
[2017-5-4 23:34:28] [RM pro] Air Conditioner sendHex (192.168.1.62; xx:xx:xx:xx:xx:xx)
[2017-5-4 23:34:29] [RM pro] Air Conditioner setCurrentHeatingCoolingState: 0
[2017-5-4 23:34:29] [RM pro] Air Conditioner setTargetHeatingCoolingState: 0
[2017-5-4 23:34:29] [RM pro] Air Conditioner setTargetHeatingCoolingState: already 0

————————————————————————
This record can be seen in this process, the selection of the cooling and closing behavior was carried out, the temperature setting is only valid after the first operation of the selection mode, other operations are not sent out hex

**Comment by lprhodes** [comment]
Release [2.3.8](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.3.8) should fix this issue. Let me know how you go with it.
