### ISSUE TITLE
is it possible to do 

### ISSUE THREAD

**Issue by hkechung** [lprhodes/homebridge-broadlink-rm#8]
is it possible to perform : 
1) volume up and down ?
2) channel up and down ?

**Comment by lprhodes** [comment]
I don't believe channel up/down can be implemented other than somehow using a switch to repeatedly send channel up until you stop and then another to do the same for down.

As for volume...I'll work on this later this week. My focus is working on an Alexa-HomeKit bridge at the moment.

**Comment by hkechung** [comment]
thank you !
