### ISSUE TITLE
Two RM mini configuration json

### ISSUE THREAD

**Issue by kapps7** [lprhodes/homebridge-broadlink-rm#80]
With using multiple RM mini devices, I want to clarify, whether I set both devices up as two platforms or accessories, I have seen different examples in past threads.

If I set them as two platforms, I get:
`Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7896a993-5b3c-467b-aa`

If I set one as a platform and one as an accessory, I get

`was not registered by any plugin`

My json is:
`
 {
		"accessory": "BroadlinkRM",
		"name": "Broadlink RM",
		"host": "10.0.1.19",
		"data": [
			{
			  "name": "TV",
			  "type": "on",
				"on": "260054005211291217XXXX",
				"off": "260054005211291216XXX"
			}
                            ]
              }

 ],
  "platforms": [
  
    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "host":"10.0.1.20",
      "accessories":[
        {
    "name": "Air Conditioner",
    "type": "air-conditioner",
    "minTemperature": 10,
    "defaultHeatTemperature": 28,
    "defaultCoolTemperature": 18,
    "autoMinimumDuration": 300,
    "heatTemperature": 20,
    "data": {
      "off": "260050020a120d100c110a120b110a000344703b0e2c0c100b110d0f0d2d0a120b120b100e0e0d2d0c100c2d0c2e0b100c2d0c2e0c2c0e2c0d2c0c0f0d100c2d0c110c100b110a130b1209120a120a130c110a110c2d0d100a2e0c120c0e0d100c2d0d2c0c110a130a1209120b130a110c100c120c0f0c110b110c110b100c100d110c0e0c2d0d2c0d2d0c110c2d0b110d2c0e2b0d00047a703b0d2c0e0e0d1109130b2e0b1209120a130a120c2d0d01",
      "temperature28": {
        "pseudo-mode": "heat",
        "data": "260050020d0e0e100c0f0e0f0c1"

      },
      "temperature18": {
        "pseudo-mode": "cool",
        "data": "260050020c100d0f0d10"
      }
    }
  }
]`

**Comment by astrojetson8** [comment]
@kapps7
2 accessories, and please see below. I've not done it yet but I plan to do so soon.
 
https://github.com/lprhodes/homebridge-broadlink-rm/issues/77
https://github.com/lprhodes/homebridge-broadlink-rm/issues/7

**Comment by lprhodes** [comment]
You create one platform. Accessories are then defined inside the platform (like in the config-sample.json)

Each accessory would have a host key which would be the IP address of the RM device you want that accessory to use.

**Comment by lprhodes** [comment]
You can find a new config sample for multiple RM devices [here](https://github.com/lprhodes/homebridge-broadlink-rm/blob/master/config-multiple-rm-devices-sample.json).

**Comment by kapps7** [comment]
Believe it or not, I worked this out in the middle of the night.. Thanks mate.
