### ISSUE TITLE
air-con accessary autoHeatTemperature and autoCoolTemperature control

### ISSUE THREAD

**Issue by leonardolau** [lprhodes/homebridge-broadlink-rm#81]
As autoHeatTemperature and autoCoolTemperature would be controlled by temperature change only, thinking if possible to add time or geo-fencing function to eliminate auto On/Off when no one at home.

**Comment by lprhodes** [comment]
ha - I was thinking the same thing this morning

For geo-fencing we'd need to do something with a separate switch. e.g. When you get home a Home scene sets the switch to on.

**Comment by lprhodes** [comment]
Thoughts on the following?

```
"autoSchedule": [
  { "days": [ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" ], "startTime": 6, "endTime": 8 },
  { "days": [ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" ], "startTime": 16, "endTime": 22 },
  { "days": [ "Saturday", "Sunday" ], "startTime": 6, "endTime": 22 },
],
"autoSwitch": "A/C Auto Switch",
```

`autoSwitch` basically points to another switch (created inside the homebridge-broadlink-rm platform). The switch state would determine whether autoHeatTemperature/autoCoolTemperature are active or not. You would then set up a scene in the Home app to turn the switch on or off based on your location.

**Comment by leonardolau** [comment]
Wow, that's really cool idea.

**Comment by lprhodes** [comment]
"autoSwitch" has been added to the latest release: [2.4.0](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.4.0)

**Comment by leonardolau** [comment]
Brilliant! Let me try it tonight!

**Comment by leonardolau** [comment]
works so nice. thanks.

**Comment by lprhodes** [comment]
Glad it works for you! I'll leave this open until I add in the time scheduling

**Comment by lprhodes** [comment]
I won't be adding the scheduling any time soon so closing this
