### ISSUE TITLE
Creating Room Types in Config.Json

### ISSUE THREAD

**Issue by jeylites** [lprhodes/homebridge-broadlink-rm#82]
Luke-  I've been using the plugin for 3 days now and It works great! Thank you!

Is there a way to specify room types on config.json file so we don't have to reconfigure them in Home app? Something like below...

"room":"OUTSIDE",
"name":"PORCH SENSOR LIGHT",
"type":"light",
"data":{
"on":"e9144600df090916091......0148",
"off":"e9144600df090916091......0148"

**Comment by lprhodes** [comment]
Nope sorry https://github.com/nfarina/homebridge/issues/792
