### ISSUE TITLE
Fan control expectation

### ISSUE THREAD

**Issue by Guoer-xz** [lprhodes/homebridge-broadlink-rm#83]
Thanks for this great plugin, as well as the active update! Allows the operator to operate the interface with a control handle, similar to light, rather than a switch?

**Comment by lprhodes** [comment]
The Home app doesn't allow for that yet. I would expect support in iOS 11

**Comment by lprhodes** [comment]
It supports Fan V1 (Home app) and Fan V2 (Siri). Both get added when you add a "fan" accessory.

You can read through #33 for more details
