### ISSUE TITLE
Send off hex twice to Projector

### ISSUE THREAD

**Issue by kapps7** [lprhodes/homebridge-broadlink-rm#84]
Hey I have a projector. It requires the off to be pressed twice with a brief interval to shut it off.
I'm trying to work out the best way to do it. The repeat switches don't have an "on". Will I need to set it up as two separate accessories or is there a way I can modify the standard switch below to send the off hex twice.

> {
          "name":"TV On/Off",
          "type":"switch",
          "host":"192.168.1.8",
          "data":{
            "on":"2600500000012...",
            "off":"2600500000012..."
          }

Thanks

**Comment by lprhodes** [comment]
I just released [2.5.0](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.5.0) - you'll now be able to use either "switch-repeat" or "switch-multi" to achieve this.
