### ISSUE TITLE
Fan

### ISSUE THREAD

**Issue by jacobwhite** [lprhodes/homebridge-broadlink-rm#85]
I've got a fan with 3 buttons, high, medium, low and off. I'm unclear about how to configure it with the settings in the config file. What is swing mode?

**Comment by lprhodes** [comment]
That's 4 buttons?

**Comment by lprhodes** [comment]
I would suggest something along these lines:

```
        {
          "name": "Fan",
          "type": "fan",
          "data": {
            "on":"2600500000012...", // Low, Medium, or High
            "off":"2600500000012...", // Off
            "fanSpeed10": "2600500000012...", // Low
            "fanSpeed50": "2600500000012...", // Medium
            "fanSpeed100": "2600500000012..." // High
          }
```

Swing mode is for fans which can either tilt the fans back and fourth or rotate the fan

**Comment by lprhodes** [comment]
Note: Siri supports the setting of speeds, the Home app does not. The accessory will pick the closest fan speed to the one requested.

**Comment by jacobwhite** [comment]
Thanks! Thats a bummer that the switch only does on and off. Thanks though!

**Comment by lprhodes** [comment]
Yeah - you could always try the Home app from the App Store, that usually has more comprehensive options.

**Comment by kapps7** [comment]
The Hesperus app has granular control over speed of the fan accessory.

**Comment by jacobwhite** [comment]
I pretty much only use Siri and control center.

**Comment by lprhodes** [comment]
You can still use Siri to set a fan speed in that case...

The 3rd-party Home app also provides a Notification Center widget which can be nearly as accessible

**Comment by jacobwhite** [comment]
Link?
