### ISSUE TITLE
Channel up/down Volume up/down

### ISSUE THREAD

**Issue by hkechung** [lprhodes/homebridge-broadlink-rm#86]
Can I check if the code changed for switch-repeat ?
the channel up/down & Volume up/down fail to work after update.

 {
                          "name":"Channel Down",
                          "type":"switch-repeat",
                          "sendCount":1,
                          "data":"2600500000012b91141114111435153514111411143514..."
                        },
                        {
                          "name":"Volume Up",
                          "type":"switch-repeat",
                          "sendCount":5,
                          "interval":0.3,
                          "data":"2600500000012a92141114111435143614111411133614..."
                        },

**Comment by lprhodes** [comment]
I'm seeing the same thing - working on it now.

**Comment by lprhodes** [comment]
Fixed in [2.5.2](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.5.2)
