### ISSUE TITLE
Open / close garage

### ISSUE THREAD

**Issue by lalamper** [lprhodes/homebridge-broadlink-rm#87]
Hi,

My garage door close after 30 seconds automatically. As there is no feedback for broadlink, is it possible to set up a timer for autoclosing?

At the moment, if I want to open it again, I have to ask Siri to close the garage, because the last status was opened. 

Thanks

**Comment by lprhodes** [comment]
Added in [2.5.2](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/2.5.2)
