### ISSUE TITLE
how can u ask it to change the TV channel ?

### ISSUE THREAD

**Issue by hkechung** [lprhodes/homebridge-broadlink-rm#9]
I add the channel 1-9  in config.json
how can i change the TV channel ?

thanks.

**Comment by lprhodes** [comment]
You should be able to ask it to set the channel to 7 etc or use the channel button in HomeKit to set select a channel.

**Comment by lprhodes** [comment]
There isn't, I copied that from elsewhere and I'm unsure how they ever got it work. I'll be removing in the next version (due later today) and replacing with a toggle that allow you to increase or decrease the channel number.

**Comment by lprhodes** [comment]
As I say I took that code from elsewhere and I've no idea how they expected it to work...I've removed support for specific channels in the new version though you could setup a switch-repeat accessory for each channel with a sendCount of 1 and call it Channel X. You could then say "Turn on Channel 1"

The same switch-repeat mechanism also works for changing the channel up or down.

Please read the release notes https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.0.0
