### ISSUE TITLE
hampton bay cieling fan and broadlink rm pro

### ISSUE THREAD

**Issue by hroman73** [lprhodes/homebridge-broadlink-rm#90]
I am having trouble configuring the ceiling fan using the fan and light accessories. My remote has fan settings 1, 2 and 3 and then an on off light setting that when held down then sets the dim. My issue is although i configure the fan speeds 1, 2, 3 and the light to go on and off, it is intermittent. also how do i set the light switch to dim?

**Comment by lprhodes** [comment]
Hi @hroman73

You'll need to expand on " it is intermittent" please.

Also post relevant logs and bits of your config

**Comment by hroman73** [comment]
in an effort to get things working i started configurations over again for fan and light accessories, its now that i notice that when performing a learn that the hex codes coming out are different each time. how do i know which is the correct one?

**Comment by hroman73** [comment]
further information i'm finding:

when stating "turn the fan on" i have it set to turn on the low rf hex
when stating "turn the fan off" the hex code i have works fine and turns the fan off
when stating "turn the fan to low" the low rf hex is sent and works
then when stating "turn the fan off" the hex code does not work...

it seems as if the hex for turning off the fan is only when its been set to on instead of a certain speed

**Comment by lprhodes** [comment]
I'd recommend figuring it out with the official broadlink app first to make sure what you're trying to do is actually achievable with your fan.

**Comment by lprhodes** [comment]
Closing, let me know if you have more info.
