### ISSUE TITLE
Switch-multi does not turn off itself

### ISSUE THREAD

**Issue by lily148** [lprhodes/homebridge-broadlink-rm#92]
I notice another problem, when I trigger a switch-multi, the switch does not turn itself off. It reply the error as below.
(node:31017) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: state is not defined
(node:31017) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lprhodes** [comment]
Good catches thanks @lily148

**Comment by jelvs** [comment]
@lprhodes hey, i have the same problem with the switch-multi-repeat, did u find a way to solve that ? Thank u very much, Cheers
