### ISSUE TITLE
setState regarding the current state

### ISSUE THREAD

**Issue by lily148** [lprhodes/homebridge-broadlink-rm#93]
Hi lprhodes,

Is it possible to allow the homebridge to sendHex regardless the current switch state?
E.g.
- At homekit, the switch is OFF, I manually turn the switch ON (homekit still showing OFF).
- Now, I ask Siri to turn the switch OFF, Siri won't do that because homekit is showing OFF.
- I need to ask Siri to turn on the switch and turn off again.
I tried to look about the code but couldn't find a way to change that.

**Comment by wailuen** [comment]
Hi Iprhodes,

I have the same problem and was thinking of approaching it another way. I am using this to control a ceiling based on broadlink RF. Would it be possible for this to constantly listen for RF signal while not transmitting and keep the status in sync when user use the external remote ?

**Comment by skyfremen** [comment]
Hi,

I have the same issue too, anyone found a workaround?

**Comment by lprhodes** [comment]
I've added a config option that you can add to each accessory called `allowResend`. Set a value of true and it should re-send the hex when you request to change an accessory to become a state that it already thinks it's in.

I've made it an option as I'm sure it'll have ramifications for the rest of the plugin so consider this to be a beta test of it,

If it doesn't work at all for you after updating to the latest version then run `npm list -g` and make sure `homebridge-platform-helper` is at version 0.0.2.

**Comment by skyfremen** [comment]
Thank you for the soloution understand it is a beta test. 
Just to highlight that for air-conditioner and light the allowResend option does not resend the hex of the defaultBrightness and defaultCoolTemperature when I just say to SIRI
Turn on the Lights / Turn on the A/C

**Comment by 7mllm7** [comment]
Say, is it also possible to make it work with iOS Home app "scenes". A scene is a set of accessories in certain state.
So for example if I have a scene called "Watching TV", that )among others) turns off a light accessory, it won't send the OFF command if it's persisted state is OFF already.
So `allowResend` works for Siri, but not for Home app...

**Comment by felipesalomao** [comment]
@lprhodes  this was not added to docs.. Add..  its great function.. I was able to make it work as i want..  But could have a more complex solution that would make it works like magic.. And if RM Pro could detect any IR signals all the time, once detected, it would change homekit device status  to keep devices aways synced even you control it using tv remote ir and homebridge at same time.. It would make not smart devices into smart devices (updating status all the time)...

**Comment by carolinomv** [comment]
anyone knows where "allowResend" is defined in .js?
