### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by wailuen** [lprhodes/homebridge-broadlink-rm#94]
There is no ability to set the fan speed via the Home app. On my aircon accessory from Sensibo and Tado, it is possible to set fan speed. It will be good if the Broadlink Fan accessory enable this.

**Comment by lprhodes** [comment]
Can you please add a screenshot for the Sensibo control in the Home app?

**Comment by wailuen** [comment]
Hi, it is behaving like a switch but the icon is a fan.
Outside. 
![](http://i.imgur.com/DYFahIY.jpg)
Inside. This should ideally be based on fan speed. 
![](http://i.imgur.com/1KgdTTt.jpg) 
Details
![](http://i.imgur.com/jLoQAk4.jpg)

**Comment by lprhodes** [comment]
Screenshots of the Sensibo fan, not the broadlink fan please.

**Comment by kapps7** [comment]
Hasn't this question been answered here https://github.com/lprhodes/homebridge-broadlink-rm/issues/85

**Comment by lprhodes** [comment]
I would have thought so but looking for screenshots in case there's something that's been missed and you can actually get this UI in the home app

**Comment by kapps7** [comment]
In the Hesperus app, the Rotation Speed is the fan speed
https://cl.ly/0o3J2B2Y3617

**Comment by lprhodes** [comment]
Ok - this is a work-around by them and has nothing to do with the Home app which is what he's after.

The unofficial "Home" app supports actual fan speed controls, so does Siri.

That's all the support we can offer at the moment until Apple add the necessary UI to the official Home app.

Relevant info:
- https://github.com/lprhodes/homebridge-broadlink-rm/blob/master/README.md#fan
- Issue #85

**Comment by wailuen** [comment]
Hi,

Sensibo fan speed on default Apple default Home app. Nothing to do with other app. 





Best Regards,

蒋玮伦
CHEONG Wai Luen

**Comment by wailuen** [comment]
Sensibo fan control on Home App
![](http://i.imgur.com/icfG9DD.jpg)
![](http://i.imgur.com/f0hHIHp.jpg)
![](http://i.imgur.com/yS1vsJX.jpg)

**Comment by lprhodes** [comment]
Interesting thanks @wailuen 

@duyleekun did you know this was possible? It seems like there is a UI for V2 fans

**Comment by duyleekun** [comment]
Interesting. There should be a way to look up the UUID for the characteristic of that device so we can replicate in this library. Maybe some app.

**Comment by kapps7** [comment]
What is the id referred to here https://cl.ly/3L1y2m202T12

**Comment by lprhodes** [comment]
I've found the characteristic - I'll get this implemented in the next few days.

**Comment by lprhodes** [comment]
It's been a busy week - I'll keep you posted when I get onto this

**Comment by lprhodes** [comment]
Added in 2.5.9

You'll need to force-quit the Home app in order for the change to show

**Comment by wailuen** [comment]
Hi, update the homebridge-broadlink-rm but the fan still behave like a switch. I had forced closed the home app and even rebooted my phone. 

The version I am on is 
![](http://i.imgur.com/EP30Ego.jpg)

Did you forget to patch in the code?

**Comment by wailuen** [comment]
Works perfectly. Need to force close the main homehub on ipad as well.
