### ISSUE TITLE
How to auto generate a 433MHz code?

### ISSUE THREAD

**Issue by crhan** [lprhodes/homebridge-broadlink-rm#95]
I want a random 433MHz RF code to control my devices. But I don't have enough controller to learn, and I don't want to buy that much.

How can I generate this code?

**Comment by lprhodes** [comment]
Try achieving this in the official broadlink app with the "Scan RF" method first to see if you can get it to work. If so then the Scan RF button in this plugin will also work. If not then there's nothing I can do sorry.

I've not actually seen any successful attempts at learning the random codes. Usually they are garage door openers which require encryption.
