### ISSUE TITLE
Add support for Broadlink e-Air

### ISSUE THREAD

**Issue by KillSwitchSIG** [lprhodes/homebridge-broadlink-rm#97]
Can we please add support for Broadlink e-Air
Device: https://www.banggood.com/BroadLink-A1-White-WiFi-Intelligent-Smart-Home-Air-Detector-Sensor-Purifier-Remote-Control-p-1002004.html

This device works using the Broadlink e-Control app - so meaning it uses the same protocol as the other broadlink devices. The device can report temperature, air quality, humidity, and light brightness.

**Comment by lprhodes** [comment]
This plugins for sending IR and RF commands rather than controlling all broadlink devices sorry. I'd suggest starting a new plugin and start with the broadlinkjs npm module as a starting point.
