### ISSUE TITLE
Determine hex code from App config or other source

### ISSUE THREAD

**Issue by abko** [lprhodes/homebridge-broadlink-rm#98]
Hello, I am a bit in doubt where to post my question, but I own a settop-box (Amino 550) which remote is not properly recognised by the Broadlink RM Mini 3. It does pick up a code, but when transmitting the learned code the STB does not respond. 
I did however via the app load a shared remote which does work from the broad link rm (mini 3).

Is there any way to derive the hex values from a shared remote in the App? I already tried recording the code send by the broadlink. Unfortunately that recorded code also does not work, similar as recording from the original remote.
Alternative idea's are also welcome, e.g. recording the remote command with LIRC and converting that.

**Comment by lprhodes** [comment]
It's possible but not easy. You'd need to use Wireshark to find the hex code being sent. You'd then need to re-work broadlinkjs to decrypt the hex code and output the code.

You may also have to find the initial encryption key sent between the broadlink app and RM device when they first talk to one another which can then be used to decrypt the key. 

All in all I'd set away a day of headaches/messing around to get what you're after.

An alternative could be to do this on Android - I've seen some tools around that allow you the export the database from the android app which should include decrypted hex codes.
