### ISSUE TITLE
Many codes via one switcher

### ISSUE THREAD

**Issue by Ant1q** [lprhodes/homebridge-broadlink-rm#99]
So, it looks like i solve my main problem with stucking.

Can you add posibility send some different codes with one action. For example: I have 2 remote controls from my TV - one for TV and one for Home Theatre, can i trun on\off both device via one switcher? Advanced example: Cheap Chinees LED Controller, it have 8 dergees of brightness with only 2 hex-codes for regilation - one for up and one for down. So for controlling it needs for different brightness send different times one code.

**Comment by lprhodes** [comment]
The switch-multi, switch-repeat and switch-multi-repeat accessories should have enough flexibility to achieve this.
